### PR TITLE
Invoke callback if fling is valid

### LINKED ISSUE #9177: [android] new camera move listeners fire in wrong order
**Platform:** Android
**Mapbox SDK version:** v5.1.0-beta.3

### Steps to trigger behavior

Move camera programmatically for ex.:
```
map.easeCamera(CameraUpdateFactory.newLatLng(new LatLng(location)), 0, false, null, true);
```
### Expected behavior
Callbacks are called in order: `onCameraMoveStarted() -> onCameraMove() -> onCameraIdle()`

### Actual behavior
Camera movement finishes with `onCameraMoveStarted()` or `onCameraMove()`, or fires infinitely with `onCameraMove()` callback sometimes mixed up with `onCameraMoveCanceled()`, or any other combination. It looks really inconsistent.

### PR DESCRIPTION
**Pull request by tobrun**
closes #9177

### CODE REVIEW

File: platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapGestureDetector.java [hunk 1]
```diff
@@ -357,6 +356,8 @@ public boolean onFling(MotionEvent e1, MotionEvent e2, float velocityX, float ve
         return false;
       }
 
+      cameraChangeDispatcher.onCameraMoveStarted(REASON_API_GESTURE);
```
Comment (LukasPaczos) [inline platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapGestureDetector.java]: I think this could be moved below `transform.cancelTransitions();` so that `onCameraMoveCanceled()` is called before `onCameraMoveStarted()`
