### PR TITLE
[qt] Fix asMapboxGLFeatureIdentifier iterator traversal

### LINKED ISSUE #12098: got an endless loop
**Platform:**windows + qt
**Mapbox SDK version:**master

platform/qt/src/qt_geojson.cpp:136

    auto it = feature.properties.constBegin();
    while (it != feature.properties.constEnd()) {
        properties.emplace(std::make_pair(it.key().toStdString(), asMapboxGLPropertyValue(it.value())));
+      ++it;
    }

when construct a QMapbox::Feature() with a properies, it will go into the dead loop. Just add "++it" to fix this bug.

### PR DESCRIPTION
**Pull request by brunoabinader**
Fixes #12098.

### CODE REVIEW

File: platform/qt/src/qt_geojson.cpp [hunk 1]
```diff
@@ -132,8 +130,7 @@ mbgl::FeatureIdentifier asMapboxGLFeatureIdentifier(const QVariant &id) {
 mbgl::Feature asMapboxGLFeature(const QMapbox::Feature &feature) {
     mbgl::PropertyMap properties;
     properties.reserve(feature.properties.size());
-    auto it = feature.properties.constBegin();
-    while (it != feature.properties.constEnd()) {
+    for (auto it = feature.properties.constBegin(); it != feature.properties.constEnd(); ++it) {
         properties.emplace(std::make_pair(it.key().toStdString(), asMapboxGLPropertyValue(it.value())));
```
Comment (pozdnyakov) [inline platform/qt/src/qt_geojson.cpp]: Maybe simpler 'for (const auto &pair: map)'?

Comment (brunoabinader) [reply platform/qt/src/qt_geojson.cpp]: Tried that, but it seems the range-based for loop drops the keys out of the iterator, causing it to just contain values.
