### PR TITLE
[core][ios][Android] Check layer compatibility with source

### LINKED ISSUE #15636: [core] Assert fires in LayerFactory::createBucket
As of https://github.com/mapbox/mapbox-gl-native/commit/40b0cb74cb9e9aae85d748f4d4ea2156cc40f4fa, when running the iOS Integration Test Harness tests, specifically `testForRaisingExceptionsOnStaleLayerObject`, there's an assert in:

https://github.com/mapbox/mapbox-gl-native/blob/40b0cb74cb9e9aae85d748f4d4ea2156cc40f4fa/src/mbgl/layermanager/layer_factory.cpp#L28-L31

for a factory of type `RasterStyleLayerPeerFactory`. Missing function?

@tmpsantos suggested this may be a regression introduced in https://github.com/mapbox/mapbox-gl-native/pull/15308

/cc @tobrun

### PR DESCRIPTION
**Pull request by pozdnyakov**
Fixes #15636

### CODE REVIEW

**Comment by julianrex** [comment]
@pozdnyakov I rebased a local copy of your branch, branched and pushed: https://github.com/mapbox/mapbox-gl-native/tree/jrex/check-source-compatibility

These are speculative fixes for the [3 failing iOS tests](https://circleci.com/gh/mapbox/mapbox-gl-native/337047):

https://github.com/mapbox/mapbox-gl-native/commit/06ee0404fcb9c075e8a6cd2343fc7b0c04163ca3 addresses: 
- `testRemovingLayerBeforeAddingSameLayer`
- `testRemovingSourceInUse`

https://github.com/mapbox/mapbox-gl-native/commit/ed7321e0b3bc02ec6d3c100bccd2a5f4fbcf3b33 addresses:
- `MGLDocumentationExampleTests.testMGLHillshadeStyleLayer()`

This last one was because it was creating a `RasterSource` instead of a `RasterDEMSource` - so I think your PR & the tests have unearthed a genuine bug 👍.

@frederoni Can you take a look at the C++/Obj-C nature of https://github.com/mapbox/mapbox-gl-native/commit/ed7321e0b3bc02ec6d3c100bccd2a5f4fbcf3b33 - I'm not super keen that it's passing C++ objects BUT this is an internal method (and not exposed publicly), so I think we should be ok here.

**Comment by pozdnyakov** [comment]
@julianrex Thank you! I've reset this PR to your branch!

File: platform/darwin/src/MGLRasterTileSource.mm [hunk 1]
```diff
@@ -33,15 +33,16 @@ - (instancetype)initWithIdentifier:(NSString *)identifier configurationURL:(NSUR
 }
 
 - (instancetype)initWithIdentifier:(NSString *)identifier configurationURL:(NSURL *)configurationURL tileSize:(CGFloat)tileSize {
-    auto source = [self pendingSourceWithIdentifier:identifier configurationURL:configurationURL tileSize:tileSize];
+    NSString *configurationURLString = configurationURL.mgl_URLByStandardizingScheme.absoluteString;
+    auto source = [self pendingSourceWithIdentifier:identifier urlOrTileset:configurationURLString.UTF8String tileSize:tileSize];
```
Comment (alexshalamov) [inline platform/darwin/src/MGLRasterTileSource.mm]: should tileSize be rounded?

File: src/mbgl/style/style_impl.cpp [hunk 2]
```diff
@@ -177,6 +178,15 @@ Layer* Style::Impl::getLayer(const std::string& id) const {
 
 Layer* Style::Impl::addLayer(std::unique_ptr<Layer> layer, optional<std::string> before) {
     // TODO: verify source
+    if (Source* source = sources.get(layer->getSourceID())) {
+        if (!source->supportsLayerType(layer->baseImpl->getTypeInfo())) {
```
Comment (alexshalamov) [inline src/mbgl/style/style_impl.cpp]: Could this be inverted to `Layer->supportsSource()`?

File: src/mbgl/style/sources/vector_source.cpp [hunk 3]
```diff
@@ -84,5 +85,11 @@ void VectorSource::loadDescription(FileSource& fileSource) {
     });
 }
 
+bool VectorSource::supportsLayerType(const mbgl::style::LayerTypeInfo* info) const {
+    return !std::strcmp(info->type, "line") || !std::strcmp(info->type, "symbol") ||
```
Comment (alexshalamov) [inline src/mbgl/style/sources/vector_source.cpp]: Could these constant strings be fetched from staticTypeInfo of a concrete layer type? Otherwise, could be error prone.

**Comment by pozdnyakov** [comment]
Working on an alternate approach atm

File: src/mbgl/style/sources/vector_source.cpp (hunk 3 above)
Comment (pozdnyakov) [reply src/mbgl/style/sources/vector_source.cpp]: Changed with the latest patches.

**Comment by frederoni** [comment]
> Can you take a look at the C++/Obj-C nature of ed7321e

I share your concerns since Obj-C has a concrete type for url but it's clear by the type of the arg.
LGTM 👍

File: platform/darwin/src/MGLRasterTileSource.mm (hunk 1 above)
Comment (julianrex) [reply platform/darwin/src/MGLRasterTileSource.mm]: Good spot. That was there before, I'll re-add.
