### PR TITLE
[core] Convert GeometryTileWorker to "one-phase" loading

### LINKED ISSUE #11538: Fatal Exception: std::out_of_range vector, Regression in 4.0 beta
**Platform:** iOS
**Mapbox SDK version:** 4.0.0-beta2

This may be related to #10844, which was included and through to be fixed in the 4.0.0-beta 2 release, however running 4.0.0-beta2 shows it isn't fixed.

Because we can not dynamically hide/show annotations without adding and removing them, I'm left rapidly adding and removing annotations. At the same time I'm also changing the coordinate on some annotations. This all happens as the user interacts with a scrollview to browse their day and the paths they took on a ski hill.

Basically I'm causing a lot of redrawing, and sometimes that leads to crashes, more-so than ever with the 4.0.0 beta 2. This has skyrocketed to be my top crasher since deploying 4.0.0 beta (needed heat maps).

screen shot 2018-03-27 at 12 52 31 pm

### Steps to trigger behavior

 1. POD Install
 2. Run the attached project on hardware, preferably an older phone (6s, for EX)
 3. It may take a minute, or a relaunch or two, to cause the crash. This seems like a race condition bug, hard to reproduce, but I have now reproduced it multiple times letting this sample project run for a minute or two on an iPhone 6s. If it doesn't trigger within 5 minutes I'd relaunch.
 4. Boom (eventually)

### Expected behavior

No boom

### Actual behavior

libc++abi.dylib: terminating with uncaught exception of type std::out_of_range: vector. 

Full crash log from production: [CrashLog.txt](https://github.com/mapbox/mapbox-gl-native/files/1852949/com.consumedbycode.slopes_issue_335_crash_c26657ad70fa4c8e818ed332dda59d51_DNE_0_v2.txt)

[MapboxCrasher.zip](https://github.com/mapbox/mapbox-gl-native/files/1852969/MapboxCrasher.zip)

### PR DESCRIPTION
**Pull request by ChrisLoer**
This is an alternative to PR #11570 as a fix for issue #11538.

It's a more complicated change than #11570, but it addresses some of the root cause by removing unnecessary intermediate state from `GeometryTile` (we wanted to make these changes already: tracked as issue #10457). I used @friedbunny's repro branch to verify that it fixes #11538.

While `GeometryTile` gets simpler because it no longer maintains a half-loaded (everything but symbol buckets) state, some of the complexity moves to `GeometryTileWorker` because it becomes responsible for holding on to the `featureIndex` and `nonSymbolBuckets` in the period between `parse()` and `performSymbolLayout()`.

This PR brings us a little closer to the JS behavior, but native is still significantly more complicated. The primary reason is that native supports incremental updates of glyphs/images, while JS requires each tile load to get a completely new set of glyphs/images from the foreground. I don't know if there are many situations where this is actually an important performance optimization for native -- although for frequently updated tiles w/ symbols, it potentially allows the reloading to be done in a single step on the background, instead of always requiring the symbol dependency back-and-forth between background and foreground.

If we did decide to go all the way to the JS behavior, we'd also have to implement some equivalent of the callback registration/management handled by `actor.js`.

I have mixed feelings about using this as the fix for `release-boba`. I think it's a move in the right direction, but I'm also worried about introducing instability late in the game. Refactoring `GeometryTileWorker` is really tricky, and I _know_ I almost introduced some bugs this afternoon.

/cc @jfirebaugh @ansis @friedbunny @tobrun @julianrex

### CODE REVIEW

File: src/mbgl/tile/geometry_tile.cpp [hunk 1]
```diff
@@ -125,36 +125,17 @@ void GeometryTile::setShowCollisionBoxes(const bool showCollisionBoxes_) {
...
-}
-
-void GeometryTile::onPlacement(PlacementResult result, const uint64_t resultCorrelationID) {
     loaded = true;
     renderable = true;
     if (resultCorrelationID == correlationID) {
         pending = false;
     }
+    
+    nonSymbolBuckets = std::move(result.nonSymbolBuckets);
```
Comment (jfirebaugh) [inline src/mbgl/tile/geometry_tile.cpp]: We can also merge `nonSymbolBuckets` and `buckets` everywhere.

File: src/mbgl/tile/geometry_tile.cpp [hunk 2]
```diff
@@ -125,36 +125,17 @@ void GeometryTile::setShowCollisionBoxes(const bool showCollisionBoxes_) {
...
-    // may not be the same (e.g. "setShowCollisionBoxes" could bump the correlation ID while
-    // waiting for glyph dependencies)
-    if (pendingData) {
-        pendingData->first = true;
-    }
-    if (pendingFeatureIndex) {
-        pendingFeatureIndex->first = true;
-    }
+    
+    dataPendingCommit = {{ std::move(result.tileData), std::move(result.featureIndex) }};
```
Comment (jfirebaugh) [inline src/mbgl/tile/geometry_tile.cpp]: Since they must be synchronized, can `tileData` be owned by the `FeatureIndex`?

File: src/mbgl/tile/geometry_tile.cpp (hunk 1 above)
Comment (ChrisLoer) [reply src/mbgl/tile/geometry_tile.cpp]: Good point! Done.

File: src/mbgl/tile/geometry_tile.cpp (hunk 2 above)
Comment (ChrisLoer) [reply src/mbgl/tile/geometry_tile.cpp]: :+1: Making this change actually exposed I bug I had previously introduced with this PR. 😬 

Because the `data.clone()` call had moved to symbol layout time, the feature index could be desynchronized from the data if a `setData` arrived while the worker was waiting for symbols (the new `data` is supposed to be queued up for a re-layout after the current one finishes). Moving ownership of the `GeometryTileData` into `FeatureIndex` solves the problem by forcing the clone to happen at the time the index is created.
