### PR TITLE
[core] Ignore shortest path in Map::cameraForLatLngs

### LINKED ISSUE #8737: Map::cameraForLatLngBounds returns incorrect CameraOptions
Been looking into an user reported bug that has the camera positioned above New York City  and is trying to move the camera to a `LatLngBounds` in China.

For the following China bounds:

screenshot at 2017-04-13 10 10 42

The following center coordinate is calculated with Map::cameraForLatLngBounds:

screenshot at 2017-04-13 10 11 15

This results in centering the camera on the east coast

image

While we were expecting: [34.6212005,104.1363335]

screenshot at 2017-04-13 10 22 10

#### Data to reproduce this with
New York City = [40.712730, -74.005953], z=12
China bounds =  [15.68169,73.499857], [53.560711, 134.77281]

GL-JS is handling the use-case described above correctly, see [here](http://jsfiddle.net/7jr0nbcv/).

### PR DESCRIPTION
**Pull request by brunoabinader**
When calculating the screen coordinates for the given geographical coordinates boundaries in `Map::cameraForLatLngs`, we use `Map::pixelForLatLng`, which is implemented by calling `Transform::latLngToScreenCoordinate`.

The latter assumed that all conversions were required to be using the longitude shortest path. This is not true for `Map::cameraForLatLngs`, in which we require the longest path to properly calculate the virtual camera center.

Fixes #8737.

/cc @tobrun @jfirebaugh

### CODE REVIEW

File: src/mbgl/map/transform.hpp [hunk 1]
```diff
@@ -144,7 +144,12 @@ class Transform : private util::noncopyable {
     bool isPanning() const { return state.isPanning(); }
 
     // Conversion and projection
-    ScreenCoordinate latLngToScreenCoordinate(const LatLng&) const;
+    enum class ConversionMode : bool {
+        FindShortestPath = 0,
+        IgnoreShortestPath
```
Comment (1ec5) [inline src/mbgl/map/transform.hpp]: 👍 `cameraForLatLngs()` itself may end up taking a `ConversionMode` option as part of the fix for #8708.

**Comment by jfirebaugh** [comment]
Ah see, I disagree with fc0a0ef. It's much easier to avoid these sorts of bugs if the project (latLngToScreenCoordinate) and unproject (screenCoordinateToLatLng) operations are exact inverses, which can't be true if unproject automatically wraps its return value.

**Comment by brunoabinader** [comment]
> It's much easier to avoid these sorts of bugs if the project (latLngToScreenCoordinate) and unproject (screenCoordinateToLatLng) operations are exact inverses, which can't be true if unproject automatically wraps its return value.

I agree. I've then moved the shortest path logic into `Map::pixelForLatLng`, which uses `ShortestPathMode::Use` by default. Inside `Map::cameraForLatLngs` we call `Map::pixelForLatLng` with `ShortestPathMode::Ignore`.

I'll be out until Tuesday so please feel free to add a patch for having `Map::cameraForLatLngs` to also use that enum (if needed) - with the changes made I don't think we need it though.
