### PR TITLE
[ios, macos] Fix MGLSymbolStyleLayer.text localization issue.

### LINKED ISSUE #14393: Unable to localize labels
As of 82b5d8e5c7c4801391cec0e52bfd7513b8a6ad6d, `-[MGLStyle localizeLabelsIntoLocale:]` no longer localizes labels to any locale in Streets style v10 or v11 or similar styles. For example, this line never gets called:

https://github.com/mapbox/mapbox-gl-native/blob/82b5d8e5c7c4801391cec0e52bfd7513b8a6ad6d/platform/darwin/src/MGLStyle.mm#L594

This method worked fine in macOS map SDK v0.10.0 against Streets style v10. (That version predates the v11 styles.)

/cc @mapbox/maps-ios

### PR DESCRIPTION
**Pull request by fabian-guerra**
Fixes #14393 introduced in https://github.com/mapbox/mapbox-gl-native/pull/14094

Localization was not performed due to the introduction of `MGLAttributedExpression` object. At localization time there was not a proper converter for format expressions, returning the same expression thus avoiding localization.

### This is how it looks now on iOS
german

### This is how it looks now on macOS
germanmacos

### CODE REVIEW

**Comment by friedbunny** [comment]
We have [`MGLExpressionTests.testLocalization`](https://github.com/mapbox/mapbox-gl-native/blob/cfd398a49957a5b05382d819b5552be096344127/platform/darwin/test/MGLExpressionTests.mm#L1181) — I think we should:

1. Add a new test for the `MGLAttributedExpression` type.
2. Make the tests fail if some unexpected type has localization attempted on it.

File: platform/darwin/src/NSExpression+MGLAdditions.mm [hunk 1]
```diff
@@ -1471,6 +1471,12 @@ - (NSExpression *)mgl_expressionLocalizedIntoLocale:(nullable NSLocale *)locale
                 if (localizedValues != self.constantValue) {
                     return [NSExpression expressionForConstantValue:localizedValues];
                 }
+            } else if ([self.constantValue isKindOfClass:[MGLAttributedExpression class]]) {
```
Comment (1ec5) [inline platform/darwin/src/NSExpression+MGLAdditions.mm]: What’s our theory for how this caused #14393? I was able to reproduce the issue in the standard Streets v10 and v11 styles. Is it because the `MGLSymbolStyleLayer.text` setter always returns an attributed expression now, even when the style JSON contains only a constant string value? If so, this may be indicative of a backwards-incompatible change that took place with the introduction of formatted expressions: a developer might reasonably expect to get an ordinary string out of the `text` property, just as we apparently did.

**Comment by 1ec5** [comment]
> Make the tests fail (or have some sort of warning, somewhere) if an unexpected type has localization attempted on it.

`-[MGLStyle localizeLabelsIntoLocale:]` works by attempting to localize _everything_ (the `text` of every MGLSymbolStyleLayer). It’s designed to fail silently so that developers can set it and forget it. But these tests should assert that `text`’s getter returns the expected expression type. It’s a good idea in general for unit tests to spell out their assumed preconditions.

**Comment by fabian-guerra** [comment]
Will followup with a style localization test.
