### PR TITLE
[android] - avoid nullpointer by validating Mapbox.java creation 

### LINKED ISSUE #8661: Throw concrete exception when no accessToken is provided
When not providing an accessToken through `Mapbox.java`, 
an Activity containing our MapView will crash with:

```
com.mapbox.mapboxsdk.plugins.testapp / com.mapbox.mapboxsdk.plugins.testapp.TrafficActivity
}: android.view.InflateException: Binary XML file line #10: Error inflating class com.mapbox.mapboxsdk.maps.MapView
                                                                                          at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2358)
                                                                                          at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2420)
                                                                                          at android.app.ActivityThread.access$900(ActivityThread.java:154)
                                                                                          at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1321)
                                                                                          at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                          at android.os.Looper.loop(Looper.java:135)
                                                                                          at android.app.ActivityThread.main(ActivityThread.java:5292)
                                                                                          at java.lang.reflect.Method.invoke(Native Method)
                                                                                          at java.lang.reflect.Method.invoke(Method.java:372)
                                                                                          at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
                                                                                          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:699)
                                                                                       Caused by: android.view.InflateException: Binary XML file line # 10: Error inflating class com.mapbox.mapboxsdk.maps.MapView
at android.view.LayoutInflater.createView(LayoutInflater.java: 633)
at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java: 743)
at android.view.LayoutInflater.rInflate(LayoutInflater.java: 806)
at android.view.LayoutInflater.inflate(LayoutInflater.java: 504)
at android.view.LayoutInflater.inflate(LayoutInflater.java: 414)
at android.view.LayoutInflater.inflate(LayoutInflater.java: 365)
at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java: 292)
at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java: 140)
at com.mapbox.mapboxsdk.plugins.testapp.TrafficActivity.onCreate(TrafficActivity.java: 25)
at android.app.Activity.performCreate(Activity.java: 5990)
at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java: 1106)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java: 2311)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java: 2420) 
at android.app.ActivityThread.access$900(ActivityThread.java: 154) 
at android.app.ActivityThread$H.handleMessage(ActivityThread.java: 1321) 
at android.os.Handler.dispatchMessage(Handler.java: 102) 
at android.os.Looper.loop(Looper.java: 135) 
at android.app.ActivityThread.main(ActivityThread.java: 5292) 
at java.lang.reflect.Method.invoke(Native Method) 
at java.lang.reflect.Method.invoke(Method.java: 372) 
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java: 904) 
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java: 699) 
Caused by: java.lang.reflect.InvocationTargetException
at java.lang.reflect.Constructor.newInstance(Native Method)
at java.lang.reflect.Constructor.newInstance(Constructor.java: 288)
at android.view.LayoutInflater.createView(LayoutInflater.java: 607)
at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java: 743) 
at android.view.LayoutInflater.rInflate(LayoutInflater.java: 806) 
at android.view.LayoutInflater.inflate(LayoutInflater.java: 504) 
at android.view.LayoutInflater.inflate(LayoutInflater.java: 414) 
at android.view.LayoutInflater.inflate(LayoutInflater.java: 365) 
at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java: 292) 
at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java: 140) 
at com.mapbox.mapboxsdk.plugins.testapp.TrafficActivity.onCreate(TrafficActivity.java: 25) 
at android.app.Activity.performCreate(Activity.java: 5990) 
at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java: 1106) 
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java: 2311) 
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java: 2420) 
at android.app.ActivityThread.access$900(ActivityThread.java: 154) 
at android.app.ActivityThread$H.handleMessage(ActivityThread.java: 1321) 
at android.os.Handler.dispatchMessage(Handler.java: 102) 
at android.os.Looper.loop(Looper.java: 135) 
at android.app.ActivityThread.main(ActivityThread.java: 5292) 
at java.lang.reflect.Method.invoke(Native Method) 
at java.lang.reflect.Method.invoke(Method.java: 372) 
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java: 904) 
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java: 699) 
Caused by: java.lang.NullPointerException: Attempt to read from field 'java.lang.String com.mapbox.mapboxsdk.Mapbox.accessToken'
on a null object reference
at com.mapbox.mapboxsdk.Mapbox.validateAccessToken(Mapbox.java: 68)
at com.mapbox.mapboxsdk.Mapbox.getAccessToken(Mapbox.java: 58)
at com.mapbox.mapboxsdk.storage.FileSource. < init > (FileSource.java: 111)
at com.mapbox.mapboxsdk.storage.FileSource.getInstance(FileSource.java: 44)
at com.mapbox.mapboxsdk.maps.NativeMapView. < init > (NativeMapView.java: 78)
at com.mapbox.mapboxsdk.maps.MapView.initialise(MapView.java: 126)
at com.mapbox.mapboxsdk.maps.MapView. < init > (MapView.java: 93)
at java.lang.reflect.Constructor.newInstance(Native Method) 
at java.lang.reflect.Constructor.newInstance(Constructor.java: 288) 
at android.view.LayoutInflater.createView(LayoutInflater.java: 607) 
at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java: 743) 
at android.view.LayoutInflater.rInflate(LayoutInflater.java: 806) 
at android.view.LayoutInflater.inflate(LayoutInflater.java: 504) 
at android.view.LayoutInflater.inflate(LayoutInflater.java: 414) 
at android.view.LayoutInflater.inflate(LayoutInflater.java: 365) 
at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java: 292) 
at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java: 140) 
at com.mapbox.mapboxsdk.plugins.testapp.TrafficActivity.onCreate(TrafficActivity.java: 25) 
at android.app.Activity.performCreate(Activity.java: 5990) 
at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java: 1106) 
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java: 2311) 
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java: 2420) 
at android.app.ActivityThread.access$900(ActivityThread.java: 154) 
at android.app.ActivityThread$H.handleMessage(ActivityThread.java: 1321) 
at android.os.Handler.dispatchMessage(Handler.java: 102) 
at android.os.Looper.loop(Looper.java: 135) 
at android.app.ActivityThread.main(ActivityThread.java: 5292) 
at java.lang.reflect.Method.invoke(Native Method) 
at java.lang.reflect.Method.invoke(Method.java: 372) 
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java: 904) 
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java: 699) 
```

This is a regression as we use to show an InvalidAccessTokenException to the developer instead.

### PR DESCRIPTION
**Pull request by tobrun**
Throw an InvalidateAccessToken exception instead.

Closes #8661

### CODE REVIEW

File: platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/Mapbox.java [hunk 1]
```diff
@@ -55,11 +55,21 @@ public static synchronized Mapbox getInstance(@NonNull Context context, @NonNull
...
     validateAccessToken();
     return INSTANCE.accessToken;
   }
 
   /**
+   * Runtime validation of Mapbox creation.
+   */
+  private static void validateMapbox() throws InvalidAccessTokenException {
+    if (INSTANCE == null) {
+      throw new InvalidAccessTokenException();
```
Comment (zugaldia) [inline platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/Mapbox.java]: @tobrun Could we have a different message thrown by this `InvalidAccessTokenException` so that the developer can differentiate between and error from `validateAccessToken` and an error `validateAccessToken`?

Comment (tobrun) [inline platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/Mapbox.java]: The shown message to the user is:

>Using MapView requires setting a valid access token. Use `Mapbox.getInstance(Context context, String accessToken)` to provide one. Please see https://www.mapbox.com/help/create-api-access-token/ to learn how to create one. More information in this guide https://www.mapbox.com/help/first-steps-android-sdk/#access-tokens. 

INSTANCE being null matches behaviour of not having provided an accesstoken. I think we can get away with the same exception as both they mean the same thing. Do you feel that specific exception would provide more context than the message above?

Comment (tobrun) [inline platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/Mapbox.java]: Maybe we should just rename the exception to a more generic name to take in account both occurrences?

Comment (zugaldia) [inline platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/Mapbox.java]: > Maybe we should just rename the exception to a more generic name to take in account both occurrences?

👍
