### PR TITLE
Fix UTF-8 encoding, add missing package-info.java files

### LINKED ISSUE #11088: Missing package-info.java
With the introduction of packages in the latest couple of releases, we neglected adding the package-info.java file that is responsible for filling in the right side of the table in the javadoc:
screen shot 2018-01-30 at 14 50 35

### LINKED ISSUE #11260: [android] Backticks mangled in localIdeographFontFamily documentation
https://www.mapbox.com/android-docs/api/map-sdk/5.3.2/com/mapbox/mapboxsdk/maps/MapboxMapOptions.html#localIdeographFontFamily-java.lang.String-

Looks like a newbie mistake on my part -- is there a limited character set or an implied non-UTF8 encoding for javadoc?

/cc @tobrun

### PR DESCRIPTION
**Pull request by tobrun**
Closes #11260 
Closes #11088 

cc @ChrisLoer

### CODE REVIEW

File: platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/renderer/egl/package-info.java [hunk 1]
```diff
@@ -0,0 +1,4 @@
+/**
+ * Contains the Mapbox Maps Android egl API classes.
```
Comment (ChrisLoer) [inline platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/renderer/egl/package-info.java]: Looks like "EGL" is usually written in caps (e.g. https://www.khronos.org/egl), so we should probably do the same here?

**Comment by tobrun** [comment]
> Is there a tool you use or a configuration option in Android Studio to handle the encoding automatically?

not afaik, though when generating the docs it will produce an error and we are planning to validate this on CI as part of https://github.com/mapbox/mapbox-gl-native/issues/9267.
