### PR TITLE
[core] Clear atlasImage rect for a removed pattern

### LINKED ISSUE #9976: Shuffling causes line-pattern/overscaled to fail
Reproduced via:
```
$ node platform/node/test/render.test.js --recycle-map \
    "runtime-styling/image-add-pattern" "line-pattern/overscaled"
* passed runtime-styling image-add-pattern
* failed line-pattern overscaled
1 passed (50.0%)
1 failed (50.0%)
```

| expected | actual | diff |
|--|--|--|
| expected | actual | diff |

The rendering artifact seems to be caused by the previous _marker_  image addition from `runtime-styling/image-add-pattern`:

actual

### PR DESCRIPTION
**Pull request by brunoabinader**
Recreating the `atlasImage` object ensures no pattern leftovers are redrawn.

Fixes #9976.

Depends on https://github.com/mapbox/mapbox-gl-js/pull/5281.

(If #9905 is merged first, then the entry in ```ignores.json``` can be removed).

### CODE REVIEW

**Comment by brunoabinader** [comment]
> This doesn't look right. It will remove all other patterns from the atlas whenever a new pattern is requested, so any style that uses multiple patterns will not work.

You are correct - I was mislead by thinking that `atlasImage` was just a placeholder for single pattern items, but as the name suggests, it holds all the images' that are eventually texture uploaded - my bad :+1:

The other option, then, is to _clear_ only the exact rect occupied by the removed pattern in `atlasImage`. I'll update this PR accordingly.

File: src/mbgl/renderer/image_manager.cpp [hunk 1]
```diff
@@ -39,6 +39,14 @@ void ImageManager::removeImage(const std::string& id) {
 
     auto it = patterns.find(id);
     if (it != patterns.end()) {
+        // Clear pattern from the atlas image.
+        const uint32_t w = it->second.bin->w;
+        const uint32_t h = it->second.bin->h;
+        const uint32_t x = it->second.bin->x;
+        const uint32_t y = it->second.bin->y;
+        PremultipliedImage blank { Size { w, h } };
+        PremultipliedImage::copy(blank, atlasImage, { 0, 0 }, { x, y }, { w, h });
```
Comment (jfirebaugh) [inline src/mbgl/renderer/image_manager.cpp]: Let's add `PremultipliedImage::clear(img, { x, y }, { w, h })` so we don't have to allocate a blank image.
