### PR TITLE
[core] Fix offline regions reporting the wrong number of tiles

### LINKED ISSUE #13437: Android - OfflineDownload throwing "too many tiles" even after deleting offline region
When downloading a lot of tiles thought the offline download, I get the expected "too many tiles" error. When deleting this offline region using the Offline Manager, I was trying to "free up" the downloaded tiles. But as soon as I started a new offline download, I instantly get the "too many tiles" error. Is that expected?

### Expected behavior
When deleting an offline region, I expect all related tiles to be migrated to the ambient cache. (I hope I am using the right term to define the ambient cache as the tile storage that is not part of the max tile count which users can download. I know that the ambient cache and persistent offline cache is the same database.)

### Actual behavior
When deleting an offline region, all downloaded tiles are still saved as non-ambient tiles. That leads to the problem that the user has to clear their app storage to download new offline regions (even if that user actually has no offline regions according to the offline manager). 

### Configuration

**Mapbox SDK versions:** 6.x, 7.x

### PR DESCRIPTION
**Pull request by tmpsantos**
- The SQL query used for checking if the tile was already in the cache was wrong.
 - Tiles being refereed by two or more regions were not always counted as one.
 - Despite making one extra query, benchmarks are showing 8% performance improvement, because we are narrowing the query results by adding one extra filter.

Fixes #13437.

### CODE REVIEW

**Comment by tmpsantos** [comment]
Still some issues to be worked with overlapping regions.

File: platform/default/src/mbgl/storage/offline_database.cpp [hunk 1]
```diff
@@ -1027,7 +1026,10 @@ bool OfflineDatabase::markUsed(int64_t regionID, const Resource& resource) {
         selectQuery.bind(4, tile.x);
         selectQuery.bind(5, tile.y);
         selectQuery.bind(6, tile.z);
-        return !selectQuery.run();
+
+        bool notOnOtherRegion = !selectQuery.run();
+
+        return notOnThisRegion && notOnOtherRegion;
```
Comment (alexshalamov) [inline platform/default/src/mbgl/storage/offline_database.cpp]: return statement is &&, why do we need to run two queries, maybe return in each branch? Sorry if I missed some important bit.

Comment (alexshalamov) [reply platform/default/src/mbgl/storage/offline_database.cpp]: Discussed offline, it is correct, both queries has to be run to check that resource is missing in both regions.

File: platform/default/src/mbgl/storage/offline_database.cpp [hunk 2]
```diff
@@ -964,13 +964,13 @@ void OfflineDatabase::putRegionResources(int64_t regionID,
...
 
 uint64_t OfflineDatabase::putRegionResourceInternal(int64_t regionID, const Resource& resource, const Response& response) {
-    if (exceedsOfflineMapboxTileCountLimit(resource)) {
-        throw MapboxTileLimitExceededException();
-    }
-
     uint64_t size = putInternal(resource, response, false).second;
     bool previouslyUnused = markUsed(regionID, resource);
 
+    if (previouslyUnused && exceedsOfflineMapboxTileCountLimit(resource)) {
```
Comment (alexshalamov) [inline platform/default/src/mbgl/storage/offline_database.cpp]: The logic has changed from initial version. Now, we insert first and then check if tiles count is over the limit. Should the count limit be checked before `putInternal / markUsed`?

Comment (tmpsantos) [reply platform/default/src/mbgl/storage/offline_database.cpp]: That was another bug. If we check before, we cannot know if the tile we are trying to insert is overlapping with another region, and in this case, not counting as a tile in the total tile count.

The insertion is inside a SQL transaction. If we throw here it will rollback and the tile will not get inserted.

Comment (alexshalamov) [reply platform/default/src/mbgl/storage/offline_database.cpp]: :+1:
