### PR TITLE
Range alpha between 0 and 1 for android int color conversion

### LINKED ISSUE #12198: Android color issues on 6.x
Refs. https://github.com/mapbox/mapbox-navigation-android/issues/1045.

As seen in https://github.com/mapbox/mapbox-navigation-android/issues/1045, on `v6.2.0` Android colors are being parsed incorrectly resulting in a black fill.

Also, on all `v6.x` versions, excluding `v6.2.0`, the Android colors that have modified alpha component are also parsed incorrectly where alpha is ignored and the color is treated as fully opaque (unless the alpha value is `0`).

All above issues refer to `Expression#color` expression. The workaround is to always use `Expression#rgb` or `Expressions#rgba`, for example instead of
```
layer.setProperties(
  fillColor(
    interpolate(
      exponential(0.8f),
      zoom(),
      stop(1, color(Color.GREEN)),
      stop(4, color(Color.BLUE)),
      stop(12, color(ContextCompat.getColor(this, R.color.red_with_alpha))),
      stop(20, color(Color.BLACK))
    )
  )
);
```
you should use 
```
layer.setProperties(
  fillColor(
    interpolate(
      exponential(0.8f),
      zoom(),
      stop(1, rgb(0, 255, 0)),
      stop(4, rgb(0, 0, 255)),
      stop(12, rgba(255, 0, 0, 0.25)),
      stop(20, rgb(0, 0, 0))
    )
  )
);
```

/cc @tobrun @Guardiola31337 @danesfeder @langsmith

### PR DESCRIPTION
**Pull request by tobrun**
Closes #12198

### CODE REVIEW

File: platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/style/layers/property_factory.java.ejs [hunk 1]
```diff
@@ -87,22 +87,28 @@ public class PropertyFactory {
...
+   * Alpha value will be converted from 0-255 range to 0-1.
+   * </p>
    *
    * @param color Android color int
    * @return String rgba color
    */
   public static String colorToRgbaString(@ColorInt int color) {
-    return String.format(Locale.US, "rgba(%d, %d, %d, %d)",
-      (color >> 16) & 0xFF, (color >> 8) & 0xFF, color & 0xFF, (color >> 24) & 0xFF);
+    return String.format(Locale.US, "rgba(%d, %d, %d, %.1f)",
```
Comment (LukasPaczos) [inline platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/style/layers/property_factory.java.ejs]: I don't think precision to only one decimal point will be enough in this case. What about increasing this to 3?

File: platform/android/MapboxGLAndroidSDK/src/test/java/com/mapbox/mapboxsdk/style/expressions/ExpressionTest.java [hunk 2]
```diff
@@ -1272,4 +1275,19 @@ public void testRawMatchNumbers() {
...
+  public void testAlphaValueInColorConversion() {
+    // regression test for #12198
+    Expression colorExpression = color(Color.parseColor("#40FF0000")); // 25% alpha red
+    Object[] result = colorExpression.toArray();
+    assertEquals("alpha value should match", 0.25, (Float) result[4], 0.01f);
+  }
+
+  @Test
+  public void testAlphaValueInStringConversion() {
+    String color = PropertyFactory.colorToRgbaString(Color.parseColor("#80FF0000")); // 50% alpha red
```
Comment (LukasPaczos) [inline platform/android/MapboxGLAndroidSDK/src/test/java/com/mapbox/mapboxsdk/style/expressions/ExpressionTest.java]: Could you rewrite this test to include the issue mentioned above?

File: platform/android/MapboxGLAndroidSDK/src/test/java/com/mapbox/mapboxsdk/style/expressions/ExpressionTest.java [hunk 3]
```diff
@@ -1272,4 +1275,19 @@ public void testRawMatchNumbers() {
...
+    String alpha = color.split(" ")[3].substring(0, 3);
```
Comment (LukasPaczos) [inline platform/android/MapboxGLAndroidSDK/src/test/java/com/mapbox/mapboxsdk/style/expressions/ExpressionTest.java]: This test case doesn't really test the implementation as we are cutting off the number on the first decimal point.
