### PR TITLE
VisibleRegion on rotated map

### LINKED ISSUE #12135: LatLngBounds of visible region incorrect when map rotated
`MapboxMap.getProjection().getVisibleRegion().latLngBounds` is wildly incorrect when the map is rotated past a certain angle. The angle at which the calculation goes off the rails is the angle of the diagonal of the `MapView`.

To demonstrate this, in my camera idle listener, I get the `LatLngBounds` as above and draw a thick red polyline around their perimeter, removing the old polyline if present. When the map is oriented north-south, half the width of the polyline is visible all around the edge of the map, exactly as you would expect. When it's rotated less than the angle of the diagonal, just a bit of the polyline is visible in the corners, again as you would expect. But as soon as it's rotated past the angle of the diagonal, it's evident that east and west are being set from the wrong corners. In this screenshot, the west edge of the bounds is being set from the bottom right corner, when it should be the bottom left.

device-2018-06-12-233157

Using 6.1.2. Also tested with 5.5.3.

### PR DESCRIPTION
**Pull request by osana**
VisibleRegion on rotated map over antimeridian 
closes #12135 , #12463

### CODE REVIEW

File: platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/Projection.java [hunk 1]
```diff
@@ -97,54 +100,119 @@ public VisibleRegion getVisibleRegion() {
...
+
+  /**
+   * Takes two {@link Point}s and finds the geographic bearing between them.
+   *
+   * @param point1 first point used for calculating the bearing
+   * @param point2 second point used for calculating the bearing
+   * @return bearing in decimal degrees
+   * @see <a href="http://turfjs.org/docs/#bearing">Turf Bearing documentation</a>
+   */
+  static double bearing(@NonNull Point point1, @NonNull Point point2) {
```
Comment (LukasPaczos) [inline platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/Projection.java]: Could we change this method's declaration to work with `LatLng`s? We would skip unnecessary creation of the `Point` object before invoking this method.

Comment (osana) [reply platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/Projection.java]: good point! Thank you.

File: platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/Projection.java [hunk 2]
```diff
@@ -12,6 +14,7 @@
 import java.util.ArrayList;
 import java.util.List;
 
+
```
Comment (LukasPaczos) [inline platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/Projection.java]: NIT - whitespace
