### PR TITLE
Fix MGLMapCamera initialization and viewing distance calculations

### LINKED ISSUE #12943: MGLMapCamera interprets viewing distance incorrectly
`+[MGLMapCamera cameraLookingAtCenterCoordinate:fromDistance:pitch:heading:]` is based on MapKit’s `+[MKMapCamera cameraLookingAtCenterCoordinate:fromDistance:pitch:heading:]`. But even though the `distance` parameter is documented as “the straight-line distance from the viewpoint to the `centerCoordinate`”, it actually controls the `altitude` parameter, which is the height the viewpoint above the ground plane. This significant discrepancy has apparently always been present in the MGLMapCamera implementation, since #2193. Fixing it will likely require a semver-major release, but in the meantime it might be desirable to add a correct initializer alongside the buggy one.

/ref #12938
/cc @mapbox/maps-ios @d-prukop

### LINKED ISSUE #12967: MGLMapCamera misinterprets eye coordinate
`+[MGLMapCamera cameraLookingAtCenterCoordinate:fromEyeCoordinate:eyeAltitude:]` calculates a pitch in radians and passes it into `-initWithCenterCoordinate:altitude:pitch:heading:`, which expects the pitch in degrees, so the resulting MGLMapCamera has much less of a pitch than expected, the wrong heading, and a shorter viewing distance – so the `eyeCoordinate` parameter doesn’t have the intended effect. If the tangent happened to be negative, then MGLMapView would ignore the pitch altogether.

https://github.com/mapbox/mapbox-gl-native/blob/66e95ac2ab6260654ba09b26e83591e3d4334c02/platform/darwin/src/MGLMapCamera.mm#L35-L36 https://github.com/mapbox/mapbox-gl-native/blob/66e95ac2ab6260654ba09b26e83591e3d4334c02/platform/darwin/src/MGLMapCamera.mm#L40

This significant discrepancy has apparently always been present in the MGLMapCamera implementation, since #2193. Unlike #12943, I think it would be tenable to fix the bug in-place, because the developer’s intent by using this method is pretty clear.

/cc @mapbox/maps-ios @d-prukop

### PR DESCRIPTION
**Pull request by 1ec5**
MGLMapCamera can now be expressed in terms of viewing distance. `+[MGLMapCamera cameraLookingAtCenterCoordinate:fromDistance:pitch:heading:]` incorrectly treated the distance as an altitude. Due to backwards compatibility concerns, this method can’t be fixed in place until the next semver-major release. Instead, separate `+cameraLookingAtCenterCoordinate:correctlyFromDistance:pitch:heading:` and `+cameraLookingAtCenterCoordinate:altitude:pitch:heading:` methods have been added, and the original method has been deprecated to head-off continuing confusion.

A `viewingDistance` property has been added to MGLMapCamera. This property is computed from the `altitude` and `pitch` properties, so there isn’t any parallel state to keep track of. The benefit of this approach over #12938 is that there are fewer, more testable code paths, and developers using this SDK can officially take advantage of the `viewingDistance` property without having to forward-declare anything. One can imagine an `eyeCoordinate` property being added along the same lines in the future.

Rewrote `+[MGLMapCamera cameraLookingAtCenterCoordinate:fromEyeCoordinate:eyeAltitude:]` to produce the right heading and pitch (and thus respect the specified eye coordinate).

Please double-check my trigonometry. ~~I still need to add unit tests before this PR can land.~~

Fixes #12943 and fixes #12967. Supersedes #12938 and part of #12518.

/cc @d-prukop @fabian-guerra @julianrex

### CODE REVIEW

File: platform/darwin/src/MGLMapCamera.mm [hunk 1]
```diff
@@ -102,6 +132,31 @@ - (id)copyWithZone:(nullable NSZone *)zone
...
+
+- (CLLocationDistance)viewingDistance {
+    CGFloat pitch = self.pitch;
+    CLLocationDirection groundAngle = 90;
+    // Angle at the viewpoint formed by the shortest straight lines to the
+    // ground and center coordinate.
+    CLLocationDirection eyeAngle = 360 - groundAngle - pitch;
+    CLLocationDistance altitude = self.altitude;
+    // Solution of triangles given angle-side-angle.
+    return altitude * sin(groundAngle) / (sin(groundAngle) * cos(eyeAngle) + sin(eyeAngle) * cos(groundAngle));
```
Comment (d-prukop) [inline platform/darwin/src/MGLMapCamera.mm]: groundAngle = PI/2, sin(PI/2) = 1 and cos(PI/2) = 0.
This equation is effectively altitude / cos(eyeAngle) which produces a negative number.
I think eyeAngle is meant to be the difference between the pitch value and 90.

Try this:
```
- (CLLocationDistance)viewingDistance {
    CLLocationDirection eyeAngleFromGround = 90 - self.pitch;
    CGFloat eyeAngleFromGroundRadians = eyeAngleFromGround * M_PI_2 / 180;
    CLLocationDistance altitude = self.altitude;
    return altitude / sin(eyeAngleFromGroundRadians)
}
```

File: platform/darwin/src/MGLMapCamera.mm [hunk 2]
```diff
@@ -102,6 +132,31 @@ - (id)copyWithZone:(nullable NSZone *)zone
...
+- (void)setViewingDistance:(CLLocationDistance)distance {
+    CGFloat pitch = self.pitch;
+    CLLocationDirection groundAngle = 90;
+    // Angle at the viewpoint formed by the shortest straight lines to the
+    // ground and center coordinate.
+    CLLocationDirection eyeAngle = 360 - groundAngle - pitch;
+    // Solution of triangles given angle-side-angle.
+    self.altitude = distance * sin(pitch) / (sin(pitch) * cos(eyeAngle) + sin(eyeAngle) + cos(pitch));
+}
+
```
Comment (d-prukop) [inline platform/darwin/src/MGLMapCamera.mm]:
```
- (void)setViewingDistance:(CLLocationDistance)distance {
    CGFloat pitch = self.pitch;
    CLLocationDirection eyeAngleFromGround = 90 - self.pitch;
    CGFloat eyeAngleFromGroundRadians = eyeAngleFromGround * M_PI_2 / 180;
    self.altitude = distance * sin(eyeAngleFromGroundRadians);
}
```

File: platform/darwin/src/MGLMapCamera.mm (hunk 1 above)
[the remark this answers is not in the document]
Comment (1ec5) [reply platform/darwin/src/MGLMapCamera.mm]: Good catch – more reason for me to unit test this thing. 😄

[the remark this answers is not in the document]
Comment (1ec5) [reply platform/darwin/src/MGLMapCamera.mm]: Spotted #12967 along the way.

**Comment by 1ec5** [comment]
Thanks for your feedback, @d-prukop. I’ve fixed the issues you pointed out and added tests.

File: platform/darwin/test/MGLMapCameraTests.m [hunk 3]
```diff
@@ -0,0 +1,67 @@
...
+
+@implementation MGLMapCameraTests
+
+- (void)testViewingDistanceInitialization {
+    CLLocationCoordinate2D fountainSquare = CLLocationCoordinate2DMake(39.10152215, -84.5124439696089);
+    MGLMapCamera *camera = [MGLMapCamera cameraLookingAtCenterCoordinate:fountainSquare
+                                                   correctlyFromDistance:10000
+                                                                   pitch:0
+                                                                 heading:0];
+    MKMapCamera *mkCamera = [MKMapCamera cameraLookingAtCenterCoordinate:fountainSquare
```
Comment (1ec5) [inline platform/darwin/test/MGLMapCameraTests.m]: As far as I can tell, this is the first time we’re explicitly testing the iOS/macOS SDK against MapKit. I think we should try to test against MapKit like this whenever an API is intended to match a MapKit API one-for-one.

**Comment by 1ec5** [comment]
I went ahead and fixed #12967 too.

File: platform/darwin/src/MGLMapCamera.h [hunk 4]
```diff
@@ -63,10 +78,47 @@ MGL_EXPORT
     The value `180` means the top of the map points due south, and so on.
  */
 + (instancetype)cameraLookingAtCenterCoordinate:(CLLocationCoordinate2D)centerCoordinate
-                                   fromDistance:(CLLocationDistance)distance
+                          correctlyFromDistance:(CLLocationDistance)distance
```
Comment (fabian-guerra) [inline platform/darwin/src/MGLMapCamera.h]: Would it be possible avoid the `correctly` word? what are your thoughts on `fromLineOfSightDistance`?

**Comment by 1ec5** [comment]
> There is still wierd behavior when animating viewingDistance and pitch at the same time.

Is this the same behavior seen in the “before” screen recording in https://github.com/mapbox/mapbox-gl-native/pull/12938#issue-217144442? If so, can you ensure that `pitch` is always set before `viewingDistance`? The conversion from `viewingDistance` to `altitude` is dependent on the `pitch`. If this is infeasible when working with Core Animation, then it would be trivial to add a `-setViewingDistance:pitch:` method to ensure the correct order.

File: platform/darwin/src/MGLMapCamera.h (hunk 4 above)
Comment (1ec5) [reply platform/darwin/src/MGLMapCamera.h]: I considered `fromLineOfSightDistance`, but it bridges to Swift as `fromLineOfSight`, which is unfortunate.

Comment (1ec5) [reply platform/darwin/src/MGLMapCamera.h]: Another possibility would be `acrossDistance`, which bridges to Swift elegantly as `across`.

Comment (fabian-guerra) [reply platform/darwin/src/MGLMapCamera.h]: I'm inclined for `acrossDistance` instead.

Comment (julianrex) [reply platform/darwin/src/MGLMapCamera.h]: I like having the word distance in there - can we use NS_SWIFT_NAME in this case? To throw some more out there, perhaps `withSubjectDistance`, `fromViewDistance`, `withCameraAtDistance`.

Comment (1ec5) [reply platform/darwin/src/MGLMapCamera.h]: > I like having the word distance in there

Forcing the word “distance” would violate [Swift API naming guidelines](https://swift.org/documentation/api-design-guidelines/#omit-needless-words). The Swift compiler is doing the right thing here, since the type is `CLLocationDistance`. I’ll go with `acrossDistance` in Objective-C, which bridges to Swift as `across`.

File: platform/darwin/test/MGLMapCameraTests.m (hunk 3 above)
Comment (julianrex) [reply platform/darwin/test/MGLMapCameraTests.m]: 👍

File: platform/darwin/src/MGLMapCamera.h [hunk 5]
```diff
@@ -63,10 +85,46 @@ MGL_EXPORT
     The value `180` means the top of the map points due south, and so on.
  */
 + (instancetype)cameraLookingAtCenterCoordinate:(CLLocationCoordinate2D)centerCoordinate
-                                   fromDistance:(CLLocationDistance)distance
+                                 acrossDistance:(CLLocationDistance)distance
```
[the remark this answers is not in the document]
Comment (1ec5) [reply platform/darwin/src/MGLMapCamera.h]: I’m not sure any of those alternatives distinguishes between the hypotenuse and adjacent any more than `acrossDistance` would, but I just don’t think that distinction is very important. Consider that the original method – which I want to return to eventually, once we deprecate the incorrect implementation – calls it `fromDistance`, for simplicity and consistency with MapKit. The point is to distinguish from the opposite (altitude), which all these options accomplish to varying degrees. (The property, meanwhile, is still called `viewingDistance` – do you think it needs to be revisited?)

If `acrossDistance` doesn’t work, then my next suggestion would be `-cameraLookingAtDistance:toCoordinate:pitch:heading:` (`camera(lookingAt:to:pitch:heading:)`) or something like that. But honestly, I keep getting frustrated because all the good ways to express this concept in English require putting a word _after_ the quantity (e.g., “from … away”), which doesn’t work here.

[the remark this answers is not in the document]
Comment (julianrex) [reply platform/darwin/src/MGLMapCamera.h]: Yep - I totally hear you about language frustrations. I think the truth is that we *have* the best one, it's just that we need to deprecate it first before re-using it! 🔀 

Let's get this one in 👍

[the remark this answers is not in the document]
Comment (1ec5) [reply platform/darwin/src/MGLMapCamera.h]: Thanks, for what it’s worth, there is a more detailed explanation of this parameter a few lines further up:

https://github.com/mapbox/mapbox-gl-native/blob/44aa4f4be2bd504da982ffdcc0ffa5e84b2c6f31/platform/darwin/src/MGLMapCamera.h#L71-L73
