### PR TITLE
[ios] Improve geometry method definitions

### LINKED ISSUE #12079: Undefined symbols for architecture x86_64:   "_MGLMapPointForCoordinate"
Calling `MGLMapPointForCoordinate` anywhere in an application linked against Mapbox, results in a linker error.

**Platform:**
iOS
**Mapbox SDK version:**
4.0.2

### Steps to trigger behavior
 1. Download the iOS sample project (https://github.com/mapbox/ios-sdk-examples)
 2. Run pod install
 3. In AppDelegate.m, add the following line within `application:didFinishLaunchingWithOptions:`:
```MGLMapPointForCoordinate(kCLLocationCoordinate2DInvalid, 0);```
 4. Build the app

### Expected behavior
The build succeeds, with no errors.

### Actual behavior
The build fails with the following linker error:
Undefined symbols for architecture x86_64:   "_MGLMapPointForCoordinate"

### PR DESCRIPTION
**Pull request by friedbunny**
Fixes #12079.

Here’s my (potentially incorrect) understanding of this fix: `MGLMapPointForCoordinate()` was `extern`-defined in a C header, but implemented in an Obj-C++ source file and mangled as a C++ symbol. `FOUNDATION_EXTERN` is C++-aware and will force C-style symbol mangling, which fixes the undefined symbol issue in consumer Obj-C projects (#12079).

You can verify the change in symbol mangling using `nm`:

_Before:_
```
00000000000d3b21 T __Z24MGLMapPointForCoordinate22CLLocationCoordinate2Dd
```
_After:_
```
00000000000a0c01 T _MGLMapPointForCoordinate
```

This PR also:
- Moves `MGL_EXPORT` for two private methods to `MGLGeometry_Private.h`, rather than defining them with the implementation.
- Adds internal docs for `MGLPointRounded()` and removes obsolete iOS 7 compatibility.

/cc @1ec5 @julianrex @kkaefer @asheemmamoowala

### CODE REVIEW

File: platform/darwin/src/MGLGeometry.mm [hunk 1]
```diff
@@ -100,7 +98,7 @@ CLLocationDirection MGLDirectionBetweenCoordinates(CLLocationCoordinate2D firstC
 
 CGPoint MGLPointRounded(CGPoint point) {
 #if TARGET_OS_IPHONE || TARGET_OS_SIMULATOR
-    CGFloat scaleFactor = [UIScreen instancesRespondToSelector:@selector(nativeScale)] ? [UIScreen mainScreen].nativeScale : [UIScreen mainScreen].scale;
+    CGFloat scaleFactor = [UIScreen mainScreen].nativeScale;
```
Comment (1ec5) [inline platform/darwin/src/MGLGeometry.mm]: This is the iOS 7 compatibility that’s being removed, by the way.

/cc @lloydsheng

**Comment by friedbunny** [comment]
_Per @asheemmamoowala’s [review](
https://github.com/mapbox/mapbox-gl-native/pull/12445#pullrequestreview-138850394):_
> Does  `MGLSubexpressionsWithJSONObjects` in _NSExpression+MGLPrivateAdditions.h_ also need the modified extern?

You’re correct that this function could also suffer from the same mangling issue as `MGLMapPointForCoordinate()`, but as a private symbol this doesn’t appear to matter.

_Before:_
```
00000000000a5247 t __Z32MGLSubexpressionsWithJSONObjectsP7NSArray
```
_After:_
```
00000000000a5247 t _MGLSubexpressionsWithJSONObjects
```


> Do you think it would be beneficial to use  `FOUNDATION_EXTERN` everywhere so that the code is consistent in how functions are exported. Would also prevent copy-🍝 from allowing this in the future.

This seems prudent to me — switching all of the `externs` in our darwin code to `FOUNDATION_EXTERN` only changes the two symbols already mentioned in this issue, but it does provide us with a modicum of safety/consistency with no downsides that I’m aware of (other than, perhaps, being something we’ll have to remember to do).

Our docs even remain the same, since it’s just an alias:

screen shot 2018-07-24 at 6 04 26 pm
