### PR TITLE
Change library loader to soloader

### LINKED ISSUE #14428: Many Fatal Exception: java.lang.UnsatisfiedLinkError
**Android versions:**6.0.1
**Device models:** Nexus 5X
**Mapbox SDK versions:** 
    implementation 'com.mapbox.mapboxsdk:mapbox-android-sdk:7.2.0' 
    implementation 'com.mapbox.mapboxsdk:mapbox-sdk-services:4.5.0'
    implementation 'com.mapbox.mapboxsdk:mapbox-android-plugin-annotation-v7:0.5.0'
    implementation 'com.mapbox.mapboxsdk:mapbox-android-navigation:0.33.2'
    implementation 'com.mapbox.mapboxsdk:mapbox-android-navigation-ui:0.33.2' 

I have just added crashlytics to my app and I got this new error from the sdk :
`No implementation found for void com.mapbox.mapboxsdk.net.NativeConnectivityListener.initialize() (tried Java_com_mapbox_mapboxsdk_net_NativeConnectivityListener_initialize and Java_com_mapbox_mapboxsdk_net_NativeConnectivityListener_initialize__)`

`com.mapbox.mapboxsdk.net.NativeConnectivityListener.initialize (NativeConnectivityListener.java)
com.mapbox.mapboxsdk.net.NativeConnectivityListener. (NativeConnectivityListener.java:27)
com.mapbox.mapboxsdk.net.ConnectivityReceiver.instance (ConnectivityReceiver.java:43)
com.mapbox.mapboxsdk.Mapbox.getInstance (Mapbox.java:60)`

I have several crashes each day on my app and it is affecting my user, we need a solution please.

fail

### LINKED ISSUE #14888: MAPBOX SDK Error: Program type already present: com.getkeepsafe.relinker.ApkLibraryInstaller
### Steps to reproduce

 1. When I run my app, i got this error 
`Error: Program type already present: com.getkeepsafe.relinker.ApkLibraryInstaller`

### Expected behavior
in dependencies, if i delete mapbox sdk and mapbox-android-plugin-place, my app works well
```
    implementation 'com.mapbox.mapboxsdk:mapbox-android-sdk:8.0.0'
    implementation 'com.mapbox.mapboxsdk:mapbox-android-plugin-places-v7:0.8.0'
```

**Android versions:** Pie
**Device models:** Pixel 2 XL
**Mapbox SDK versions:** Mapbox sdk 8.0.0 and Mapbox plugin place v7 0.8.0

Thank you,,.

### PR DESCRIPTION
**Pull request by tobrun**
This PR changes our library loader from relinker to soloader. We initially switched to relinker based on advice given by Google in their NDK changelog. Now with getting feeedback as  https://github.com/mapbox/mapbox-gl-native/issues/14888 and https://github.com/mapbox/mapbox-gl-native/issues/14428. Let's move forward using [soloader](https://github.com/facebook/SoLoader) from Facebook. It should be more stable.

Closes #14428 
Closes #14888

### CODE REVIEW

File: platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/module/loader/LibraryLoaderProviderImpl.java [hunk 1]
```diff
@@ -23,36 +24,25 @@
...
     @Override
     public void load(String name) {
       try {
-        Context context = Mapbox.getApplicationContext();
-        ReLinker.log(new LibraryLogger()).loadLibrary(context, name);
+        init(Mapbox.getApplicationContext(),false);
+        loadLibrary(name);
       } catch (MapboxConfigurationException exception) {
-        Logger.e(LibraryLogger.TAG, "Couldn't load so file with relinker, application context missing, "
+        Logger.e(TAG, "Couldn't load so file with relinker, application context missing, "
```
Comment (zugaldia) [inline platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/module/loader/LibraryLoaderProviderImpl.java]: relinker -> soloader

File: platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/module/loader/LibraryLoaderProviderImpl.java [hunk 2]
```diff
@@ -23,36 +24,25 @@
...
+  private static class SoLibraryLoader extends LibraryLoader {
+
+    private static final String TAG = "SoLibraryLoader";
 
     @Override
     public void load(String name) {
       try {
-        Context context = Mapbox.getApplicationContext();
-        ReLinker.log(new LibraryLogger()).loadLibrary(context, name);
+        init(Mapbox.getApplicationContext(),false);
```
Comment (zugaldia) [inline platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/module/loader/LibraryLoaderProviderImpl.java]: What does `false` mean in this context? could its value bring any regressions? I'd add a comment or add a named variable.

Comment (tobrun) [reply platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/module/loader/LibraryLoaderProviderImpl.java]: this references to exoPackage which is used when building with [Buck](https://buck.build/article/exopackage.html).
Added a small comment with a link to exopackage.

File: platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/module/loader/LibraryLoaderProviderImpl.java [hunk 3]
```diff
@@ -23,36 +24,26 @@
    */
   @Override
   public LibraryLoader getDefaultLibraryLoader() {
-    return new ReLinkerLibraryLoader();
+    return new SoLibraryLoader();
   }
 
   /**
    * Concrete implementation of a LibraryLoader using ReLinker.
```
Comment (yunikkk) [inline platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/module/loader/LibraryLoaderProviderImpl.java]: nit: ReLinker
