### PR TITLE
[ios] Standardize exception definitions

### LINKED ISSUE #7258: Standardize NSException names
Most of the NSExceptions we raise in the iOS and macOS SDKs are named with ad-hoc names such as “Value not handled”. Instead, we should either use one of the [predefined exception names](https://developer.apple.com/reference/foundation/1613022-foundation_constants/1660462-general_exception_names?language=objc) or define a string constant such as “MGLIdentifierCollisionException” in MGLTypes.h for use with these exceptions. This way, test code can more easily check for the exception with `XCTAssertThrowsSpecificNamed()`, and we could start adding notes about exception conditions in our method documentation.

/cc @incanus @frederoni

### PR DESCRIPTION
**Pull request by friedbunny**
Fixes #7258 by converting stringly-typed exception names into `MGLExceptionName`-typed constants. This doesn’t attempt to document the exceptions, but that could happen in the future.

/cc @1ec5 @fabian-guerra @julianrex @captainbarbosa

### CODE REVIEW

**Comment by friedbunny** [comment]
@julianrex and I were curious how this ended up looking in Swift:

screen shot 2018-08-08 at 6 58 44 pm

File: platform/darwin/src/MGLTypes.h [hunk 1]
```diff
@@ -30,6 +30,11 @@ NS_ASSUME_NONNULL_BEGIN
     typedef NSString *NSNotificationName;
 #endif
 
+typedef NSString *MGLExceptionName NS_EXTENSIBLE_STRING_ENUM;
```
Comment (friedbunny) [inline platform/darwin/src/MGLTypes.h]: I was copying `NSExceptionName`, but I’m going to look at replacing this with `NS_TYPED_EXTENSIBLE_ENUM` on [Apple’s recommendation](https://developer.apple.com/documentation/swift/objective_c_and_c_code_customization/grouping_related_objective_c_constants):

> You might encounter Objective-C code that uses the older `NS_STRING_ENUM` and `NS_EXTENSIBLE_STRING_ENUM` macros, which were used to group string constants. Use `NS_TYPED_ENUM` and `NS_TYPED_EXTENSIBLE_ENUM` when grouping related constants of any type, including string constants.

**Comment by friedbunny** [comment]
> Instead of having a master header with all the exceptions, we will declare on each file the exceptions it throws (if any)? If so, should we document this?

Defining non-generic constants close to their main usage sites is generally a good practice, I think, and is something we’ve been doing with other constants, like `MGLTileSourceOption` and friends. I’ll go through and add a bit of private documentation in `MGLTypes` to try and make it clear that those are generic exceptions.

File: platform/darwin/src/MGLTypes.h (hunk 1 above)
Comment (friedbunny) [reply platform/darwin/src/MGLTypes.h]: Xcode 9 has all of these defined as the same thing, so it’s just cosmetic:

```
#define NS_STRING_ENUM _NS_TYPED_ENUM
#define NS_EXTENSIBLE_STRING_ENUM _NS_TYPED_EXTENSIBLE_ENUM

#define NS_TYPED_ENUM _NS_TYPED_ENUM
#define NS_TYPED_EXTENSIBLE_ENUM _NS_TYPED_EXTENSIBLE_ENUM
```

... but let’s still standardize on the new one.

File: platform/ios/src/MGLMapView.mm [hunk 2]
```diff
@@ -6296,8 +6301,8 @@ - (void)setStyleURL__:(nullable NSString *)URLString
     NSURL *url = URLString.length ? [NSURL URLWithString:URLString] : nil;
     if (URLString.length && !url)
     {
-        [NSException raise:@"Invalid style URL" format:
-         @"“%@” is not a valid style URL.", URLString];
+        [NSException raise:MGLInvalidStyleURLException
```
Comment (1ec5) [inline platform/ios/src/MGLMapView.mm]: #12640 takes care of the macOS side of this change.
