### PR TITLE
[core] Add API for clearing tiles from the ambient cache

### LINKED ISSUE #14549: Storage not cleared when deleting an OfflineRegion
### Steps to reproduce

When deleting an `OfflineRegion`, the storage is not cleared.
If you open the App Info, the space used remains the same.
Does the delete method from the `OfflineRegion` clear the storage allocated for that?

Tested in the Mapbox Demo app.
To reproduce, download a large offline region (50MB or up), as I'm not sure if it happens for small offline region definitions.

No other regions were downloaded, just this single one.

### Expected behavior

The storage used by the `OfflineRegion` region to be cleared

### Actual behavior

The storage is not cleared

### Configuration

**Android versions:** 8 / 9
**Device models:** Galaxy S8 / Any Emulator
**Mapbox SDK versions:** checked on 7.2.0 and up

### PR DESCRIPTION
**Pull request by tmpsantos**
This new API will really remove the tiles and shrink the database by calling `VACUUM`, which can be potentially slow.

Fixes #14549

### CODE REVIEW

File: platform/default/src/mbgl/storage/offline_database.cpp [hunk 1]
```diff
@@ -791,7 +809,7 @@ std::exception_ptr OfflineDatabase::deleteRegion(OfflineRegion&& region) try {
 
     evict(0);
     assert(db);
-    db->exec("PRAGMA incremental_vacuum");
+    db->exec("VACUUM");
```
Comment (julianrex) [inline platform/default/src/mbgl/storage/offline_database.cpp]: I don't know enough here, but is this something that should be scheduled for some idle time in the future?

File: include/mbgl/storage/default_file_source.hpp [hunk 2]
```diff
@@ -144,6 +144,14 @@ class DefaultFileSource : public FileSource {
      */
     void deleteOfflineRegion(OfflineRegion&&, std::function<void (std::exception_ptr)>);
 
+    /*
+     * Invalidate all the tiles from an offline region forcing Mapbox GL to revalidate
+     * the tiles with the server before using. This is more efficient than deleting the
+     * offline region and downloading it again because if the data on the cache matches
+     * the server, no new data gets transmitted.
+     */
+    void invalidateOfflineRegion(OfflineRegion&, std::function<void (std::exception_ptr)>);
```
Comment (pozdnyakov) [inline include/mbgl/storage/default_file_source.hpp]: why mutable reference?

File: platform/default/src/mbgl/storage/offline_database.cpp (hunk 1 above)
Comment (pozdnyakov) [reply platform/default/src/mbgl/storage/offline_database.cpp]: This method has become heavier, right? is it expected and should it be also mentioned in the method description?

Comment (pozdnyakov) [reply platform/default/src/mbgl/storage/offline_database.cpp]: Also is it an option to schedule `VACUUM` separately, so that it is performed in a different callchain?

Comment (tmpsantos) [reply platform/default/src/mbgl/storage/offline_database.cpp]: It has not become heavier, I could not measure any performance difference between calling `VACUUM` and `PRAGMA incremental_vacuum` in this case. The reason why I'm replacing with `VACUUM` is because `PRAGMA incremental_vacuum` was not working and we would need to migrate existing databases to a new version to make it work.

File: include/mbgl/storage/default_file_source.hpp (hunk 2 above)
Comment (tmpsantos) [reply include/mbgl/storage/default_file_source.hpp]: I'm following the style on this file and I believe it is like this on other methods (like delete) because of const-correctness. It will effectively change the offline region even though it could be passed as const ref.

File: platform/default/src/mbgl/storage/offline_database.cpp (hunk 1 above)
Comment (tmpsantos) [reply platform/default/src/mbgl/storage/offline_database.cpp]: @julianrex I think that is a good idea, but we would have to keep a state on the database that it is pending a `VACUUM`, because the app could be killed before we run it. Another problem I found when working on this code is that we only request data from the network after we query the database synchronously. One thing that could be done already is make the network request before accessing the cache to increase parallelism, but ideally access to the database should also be asynchronous and not block the network thread.
