### PR TITLE
Hardening map destruction

### LINKED ISSUE #10563: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.mapbox.mapboxsdk.maps.NativeMapView.addAnnotationIcon(java.lang.String, int, int, float, byte[])' on a null object reference and Error occurred trying to report a new Location
**Platform: Android
Mapbox SDK version: 5.2.0**
When I click a button, the map will load in a fragment. However, when click the button several times ,there is a error occured:

```
11-27 15:11:02.430 1821-1821/com.example.hgis.tdmapbox2 E/AndroidRuntime: FATAL EXCEPTION: main
                                                                          Process: com.example.hgis.tdmapbox2, PID: 1821
                                                                          java.lang.NullPointerException: Attempt to invoke virtual method 'void com.mapbox.mapboxsdk.maps.NativeMapView.addAnnotationIcon(java.lang.String, int, int, float, byte[])' on a null object reference
                                                                              at com.mapbox.mapboxsdk.maps.IconManager.loadIcon(IconManager.java:115)
                                                                              at com.mapbox.mapboxsdk.maps.IconManager.<init>(IconManager.java:37)
                                                                              at com.mapbox.mapboxsdk.maps.MapView.initialiseMap(MapView.java:174)
                                                                              at com.mapbox.mapboxsdk.maps.MapView.access$800(MapView.java:70)
                                                                              at com.mapbox.mapboxsdk.maps.MapView$5$1.run(MapView.java:304)
                                                                              at android.os.Handler.handleCallback(Handler.java:761)
                                                                              at android.os.Handler.dispatchMessage(Handler.java:98)
                                                                              at android.os.Looper.loop(Looper.java:156)
                                                                              at android.app.ActivityThread.main(ActivityThread.java:6523)
                                                                              at java.lang.reflect.Method.invoke(Native Method)
                                                                              at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:942)
                                                                              at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:832)
11-27 15:11:02.438 1233-5868/? E/ReportTools: This is not beta user build
11-27 15:11:02.686 1977-1977/com.example.hgis.tdmapbox2:lost E/FusedLocationProviderServiceDelegate: Error occurred trying to report a new Location
                                                                                                     android.os.DeadObjectException
                                                                                                         at android.os.BinderProxy.transactNative(Native Method)
                                                                                                         at android.os.BinderProxy.transact(Binder.java:617)
                                                                                                         at com.mapzen.android.lost.internal.IFusedLocationProviderCallback$Stub$Proxy.onLocationChanged(IFusedLocationProviderCallback.java:129)
                                                                                                         at com.mapzen.android.lost.internal.FusedLocationProviderServiceDelegate.reportLocation(FusedLocationProviderServiceDelegate.java:95)
                                                                                                         at com.mapzen.android.lost.internal.FusionEngine.onLocationChanged(FusionEngine.java:196)
                                                                                                         at android.location.LocationManager$ListenerTransport._handleMessage(LocationManager.java:317)
                                                                                                         at android.location.LocationManager$ListenerTransport.-wrap0(LocationManager.java)
                                                                                                         at android.location.LocationManager$ListenerTransport$2.handleMessage(LocationManager.java:249)
                                                                                                         at android.os.Handler.dispatchMessage(Handler.java:105)
                                                                                                         at android.os.Looper.loop(Looper.java:156)
                                                                                                         at android.app.ActivityThread.main(ActivityThread.java:6523)
                                                                                                         at java.lang.reflect.Method.invoke(Native Method)
                                                                                                         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:942)
                                                                                                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:832)
```

### PR DESCRIPTION
**Pull request by tobrun**
Follow up from https://github.com/mapbox/mapbox-gl-native/pull/10804.
Fixes #10563.

cc @hashfunction

### CODE REVIEW

File: platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapView.java [hunk 1]
```diff
@@ -296,51 +293,43 @@ private void initialiseDrawingSurface(MapboxMapOptions options) {
...
 
       glSurfaceView.setVisibility(View.VISIBLE);
-
     }
 
     nativeMapView = new NativeMapView(this, mapRenderer);
     nativeMapView.resizeView(getMeasuredWidth(), getMeasuredHeight());
   }
 
+  private void initRenderSurface() {
```
Comment (ivovandongen) [inline platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapView.java]: Small nit. But could we rename this to something like `onSurfaceCreated`? It doesn't really initialise the render surface.

Comment (tobrun) [reply platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapView.java]: https://github.com/mapbox/mapbox-gl-native/pull/11023
