### PR TITLE
[core] Limit pitch based on edge insets. Fix max Z calculation in getProjMatrix.

### LINKED ISSUE #15163: Runaway tile downloads, symbol placement when map is tilted with top padding
As of #14664, increasing the camera’s top padding can cause the camera’s focal point to lie lower than the center of the map. This significantly improves the perspective effect, but it also causes excessive detail to be shown toward the top of the map. Adaptive tile coverage (#9037) is still unimplemented, so tiles for the same zoom level get loaded throughout the map and displayed in smaller and smaller cells as you go toward the top of the map.

Here’s a map view displayed full-screen on an iPhone 8 simulator, with the top content inset set to 40% of the view’s height and the left content inset set to half the view’s height. The camera is rotated 258° counterclockwise from north (approximately west-southwest), tilted 60°, and raised about 200 meters above the ground. Tile boundaries are enabled. The top of the map is covered by an inordinate number of tiles:

boundaries

Sometimes, with slightly different rotation and zooming, mbgl hangs because of the sheer amount of symbol placement that needs to happen – many times the amount of symbol placement that would happen with a normal viewport:

```
#0	0x000000010c939d68 in std::__1::__tree<std::__1::__value_type<std::__1::basic_string<char16_t, std::__1::char_traits<char16_t>, std::__1::allocator<char16_t> >, std::__1::vector<mbgl::IndexedSymbolInstance, std::__1::allocator<mbgl::IndexedSymbolInstance> > >, std::__1::__map_value_compare<std::__1::basic_string<char16_t, std::__1::char_traits<char16_t>, std::__1::allocator<char16_t> >, std::__1::__value_type<std::__1::basic_string<char16_t, std::__1::char_traits<char16_t>, std::__1::allocator<char16_t> >, std::__1::vector<mbgl::IndexedSymbolInstance, std::__1::allocator<mbgl::IndexedSymbolInstance> > >, std::__1::less<std::__1::basic_string<char16_t, std::__1::char_traits<char16_t>, std::__1::allocator<char16_t> > >, true>, std::__1::allocator<std::__1::__value_type<std::__1::basic_string<char16_t, std::__1::char_traits<char16_t>, std::__1::allocator<char16_t> >, std::__1::vector<mbgl::IndexedSymbolInstance, std::__1::allocator<mbgl::IndexedSymbolInstance> > > > >::__root() const at /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/__tree:1076
#1	0x000000010c939c89 in std::__1::__tree<std::__1::__value_type<std::__1::basic_string<char16_t, std::__1::char_traits<char16_t>, std::__1::allocator<char16_t> >, std::__1::vector<mbgl::IndexedSymbolInstance, std::__1::allocator<mbgl::IndexedSymbolInstance> > >, std::__1::__map_value_compare<std::__1::basic_string<char16_t, std::__1::char_traits<char16_t>, std::__1::allocator<char16_t> >, std::__1::__value_type<std::__1::basic_string<char16_t, std::__1::char_traits<char16_t>, std::__1::allocator<char16_t> >, std::__1::vector<mbgl::IndexedSymbolInstance, std::__1::allocator<mbgl::IndexedSymbolInstance> > >, std::__1::less<std::__1::basic_string<char16_t, std::__1::char_traits<char16_t>, std::__1::allocator<char16_t> > >, true>, std::__1::allocator<std::__1::__value_type<std::__1::basic_string<char16_t, std::__1::char_traits<char16_t>, std::__1::allocator<char16_t> >, std::__1::vector<mbgl::IndexedSymbolInstance, std::__1::allocator<mbgl::IndexedSymbolInstance> > > > >::~__tree() at /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/__tree:1831
#2	0x000000010c939c65 in std::__1::__tree<std::__1::__value_type<std::__1::basic_string<char16_t, std::__1::char_traits<char16_t>, std::__1::allocator<char16_t> >, std::__1::vector<mbgl::IndexedSymbolInstance, std::__1::allocator<mbgl::IndexedSymbolInstance> > >, std::__1::__map_value_compare<std::__1::basic_string<char16_t, std::__1::char_traits<char16_t>, std::__1::allocator<char16_t> >, std::__1::__value_type<std::__1::basic_string<char16_t, std::__1::char_traits<char16_t>, std::__1::allocator<char16_t> >, std::__1::vector<mbgl::IndexedSymbolInstance, std::__1::allocator<mbgl::IndexedSymbolInstance> > >, std::__1::less<std::__1::basic_string<char16_t, std::__1::char_traits<char16_t>, std::__1::allocator<char16_t> > >, true>, std::__1::allocator<std::__1::__value_type<std::__1::basic_string<char16_t, std::__1::char_traits<char16_t>, std::__1::allocator<char16_t> >, std::__1::vector<mbgl::IndexedSymbolInstance, std::__1::allocator<mbgl::IndexedSymbolInstance> > > > >::~__tree() at /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/__tree:1828
#3	0x000000010c939c45 in std::__1::map<std::__1::basic_string<char16_t, std::__1::char_traits<char16_t>, std::__1::allocator<char16_t> >, std::__1::vector<mbgl::IndexedSymbolInstance, std::__1::allocator<mbgl::IndexedSymbolInstance> >, std::__1::less<std::__1::basic_string<char16_t, std::__1::char_traits<char16_t>, std::__1::allocator<char16_t> > >, std::__1::allocator<std::__1::pair<std::__1::basic_string<char16_t, std::__1::char_traits<char16_t>, std::__1::allocator<char16_t> > const, std::__1::vector<mbgl::IndexedSymbolInstance, std::__1::allocator<mbgl::IndexedSymbolInstance> > > > >::~map() at /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/__tree:1504
#4	0x000000010c939c25 in std::__1::map<std::__1::basic_string<char16_t, std::__1::char_traits<char16_t>, std::__1::allocator<char16_t> >, std::__1::vector<mbgl::IndexedSymbolInstance, std::__1::allocator<mbgl::IndexedSymbolInstance> >, std::__1::less<std::__1::basic_string<char16_t, std::__1::char_traits<char16_t>, std::__1::allocator<char16_t> > >, std::__1::allocator<std::__1::pair<std::__1::basic_string<char16_t, std::__1::char_traits<char16_t>, std::__1::allocator<char16_t> > const, std::__1::vector<mbgl::IndexedSymbolInstance, std::__1::allocator<mbgl::IndexedSymbolInstance> > > > >::~map() at /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/__tree:1504
#5	0x000000010c939c09 in mbgl::TileLayerIndex::~TileLayerIndex() at /path/to/mapbox-gl-native/src/mbgl/text/cross_tile_symbol_index.hpp:31
#6	0x000000010c939be5 in mbgl::TileLayerIndex::~TileLayerIndex() at /path/to/mapbox-gl-native/src/mbgl/text/cross_tile_symbol_index.hpp:31
#7	0x000000010c939bc9 in std::__1::pair<mbgl::OverscaledTileID const, mbgl::TileLayerIndex>::~pair() at /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/utility:314
#8	0x000000010c939ba5 in std::__1::pair<mbgl::OverscaledTileID const, mbgl::TileLayerIndex>::~pair() at /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/utility:314
#9	0x000000010c939b89 in void std::__1::allocator_traits<std::__1::allocator<std::__1::__tree_node<std::__1::__value_type<mbgl::OverscaledTileID, mbgl::TileLayerIndex>, void*> > >::__destroy<std::__1::pair<mbgl::OverscaledTileID const, mbgl::TileLayerIndex> >(std::__1::integral_constant<bool, false>, std::__1::allocator<std::__1::__tree_node<std::__1::__value_type<mbgl::OverscaledTileID, mbgl::TileLayerIndex>, void*> >&, std::__1::pair<mbgl::OverscaledTileID const, mbgl::TileLayerIndex>*) at /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/memory:1747
#10	0x000000010c939abd in void std::__1::allocator_traits<std::__1::allocator<std::__1::__tree_node<std::__1::__value_type<mbgl::OverscaledTileID, mbgl::TileLayerIndex>, void*> > >::destroy<std::__1::pair<mbgl::OverscaledTileID const, mbgl::TileLayerIndex> >(std::__1::allocator<std::__1::__tree_node<std::__1::__value_type<mbgl::OverscaledTileID, mbgl::TileLayerIndex>, void*> >&, std::__1::pair<mbgl::OverscaledTileID const, mbgl::TileLayerIndex>*) at /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/memory:1595
#11	0x000000010c939a2f in std::__1::__tree<std::__1::__value_type<mbgl::OverscaledTileID, mbgl::TileLayerIndex>, std::__1::__map_value_compare<mbgl::OverscaledTileID, std::__1::__value_type<mbgl::OverscaledTileID, mbgl::TileLayerIndex>, std::__1::less<mbgl::OverscaledTileID>, true>, std::__1::allocator<std::__1::__value_type<mbgl::OverscaledTileID, mbgl::TileLayerIndex> > >::destroy(std::__1::__tree_node<std::__1::__value_type<mbgl::OverscaledTileID, mbgl::TileLayerIndex>, void*>*) at /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/__tree:1843
#12	0x000000010c9399f4 in std::__1::__tree<std::__1::__value_type<mbgl::OverscaledTileID, mbgl::TileLayerIndex>, std::__1::__map_value_compare<mbgl::OverscaledTileID, std::__1::__value_type<mbgl::OverscaledTileID, mbgl::TileLayerIndex>, std::__1::less<mbgl::OverscaledTileID>, true>, std::__1::allocator<std::__1::__value_type<mbgl::OverscaledTileID, mbgl::TileLayerIndex> > >::destroy(std::__1::__tree_node<std::__1::__value_type<mbgl::OverscaledTileID, mbgl::TileLayerIndex>, void*>*) at /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/__tree:1841
#13	0x000000010c9399e3 in std::__1::__tree<std::__1::__value_type<mbgl::OverscaledTileID, mbgl::TileLayerIndex>, std::__1::__map_value_compare<mbgl::OverscaledTileID, std::__1::__value_type<mbgl::OverscaledTileID, mbgl::TileLayerIndex>, std::__1::less<mbgl::OverscaledTileID>, true>, std::__1::allocator<std::__1::__value_type<mbgl::OverscaledTileID, mbgl::TileLayerIndex> > >::destroy(std::__1::__tree_node<std::__1::__value_type<mbgl::OverscaledTileID, mbgl::TileLayerIndex>, void*>*) at /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/__tree:1840
#14	0x000000010c9399f4 in std::__1::__tree<std::__1::__value_type<mbgl::OverscaledTileID, mbgl::TileLayerIndex>, std::__1::__map_value_compare<mbgl::OverscaledTileID, std::__1::__value_type<mbgl::OverscaledTileID, mbgl::TileLayerIndex>, std::__1::less<mbgl::OverscaledTileID>, true>, std::__1::allocator<std::__1::__value_type<mbgl::OverscaledTileID, mbgl::TileLayerIndex> > >::destroy(std::__1::__tree_node<std::__1::__value_type<mbgl::OverscaledTileID, mbgl::TileLayerIndex>, void*>*) at /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/__tree:1841
#15	0x000000010c9399e3 in std::__1::__tree<std::__1::__value_type<mbgl::OverscaledTileID, mbgl::TileLayerIndex>, std::__1::__map_value_compare<mbgl::OverscaledTileID, std::__1::__value_type<mbgl::OverscaledTileID, mbgl::TileLayerIndex>, std::__1::less<mbgl::OverscaledTileID>, true>, std::__1::allocator<std::__1::__value_type<mbgl::OverscaledTileID, mbgl::TileLayerIndex> > >::destroy(std::__1::__tree_node<std::__1::__value_type<mbgl::OverscaledTileID, mbgl::TileLayerIndex>, void*>*) at /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/__tree:1840
#16	0x000000010c9399e3 in std::__1::__tree<std::__1::__value_type<mbgl::OverscaledTileID, mbgl::TileLayerIndex>, std::__1::__map_value_compare<mbgl::OverscaledTileID, std::__1::__value_type<mbgl::OverscaledTileID, mbgl::TileLayerIndex>, std::__1::less<mbgl::OverscaledTileID>, true>, std::__1::allocator<std::__1::__value_type<mbgl::OverscaledTileID, mbgl::TileLayerIndex> > >::destroy(std::__1::__tree_node<std::__1::__value_type<mbgl::OverscaledTileID, mbgl::TileLayerIndex>, void*>*) at /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/__tree:1840
#17	0x000000010c9399f4 in std::__1::__tree<std::__1::__value_type<mbgl::OverscaledTileID, mbgl::TileLayerIndex>, std::__1::__map_value_compare<mbgl::OverscaledTileID, std::__1::__value_type<mbgl::OverscaledTileID, mbgl::TileLayerIndex>, std::__1::less<mbgl::OverscaledTileID>, true>, std::__1::allocator<std::__1::__value_type<mbgl::OverscaledTileID, mbgl::TileLayerIndex> > >::destroy(std::__1::__tree_node<std::__1::__value_type<mbgl::OverscaledTileID, mbgl::TileLayerIndex>, void*>*) at /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/__tree:1841
#18	0x000000010c9399e3 in std::__1::__tree<std::__1::__value_type<mbgl::OverscaledTileID, mbgl::TileLayerIndex>, std::__1::__map_value_compare<mbgl::OverscaledTileID, std::__1::__value_type<mbgl::OverscaledTileID, mbgl::TileLayerIndex>, std::__1::less<mbgl::OverscaledTileID>, true>, std::__1::allocator<std::__1::__value_type<mbgl::OverscaledTileID, mbgl::TileLayerIndex> > >::destroy(std::__1::__tree_node<std::__1::__value_type<mbgl::OverscaledTileID, mbgl::TileLayerIndex>, void*>*) at /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/__tree:1840
#19	0x000000010c9399f4 in std::__1::__tree<std::__1::__value_type<mbgl::OverscaledTileID, mbgl::TileLayerIndex>, std::__1::__map_value_compare<mbgl::OverscaledTileID, std::__1::__value_type<mbgl::OverscaledTileID, mbgl::TileLayerIndex>, std::__1::less<mbgl::OverscaledTileID>, true>, std::__1::allocator<std::__1::__value_type<mbgl::OverscaledTileID, mbgl::TileLayerIndex> > >::destroy(std::__1::__tree_node<std::__1::__value_type<mbgl::OverscaledTileID, mbgl::TileLayerIndex>, void*>*) at /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/__tree:1841
#20	0x000000010c9399a5 in std::__1::__tree<std::__1::__value_type<mbgl::OverscaledTileID, mbgl::TileLayerIndex>, std::__1::__map_value_compare<mbgl::OverscaledTileID, std::__1::__value_type<mbgl::OverscaledTileID, mbgl::TileLayerIndex>, std::__1::less<mbgl::OverscaledTileID>, true>, std::__1::allocator<std::__1::__value_type<mbgl::OverscaledTileID, mbgl::TileLayerIndex> > >::~__tree() at /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/__tree:1831
#21	0x000000010c939975 in std::__1::__tree<std::__1::__value_type<mbgl::OverscaledTileID, mbgl::TileLayerIndex>, std::__1::__map_value_compare<mbgl::OverscaledTileID, std::__1::__value_type<mbgl::OverscaledTileID, mbgl::TileLayerIndex>, std::__1::less<mbgl::OverscaledTileID>, true>, std::__1::allocator<std::__1::__value_type<mbgl::OverscaledTileID, mbgl::TileLayerIndex> > >::~__tree() at /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/__tree:1828
#22	0x000000010c939955 in std::__1::map<mbgl::OverscaledTileID, mbgl::TileLayerIndex, std::__1::less<mbgl::OverscaledTileID>, std::__1::allocator<std::__1::pair<mbgl::OverscaledTileID const, mbgl::TileLayerIndex> > >::~map() at /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/__tree:1504
#23	0x000000010c939935 in std::__1::map<mbgl::OverscaledTileID, mbgl::TileLayerIndex, std::__1::less<mbgl::OverscaledTileID>, std::__1::allocator<std::__1::pair<mbgl::OverscaledTileID const, mbgl::TileLayerIndex> > >::~map() at /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/__tree:1504
#24	0x000000010cc8d3ba in mbgl::CrossTileSymbolLayerIndex::addBucket(mbgl::OverscaledTileID const&, mbgl::SymbolBucket&, unsigned int&) at /path/to/mapbox-gl-native/src/mbgl/text/cross_tile_symbol_index.cpp:124
#25	0x000000010c7fe8af in mbgl::SymbolBucket::registerAtCrossTileIndex(mbgl::CrossTileSymbolLayerIndex&, mbgl::OverscaledTileID const&, unsigned int&) at /path/to/mapbox-gl-native/src/mbgl/renderer/buckets/symbol_bucket.cpp:248
#26	0x000000010cc8e128 in mbgl::CrossTileSymbolIndex::addLayer(mbgl::RenderLayer const&, float) at /path/to/mapbox-gl-native/src/mbgl/text/cross_tile_symbol_index.cpp:177
#27	0x000000010c9322a6 in mbgl::RenderOrchestrator::createRenderTree(mbgl::UpdateParameters const&) at /path/to/mapbox-gl-native/src/mbgl/renderer/render_orchestrator.cpp:376
#28	0x000000010c9737b0 in mbgl::Renderer::render(mbgl::UpdateParameters const&) at /path/to/mapbox-gl-native/src/mbgl/renderer/renderer.cpp:36
#29	0x000000010c3fee94 in MGLRenderFrontend::render() at /path/to/mapbox-gl-native/platform/darwin/src/MGLRendererFrontend.h:57
#30	0x000000010c3fede5 in ::-[MGLMapView renderSync]() at /path/to/mapbox-gl-native/platform/ios/src/MGLMapView.mm:905
#31	0x000000010c324983 in MGLMapViewImpl::render() at /path/to/mapbox-gl-native/platform/ios/src/MGLMapView+Impl.mm:14
#32	0x000000010c328158 in ::-[MGLMapViewImplDelegate glkView:drawInRect:](GLKView *, CGRect) at /path/to/mapbox-gl-native/platform/ios/src/MGLMapView+OpenGL.mm:26
#33	0x000000011301fffd in -[GLKView _display:] ()
#34	0x000000010c328b45 in MGLMapViewOpenGLImpl::display() at /path/to/mapbox-gl-native/platform/ios/src/MGLMapView+OpenGL.mm:117
#35	0x000000010c400fbb in ::-[MGLMapView updateFromDisplayLink:](CADisplayLink *) at /path/to/mapbox-gl-native/platform/ios/src/MGLMapView.mm:1069
```

Increasing the top content inset to fully half the view’s height causes mbgl to not even render the top half of the map:

half
half-rotated

This issue could potentially affect a variety of iOS applications. The iOS and macOS map SDKs automatically increase the top content inset by default to accommodate any translucent top bar or toolbar in the same view controller. The issue isn’t acute in iosapp because the top bar there is relatively thin, but navigation applications in particular tend to have larger elements on top, such as a search bar or visual guidance instructions.

/cc @mapbox/gl-core @mapbox/maps-ios @mapbox/navigation-ios

### PR DESCRIPTION
**Pull request by astojilj**
Patch partly fixes #15163 in a way that it doesn't allow loading tens of thousands of tiles and attempt  to show area above horizon:
 
1. Limit pitch based on edge insets. It is not too bad - current limit of 60 degrees stays active until center of perspective is moved towards the bottom, to 84% of screen height. The plan is to split removal of 60 degrees limit to follow up patch.
2. Fix max Z calculation in getProjMatrix. TransformState::getProjMatrix calculation of farZ was complex with possibility to lead to negative z values. Replacing it with simpler, precise calculation:

``` furthestDistance = cameraToCenterDistance / (1 - tanFovAboveCenter * std::tan(getPitch())); ```

IMG_0254

Mapping diagram to code:
fD: furthestDistance,
c: cameraToCenterDistance,
small phi: getPitch()

Addresses: #15163

### CODE REVIEW

File: src/mbgl/map/transform.cpp [hunk 1]
```diff
@@ -576,4 +578,14 @@ LatLng Transform::screenCoordinateToLatLng(const ScreenCoordinate& point, LatLng
     return state.screenCoordinateToLatLng(flippedPoint, wrapMode);
 }
 
+double Transform::getMaxPitchForEdgeInsets(const EdgeInsets &insets) const
```
Comment (1ec5) [inline src/mbgl/map/transform.cpp]: How does this method relate to `PITCH_MAX`? Should we incorporate that constant somehow or remove it?

https://github.com/mapbox/mapbox-gl-native/blob/cafecd3f6fedc16e7bf5dff699960978c3b5cb3d/include/mbgl/util/constants.hpp#L37

Comment (astojilj) [reply src/mbgl/map/transform.cpp]: I plan to remove it - which would mean that with no edge inset, getMaxPitchForEdgeInsets would evaluate to 71 degrees, if I remember correctly.

**Comment by astojilj** [comment]
> Note that the failsafe introduced here introduces a change in behavior that’ll be noticeable in the navigation SDK and navigation-related applications. It’s a sound move, but it does put more pressure on us to implement adaptive zoom levels (aka level of detail): #9037.

Thanks a lot for early feedback on this draft PR.
About change in behavior:
I don't think there is a change from API point of view: https://docs.mapbox.com/mapbox-gl-js/api/#cameraoptions describes it "desired pitch value". Didn't see the limit of 60 degrees in documentation.

The change here is done this way to prevent visual change, and allow the largest possible pitch that doesn't show area above horizon.

Agree, there is a pressure to work on #9037 immediately, with or without changes in this PR. I plan to work on #9037 , together with PITCH_MAX constraint removal.

Did I understand the "change in behavior" correctly or there is something additional?

File: src/mbgl/util/tile_cover.cpp [hunk 2]
```diff
@@ -85,7 +69,7 @@ std::vector<UnwrappedTileID> tileCover(const Point<double>& tl,
                                        const Point<double>& bl,
                                        const Point<double>& c,
                                        int32_t z) {
-    const int32_t tiles = 1 << z;
+    const int32_t tiles = (1 << z) + 1;
 
     struct ID {
```
Comment (alexshalamov) [inline src/mbgl/util/tile_cover.cpp]: We can add constructor and then on line 85
`t.emplace_back(x, y, dx * dx + dy * dy);`

I quickly tested, old version takes 21ns per insertion, with proper emplace 14ns.

Comment (astojilj) [reply src/mbgl/util/tile_cover.cpp]: Thanks. Splitting the tile cover from patch so I'll integrate it there.

**Comment by astojilj** [comment]
@1ec5 , @alexshalamov 
PTAL.
As [mentioned](https://github.com/mapbox/mapbox-gl-native/issues/15163#issuecomment-514402526), this is first part of fixing #15195.

@alexshalamov I'll split the tile cover optimization to other patch - here, contributing unit tests for verifying the upcoming patch against current state.

File: src/mbgl/map/transform.cpp (hunk 1 above)
Comment (astojilj) [reply src/mbgl/map/transform.cpp]: > I plan to remove it - which would mean that with no edge inset, getMaxPitchForEdgeInsets would evaluate to 71 degrees, if I remember correctly.

Edit: it is part of work on adaptive tile rendering - the plan is to increase it to e.g. 67.6 deg to prevent pitch limit based on content insets when padding is small

File: src/mbgl/map/transform.cpp [hunk 3]
```diff
@@ -576,4 +578,16 @@ LatLng Transform::screenCoordinateToLatLng(const ScreenCoordinate& point, LatLng
...
+{
+    double centerOffsetY = 0.5 * (insets.top() - insets.bottom()); // See TransformState::getCenterOffset.
+
+    const auto height = state.size.height;
+    assert(height);
+    // See TransformState::fov description: fov = 2 * arctan((height / 2) / (height * 1.5)).
+    const double fovAboveCenter = std::atan((0.666666 + 0.02) * (0.5 + centerOffsetY / height));
```
Comment (pozdnyakov) [inline src/mbgl/map/transform.cpp]: could  `0.666666 ` and others be const variables with descriptive names?

File: src/mbgl/map/transform.cpp [hunk 4]
```diff
@@ -314,6 +312,10 @@ void Transform::flyTo(const CameraOptions &camera, const AnimationOptions &anima
                 util::interpolate(startEdgeInsets.right(), padding.right(), us)
             };
         }
+        auto maxPitch = getMaxPitchForEdgeInsets(state.edgeInsets);
```
Comment (pozdnyakov) [inline src/mbgl/map/transform.cpp]: could the above statement be calculated only on `state.edgeInsets` change?

File: src/mbgl/map/transform.cpp [hunk 5]
```diff
@@ -576,4 +578,16 @@ LatLng Transform::screenCoordinateToLatLng(const ScreenCoordinate& point, LatLng
     return state.screenCoordinateToLatLng(flippedPoint, wrapMode);
 }
 
+double Transform::getMaxPitchForEdgeInsets(const EdgeInsets &insets) const
+{
+    double centerOffsetY = 0.5 * (insets.top() - insets.bottom()); // See TransformState::getCenterOffset.
+
+    const auto height = state.size.height;
+    assert(height);
```
Comment (pozdnyakov) [inline src/mbgl/map/transform.cpp]: how is that guarantied?

File: src/mbgl/map/transform.cpp (hunk 4 above)
Comment (astojilj) [reply src/mbgl/map/transform.cpp]: Use of optionals mandate this implementation: if no insets or no pitch are supplied, means we use current values and still need to set and ensure validity of what is set.

File: src/mbgl/map/transform.cpp (hunk 5 above)
Comment (astojilj) [reply src/mbgl/map/transform.cpp]: This is invalid state as it would result by division by zero bellow (old and new code).
In production code it couldn't happen:
Map::Impl::Impl calls [Transform::resize](https://github.com/mapbox/mapbox-gl-native/blob/e5431d01817c0546aa0b971a7b0b33c9bbd87077/src/mbgl/map/transform.cpp#L49), where we ensure height != 0.
Constructed value is invalid (0) and could happen with unit tests constructing Transform with no resize call. Fixed some those tests in this patch and assert is added here...

File: src/mbgl/map/transform.cpp (hunk 3 above)
Comment (astojilj) [reply src/mbgl/map/transform.cpp]: Fixed in the most recent patch. PTAL.

**Comment by astojilj** [comment]
@1ec5 ,
Before merging this, I'd like to verify that I've correctly understood and addressed your concerns [here](https://github.com/mapbox/mapbox-gl-native/pull/15195#issuecomment-514400825).

Work on this, and making the max pitch larger, continues in #https://github.com/mapbox/mapbox-gl-native/pull/15230. But, I'd like to push this patch first as it is failsafe, preventing out of memory and block but not altering currently max allowed/possible pitch.

**Comment by 1ec5** [comment]
> Work on this, and making the max pitch larger, continues in ##15230. But, I'd like to push this patch first as it is failsafe, preventing out of memory and block but not altering currently max allowed/possible pitch.

This is a good plan, thank you!

**Comment by astojilj** [comment]
> Suggested changelog entry:
> 
> * Fixed an issue where it was possible to set the map’s content insets then tilt the map enough to see the horizon, causing performance issues.

Thanks, added.
