### PR TITLE
[ios] Set backup exclusion flag after initializing DefaultFileSource

### LINKED ISSUE #5112: MGLOfflineStorage iCloud Backup
We're using MGLOfflineStorage to download offline maps as shown in your example code. And it seems that downloaded data gets backed up to iCloud. Which is against Apple guidelines. Actually we found it out after being rejected. 

Steps to reproduce:

・Check iCloud backup size for an app in settings before downloading offline region.
・Check iCloud backup size after

### PR DESCRIPTION
**Pull request by friedbunny**
Speculatively fixes #5112, where apps mistakenly backup the offline/ambient cache.

This moves the backup exclusion flag to a point just after `DefaultFileSource` has been created/initialized, ensuring that this flag is set on every launch.

As with the other offline storage tests, the new `-testBackupExclusion` must be run in alphabetical order — or, at least after the cache has been initialized. The cache file will persist in the simulator when you run these tests locally.

/cc @1ec5

### CODE REVIEW

File: platform/darwin/test/MGLOfflineStorageTests.m [hunk 1]
```diff
@@ -97,6 +97,29 @@ - (void)testAddPack {
...
+
+    NSURL *cacheURL = [cacheDirectoryURL URLByAppendingPathComponent:@"cache.db"];
+    XCTAssertTrue([[NSFileManager defaultManager] fileExistsAtPath:cacheURL.path], @"Cache database should exist.");
+
+    NSError *error = nil;
+    NSNumber *exclusionFlag = nil;
+    [cacheURL getResourceValue:&exclusionFlag
+                        forKey:NSURLIsExcludedFromBackupKey
+                         error:&error];
+    XCTAssertTrue([exclusionFlag boolValue], @"Backup exclusion flag should be set for cache database.");
```
Comment (1ec5) [inline platform/darwin/test/MGLOfflineStorageTests.m]: Nit: check for `nil` before downcasting to a `BOOL`. Either would be a failure in this case, but this is a reminder in case we’ve made a similar assumption elsewhere.

Comment (friedbunny) [inline platform/darwin/test/MGLOfflineStorageTests.m]: Which would be the runtime behavior when `exclusionFlag == nil`?

```
(lldb) po [exclusionFlag boolValue]
<nil>

(lldb) p [exclusionFlag boolValue]
(BOOL) $2 = NO
```

`nil`, no?

Comment (1ec5) [inline platform/darwin/test/MGLOfflineStorageTests.m]: When `exclusionFlag` is `nil`, `[exclusionFlag boolValue]` is `NO`, just as if `exclusionFlag` had been equal to `@NO`. By invoking the `po` command, you’re treating the `BOOL` as an object pointer and attempting to print its `-description`, which is `nil`.

Comment (friedbunny) [inline platform/darwin/test/MGLOfflineStorageTests.m]: Added an extra check that `exclusionFlag` exists in 6becc07.
