### PR TITLE
Check for duplicate layer IDs

### LINKED ISSUE #7254: Throw exception when adding layer with duplicate ID
Similar to #7011, we should throw an exception when adding a layer to the style whose ID is already in use by another layer in the style. The style specification describes the [`id`](https://www.mapbox.com/mapbox-gl-style-spec/#layer-id) property on a layer as “unique”, and `mbgl::Map::getLayer()` relies on that fact.

Alternatively, it would be possible to silently replace the existing layer that has a matching ID. But I’d prefer that we make the developer explicitly replace the layer, since reusing an ID is most likely an unintentional error.

/cc @ivovandongen @jfirebaugh

### PR DESCRIPTION
**Pull request by ivovandongen**
Fixes #7254

### CODE REVIEW

**Comment by ivovandongen** [comment]
cc @1ec5 @jfirebaugh

File: platform/darwin/src/MGLStyle.mm [hunk 1]
```diff
@@ -190,7 +190,11 @@ - (void)addLayer:(MGLStyleLayer *)layer
          layer];
     }
 
-    self.mapView.mbglMap->addLayer(std::unique_ptr<mbgl::style::Layer>(layer.layer));
+    try {
+        self.mapView.mbglMap->addLayer(std::unique_ptr<mbgl::style::Layer>(layer.layer));
```
Comment (ivovandongen) [inline platform/darwin/src/MGLStyle.mm]: Added (tests) for `MGLStyle#insertLayer` and and `MGLMapView#insertCustomStyleLayerWithIdentifier`.

File: platform/ios/test/MGLLayerTests.m [hunk 2]
```diff
@@ -0,0 +1,25 @@
+#import "MGLMapViewTests.h"
```
Comment (ivovandongen) [inline platform/ios/test/MGLLayerTests.m]: Moved the files and added to macos as well. Excluded the custom layer tests for macos as the header is ios specific. Also changed the source test according to https://github.com/mapbox/mapbox-gl-native/pull/7203#discussion_r90384300

Comment (1ec5) [inline platform/ios/test/MGLLayerTests.m]: That’s fine; the custom style layer API is getting folded into the normal style layer API in #7250, so soon there won’t be anything extra to test.

File: platform/darwin/test/MGLLayerTests.m [hunk 3]
```diff
@@ -0,0 +1,43 @@
...
+    
+    //Try to insert the duplicate
+    XCTAssertThrowsSpecific([self.mapView.style insertLayer:layer3 belowLayer:layer1], NSException);
+    
+    #if TARGET_OS_IPHONE
+    //Try to insert a duplicate custom layer
+    MGLCustomStyleLayerPreparationHandler preparationHandler = ^{};
+    MGLCustomStyleLayerDrawingHandler drawingHandler = ^(CGSize size, CLLocationCoordinate2D centerCoordinate, double zoomLevel, CLLocationDirection direction, CGFloat pitch, CGFloat perspectiveSkew) {
+    };
+    MGLCustomStyleLayerCompletionHandler completionHander = ^{};
```
Comment (1ec5) [inline platform/darwin/test/MGLLayerTests.m]: FYI, feel free to inline these blocks into the method call. Long lines are par for the course in Objective-C. 😉

**Comment by 1ec5** [comment]
The iOS test failure appears to be what I fixed in #7228 on the release-ios-v3.4.0 branch.

**Comment by ivovandongen** [comment]
> The iOS test failure appears to be what I fixed in #7228 on the release-ios-v3.4.0 branch.

@1ec5 Could you merge this into master so I can rebase this pr on it?

File: platform/darwin/src/MGLStyle.mm [hunk 4]
```diff
@@ -211,7 +215,11 @@ - (void)insertLayer:(MGLStyleLayer *)layer belowLayer:(MGLStyleLayer *)otherLaye
     }
 
     const mbgl::optional<std::string> belowLayerId{otherLayer.identifier.UTF8String};
-    self.mapView.mbglMap->addLayer(std::unique_ptr<mbgl::style::Layer>(layer.layer), belowLayerId);
+    try {
+        self.mapView.mbglMap->addLayer(std::unique_ptr<mbgl::style::Layer>(layer.layer), belowLayerId);
```
Comment (1ec5) [inline platform/darwin/src/MGLStyle.mm]: Now that #7282 has landed, including the changes in #6097, you’ll need to wrap any call to `-[MGLStyleLayer addToMapView:]` in this try-catch block or alternatively move this try-catch block to every implementation of `-addToMapView:` in the concrete subclasses of MGLStyleLayer.

**Comment by ivovandongen** [comment]
@1ec5 I've rebased and updated the ios handling/tests: https://github.com/mapbox/mapbox-gl-native/pull/7257/commits/c005962117b3dda2ed663b482625c5ae62fa6333

File: platform/ios/src/MGLMapView.mm [hunk 5]
```diff
@@ -5353,9 +5353,13 @@ - (void)insertCustomStyleLayerWithIdentifier:(NSString *)identifier preparationH
...
     MGLCustomStyleLayerHandlers *context = new MGLCustomStyleLayerHandlers(preparation, drawing, completion);
-    _mbglMap->addLayer(std::make_unique<mbgl::style::CustomLayer>(identifier.UTF8String, MGLPrepareCustomStyleLayer,
-                                                                  MGLDrawCustomStyleLayer, MGLFinishCustomStyleLayer, context),
-                       otherIdentifier ? mbgl::optional<std::string>(otherIdentifier.UTF8String) : mbgl::optional<std::string>());
+    try {
+        _mbglMap->addLayer(std::make_unique<mbgl::style::CustomLayer>(identifier.UTF8String, MGLPrepareCustomStyleLayer,
+                                                                      MGLDrawCustomStyleLayer, MGLFinishCustomStyleLayer, context),
+                           otherIdentifier ? mbgl::optional<std::string>(otherIdentifier.UTF8String) : mbgl::optional<std::string>());
+    } catch (std::runtime_error & err) {
+        [NSException raise:@"MGLRedundantLayerIdentiferException" format:@"%s", err.what()];
```
Comment (1ec5) [inline platform/ios/src/MGLMapView.mm]: I just realized we’ve been saying “identifer” instead of “identifier”, both for layers and sources. I can fix that typo in a separate PR, since we also need to add a note to the documentation for the affected methods about `MGLRedundantLayerIdentifierException` ([prior art involving sources](https://github.com/mapbox/mapbox-gl-native/blob/93b5ea060237de22b347527f3dc95e6f7cdb7251/platform/darwin/src/MGLStyle.h#L204-L206)).

**Comment by ivovandongen** [comment]
@kkaefer I've added the backend guard in https://github.com/mapbox/mapbox-gl-native/pull/7257/commits/3f0c6c829443cec27764f025bcd87c6c3121a01b as you suggested and made `activate`/`deactivate` protected.

File: platform/ios/src/MGLMapView.mm (hunk 5 above)
Comment (1ec5) [inline platform/ios/src/MGLMapView.mm]: If you’re in a good spot to do it, can you rename `MGLRedundantLayerIdentiferException` to `MGLRedundantLayerIdentiferException`? I don’t think we have any instances of it in the release branch, so this is a good branch to do it in. I can take care of `MGLRedundantSourceIdentiferException` separately: #7314.

File: platform/darwin/src/MGLStyle.mm [hunk 6]
```diff
@@ -350,7 +358,11 @@ - (void)addLayer:(MGLStyleLayer *)layer
          layer];
     }
     [self willChangeValueForKey:@"layers"];
-    [layer addToMapView:self.mapView];
+    try {
+        [layer addToMapView:self.mapView];
+    } catch (std::runtime_error & err) {
```
Comment (kkaefer) [inline platform/darwin/src/MGLStyle.mm]: We're catching a generic exception here, but always forward a `MGLRedundantLayerIdentifierException`. What we should do long term is to convert all of the generic `std::runtime_error` into individual exception types, and to exception-specific catches that we can then forward.

File: src/mbgl/style/style.cpp [hunk 7]
```diff
@@ -198,6 +198,16 @@ Layer* Style::getLayer(const std::string& id) const {
 Layer* Style::addLayer(std::unique_ptr<Layer> layer, optional<std::string> before) {
     // TODO: verify source
 
+    //Guard against duplicate layer ids
```
Comment (kkaefer) [inline src/mbgl/style/style.cpp]: Code style is to have a space after `//`.

File: src/mbgl/style/style.cpp [hunk 8]
```diff
@@ -198,6 +198,16 @@ Layer* Style::getLayer(const std::string& id) const {
...
+    auto it = std::find_if(layers.begin(), layers.end(), [&](const auto& existing) {
+        return existing->getID() == layer->getID();
+    });
+
+    if (it != layers.end()) {
+        std::string msg = "Layer " + layer->getID() + " already exists";
+        throw std::runtime_error(msg.c_str());
```
Comment (kkaefer) [inline src/mbgl/style/style.cpp]: no need to to `c_str()` here; `std::runtime_error` also accepts `std::string`. You could change this to something like this;

```c++
throw std::runtime_error(std::string{"Layer "} + layer->getID() + " already exists");
```

File: test/style/style_layer.test.cpp [hunk 9]
```diff
@@ -268,3 +274,24 @@ TEST(Layer, Observer) {
...
+
+    //Add initial layer
+    style.addLayer(std::make_unique<LineLayer>("line", "unusedsource"));
+
+    //Try to add duplicate
+    try {
+        style.addLayer(std::make_unique<LineLayer>("line", "unusedsource"));
+        FAIL() << "Should not have been allowed to add a duplicate layer id";
+    } catch (std::runtime_error) {
+        //Expected
```
Comment (kkaefer) [inline test/style/style_layer.test.cpp]: Check message here

File: test/style/style_layer.test.cpp [hunk 10]
```diff
@@ -268,3 +274,24 @@ TEST(Layer, Observer) {
...
+    style.setJSON(util::read_file("test/fixtures/resources/style-unused-sources.json"));
+
+    //Add initial layer
+    style.addLayer(std::make_unique<LineLayer>("line", "unusedsource"));
+
+    //Try to add duplicate
+    try {
+        style.addLayer(std::make_unique<LineLayer>("line", "unusedsource"));
+        FAIL() << "Should not have been allowed to add a duplicate layer id";
+    } catch (std::runtime_error) {
```
Comment (kkaefer) [inline test/style/style_layer.test.cpp]: The rule for exceptions in C++ is to throw by value and catch a `const` reference

File: platform/darwin/src/MGLStyle.mm [hunk 11]
```diff
@@ -271,10 +271,18 @@ - (void)insertObject:(MGLStyleLayer *)styleLayer inLayersAtIndex:(NSUInteger)ind
         [NSException raise:NSRangeException
                     format:@"Cannot insert style layer at out-of-bounds index %lu.", (unsigned long)index];
     } else if (index == 0) {
-        [styleLayer addToMapView:self.mapView];
+        try {
+            [styleLayer addToMapView:self.mapView];
+        } catch (std::runtime_error & err) {
```
Comment (kkaefer) [inline platform/darwin/src/MGLStyle.mm]: `const`

File: platform/darwin/test/MGLStyleTests.mm [hunk 12]
```diff
@@ -165,6 +168,30 @@ - (void)testAddingLayersTwice {
...
+    MGLFillStyleLayer *initial = [[MGLFillStyleLayer alloc] initWithIdentifier:@"my-layer" source:source];
+    [self.mapView.style addLayer:initial];
+    
+    //Try to add the duplicate
+    XCTAssertThrowsSpecificNamed([self.mapView.style addLayer:[[MGLFillStyleLayer alloc] initWithIdentifier:@"my-layer" source:source]], NSException, @"MGLRedundantLayerIdentifierException");
+    XCTAssertThrowsSpecificNamed([self.mapView.style insertLayer:[[MGLFillStyleLayer alloc] initWithIdentifier:@"my-layer" source:source] belowLayer:initial],NSException, @"MGLRedundantLayerIdentifierException");
+    XCTAssertThrowsSpecificNamed([self.mapView.style insertLayer:[[MGLFillStyleLayer alloc] initWithIdentifier:@"my-layer" source:source] aboveLayer:initial], NSException, @"MGLRedundantLayerIdentifierException");
+    XCTAssertThrowsSpecificNamed([self.mapView.style insertLayer:[[MGLFillStyleLayer alloc] initWithIdentifier:@"my-layer" source:source] atIndex:0], NSException, @"MGLRedundantLayerIdentifierException");
+
+    #if TARGET_OS_IPHONE
```
Comment (kkaefer) [inline platform/darwin/test/MGLStyleTests.mm]: Macros are not indented

**Comment by ivovandongen** [comment]
@kkaefer Thanks for the review, I've addressed your notes.
