### PR TITLE
[core] Relayout tiles cherry-picked from the cache

### LINKED ISSUE #9900: Shuffling causes line-pitch/pitch15 to fail
Reproduced via:
```
$ node platform/node/test/render.test.js --recycle-map \
    icon-pitch-scaling/rotation-alignment-viewport \
    text-pitch-alignment/viewport-text-rotation-alignment-map \
    line-pitch/pitch15
* passed icon-pitch-scaling rotation-alignment-viewport
* ignore text-pitch-alignment viewport-text-rotation-alignment-map (https://github.com/mapbox/mapbox-gl-native/issues/9732)
* failed line-pitch pitch15
```

| expected | actual | diff |
|--|--|--|
| expected | actual | diff |

_Possibly_ related: https://github.com/mapbox/mapbox-gl-native/issues/9732

### PR DESCRIPTION
**Pull request by brunoabinader**
Imagine the following scenario:

1. A map is created with a given vector source `source`, layer `foo` and LatLngZoom position **1**.
Render occurs: A render tile for the tile coordinate corresponding to position 1 is created, passing layer `foo` via [tile.setLayers](https://github.com/mapbox/mapbox-gl-native/blob/master/src/mbgl/renderer/tile_pyramid.cpp#L143).

2. The map now goes to position **2**, far enough to be outside of the render source's tile pyramid. Also, a new layer `bar` is added to the style.
Render occurs: A render tile for the tile coordinate corresponding to position **2** is created.

3. The map now goes back to position **1**.
Render occurs: The previously cached/retained render tile generated for position **1** is reused, and no relayout is made because there were neither [layout differences](https://github.com/mapbox/mapbox-gl-native/blob/master/src/mbgl/renderer/renderer_impl.cpp#L207) nor [image diffs](https://github.com/mapbox/mapbox-gl-native/blob/master/src/mbgl/renderer/renderer_impl.cpp#L208-L210). Because `setLayout` never occurs, the tile renders without the layout from layer `bar` :boom:

This PR enforces relayout for _all_ retained tiles if `needsRelayout` is true - which includes not only those retained tiles that are actually rendered. Relayout is also needed when a previous layer associated with a given source has been removed.

Added `API.RecycleMapRefreshRenderTileLayers` utest to verify.

Fixes #9900.

### CODE REVIEW

File: src/mbgl/renderer/tile_pyramid.cpp [hunk 1]
```diff
@@ -66,6 +66,11 @@ void TilePyramid::update(const std::vector<Immutable<style::Layer::Impl>>& layer
     // If we need a relayout, abandon any cached tiles; they're now stale.
     if (needsRelayout) {
         cache.clear();
+
```
Comment (jfirebaugh) [inline src/mbgl/renderer/tile_pyramid.cpp]: I agree that cached and non-retained tiles need to be either discarded or updated, but I'm wondering about the specific choice you made. With these changes:

* Tiles that were already in the cache are discarded
* Tiles that are retained are updated (`setLayers` is called)
* Tiles that are not retained are updated and then go into the cache

Is that the best strategy? What makes it better than these alternatives:

* Discard both already cached and non-retained tiles
* Update both already cached and non-retained tiles

My instinct is to be pessimistic and go with the former -- assume that the cost of updating non-retained tiles is high compared to the likelihood that it'll be wasted work because the tile gets flushed from the cache before being retrieved.

File: src/mbgl/renderer/renderer_impl.cpp [hunk 2]
```diff
@@ -186,11 +186,22 @@ void Renderer::Impl::render(const UpdateParameters& updateParameters) {
         renderSources.emplace(entry.first, std::move(renderSource));
     }
 
+    const bool hasImageDiff = !(imageDiff.added.empty() && imageDiff.removed.empty() && imageDiff.changed.empty());
+
+    auto hasRemovedLayerWithSourceID = [&](const auto& sourceID) {
```
[the remark this answers is not in the document]
Comment (brunoabinader) [reply src/mbgl/renderer/renderer_impl.cpp]: Fair point - I believe we can also achieve that via integration test :+1: I'll leave this out of this PR for now.

File: src/mbgl/renderer/tile_pyramid.cpp (hunk 1 above)
Comment (brunoabinader) [reply src/mbgl/renderer/tile_pyramid.cpp]: Thanks for the thoughtful review @jfirebaugh - I can see now that updating tiles before caching them is actually a bad strategy - what we should be doing instead is updating when cherry-picking them in ```createTileFn```.

Also, I liked the _discard both cached and non-retained tiles when re-layout is needed_ approach. I have a solution for that, and am now going to work on the integration tests as suggested.

The cons I can see from disposing unused tiles upon re-layout are that we might end up doing more tile creation/destruction on specific use cases - but I don't think this should be the common case.

File: src/mbgl/renderer/renderer_impl.cpp (hunk 2 above)
[the remark this answers is not in the document]
Comment (brunoabinader) [reply src/mbgl/renderer/renderer_impl.cpp]: Good news: By updating tiles when cherry-picking them from the cache, we no longer need to worry about this particular issue.

**Comment by brunoabinader** [comment]
Updates after @jfirebaugh's review:
- Integration test added in https://github.com/mapbox/mapbox-gl-js/pull/5269.
- Depends on Node GeoJSON converter implemented in https://github.com/mapbox/mapbox-gl-native/pull/9961.

File: src/mbgl/renderer/tile_pyramid.cpp [hunk 3]
```diff
@@ -138,14 +138,12 @@ void TilePyramid::update(const std::vector<Immutable<style::Layer::Impl>>& layer
...
-                tile->setLayers(layers);
+            if (!tile) {
+                return nullptr;
             }
+            tile->setObserver(observer);
         }
-        if (!tile) {
-            return nullptr;
-        }
+        tile->setLayers(layers);
```
Comment (jfirebaugh) [inline src/mbgl/renderer/tile_pyramid.cpp]: I don't think this is the right fix -- forcing a tile to re-layout whenever it is retrieved from the cache negates most of the benefit of caching.

Comment (brunoabinader) [reply src/mbgl/renderer/tile_pyramid.cpp]: Agreed it is not ideal. In this case the other option left is to discard, but not save in cache stale tiles when needing relayout. This also works and now I realize this is the approach with less performance impact. I'll update the PR accordingly.

**Comment by brunoabinader** [comment]
@jfirebaugh current proposal now is in line with yours: _discard both already cached and non-retained tiles if needs relayout_.

File: src/mbgl/renderer/tile_pyramid.cpp [hunk 4]
```diff
@@ -185,15 +185,17 @@ void TilePyramid::update(const std::vector<Immutable<style::Layer::Impl>>& layer
 }
 
 // Moves all tiles to the cache except for those specified in the retain set.
-void TilePyramid::removeStaleTiles(const std::set<OverscaledTileID>& retain) {
+void TilePyramid::removeStaleTiles(const std::set<OverscaledTileID>& retain, const bool needsRelayout) {
```
Comment (jfirebaugh) [inline src/mbgl/renderer/tile_pyramid.cpp]: I'd just go ahead and inline `removeStaleTiles`... it's only called from the one place.
