### PR TITLE
[core] Mark tracked state as dirty when the tracked object is destroyed

### LINKED ISSUE #6469: [iOS] SIGABRT in src/mbgl/geometry/buffer.hpp:60
**Platform:** iPad
**Mapbox SDK version:** master as of 0f5b194617e0250280e0536794625a733a7d447e. clean build on my mac.

### Steps to trigger behavior

 1. play with the map until crash

### Expected behavior

No crash

### Actual behavior

Crashes with the following stack. Happend twice for me now after clean build of master as of now.

```
Thread 1Queue : com.apple.main-thread (serial)
#0	0x0000000185be6014 in __pthread_kill ()
#1	0x0000000185cad460 in pthread_kill ()
#2	0x0000000185b5a3f4 in abort ()
#3	0x00000001856252d4 in abort_message ()
#4	0x0000000185642ca8 in default_terminate_handler() ()
#5	0x0000000185650860 in _objc_terminate() ()
#6	0x000000018563f66c in std::__terminate(void (*)()) ()
#7	0x000000018563f6dc in std::terminate() ()
#8	0x00000001003fc804 in __clang_call_terminate ()
#9	0x00000001006e25e8 in mbgl::Buffer<16, 34962u, 8192, false>::bind(mbgl::gl::ObjectStore&, mbgl::gl::Config&)::'lambda'()::operator()() const::__MBGL_C_E::~__MBGL_C_E() at /Users/halset/projects/ext/mapbox-gl-native/src/mbgl/geometry/buffer.hpp:60
#10	0x00000001006e2580 in mbgl::Buffer<16, 34962u, 8192, false>::bind(mbgl::gl::ObjectStore&, mbgl::gl::Config&)::'lambda'()::operator()() const::__MBGL_C_E::~__MBGL_C_E() at /Users/halset/projects/ext/mapbox-gl-native/src/mbgl/geometry/buffer.hpp:60
#11	0x00000001006e2530 in mbgl::Buffer<16, 34962u, 8192, false>::bind(mbgl::gl::ObjectStore&, mbgl::gl::Config&)::'lambda'()::operator()() const at /Users/halset/projects/ext/mapbox-gl-native/src/mbgl/geometry/buffer.hpp:60
#12	0x00000001006e24e8 in mbgl::Buffer<16, 34962u, 8192, false>::bind(mbgl::gl::ObjectStore&, mbgl::gl::Config&) at /Users/halset/projects/ext/mapbox-gl-native/src/mbgl/geometry/buffer.hpp:60
#13	0x00000001006dfd70 in mbgl::Buffer<16, 34962u, 8192, false>::upload(mbgl::gl::ObjectStore&, mbgl::gl::Config&) at /Users/halset/projects/ext/mapbox-gl-native/src/mbgl/geometry/buffer.hpp:81
#14	0x00000001006dfba8 in mbgl::SymbolBucket::upload(mbgl::gl::ObjectStore&, mbgl::gl::Config&) at /Users/halset/projects/ext/mapbox-gl-native/src/mbgl/renderer/symbol_bucket.cpp:28
#15	0x00000001006d0430 in mbgl::Painter::render(mbgl::style::Style const&, mbgl::FrameData const&, mbgl::SpriteAtlas&) at /Users/halset/projects/ext/mapbox-gl-native/src/mbgl/renderer/painter.cpp:114
#16	0x00000001006978a8 in mbgl::Map::Impl::render() at /Users/halset/projects/ext/mapbox-gl-native/src/mbgl/map/map.cpp:266
#17	0x00000001006972cc in mbgl::Map::render() at /Users/halset/projects/ext/mapbox-gl-native/src/mbgl/map/map.cpp:173
#18	0x0000000100480280 in ::-[MGLMapView glkView:drawInRect:](GLKView *, CGRect) at /Users/halset/projects/ext/mapbox-gl-native/platform/ios/src/MGLMapView.mm:852
#19	0x0000000190b0fb50 in -[GLKView _display:] ()
#20	0x0000000100481384 in ::-[MGLMapView updateFromDisplayLink]() at /Users/halset/projects/ext/mapbox-gl-native/platform/ios/src/MGLMapView.mm:979
#21	0x0000000189e14640 in CA::Display::DisplayLinkItem::dispatch(unsigned long long) ()
#22	0x0000000189e144ec in CA::Display::DisplayLink::dispatch_items(unsigned long long, unsigned long long, unsigned long long) ()
#23	0x0000000186e84570 in IODispatchCalloutFromCFMessage ()
#24	0x0000000186bae56c in __CFMachPortPerform ()
#25	0x0000000186bc6934 in __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE1_PERFORM_FUNCTION__ ()
#26	0x0000000186bc60e8 in __CFRunLoopDoSource1 ()
#27	0x0000000186bc3bcc in __CFRunLoopRun ()
#28	0x0000000186af2048 in CFRunLoopRunSpecific ()
#29	0x0000000188575198 in GSEventRunModal ()
#30	0x000000018cac4818 in -[UIApplication _run] ()
#31	0x000000018cabf550 in UIApplicationMain ()
#32	0x00000001000af0e8 in main at /Users/halset/projects/NaVida/main.m:14
#33	0x0000000185ad45b8 in start ()
```

### LINKED ISSUE #6484: Crash in mbgl::Buffer when showing an annotation backed by sprite
**Platform:** iOS
**Mapbox SDK version:** `master` branch as of 9/27/2016

### Steps to trigger behavior

 1. Start iossim app
 2. Tap and hold to add a single annotation backed by a sprite (annotation classic)
 3. Pan back and forth a few times

### Expected behavior

No crash.

### Actual behavior

Crash with [this trace](https://gist.github.com/boundsj/c682cd8567fcc914de01bfe986270340)

### Additional notes

I'm able to reproduce this 100% of the time with the steps noted above on macOS Sierra, Xcode 8, and iPhone 6 **simulator**. So far I've been unable to reproduce on a device (I've only tried iPhone 7, iOS 10).

cc @incanus @1ec5 @jfirebaugh

### PR DESCRIPTION
**Pull request by jfirebaugh**
Fixes #6469
Fixes #6484

### CODE REVIEW

File: src/mbgl/gl/context.cpp [hunk 1]
```diff
@@ -61,6 +61,11 @@ void Context::setDirtyState() {
 
 void Context::performCleanup() {
     for (GLuint id : abandonedPrograms) {
+        for (const auto& p : abandonedPrograms) {
+            if (program == p) {
+                program.setDirty();
+            }
+        }
```
Comment (kkaefer) [inline src/mbgl/gl/context.cpp]: Great, this wouldn't have been possible yesterday ;)

**Comment by halset** [comment]
This fixes #6469 for me, thanks!
