### PR TITLE
[core] Fix ambiguous condition on the sort criteria

### LINKED ISSUE #7737: [core] Crash when simulating heavy user interaction
How to reproduce: create a fullscreen map and put on maximum tilt. Rotate the map quickly, simulating lots of tiles loading/unloading.

Linux backtrace:

```
#0  0x00007f0faa7d2bab in void std::__introsort_loop<__gnu_cxx::__normal_iterator<std::reference_wrapper<mbgl::RenderTile>*, std::vector<std::reference_wrapper<mbgl::RenderTile>, std::allocator<std::reference_wrapper<mbgl::RenderTile> > > >, long, __gnu_cxx::__ops::_Iter_comp_iter<mbgl::style::Style::getRenderData(mbgl::MapDebugOptions, float) const::{lambda(mbgl::RenderTile const&, mbgl::RenderTile const&)#2}> >(__gnu_cxx::__normal_iterator<std::reference_wrapper<mbgl::RenderTile>*, std::vector<std::reference_wrapper<mbgl::RenderTile>, std::allocator<std::reference_wrapper<mbgl::RenderTile> > > >, __gnu_cxx::__ops::_Iter_comp_iter<mbgl::style::Style::getRenderData(mbgl::MapDebugOptions, float) const::{lambda(mbgl::RenderTile const&, mbgl::RenderTile const&)#2}>, long, __gnu_cxx::__ops::_Iter_comp_iter<mbgl::style::Style::getRenderData(mbgl::MapDebugOptions, float) const::{lambda(mbgl::RenderTile const&, mbgl::RenderTile const&)#2}>) ()
   from /home/tmpsantos/Projects/mapbox-gl-native/build/qt-linux-x86_64/Release/libqmapboxgl.so
#1  0x00007f0faa7d2db7 in void std::__introsort_loop<__gnu_cxx::__normal_iterator<std::reference_wrapper<mbgl::RenderTile>*, std::vector<std::reference_wrapper<mbgl::RenderTile>, std::allocator<std::reference_wrapper<mbgl::RenderTile> > > >, long, __gnu_cxx::__ops::_Iter_comp_iter<mbgl::style::Style::getRenderData(mbgl::MapDebugOptions, float) const::{lambda(mbgl::RenderTile const&, mbgl::RenderTile open a mapconst&)#2}> >(__gnu_cxx::__normal_iterator<std::reference_wrapper<mbgl::RenderTile>*, std::vector<std::reference_wrapper<mbgl::RenderTile>, std::allocator<std::reference_wrapper<mbgl::RenderTile> > > >, __gnu_cxx::__ops::_Iter_comp_iter<mbgl::style::Style::getRenderData(mbgl::MapDebugOptions, float) const::{lambda(mbgl::RenderTile const&, mbgl::RenderTile const&)#2}>, long, __gnu_cxx::__ops::_Iter_comp_iter<mbgl::style::Style::getRenderData(mbgl::MapDebugOptions, float) const::{lambda(mbgl::RenderTile const&, mbgl::RenderTile const&)#2}>) ()
   from /home/tmpsantos/Projects/mapbox-gl-native/build/qt-linux-x86_64/Release/libqmapboxgl.so
#2  0x00007f0faa7d7349 in mbgl::style::Style::getRenderData(mbgl::MapDebugOptions, float) const ()
   from /home/tmpsantos/Projects/mapbox-gl-native/build/qt-linux-x86_64/Release/libqmapboxgl.so
#3  0x00007f0faa7b1c79 in mbgl::Painter::render(mbgl::style::Style const&, mbgl::FrameData const&, mbgl::View&, mbgl::SpriteAtlas&) ()
   from /home/tmpsantos/Projects/mapbox-gl-native/build/qt-linux-x86_64/Release/libqmapboxgl.so
#4  0x00007f0faa7a1499 in mbgl::Map::render(mbgl::View&) ()
   from /home/tmpsantos/Projects/mapbox-gl-native/build/qt-linux-x86_64/Release/libqmapboxgl.so
#5  0x000000000040537c in MapWindow::paintGL() ()
#6  0x00007f0faa22bdad in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#7  0x00007f0faa20cf88 in QWidget::event(QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#8  0x00007f0faa1ca05c in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#9  0x00007f0faa1cf516 in QApplication::notify(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#10 0x00007f0fa98d738b in QCoreApplication::notifyInternal(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#11 0x00007f0faa205a79 in QWidgetPrivate::sendPaintEvent(QRegion const&) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#12 0x00007f0faa1d6f21 in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#13 0x00007f0faa1d7a8c in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#14 0x00007f0faa1f5c1f in QWidgetPrivate::syncBackingStore() () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#15 0x00007f0faa20cd88 in QWidget::event(QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#16 0x00007f0faa1ca05c in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#17 0x00007f0faa1cf516 in QApplication::notify(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#18 0x00007f0fa98d738b in QCoreApplication::notifyInternal(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#19 0x00007f0fa98d9786 in QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*) ()
   from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#20 0x00007f0fa992d3c3 in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#21 0x00007f0fa72cb1a7 in g_main_context_dispatch () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#22 0x00007f0fa72cb400 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#23 0x00007f0fa72cb4ac in g_main_context_iteration () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#24 0x00007f0fa992d7cf in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) ()
   from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
```

@brunoabinader managed to reproduce also on OSX.

### PR DESCRIPTION
**Pull request by tmpsantos**
The previous sorting criteria would sometimes allow

C > B, B > A but A > C, making the internal std::sort
code sometimes point to an invalid reference.

Fixes #7737

### CODE REVIEW

File: src/mbgl/style/style.cpp [hunk 1]
```diff
@@ -456,13 +455,18 @@ RenderData Style::getRenderData(MapDebugOptions debugOptions, float angle) const
...
-                    a.id.canonical.y != b.id.canonical.y ? (isLeft ? sortY : !sortY) :
-                    a.id.wrap != b.id.wrap ? (isBottom ? sortW : !sortW) : (isBottom ? sortX : !sortX);
+                      [angle](const RenderTile& a, const RenderTile& b) {
+                Point<float> pa(a.id.canonical.x, a.id.canonical.y);
+                Point<float> pb(b.id.canonical.x, b.id.canonical.y);
+
+                auto par = util::rotate(pa, angle);
+                auto pbr = util::rotate(pb, angle);
+
+                if (par.y == pbr.y) {
```
Comment (jfirebaugh) [inline src/mbgl/style/style.cpp]: `return std::tie(par.y, par.x) < std::tie(pbr.y, pbr.x);`

Comment (tmpsantos) [inline src/mbgl/style/style.cpp]: Thanks, much better with `std::tie`. Done.
