### PR TITLE
Hook up hillshade style layers, raster DEM sources to iOS/macOS

### LINKED ISSUE #10991: Add darwin style code for raster-dem and hillshade
Per https://github.com/mapbox/mapbox-gl-native/pull/10642#discussion_r163034806

> Unfortunately, darwin-style-code is unable to automate the entire process of adding a new layer type, so some changes are still needed before this layer type can be used on iOS and macOS:

After #10642 ships we will need to:

* [x] Implement an MGLRasterDEMSource class
* [x] [Add the new files](https://github.com/mapbox/mapbox-gl-native/blob/master/platform/ios/DEVELOPING.md#adding-a-source-code-file) to the SDKs
   Otherwise the new MGLStyleLayer subclass doesn’t get included in the SDK.
* [x] [Add the new classes](https://github.com/mapbox/mapbox-gl-native/blob/master/platform/ios/DEVELOPING.md#making-a-type-or-constant-public) to the documentation table of contents
   Otherwise the new MGLStyleLayer subclass isn’t listed with the other subclasses in the jazzy documentation.
* [x] [Wrap the new layer type](https://github.com/mapbox/mapbox-gl-native/blob/2d15aed43c9faa875a8f625c3afc286f1175e0ce/platform/darwin/src/MGLStyle.mm#L388) in an Objective-C object in the runtime styling API
   Otherwise the runtime styling API may crash when introspecting the current style.
* [x] [Refine the new class’s documentation](https://github.com/mapbox/mapbox-gl-native/blob/2d15aed43c9faa875a8f625c3afc286f1175e0ce/platform/darwin/scripts/style-spec-overrides-v8.json#L11)
   Otherwise the API reference isn’t self-contained.
* [x] [Add an icon](https://github.com/mapbox/mapbox-gl-native/blob/master/platform/macos/app/StyleLayerIconTransformer.m) to represent this layer type in the sidebar of macosapp
   Otherwise terrain layers look blank in the sidebar.
* [x] Mention the new APIs in the changelogs
   Otherwise iOS developers won’t know about the new feature.

### PR DESCRIPTION
**Pull request by 1ec5**
This PR adds the MGLHillshadeStyleLayer class implemented in #10642 to the iOS and macOS map SDKs and implements a new MGLRasterDEMSource class to provide the data used by hillshade style layers. Along the way, the runtime styling code generation script had to be modified to treat hillshade style layers like raster style layers. Now MGLHillshadeStyleLayer is a subclass of MGLForegroundStyleLayer, just like MGLRasterStyleLayer.

Finally, a Debug ‣ Enhance Terrain menu item has been added to macosapp so that you can swap out any style’s Mapbox Terrain–based hillshading layers with a single Mapbox Terrain-RGB–based hillshading layer. The new layers are inserted in the same place as the old ones, though no effort is made to match the new layer’s appearance to the old layers’ appearance. That would be an interesting research project.

before after
**_Enhance!_**

<details>
<summary>Bloopers</summary>

terraformed

_The Mapbox Outdoors style has a single source that composites Mapbox Terrain with Mapbox Streets. So every layer is technically based on Mapbox Terrain. The Enhance Terrain command needed to remove only those based on the `hillshade` layer in Terrain._

</details>

Fixes #10991.

/cc @mollymerp @friedbunny

### CODE REVIEW

**Comment by lbud** [comment]
> Finally, a Debug ‣ Enhance Terrain menu item has been added to macosapp so that you can swap out any style’s Mapbox Terrain–based hillshading layers with a single Mapbox Terrain-RGB–based hillshading layer.

:smile:

File: platform/darwin/src/MGLRasterDEMSource.h [hunk 1]
```diff
@@ -0,0 +1,40 @@
...
+ <a href="https://www.mapbox.com/mapbox-gl-style-spec/#sources-raster-dem"><code>raster-dem</code></a>
+ source defined by the style JSON file is represented at runtime by an
+ `MGLRasterDEMSource` object that you can use to initialize new style layers.
+ You can also add and remove sources dynamically using methods such as
+ `-[MGLStyle addSource:]` and `-[MGLStyle sourceWithIdentifier:]`.
+
+ ### Example
+
+ ```swift
+ let source = MGLRasterDEMSource(identifier: "hills", tileURLTemplates: ["https://example.com/raster-rgb/{z}/{x}/{y}.png"], options: [
```
Comment (mollymerp) [inline platform/darwin/src/MGLRasterDEMSource.h]: can we use `mapbox://mapbox.terrain-rgb` url here so the example actually works if copied and pasted?

File: platform/darwin/src/MGLRasterDEMSource.h [hunk 2]
```diff
@@ -0,0 +1,40 @@
...
+     .minimumZoomLevel: 9,
+     .maximumZoomLevel: 16,
+     .tileSize: 512,
```
Comment (mollymerp) [inline platform/darwin/src/MGLRasterDEMSource.h]: is this assuming devicePixelRatio of 2? otherwise tilesize should be 256px

File: platform/darwin/src/MGLHillshadeStyleLayer.h [hunk 3]
```diff
@@ -24,8 +24,15 @@ typedef NS_ENUM(NSUInteger, MGLHillshadeIlluminationAnchor) {
 };
 
 /**
- Client-side hillshading visualization based on DEM data. Currently, the
- implementation only supports Mapbox Terrain RGB tiles
+ An `MGLHillshadeStyleLayer` is a style layer that renders raster <a
+ href="https://en.wikipedia.org/wiki/Digital_elevation_model">digital elevation
+ model</a> (DEM) tiles on the map.
```
[the remark this answers is not in the document]
Comment (1ec5) [reply platform/darwin/src/MGLHillshadeStyleLayer.h]: From that Wikipedia article, I gathered that _digital elevation model_ is a generic term, encompassing other formats like USGS DEM. Would Terrarium be considered a DEM format?

File: platform/darwin/src/MGLRasterDEMSource.h (hunk 1 above)
Comment (1ec5) [reply platform/darwin/src/MGLRasterDEMSource.h]: Few if any of these in-header examples work when copy-pasted. But since this one was so close to working, and since specifying a configuration URL is so much easier than specifying all the TileJSON parameters manually, I went ahead and implemented your suggestion.

File: platform/darwin/src/MGLHillshadeStyleLayer.h (hunk 3 above)
[the remark this answers is not in the document]
Comment (friedbunny) [reply platform/darwin/src/MGLHillshadeStyleLayer.h]: We should avoid being overly broad here, especially if it’s suggesting something we don’t currently support.

File: platform/macos/app/MapDocument.m [hunk 4]
```diff
@@ -739,6 +758,49 @@ - (IBAction)removeGraticuleLayer:(id)sender {
...
+            continue;
+        }
+        
+        if (source.mapboxTerrain) {
+            [terrainSourceIdentifiers addObject:source.identifier];
+        }
+    }
+    
+    // Find and remove all the style layers using those sources.
+    NSUInteger hillshadeIndex = NSNotFound;
```
Comment (friedbunny) [inline platform/macos/app/MapDocument.m]: [TIL.](https://developer.apple.com/documentation/foundation/nsnotfound)

File: platform/macos/app/resources/hillshade.svg [hunk 5]
```diff
@@ -0,0 +1,87 @@
...
+   xmlns:sodipodi="http://sodipodi.sourceforge.net/DTD/sodipodi-0.dtd"
+   xmlns:inkscape="http://www.inkscape.org/namespaces/inkscape"
+   width="16"
+   height="16"
+   viewBox="0 0 16 16"
+   id="svg4148"
+   version="1.1"
+   inkscape:version="0.92.2 5c3e80d, 2017-08-06"
+   sodipodi:docname="hillshade.svg"
+   inkscape:export-filename="/Users/mxn/Desktop/symbol.png"
```
Comment (friedbunny) [inline platform/macos/app/resources/hillshade.svg]: Not a big deal, but Inkscape sure does toss a lot of cruft into SVGs. There are a variety of SVG optimizers/minifiers out there, if you felt so inclined.

File: platform/darwin/src/MGLHillshadeStyleLayer.h (hunk 3 above)
[the remark this answers is not in the document]
Comment (1ec5) [reply platform/darwin/src/MGLHillshadeStyleLayer.h]: It’s true that we should avoid overpromising, but I think it’s also important to draw a connection to the MGLRasterDEMSource class, which does use the same terminology, since the type system doesn’t otherwise guide the developer towards using MGLHillshadeStyleLayer with MGLRasterDEMSource.

File: platform/macos/app/resources/hillshade.svg (hunk 5 above)
Comment (1ec5) [reply platform/macos/app/resources/hillshade.svg]: This would be good tail work, since all the SVGs in the platform/macos/app/resources/ folder are in Inkscape SVG format.

Comment (1ec5) [reply platform/macos/app/resources/hillshade.svg]: #11051
