### PR TITLE
Fix crash removing offline pack while another pack is downloading

### LINKED ISSUE #4286: iOS Offline bindings trigger assertion if pack is removed while another pack is downloading
Repro:

- resume a pack 
- attempt removePack for a previously completed pack
- trigger assertion "Cannot invalidate an already invalid offline pack.” in `MGLOfflinePack invalidate` (via `MGLOfflineStorage removePack`)

backtrace:

```
* thread #1: tid = 0x40c480, 0x000000018208bf48 libobjc.A.dylib`objc_exception_throw, queue = 'com.apple.main-thread', stop reason = breakpoint 1.2
    frame #0: 0x000000018208bf48 libobjc.A.dylib`objc_exception_throw
    frame #1: 0x0000000182a1d7d0 CoreFoundation`+[NSException raise:format:arguments:] + 108
    frame #2: 0x000000018339099c Foundation`-[NSAssertionHandler handleFailureInMethod:object:file:lineNumber:description:] + 112
    frame #3: 0x00000001005d88dc Mapbox`-[MGLOfflinePack invalidate] + 184
    frame #4: 0x00000001005da684 Mapbox`-[MGLOfflineStorage removePack:withCompletionHandler:] + 108
  * frame #5: 0x00000001000cd588 Sirius`Sirius.ViewController.tableView (tableView=0x00000001558ffe00, editingStyle=Delete
```

cc @1ec5

### PR DESCRIPTION
**Pull request by 1ec5**
Remove all references to an offline pack before the call to `-[MGLOfflineStorage removePackWithCompletionHander:]`. Allow null completion handlers in MGLOfflineStorage APIs.

Fixes #4286.

/cc @boundsj

### CODE REVIEW

File: platform/ios/app/MBXOfflinePacksTableViewController.m [hunk 1]
```diff
@@ -164,12 +164,9 @@ - (UITableViewCell *)tableView:(UITableView *)tableView cellForRowAtIndexPath:(N
...
         MGLOfflinePack *pack = self.offlinePacks[indexPath.row];
-        __weak MBXOfflinePacksTableViewController *weakSelf = self;
-        [[MGLOfflineStorage sharedOfflineStorage] removePack:pack withCompletionHandler:^(NSError *error) {
-            MBXOfflinePacksTableViewController *strongSelf = weakSelf;
-            [strongSelf.offlinePacks removeObjectAtIndex:indexPath.row];
-            [strongSelf.tableView deleteRowsAtIndexPaths:@[indexPath] withRowAnimation:UITableViewRowAnimationAutomatic];
-        }];
+        [self.offlinePacks removeObjectAtIndex:indexPath.row];
+        [self.tableView deleteRowsAtIndexPaths:@[indexPath] withRowAnimation:UITableViewRowAnimationAutomatic];
+        [[MGLOfflineStorage sharedOfflineStorage] removePack:pack withCompletionHandler:NULL];
```
Comment (boundsj) [inline platform/ios/app/MBXOfflinePacksTableViewController.m]: nit: s/NULL/nil

**Comment by boundsj** [comment]
:+1:

File: platform/ios/app/MBXOfflinePacksTableViewController.m (hunk 1 above)
Comment (1ec5) [inline platform/ios/app/MBXOfflinePacksTableViewController.m]: I learned something today! :smile:

**Comment by 1ec5** [comment]
Cherry-picked into release-ios-3.2.0-android-4.0.0 branch as ac541290607e968343490c046e0d4e5f48471bba and 922269cd7c543df6b5e2b2c649e72099d9320262.
