### PR TITLE
[ios] Fallback to Mapbox.bundle as the framework bundle

### LINKED ISSUE #9072: String localization does not work when using the static framework
Our replacement [`NSLocalizedString` methods](https://github.com/mapbox/mapbox-gl-native/blob/a19fd817300abf00b81cba5765fda62c48057efa/platform/darwin/src/NSBundle%2BMGLAdditions.h#L20) rely on [`+[NSBundle mgl_frameworkBundle]`](https://github.com/mapbox/mapbox-gl-native/blob/a19fd817300abf00b81cba5765fda62c48057efa/platform/darwin/src/NSBundle%2BMGLAdditions.m#L7) to provide the Mapbox bundle that contains the localizations.

When using the static Mapbox.framework:
1. Localizations live in a separate Mapbox.bundle.
2. `+[NSBundle mgl_frameworkBundle]` returns the app bundle (not Mapbox.framework or Mapbox.bundle).

This means that localizations never load because we’re looking for them in the base app bundle, not Mapbox.bundle.

(Mapbox.bundle has existed for static builds since https://github.com/mapbox/mapbox-gl-native/pull/4455.)

## Why do images and such work?
For other resources that we load from the bundle, like [images](https://github.com/mapbox/mapbox-gl-native/blob/a19fd817300abf00b81cba5765fda62c48057efa/platform/ios/src/MGLMapView.mm#L5294-L5297) or [SSL certificates](https://github.com/mapbox/mapbox-gl-native/blob/a19fd817300abf00b81cba5765fda62c48057efa/platform/ios/src/MGLAPIClient.m#L120), we manually append `Mapbox.bundle` to the path using [`-[NSBundle mgl_resourcesDirectory]`](https://github.com/mapbox/mapbox-gl-native/blob/a19fd817300abf00b81cba5765fda62c48057efa/platform/darwin/src/NSBundle%2BMGLAdditions.m#L35):

```objc
NSBundle *frameworkBundle = [NSBundle mgl_frameworkBundle];
NSString *resource = [frameworkBundle pathForResource:@"somefile"
                                               ofType:@"extension"
                                          inDirectory:frameworkBundle.mgl_resourcesDirectory];
[NSData dataWithContentsOfFile:resource];
```

This works, but seems like incorrect behavior: shouldn’t we be treating Mapbox.bundle as _the_ bundle and not just a directory?

/cc @boundsj @1ec5

### PR DESCRIPTION
**Pull request by friedbunny**
Fixes #9072 and unblocks #9060. When using the static framework, load resources from Mapbox.bundle.

/cc @boundsj @1ec5

### CODE REVIEW

File: platform/darwin/src/NSBundle+MGLAdditions.m [hunk 1]
```diff
@@ -6,12 +6,13 @@ @implementation NSBundle (MGLAdditions)
...
     NSBundle *bundle = [self bundleForClass:[MGLAccountManager class]];
-    if (![bundle.infoDictionary[@"CFBundlePackageType"] isEqualToString:@"FMWK"] && !bundle.mgl_resourcesDirectory) {
+
+    if (![bundle.infoDictionary[@"CFBundlePackageType"] isEqualToString:@"FMWK"] && [bundle pathForResource:@"Mapbox" ofType:@"bundle"]) {
         // For static frameworks, the bundle is the containing application
-        // bundle but the resources are still in the framework bundle.
-        bundle = [NSBundle bundleWithPath:[bundle.privateFrameworksPath
-                                           stringByAppendingPathComponent:@"Mapbox.framework"]];
+        // bundle but the resources are in Mapbox.bundle.
+        bundle = [self bundleWithPath:[bundle pathForResource:@"Mapbox" ofType:@"bundle"]];
```
Comment (1ec5) [inline platform/darwin/src/NSBundle+MGLAdditions.m]: Perhaps refactor this change so that we don't look for Mapbox.bundle twice. This is asynchronous disk access, so I'd want to keep a light touch.

Comment (friedbunny) [inline platform/darwin/src/NSBundle+MGLAdditions.m]: I’d really like an `if let` right about now.

**Comment by friedbunny** [comment]
@1ec5 Do you think we should consider adding a warning or an exception if the SDK’s resource bundle can’t be found? It not existing would indicate a problem in most any situation I can imagine.

File: platform/darwin/src/NSBundle+MGLAdditions.m (hunk 1 above)
Comment (friedbunny) [inline platform/darwin/src/NSBundle+MGLAdditions.m]: → https://github.com/mapbox/mapbox-gl-native/pull/9074/commits/fd597d362a1e1d7d1fcea80e6bc00e23088b7838

File: platform/darwin/src/NSBundle+MGLAdditions.m [hunk 2]
```diff
@@ -6,12 +6,19 @@ @implementation NSBundle (MGLAdditions)
...
-        // bundle but the resources are still in the framework bundle.
-        bundle = [NSBundle bundleWithPath:[bundle.privateFrameworksPath
-                                           stringByAppendingPathComponent:@"Mapbox.framework"]];
+        // bundle but the resources are in Mapbox.bundle.
+        NSString *bundlePath = [bundle pathForResource:@"Mapbox" ofType:@"bundle"];
+        if (bundlePath) {
+            bundle = [self bundleWithPath:bundlePath];
+        } else {
+            [NSException raise:@"Bundle not found" format:
+             @"The Mapbox framework bundle could not be found in this app. If using the Mapbox iOS SDK as a static framework, make sure that Mapbox.bundle is copied into the root of the app bundle."];
```
Comment (1ec5) [inline platform/darwin/src/NSBundle+MGLAdditions.m]: I was going to suggest something really meta – that we should make this exception localizable like all the others – but then I realized doing so would preempt the exception with infinite recursion! 😆

File: platform/darwin/src/NSBundle+MGLAdditions.m [hunk 3]
```diff
@@ -6,12 +6,19 @@ @implementation NSBundle (MGLAdditions)
...
         // For static frameworks, the bundle is the containing application
-        // bundle but the resources are still in the framework bundle.
-        bundle = [NSBundle bundleWithPath:[bundle.privateFrameworksPath
-                                           stringByAppendingPathComponent:@"Mapbox.framework"]];
+        // bundle but the resources are in Mapbox.bundle.
+        NSString *bundlePath = [bundle pathForResource:@"Mapbox" ofType:@"bundle"];
+        if (bundlePath) {
+            bundle = [self bundleWithPath:bundlePath];
+        } else {
+            [NSException raise:@"Bundle not found" format:
```
Comment (1ec5) [inline platform/darwin/src/NSBundle+MGLAdditions.m]: Per #7258, the exception name should be camel-cased and prefixed with the class prefix.

Comment (friedbunny) [inline platform/darwin/src/NSBundle+MGLAdditions.m]: This has become `MGLBundleNotFoundException` in dbde3ca.
