### PR TITLE
[android] - fix polygon test activity

### LINKED ISSUE #6488: Crash recreating activity in PolygonActivity
I was able to trigger a crash rotating the PolygonActivity a couple of times:

Logcat:
```java
9-28 09:24:31.937 17138-17138/com.mapbox.mapboxsdk.testapp A/libc: ../../../src/mbgl/tile/geometry_tile_data.cpp:53: void mbgl::processPolynodeBranch(ClipperLib::PolyNode *, mbgl::GeometryCollection &): assertion "signedArea(rings.back()) > 0" failed
09-28 09:24:31.937 17138-17138/com.mapbox.mapboxsdk.testapp A/libc: Fatal signal 6 (SIGABRT), code -6 in tid 17138 (pboxsdk.testapp)
[ 09-28 09:24:31.939   167:  167 W/] debuggerd: handling request: pid=17138 uid=10181 gid=10181 tid=17138
09-28 09:24:32.016 17283-17283/? A/DEBUG: *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
09-28 09:24:32.016 17283-17283/? A/DEBUG: Build fingerprint: 'google/ryu/dragon:7.0/NRD90R/3141966:user/release-keys'
09-28 09:24:32.016 17283-17283/? A/DEBUG: Revision: '0'
09-28 09:24:32.016 17283-17283/? A/DEBUG: ABI: 'arm64'
09-28 09:24:32.016 17283-17283/? A/DEBUG: pid: 17138, tid: 17138, name: pboxsdk.testapp  >>> com.mapbox.mapboxsdk.testapp <<<
09-28 09:24:32.016 17283-17283/? A/DEBUG: signal 6 (SIGABRT), code -6 (SI_TKILL), fault addr --------
09-28 09:24:32.018 17283-17283/? A/DEBUG: Abort message: '../../../src/mbgl/tile/geometry_tile_data.cpp:53: void mbgl::processPolynodeBranch(ClipperLib::PolyNode *, mbgl::GeometryCollection &): assertion "signedArea(rings.back()) > 0" failed'
09-28 09:24:32.018 17283-17283/? A/DEBUG:     x0   0000000000000000  x1   00000000000042f2  x2   0000000000000006  x3   0000000000000008
09-28 09:24:32.018 17283-17283/? A/DEBUG:     x4   0064656c69616620  x5   0000000000000000  x6   0000000000000080  x7   0000000000000040
09-28 09:24:32.018 17283-17283/? A/DEBUG:     x8   0000000000000083  x9   ffffffffffffffdf  x10  0000000000000000  x11  0000000000000001
09-28 09:24:32.018 17283-17283/? A/DEBUG:     x12  0000000000000038  x13  0000000000000000  x14  0000000000000000  x15  0037df0a69b2a5d7
09-28 09:24:32.018 17283-17283/? A/DEBUG:     x16  0000007e32428ed0  x17  0000007e323d2a2c  x18  0000000000000000  x19  0000007e3387db40
09-28 09:24:32.018 17283-17283/? A/DEBUG:     x20  0000000000000006  x21  0000007e3387da98  x22  0000000000000009  x23  0000007fda2273d0
09-28 09:24:32.018 17283-17283/? A/DEBUG:     x24  0000007e0a4d7d98  x25  0000007e0a4d7d98  x26  0000007e15244344  x27  0000007e1087ae24
09-28 09:24:32.018 17283-17283/? A/DEBUG:     x28  0000007e0a88f620  x29  0000007fda227130  x30  0000007e323cfe58
09-28 09:24:32.018 17283-17283/? A/DEBUG:     sp   0000007fda227110  pc   0000007e323d2a34  pstate 0000000060000000
09-28 09:24:32.423 17283-17283/? A/DEBUG: backtrace:
09-28 09:24:32.423 17283-17283/? A/DEBUG:     #00 pc 000000000006ba34  /system/lib64/libc.so (tgkill+8)
09-28 09:24:32.423 17283-17283/? A/DEBUG:     #01 pc 0000000000068e54  /system/lib64/libc.so (pthread_kill+64)
09-28 09:24:32.423 17283-17283/? A/DEBUG:     #02 pc 0000000000023ed8  /system/lib64/libc.so (raise+24)
09-28 09:24:32.423 17283-17283/? A/DEBUG:     #03 pc 000000000001c790  /system/lib64/libc.so (abort+52)
09-28 09:24:32.423 17283-17283/? A/DEBUG:     #04 pc 0000000000020e88  /system/lib64/libc.so (__libc_fatal+104)
09-28 09:24:32.423 17283-17283/? A/DEBUG:     #05 pc 000000000001cba8  /system/lib64/libc.so (__assert2+48)
09-28 09:24:32.423 17283-17283/? A/DEBUG:     #06 pc 000000000014acdc  /data/app/com.mapbox.mapboxsdk.testapp-1/lib/arm64/libmapbox-gl.so
09-28 09:24:32.423 17283-17283/? A/DEBUG:     #07 pc 000000000014a7d0  /data/app/com.mapbox.mapboxsdk.testapp-1/lib/arm64/libmapbox-gl.so
09-28 09:24:32.423 17283-17283/? A/DEBUG:     #08 pc 000000000019c8cc  /data/app/com.mapbox.mapboxsdk.testapp-1/lib/arm64/libmapbox-gl.so
09-28 09:24:32.423 17283-17283/? A/DEBUG:     #09 pc 0000000000185c54  /data/app/com.mapbox.mapboxsdk.testapp-1/lib/arm64/libmapbox-gl.so
09-28 09:24:32.423 17283-17283/? A/DEBUG:     #10 pc 000000000018621c  /data/app/com.mapbox.mapboxsdk.testapp-1/lib/arm64/libmapbox-gl.so
09-28 09:24:32.423 17283-17283/? A/DEBUG:     #11 pc 0000000000199cc0  /data/app/com.mapbox.mapboxsdk.testapp-1/lib/arm64/libmapbox-gl.so
09-28 09:24:32.423 17283-17283/? A/DEBUG:     #12 pc 0000000000199ba0  /data/app/com.mapbox.mapboxsdk.testapp-1/lib/arm64/libmapbox-gl.so
09-28 09:24:32.423 17283-17283/? A/DEBUG:     #13 pc 000000000010686c  /data/app/com.mapbox.mapboxsdk.testapp-1/lib/arm64/libmapbox-gl.so
09-28 09:24:32.423 17283-17283/? A/DEBUG:     #14 pc 0000000000104dbc  /data/app/com.mapbox.mapboxsdk.testapp-1/lib/arm64/libmapbox-gl.so
09-28 09:24:32.423 17283-17283/? A/DEBUG:     #15 pc 0000000000109010  /data/app/com.mapbox.mapboxsdk.testapp-1/lib/arm64/libmapbox-gl.so
09-28 09:24:32.423 17283-17283/? A/DEBUG:     #16 pc 00000000000eaaf8  /data/app/com.mapbox.mapboxsdk.testapp-1/lib/arm64/libmapbox-gl.so
09-28 09:24:32.423 17283-17283/? A/DEBUG:     #17 pc 0000000000161268  /data/app/com.mapbox.mapboxsdk.testapp-1/lib/arm64/libmapbox-gl.so
09-28 09:24:32.423 17283-17283/? A/DEBUG:     #18 pc 0000000000160e7c  /data/app/com.mapbox.mapboxsdk.testapp-1/lib/arm64/libmapbox-gl.so
09-28 09:24:32.423 17283-17283/? A/DEBUG:     #19 pc 000000000001830c  /system/lib64/libutils.so (_ZN7android6Looper9pollInnerEi+916)
09-28 09:24:32.423 17283-17283/? A/DEBUG:     #20 pc 0000000000017eb8  /system/lib64/libutils.so (_ZN7android6Looper8pollOnceEiPiS1_PPv+60)
09-28 09:24:32.423 17283-17283/? A/DEBUG:     #21 pc 00000000000eb0e0  /system/lib64/libandroid_runtime.so (_ZN7android18NativeMessageQueue8pollOnceEP7_JNIEnvP8_jobjecti+48)
09-28 09:24:32.423 17283-17283/? A/DEBUG:     #22 pc 0000000001ebade0  /system/framework/arm64/boot-framework.oat (offset 0x163a000) (android.os.MessageQueue.nativePollOnce+140)
09-28 09:24:32.423 17283-17283/? A/DEBUG:     #23 pc 0000000001ebc9f0  /system/framework/arm64/boot-framework.oat (offset 0x163a000) (android.os.MessageQueue.next+236)
09-28 09:24:32.423 17283-17283/? A/DEBUG:     #24 pc 0000000001eb6738  /system/framework/arm64/boot-framework.oat (offset 0x163a000) (android.os.Looper.loop+340)
09-28 09:24:32.423 17283-17283/? A/DEBUG:     #25 pc 00000000016f2e28  /system/framework/arm64/boot-framework.oat (offset 0x163a000) (android.app.ActivityThread.main+516)
09-28 09:24:32.423 17283-17283/? A/DEBUG:     #26 pc 00000000000d1e68  /system/lib64/libart.so (art_quick_invoke_static_stub+600)
09-28 09:24:32.423 17283-17283/? A/DEBUG:     #27 pc 00000000000de8ac  /system/lib64/libart.so (_ZN3art9ArtMethod6InvokeEPNS_6ThreadEPjjPNS_6JValueEPKc+256)
09-28 09:24:32.423 17283-17283/? A/DEBUG:     #28 pc 000000000042974c  /system/lib64/libart.so (_ZN3artL18InvokeWithArgArrayERKNS_33ScopedObjectAccessAlreadyRunnableEPNS_9ArtMethodEPNS_8ArgArrayEPNS_6JValueEPKc+108)
09-28 09:24:32.424 17283-17283/? A/DEBUG:     #29 pc 000000000042b2b8  /system/lib64/libart.so (_ZN3art12InvokeMethodERKNS_33ScopedObjectAccessAlreadyRunnableEP8_jobjectS4_S4_m+1188)
09-28 09:24:32.424 17283-17283/? A/DEBUG:     #30 pc 00000000003a2398  /system/lib64/libart.so (_ZN3artL13Method_invokeEP7_JNIEnvP8_jobjectS3_S3_+56)
09-28 09:24:32.424 17283-17283/? A/DEBUG:     #31 pc 0000000000672038  /system/framework/arm64/boot.oat (offset 0x5a1000) (java.lang.reflect.Method.invoke+180)
09-28 09:24:32.424 17283-17283/? A/DEBUG:     #32 pc 0000000002572350  /system/framework/arm64/boot-framework.oat (offset 0x163a000) (com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run+124)
09-28 09:24:32.424 17283-17283/? A/DEBUG:     #33 pc 00000000025735ac  /system/framework/arm64/boot-framework.oat (offset 0x163a000) (com.android.internal.os.ZygoteInit.main+1432)
09-28 09:24:32.424 17283-17283/? A/DEBUG:     #34 pc 00000000000d1e68  /system/lib64/libart.so (art_quick_invoke_static_stub+600)
09-28 09:24:32.424 17283-17283/? A/DEBUG:     #35 pc 00000000000de8ac  /system/lib64/libart.so (_ZN3art9ArtMethod6InvokeEPNS_6ThreadEPjjPNS_6JValueEPKc+256)
09-28 09:24:32.424 17283-17283/? A/DEBUG:     #36 pc 000000000042974c  /system/lib64/libart.so (_ZN3artL18InvokeWithArgArrayERKNS_33ScopedObjectAccessAlreadyRunnableEPNS_9ArtMethodEPNS_8ArgArrayEPNS_6JValueEPKc+108)
09-28 09:24:32.424 17283-17283/? A/DEBUG:     #37 pc 00000000004293a4  /system/lib64/libart.so (_ZN3art17InvokeWithVarArgsERKNS_33ScopedObjectAccessAlreadyRunnableEP8_jobjectP10_jmethodIDSt9__va_list+380)
09-28 09:24:32.424 17283-17283/? A/DEBUG:     #38 pc 00000000003440c4  /system/lib64/libart.so (_ZN3art3JNI21CallStaticVoidMethodVEP7_JNIEnvP7_jclassP10_jmethodIDSt9__va_list+600)
09-28 09:24:32.424 17283-17283/? A/DEBUG:     #39 pc 000000000009bd44  /system/lib64/libandroid_runtime.so
09-28 09:24:32.424 17283-17283/? A/DEBUG:     #40 pc 000000000009e380  /system/lib64/libandroid_runtime.so (_ZN7android14AndroidRuntime5startEPKcRKNS_6VectorINS_7String8EEEb+708)
09-28 09:24:32.424 17283-17283/? A/DEBUG:     #41 pc 000000000000225c  /system/bin/app_process64
09-28 09:24:32.424 17283-17283/? A/DEBUG:     #42 pc 000000000001a514  /system/lib64/libc.so (__libc_init+88)
09-28 09:24:32.424 17283-17283/? A/DEBUG:     #43 pc 0000000000001cc8  /system/bin/app_process64
                                          
                                          
                                          [ 09-28 09:24:33.082   167:  167 W/         ]
                                          debuggerd: resuming target 17138
```

ndk-stack:

```java
********** Crash dump: **********
Build fingerprint: 'google/ryu/dragon:7.0/NRD90R/3141966:user/release-keys'
pid: 21096, tid: 21096, name: pboxsdk.testapp  >>> com.mapbox.mapboxsdk.testapp <<<
signal 6 (SIGABRT), code -6 (SI_TKILL), fault addr --------
Stack frame #00 pc 00049d64  /system/lib/libc.so (tgkill+12)
Stack frame #01 pc 00047503  /system/lib/libc.so (pthread_kill+34)
Stack frame #02 pc 0001d855  /system/lib/libc.so (raise+10)
Stack frame #03 pc 000193a1  /system/lib/libc.so (__libc_android_abort+34)
Stack frame #04 pc 00017014  /system/lib/libc.so (abort+4)
Stack frame #05 pc 0001b84f  /system/lib/libc.so (__libc_fatal+22)
Stack frame #06 pc 0001959b  /system/lib/libc.so (__assert2+18)
Stack frame #07 pc 00133bb4  /data/app/com.mapbox.mapboxsdk.testapp-1/lib/arm/libmapbox-gl.so: Routine mbgl::processPolynodeBranch(ClipperLib::PolyNode*, mbgl::GeometryCollection&) at /Users/nurbot/mapbox-gl-native/build/android-arm-v7/Debug/../../../src/mbgl/tile/geometry_tile_data.cpp:53 (discriminator 2)
Stack frame #08 pc 00133848  /data/app/com.mapbox.mapboxsdk.testapp-1/lib/arm/libmapbox-gl.so: Routine mbgl::fixupPolygons(mbgl::GeometryCollection const&) at /Users/nurbot/mapbox-gl-native/build/android-arm-v7/Debug/../../../src/mbgl/tile/geometry_tile_data.cpp:83
Stack frame #09 pc 0018f3e4  /data/app/com.mapbox.mapboxsdk.testapp-1/lib/arm/libmapbox-gl.so: Routine mbgl::ShapeAnnotationImpl::updateTileData(mbgl::CanonicalTileID const&, mbgl::AnnotationTileData&) at /Users/nurbot/mapbox-gl-native/build/android-arm-v7/Debug/../../../src/mbgl/annotation/shape_annotation_impl.cpp:53
Stack frame #10 pc 001751c0  /data/app/com.mapbox.mapboxsdk.testapp-1/lib/arm/libmapbox-gl.so: Routine mbgl::AnnotationManager::getTileData(mbgl::CanonicalTileID const&) at /Users/nurbot/mapbox-gl-native/build/android-arm-v7/Debug/../../../src/mbgl/annotation/annotation_manager.cpp:170 (discriminator 1)
Stack frame #11 pc 001757fc  /data/app/com.mapbox.mapboxsdk.testapp-1/lib/arm/libmapbox-gl.so: Routine mbgl::AnnotationManager::addTile(mbgl::AnnotationTile&) at /Users/nurbot/mapbox-gl-native/build/android-arm-v7/Debug/../../../src/mbgl/annotation/annotation_manager.cpp:215
Stack frame #12 pc 0018c628  /data/app/com.mapbox.mapboxsdk.testapp-1/lib/arm/libmapbox-gl.so: Routine AnnotationTile at /Users/nurbot/mapbox-gl-native/build/android-arm-v7/Debug/../../../src/mbgl/annotation/annotation_tile.cpp:15
Stack frame #13 pc 0018c534  /data/app/com.mapbox.mapboxsdk.testapp-1/lib/arm/libmapbox-gl.so: Routine std::__ndk1::__unique_if<mbgl::AnnotationTile>::__unique_single std::__ndk1::make_unique<mbgl::AnnotationTile, mbgl::OverscaledTileID const&, mbgl::style::UpdateParameters const&>(mbgl::OverscaledTileID const&, mbgl::style::UpdateParameters const&) at /Users/nurbot/mapbox-gl-native/mason_packages/osx-x86_64/android-ndk/arm-9-r12b/bin/../lib/gcc/arm-linux-androideabi/4.9.x/../../../../include/c++/4.9.x/memory:3047
Stack frame #14 pc 000ec8c8  /data/app/com.mapbox.mapboxsdk.testapp-1/lib/arm/libmapbox-gl.so: Routine operator() at /Users/nurbot/mapbox-gl-native/build/android-arm-v7/Debug/../../../src/mbgl/style/source_impl.cpp:122
Stack frame #15 pc 000ead70  /data/app/com.mapbox.mapboxsdk.testapp-1/lib/arm/libmapbox-gl.so: Routine void mbgl::algorithm::updateRenderables<mbgl::style::Source::Impl::updateTiles(mbgl::style::UpdateParameters const&)::$_0, mbgl::style::Source::Impl::updateTiles(mbgl::style::UpdateParameters const&)::$_1, mbgl::style::Source::Impl::updateTiles(mbgl::style::UpdateParameters const&)::$_3, mbgl::style::Source::Impl::updateTiles(mbgl::style::UpdateParameters const&)::$_2, std::__ndk1::vector<mbgl::UnwrappedTileID, std::__ndk1::allocator<mbgl::UnwrappedTileID> > >(mbgl::style::Source::Impl::updateTiles(mbgl::style::UpdateParameters const&)::$_0, mbgl::style::Source::Impl::updateTiles(mbgl::style::UpdateParameters const&)::$_1, mbgl::style::Source::Impl::updateTiles(mbgl::style::UpdateParameters const&)::$_3, mbgl::style::Source::Impl::updateTiles(mbgl::style::UpdateParameters const&)::$_2, std::__ndk1::vector<mbgl::UnwrappedTileID, std::__ndk1::allocator<mbgl::UnwrappedTileID> > const&, mbgl::Range<unsigned char> const&, unsigned char) at /Users/nurbot/mapbox-gl-native/build/android-arm-v7/Debug/../../../src/mbgl/algorithm/update_renderables.hpp:37
Stack frame #16 pc 000ef630  /data/app/com.mapbox.mapboxsdk.testapp-1/lib/arm/libmapbox-gl.so: Routine mbgl::style::Style::updateTiles(mbgl::style::UpdateParameters const&) at /Users/nurbot/mapbox-gl-native/build/android-arm-v7/Debug/../../../src/mbgl/style/style.cpp:216 (discriminator 2)
Stack frame #17 pc 000cdfb8  /data/app/com.mapbox.mapboxsdk.testapp-1/lib/arm/libmapbox-gl.so: Routine mbgl::Map::Impl::update() at /Users/nurbot/mapbox-gl-native/build/android-arm-v7/Debug/../../../src/mbgl/map/map.cpp:238 (discriminator 1)
Stack frame #18 pc 0014cae8  /data/app/com.mapbox.mapboxsdk.testapp-1/lib/arm/libmapbox-gl.so: Routine mbgl::util::RunLoop::Impl::processRunnables() at /Users/nurbot/mapbox-gl-native/build/android-arm-v7/Debug/../../../platform/android/src/run_loop.cpp:180
Stack frame #19 pc 0014d2c4  /data/app/com.mapbox.mapboxsdk.testapp-1/lib/arm/libmapbox-gl.so: Routine mbgl::util::RunLoop::runOnce() at /Users/nurbot/mapbox-gl-native/build/android-arm-v7/Debug/../../../platform/android/src/run_loop.cpp:238 (discriminator 2)
Stack frame #20 pc 0014c6a0  /data/app/com.mapbox.mapboxsdk.testapp-1/lib/arm/libmapbox-gl.so: Routine (anonymous namespace)::looperCallbackDefault(int, int, void*) at /Users/nurbot/mapbox-gl-native/build/android-arm-v7/Debug/../../../platform/android/src/run_loop.cpp:45
Stack frame #21 pc 00011e73  /system/lib/libutils.so (_ZN7android6Looper9pollInnerEi+610)
Stack frame #22 pc 00011b83  /system/lib/libutils.so (_ZN7android6Looper8pollOnceEiPiS1_PPv+26)
Stack frame #23 pc 0008e1d1  /system/lib/libandroid_runtime.so (_ZN7android18NativeMessageQueue8pollOnceEP7_JNIEnvP8_jobjecti+22)
Stack frame #24 pc 01b4eb65  /system/framework/arm/boot-framework.oat (offset 0x153f000) (android.os.MessageQueue.nativePollOnce+96)
Stack frame #25 pc 01b50071  /system/framework/arm/boot-framework.oat (offset 0x153f000) (android.os.MessageQueue.next+188)
Stack frame #26 pc 01b4b90b  /system/framework/arm/boot-framework.oat (offset 0x153f000) (android.os.Looper.loop+366)
Stack frame #27 pc 015c2ce7  /system/framework/arm/boot-framework.oat (offset 0x153f000) (android.app.ActivityThread.main+426)
Stack frame #28 pc 000a8f41  /system/lib/libart.so (art_quick_invoke_stub_internal+64)
Stack frame #29 pc 004015b9  /system/lib/libart.so (art_quick_invoke_static_stub+228)
Stack frame #30 pc 000b01ff  /system/lib/libart.so (_ZN3art9ArtMethod6InvokeEPNS_6ThreadEPjjPNS_6JValueEPKc+178)
Stack frame #31 pc 00312671  /system/lib/libart.so (_ZN3artL18InvokeWithArgArrayERKNS_33ScopedObjectAccessAlreadyRunnableEPNS_9ArtMethodEPNS_8ArgArrayEPNS_6JValueEPKc+56)
Stack frame #32 pc 00313a03  /system/lib/libart.so (_ZN3art12InvokeMethodERKNS_33ScopedObjectAccessAlreadyRunnableEP8_jobjectS4_S4_j+766)
Stack frame #33 pc 002bae89  /system/lib/libart.so (_ZN3artL13Method_invokeEP7_JNIEnvP8_jobjectS3_S3_+40)
Stack frame #34 pc 00603f39  /system/framework/arm/boot.oat (offset 0x56d000) (java.lang.reflect.Method.invoke+116)
Stack frame #35 pc 02031b39  /system/framework/arm/boot-framework.oat (offset 0x153f000) (com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run+100)
Stack frame #36 pc 020329b5  /system/framework/arm/boot-framework.oat (offset 0x153f000) (com.android.internal.os.ZygoteInit.main+1216)
Stack frame #37 pc 000a8f41  /system/lib/libart.so (art_quick_invoke_stub_internal+64)
Stack frame #38 pc 004015b9  /system/lib/libart.so (art_quick_invoke_static_stub+228)
Stack frame #39 pc 000b01ff  /system/lib/libart.so (_ZN3art9ArtMethod6InvokeEPNS_6ThreadEPjjPNS_6JValueEPKc+178)
Stack frame #40 pc 00312671  /system/lib/libart.so (_ZN3artL18InvokeWithArgArrayERKNS_33ScopedObjectAccessAlreadyRunnableEPNS_9ArtMethodEPNS_8ArgArrayEPNS_6JValueEPKc+56)
Stack frame #41 pc 00312483  /system/lib/libart.so (_ZN3art17InvokeWithVarArgsERKNS_33ScopedObjectAccessAlreadyRunnableEP8_jobjectP10_jmethodIDSt9__va_list+266)
Stack frame #42 pc 002757e3  /system/lib/libart.so (_ZN3art3JNI21CallStaticVoidMethodVEP7_JNIEnvP7_jclassP10_jmethodIDSt9__va_list+426)
Stack frame #43 pc 000635b9  /system/lib/libandroid_runtime.so
Stack frame #44 pc 00064e8b  /system/lib/libandroid_runtime.so (_ZN7android14AndroidRuntime5startEPKcRKNS_6VectorINS_7String8EEEb+498)
Stack frame #45 pc 00001947  /system/bin/app_process32
Stack frame #46 pc 00016c2d  /system/lib/libc.so (__libc_init+48)
Stack frame #47 pc 00001564  /system/bin/app_process32
```

Note that there is also a bug with how we restore the polygon, probably related:
ezgif com-video-to-gif 64

### PR DESCRIPTION
**Pull request by tobrun**
Closes #6488:
- Fixes state of Polygon when recreating (resolves crash)
- Refactor into static config inner class (thoughts?)
- Introduces a toolbar composer class (thoughts?)
- cleanup code PolygonActivity

Review @ivovandongen

### CODE REVIEW

File: platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/annotation/PolygonActivity.java [hunk 1]
```diff
@@ -95,15 +72,17 @@ protected void onCreate(Bundle savedInstanceState) {
         mapView.getMapAsync(this);
 
         // add to layout
-        ((ViewGroup) findViewById(R.id.container)).addView(mapView);
+        ViewGroup container = (ViewGroup) findViewById(R.id.container);
+        if(container!=null){
```
Comment (ivovandongen) [inline platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/annotation/PolygonActivity.java]: Nit: Some spaces would be nice

File: platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/annotation/PolygonActivity.java [hunk 2]
```diff
@@ -156,18 +135,14 @@ public boolean onOptionsItemSelected(MenuItem item) {
...
-                }
-                polygon.setPoints(POINTS);
+                polygon.setPoints(allPoints ? STAR_SHAPE_POINTS : BROKEN_SHAPE_POINTS);
                 return true;
 
             case R.id.action_id_color:
                 color = !color;
                 polygon.setFillColor(color ? BLUE_COLOR : RED_COLOR);
                 return true;
+
```
Comment (ivovandongen) [inline platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/annotation/PolygonActivity.java]: Nit: enter

File: platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/annotation/PolygonActivity.java [hunk 3]
```diff
@@ -178,4 +153,33 @@ public boolean onCreateOptionsMenu(Menu menu) {
         getMenuInflater().inflate(R.menu.menu_polygon, menu);
         return true;
     }
+
+    final static class Config{
```
Comment (ivovandongen) [inline platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/annotation/PolygonActivity.java]: space

File: platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/annotation/PolygonActivity.java [hunk 4]
```diff
@@ -178,4 +153,33 @@ public boolean onCreateOptionsMenu(Menu menu) {
...
+            add(new LatLng(45.515008, -122.664070));
+            add(new LatLng(45.502496, -122.669048));
+            add(new LatLng(45.515369, -122.678489));
+            add(new LatLng(45.506346, -122.702007));
+            add(new LatLng(45.522585, -122.685699));
+        }
+        };
+
+        static final List<LatLng> BROKEN_SHAPE_POINTS =
+                STAR_SHAPE_POINTS.subList(0, STAR_SHAPE_POINTS.size()-3);
```
Comment (ivovandongen) [inline platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/annotation/PolygonActivity.java]: Nit: spaces

File: platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/annotation/PolygonActivity.java [hunk 5]
```diff
@@ -178,4 +153,33 @@ public boolean onCreateOptionsMenu(Menu menu) {
...
+
+    final static class Config{
+        static final int BLUE_COLOR = Color.parseColor("#3bb2d0");
+        static final int RED_COLOR = Color.parseColor("#AF0000");
+
+        static final float FULL_ALPHA = 1.0f;
+        static final float PARTIAL_ALPHA = 0.5f;
+        static final float NO_ALPHA = 0.0f;
+
+        static final List<LatLng> STAR_SHAPE_POINTS = new ArrayList<LatLng>() {{
```
Comment (ivovandongen) [inline platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/annotation/PolygonActivity.java]: Interesting way of initialising the List!
