### PR TITLE
[ios, macos] Avoid implicit capture of MBGLOfflineRegionObserver this pointer

### LINKED ISSUE #6092: Unrecognized selector crash when suspending and removing MGLOfflinePack
Platform: iOS 9.3.4
Mapbox SDK version: 3.3.1
### Steps to trigger behavior

When I try to cancel the download of an MGLOfflinePack, i get this error:

```
-[NSTaggedPointerString offlineRegionStatusDidChange:]: unrecognized selector sent to instance 0xa0000000148344a4
2016-08-19 16:53:08.187 ChemPark[659:57661] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[NSTaggedPointerString offlineRegionStatusDidChange:]: unrecognized selector sent to instance 0xa0000000148344a4'
*** First throw call stack:
(0x181aa6db0 0x18110bf80 0x181aadc4c 0x181aaabec 0x1819a8c5c 0x100f484e4 0x102ba9a7c 0x102ba9a3c 0x102baf4e4 0x181a5cd50 0x181a5abb8 0x181984c50 0x18326c088 0x186c6e088 0x1002b1c70 0x1815228b8)
libc++abi.dylib: terminating with uncaught exception of type NSException
```

I am using this code for the task:

```
let packs = MGLOfflineStorage.sharedOfflineStorage().packs

        for pack in packs! {

            pack.suspend()

            MGLOfflineStorage.sharedOfflineStorage().removePack(pack, withCompletionHandler: nil)

        }
```

It seems similar to https://github.com/mapbox/mapbox-gl-native/issues/4394, except this issue only seems to happen if i cancel the download, not after successfully completing the download.
### Expected behavior

I was hoping to stop the download.
### Actual behavior

Crash

### PR DESCRIPTION
**Pull request by jfirebaugh**
`MBGLOfflineRegionObserver` is owned by the offline database thread, and might be destroyed by the time the `dispatch_async` completes. Instead of implicitly capturing `this`, capture a copy of the `MBGLOfflinePack` weak pointer.

Speculatively fixes #6092.

### CODE REVIEW

File: platform/darwin/src/MGLOfflinePack.mm [hunk 1]
```diff
@@ -227,19 +227,22 @@ - (void)didReceiveMaximumAllowedMapboxTiles:(uint64_t)limit {
 @end
 
 void MBGLOfflineRegionObserver::statusChanged(mbgl::OfflineRegionStatus status) {
+    __weak MBGLOfflinePack *_pack = pack;
```
Comment (1ec5) [inline platform/darwin/src/MGLOfflinePack.mm]: The class is called `MGLOfflinePack`, so the build is failing currently. The convention is to name the weak variable `weakPack` to more clearly distinguish the two variables.

**Comment by jfirebaugh** [comment]
Seems like the changelog entry will be easiest to add in the cherry pick to `release-boba`. Adding it here would produce conflict during the cherry pick and then again when merging release-boba back to master.
