### PR TITLE
[ios] Fix bug where scale bar shows 0 mm instead of 0

### LINKED ISSUE #15197: Scalebar shows 0 mm instead of 0
Hello!

From time to time, in non-standard locales (DE-de and EN-it)
the map scale starts showing the value `0 mm` instead of the classical `0`

### Configuration

**Mapbox SDK versions:** 5.1.0
**iOS/macOS versions:** iOS 12

### PR DESCRIPTION
**Pull request by jmkiley**
Fixes #15197 

Following the fix set out by @julianrex in https://github.com/mapbox/mapbox-gl-native/issues/15197#issuecomment-521087541

I would like to do some more testing around the observer for locale change.

### CODE REVIEW

File: platform/ios/src/MGLScaleBar.mm [hunk 1]
```diff
@@ -180,8 +180,17 @@ - (void)commonInit {
...
+
+    [[NSNotificationCenter defaultCenter] addObserver:self selector:@selector(resetLabelImageCache) name:NSCurrentLocaleDidChangeNotification object:nil];
 }
 
+- (void)dealloc {
+    [[NSNotificationCenter defaultCenter] removeObserver:self];
+}
+- (void)resetLabelImageCache {
+    self.labelImageCache = [[NSMutableDictionary alloc] init];
+
```
Comment (julianrex) [inline platform/ios/src/MGLScaleBar.mm]: We'll need to add a call to `[self addZeroLabel];` here.

**Comment by jmkiley** [comment]
I tested this PR using the repro code from https://github.com/mapbox/mapbox-gl-native/issues/15197#issuecomment-520750443

Devices/Simulators used:
- iPhone XR (simulator & physical device)
- iPad Pro 10.5" (simulator)
- iPhone X (physical device)
- iPhone 8 (physical device)
- iPad 9.7" (physical device)

Testing methods for the `0mm` fix:
1. Set the app's language and locale to German (Germany)/Germany, Japanese/Japan, Italian/Italy, or Arabic/Yemen. 
2. Zoom in and out on the map.
3. Send the app into the background
4. Bring the app back into the foreground and zoom in and out again.

To check the locale update:
1. Send the app to the background.
2. Change the language/locale in the device settings.
3. Bring the app back to the foreground.
