### PR TITLE
 [ios] Fix pinch drift ignoring delegate camera change response

### LINKED ISSUE #11422: Pinch gesture can escape delegate-limited bounds
**Platform:** iOS
**Mapbox SDK version:** 3.7.4, 3.7.5

### Steps to trigger behavior

 1. Try to limit the user’s ability to move outside a coordinate bounds with `-[MGLMapViewDelegate mapView:shouldChangeFromCamera:toCamera:]`, [as with this example](https://github.com/mapbox/ios-sdk-examples/blob/cdff47276d261d58c7eb2d0ba75d9cce6c308417/Examples/ObjectiveC/BlockingGesturesDelegateExample.m).
 2. Pinch zoom, such that it triggers inertial deceleration.

### Expected behavior
Map is limited to specified coordinate bounds.

### Actual behavior
User can break out of limited bounds with a pinch gesture that decelerates beyond said bounds. Once beyond the bounds, the deceleration movement for pinch gestures continues to work but the initial pinch is blocked.

#### Notes
- Bisects back to 9ee99c9 (#11151), so this was a regression in `ios-v3.7.4`.
- Pan deceleration stops at bounds, as expected.
- This issue does not exist when `MGLMapView.decelerationRate` is set to `MGLMapViewDecelerationRateImmediate` (i.e., disabling gesture deceleration).

/cc @julianrex

### PR DESCRIPTION
**Pull request by friedbunny**
Fixes #11422, where the pinch gesture could drift beyond the bounds imposed by `-[MGLMapViewDelegate mapView:shouldChangeFromCamera:toCamera:]`.

This doesn’t add a unit test, but does add a debug option to iosapp.

/cc @julianrex @fabian-guerra @lilykaiser

### CODE REVIEW

File: platform/ios/src/MGLMapView.mm [hunk 1]
```diff
@@ -1459,10 +1459,12 @@ - (void)handlePinchGesture:(UIPinchGestureRecognizer *)pinch
         double zoom = log2(newScale);
         MGLMapCamera *toCamera = [self cameraByZoomingToZoomLevel:zoom aroundAnchorPoint:centerPoint];
 
-        if ([self _shouldChangeFromCamera:oldCamera toCamera:toCamera])
+        if ( ! [self _shouldChangeFromCamera:oldCamera toCamera:toCamera])
```
Comment (friedbunny) [inline platform/ios/src/MGLMapView.mm]: This is the key line — if the response from the delegate is `NO` we shouldn’t drift. Previously, this would always allow drifting because, if the delegate responded `NO` it would move on to the following `else`.
