### PR TITLE
Clear RenderGeoJSONSource tilePyramid if no data is available

### LINKED ISSUE #9868: Asynchronism between style and render style causing rendering failures in still mode
With https://github.com/mapbox/mapbox-gl-native/pull/9689, we're adding an option for recycling the map object when running our render tests. These should be all passing now, except that occasionally you'll get at least one of the `geojson/external-*` render tests to fail.

When these tests fail, you can see from the rendering results that the test is using geometry data from a previous test run e.g. if the last test run was `geojson/external-failure` and the current one is `geojson/external-invalid`, you'll occasionally get the rendering result from `external-failure` in `external-invalid`.

Here's my understanding of the GeoJSON source workflow so far:

In still mode, there are multiple calls for `Map::Impl::update`, and each call creates a new `UpdateParameters` object which contains, among other things, data from all the style's sources implementations. These calls triggers the renderer frontend to eventually invalidate the renderer and force it to render, using the last-received `UpdateParameters`. We have safeguards in the renderer implementation that checks whether both the style and render style are loaded before notifying the still image requester that we ended up rendering. For a style to be loaded, we need all its sources to be also in loaded state - and in the case of GeoJSONSource, when its data is set via `setUrl`, it only goes to `loaded` state after receiving a reply from the file source request for that given URL (notifying the style via `onSourceLoaded`).

However, for some unknown reason, we're either not rendering the last-received `UpdateParameters` or failing to notify the renderer that the render style data needs to be updated.

### PR DESCRIPTION
**Pull request by brunoabinader**
In some circumstances, two different objects might get the same memory address if the former has been deleted before the latter gets constructed. Thus, we cannot rely solely on pointer comparsion when checking whether to update the tile data in `RenderGeoJSONSource::tylePiramid`.

Fixes #9868.

### CODE REVIEW

File: src/mbgl/renderer/sources/render_geojson_source.cpp [hunk 1]
```diff
@@ -38,8 +38,9 @@ void RenderGeoJSONSource::update(Immutable<style::Source::Impl> baseImpl_,
         return;
     }
 
-    if (data_ != data) {
+    if (data_ != data || data_->needsUpdate) {
```
Comment (kkaefer) [inline src/mbgl/renderer/sources/render_geojson_source.cpp]: Given that we're already checking `needsUpdate`, we can remove the pointer comparison altogether.

**Comment by jfirebaugh** [comment]
Are you sure this is the issue? I considered this possibility when I wrote this code, and concluded it wasn't possible:

* `GeoJSONData` is owned by `GeoJSONSource::Impl`
* `GeoJSONSource::Impl` is held in an `Immutable`
* `RenderGeoJSONSource` shared ownership of an `Immutable<GeoJSONSource::Impl>` (in the base `RenderSource`)
* In `RenderGeoJSONSource::update`, the baseImpls are swapped at the beginning of the function, so it's possible that _at the time of the comparison_, `data` is no longer valid. But we can say that _when RenderGeoJSONSource::update begins execution_:
   * `data` is live, because it's a pointer to the same `data` in the ownership chain above, which was live at that point
   * and obviously `baseImpl_` and its `data_` is live since it's a function parameter.
   * → Therefore both objects were live at one point, so their pointers can't be equal

**Comment by brunoabinader** [comment]
OK, let's get back to the following assumptions:

1. The test fails when the map object already contains a style object, including its sources and layers.
2. Whenever parsing a style, `Style::Impl` clears all sources and layers
2. When a source is removed, we don't immediately delete its impl if there is a reference for it in a render source created on a previous render step.

This guarantees the pointer comparison arithmetic would be valid by following the ownership chain described in https://github.com/mapbox/mapbox-gl-native/pull/9883#issuecomment-325672560.

_However_, there is an exception:

When `data` is null (which occurs when `GeoJSONSource` is created, but the file source lambda in `GeoJSONSource::loadDescription` has not yet finished fetching the source), we [early return](https://github.com/mapbox/mapbox-gl-native/blob/master/src/mbgl/renderer/sources/render_geojson_source.cpp#L37) without updating `data` - which might now point to a non-living source data. In the next source update, if the new source data has the same memory address as the new one, then 💥  (see printf backtrace below):

```
[0x101e174c8] GeoJSONSource::Impl::Impl
[0x101e167e0] RenderGeoJSONSource::update (old data: 0x101e18ac0 new data: 0x0)
[0x101e19918] GeoJSONSource::Impl::~Impl
[0x101e18ac0] GeoJSONData::~GeoJSONData
[0x101e17f70] GeoJSONSource::operator() (parsed baseImpl)
[0x101e1f958] GeoJSONSource::Impl::Impl (other: 0x101e174c8)
[0x101e18ac0] GeoJSONData::GeoJSONData
[0x101e167e0] RenderGeoJSONSource::update (old data: 0x101e18ac0 new data: 0x101e18ac0)
[0x101e174c8] GeoJSONSource::Impl::~Impl
* failed geojson external-linestring
```

In sum: we could also _solve_ this problem by always updating `data` before checking whether it is valid or not and early returning.

**Comment by jfirebaugh** [comment]
Ahh, good analysis -- I hadn't considered that possibility.

> In sum: we could also solve this problem by always updating data before checking whether it is valid or not and early returning.

Yeah, that sounds like the correct approach. Corrected version would be something like:

```
    if (data_ != data) {
        data = data_;
        tilePyramid.cache.clear();

        if (data) {
            for (auto const& item : tilePyramid.tiles) {
                static_cast<GeoJSONTile*>(item.second.get())->updateData(data->getTile(item.first.canonical));
            }
        } else {
            // clear existing tiles
        }
    }
```
