### PR TITLE
[core] fix flickering caused by incorrect ClipIDs

### LINKED ISSUE #12981: [core] ClipIDGenerator bug causing flicker on fill (probably all clipped) layers when using multiple sources
I am pretty confident that #12868, #11877, #12790 are all related to a bug with clip id generation causing incorrect clipping when using multiple sources for clipped layers. I'm currently working on diagnosing and fixing it.

Going to close those issues and concentrate discussion on this ticket. 

Also another part of #12868 is that I don't think we should be prefetching annotation tiles (similar to geojson tiles as addressed in #12529)

cc @kkaefer

### PR DESCRIPTION
**Pull request by mollymerp**
fix #12981 

need to add unit test and possibly render tests

### CODE REVIEW

**Comment by LukasPaczos** [comment]
I tested this one quickly and can't reproduce issues mentioned in https://github.com/mapbox/mapbox-gl-native/issues/11877 :rocket:

**Comment by mb12** [comment]
@mollyperp Can you please kindly clarify the following?

1)  Is it possible to explain why/how incorrect clip id results in flickering visual artifacts? Is the flicker result of an over zoomed parent tile overlapping onto some other tile because it has not been clipped?

2) Also is it possible to  why clipping is needed for correct rendering ( at a logical level) and how it works?

**Comment by mourner** [comment]
@mollymerp I'm wondering — could this also fix #12452? That problem also seems related to clip ids (a flicker of buffers outside of tiles on zoom).

**Comment by mollymerp** [comment]
@mourner yep looks like it could be the same issue. will check and let you know.

**Comment by mollymerp** [comment]
@mourner just confirmed this change also fixes #12452 🎉

File: src/mbgl/algorithm/generate_clip_ids_impl.hpp [hunk 1]
```diff
@@ -64,7 +64,7 @@ void ClipIDGenerator::update(std::vector<std::reference_wrapper<Renderable>> ren
         uint8_t count = 1;
         for (auto& it : renderables) {
             auto& renderable = it.get();
-            if (!renderable.used) {
+            if (!renderable.used || !renderable.needsClipping) {
```
Comment (sansumbrella) [inline src/mbgl/algorithm/generate_clip_ids_impl.hpp]: Any feeling on `!(renderable.used && renderable.needsClipping)` instead? It has the same results as the above expression for all four `bool, bool` permutations.

Comment (lbud) [reply src/mbgl/algorithm/generate_clip_ids_impl.hpp]: Interesting nit @sansumbrella — I'm curious about your reasoning behind this comment? In general I find code reviews to be most helpful when they express suggestions about improving functionality, efficiency, or readability, rather than simply suggesting a different way to write the same thing (with the same or, theoretically, [slightly worse](https://en.wikipedia.org/wiki/Short-circuit_evaluation) performance) — unless there's some other motivation behind this suggestion, in which case please share such reasoning while reviewing!

Comment (dsuresh-ap) [reply src/mbgl/algorithm/generate_clip_ids_impl.hpp]: I personally prefer how the existing code is with `(!renderable.used || !renderable.needsClipping)`. The logic is easier to understand when glancing at it.

**Comment by kkaefer** [comment]
Bug was introduced in https://github.com/mapbox/mapbox-gl-native/pull/10198

**Comment by mollymerp** [comment]
@kkaefer thanks for the review – can you also 👍 the change in 62061e1 before I merge?

File: platform/ios/CHANGELOG.md [hunk 2]
```diff
@@ -10,6 +10,7 @@ Mapbox welcomes participation and contributions from everyone. Please read [CONT
 * Added an `MGLSymbolStyleLayer.symbolZOrder` property for forcing point features in a symbol layer to be layered in the same order that they are specified in the layer’s associated source. ([#12783](https://github.com/mapbox/mapbox-gl-native/pull/12783))
 * Fixed a crash when a style layer `*-pattern` property evaluates to nil for a particular feature. ([#12896](https://github.com/mapbox/mapbox-gl-native/pull/12896))
 * Fixed an issue with view annotations (including the user location annotation) and the GL map lagging relative to each other. ([#12895](https://github.com/mapbox/mapbox-gl-native/pull/12895))
+* Fixed an issue where fill and line layers would occasionally flicker on zoom due to a bug in `ClipIDGenerator` ([#12982](https://github.com/mapbox/mapbox-gl-native/pull/12982))
```
Comment (friedbunny) [inline platform/ios/CHANGELOG.md]: Small nit: since these changelogs are meant to be end-developer facing, it’s usually not necessary to mention internal implementation details. In this case, I’d suggest lopping off the “due to a bug in `ClipIDGenerator`”, as that’s only relevant to us.
