### PR TITLE
[core] Avoid clipping symbols in continuous mode

### LINKED ISSUE #1673: add padding to annotation tiles
In order to properly sort markers across tiles (#988) we need annotation tiles to also include features that are outside of the tile's boundaries, but within a certain distance of the tile edge.

This will let us clip markers to tile boundaries at draw time to avoid incorrect overlap across tiles. Since markers near edges are included in both tiles they will be drawn seamlessly. Half the marker will be drawn by one tile and half by the other. This is how the -js implementation works.

This should be done after https://github.com/mapbox/mapbox-gl-native/pull/1666 and https://github.com/mapbox/mapbox-gl-native/pull/1655 are merged.

This will fix 
screen shot 2015-06-02 at 11 28 57 am

After implementing, change these two lines:
https://github.com/mapbox/mapbox-gl-native/blob/3dfa317cf9689c5bbd0994f86bdf6b068b1c6716/src/mbgl/renderer/symbol_bucket.cpp#L326
https://github.com/mapbox/mapbox-gl-native/blob/3dfa317cf9689c5bbd0994f86bdf6b068b1c6716/src/mbgl/renderer/painter_symbol.cpp#L122

### PR DESCRIPTION
**Pull request by brunoabinader**
~~Re-enable symbol clipping based on layout property settings, cleaning up workarounds and adds padding to symbol annotation tiles.~~

Avoid clipping symbols in continuous mode - preserving clipping behavior in still mode. To avoid overdrawing symbols on tile edges, we avoid inserting symbol features with anchors located among the tile extent edges.

Fixes #1673 and #6670.

/cc @jfirebaugh @ansis

### CODE REVIEW

**Comment by jfirebaugh** [comment]
Can you comment on https://github.com/mapbox/mapbox-gl-native/issues/6670#issuecomment-254331003 and help fill in the gaps in my understanding?

**Comment by brunoabinader** [comment]
> Can you comment on #6670 (comment) and help fill in the gaps in my understanding?

I've added an extensive introspection as a [comment in #6670](https://github.com/mapbox/mapbox-gl-native/issues/6670#issuecomment-256524251).

File: src/mbgl/layout/symbol_layout.cpp [hunk 1]
```diff
@@ -298,8 +297,7 @@ void SymbolLayout::addFeature(const GeometryCollection &lines,
             // be drawn across tile boundaries. Instead they need to be included in
             // the buffers for both tiles and clipped to tile boundaries at draw time.
             //
-            // TODO remove the `&& false` when is #1673 implemented
-            const bool addToBuffers = (mode == MapMode::Still) || inside || (mayOverlap && false);
+            const bool addToBuffers = inside || mayOverlap;
```
Comment (jfirebaugh) [inline src/mbgl/layout/symbol_layout.cpp]: I don't see how removing `mode == MapMode::Still` here is safe. In still mode, rendering a single tile, we _cannot_ throw away features in the tile buffer under any circumstances, for the reasons detailed in https://github.com/mapbox/mapbox-gl-native/issues/6670#issuecomment-254331003.

Comment (brunoabinader) [inline src/mbgl/layout/symbol_layout.cpp]: You are right - for Still mode we need to render _all_ features.

**Comment by brunoabinader** [comment]
Per https://github.com/mapbox/mapbox-gl-native/issues/6670#issuecomment-257227118 - it seems we no longer need padding for symbol annotations - we can sort symbol render tiles instead prior to rendering.

We still clip in still mode, but just because we need to update our render test results. I'm deferring this work to a following PR.

**Comment by brunoabinader** [comment]
Based on @jfirebaugh's [comments](https://github.com/mapbox/mapbox-gl-native/issues/6670#issuecomment-259825324), I'm going to revert a few comments about clipping symbols for Still mode I've had removed on this PR. Will flag it reviewable again once it is finished.

**Comment by brunoabinader** [comment]
Ready for review.

**Comment by brunoabinader** [comment]
@jfirebaugh @ansis I have cleaned up the patches from this PR, removing stuff that was not related to the proposed changes:

- Avoid clipping symbols in continuous mode - preserving clipping behavior in still mode. We alleviate the rendering artifacts mentioned in https://github.com/mapbox/mapbox-gl-native/issues/1673 by sorting render tiles in reverse Y prior to rendering.
- To avoid overdrawing symbols on tile edges, we avoid inserting symbol features with anchors located among the tile extent edges - fixes https://github.com/mapbox/mapbox-gl-native/issues/6670.
