### PR TITLE
[ios] snap to north if interaction ends within ±7°

### LINKED ISSUE #1064: Compass/bearing snapping fails when also zooming
If one rotates and then pinch zooms, the pinch gesture [cancels the map transition](https://github.com/mapbox/mapbox-gl-native/blob/9dd9bd6e9ddf40ae3ae1746b191ce7d0a8ea0842/platform/ios/MGLMapView.mm#L644) called by the fancy new snapping (#1059) but `bearing` still gets reset and becomes out of sync. :disappointed:

```
2015-03-22 21:19:55.291 Mapbox GL[5984:764115] Rotate: -2.208035º
2015-03-22 21:19:55.292 Mapbox GL[5984:764115] Should we snap?: 357.791965º
2015-03-22 21:19:55.292 Mapbox GL[5984:764115] SNAP!
2015-03-22 21:19:55.294 Mapbox GL[5984:764115] Pinch: -0.000000º
...
2015-03-22 21:26:44.939 Mapbox GL[5984:764115] Rotate: -3.104398º
2015-03-22 21:26:44.939 Mapbox GL[5984:764115] Should we snap?: 356.895602º
2015-03-22 21:26:44.940 Mapbox GL[5984:764115] SNAP!
2015-03-22 21:26:44.940 Mapbox GL[5984:764115] Pinch: -0.000000º
```
[screen-shot-2015-03-22-at-9 20 17-pm](https://cloud.githubusercontent.com/assets/1198851/6774501/b763a54a-d0de-11e4-8e23-8504be4ffce7.png)

### PR DESCRIPTION
**Pull request by friedbunny**
If a user pinch-rotates and the gesture ends within ±7° of north, reset to north (0°).

This behavior is the same as in MapKit.

First proposed in #938, implemented in #1059, reverted in #1064. (Closes #1064.)

/cc @1ec5

### CODE REVIEW

**Comment by friedbunny** [comment]
Going to leave this convenient `iosapp` debug code here:

```objc
- (void)mapViewRegionIsChanging:(__unused MGLMapView *)mapView
{
    [self updateDirectionDebug];
}
- (void)mapView:(__unused MGLMapView *)mapView regionDidChangeAnimated:(__unused BOOL)animated
{
    [self updateDirectionDebug];
}

- (void)updateDirectionDebug
{
    if (! _directionDebug)
    {
        _directionDebug = [[UILabel alloc] initWithFrame:CGRectMake(250, 100, 100, 50)];
        [self.view addSubview:_directionDebug];
    }

    _directionDebug.text = [NSString stringWithFormat:@"%.2f", self.mapView.direction];
}
```

**Comment by 1ec5** [comment]
Could this be done as part of `-unrotateIfNeededAnimated:`?

**Comment by friedbunny** [comment]
I'm looking into integrating it in `-unrotateIfNeededAnimated:`. That does get called rather frequently...

**Comment by friedbunny** [comment]
I went ahead and integrated the snapping with `-unrotateIfNeededAnimated:`. This will cover more cases and be called more frequently.

I've not copied the delayed animations and disabled user inaction that exists just above in  `-unrotateIfNeededAnimated:` because it does not appear to be necessary.

File: platform/ios/src/MGLMapView.mm [hunk 1]
```diff
@@ -3053,6 +3055,10 @@ - (void)unrotateIfNeededAnimated:(BOOL)animated
             [self resetNorthAnimated:NO];
         }
     }
+    else if (self.compassView.alpha > 0 && (self.direction < snapTolerance || self.direction > 360 - snapTolerance))
```
Comment (1ec5) [inline platform/ios/src/MGLMapView.mm]: What if the developer hides the compass view? Shouldn’t the map view snap to north regardless?

Comment (friedbunny) [inline platform/ios/src/MGLMapView.mm]: Good point, will look at changing this.

**Comment by friedbunny** [comment]
Ergh, accidentally included iosapp debug code. Will back that out.

**Comment by friedbunny** [comment]
Rebased and squashed.
