### PR TITLE
Pass std::exception_ptr in MapObserver::onDidFailLoadingMap

### LINKED ISSUE #8398: -[MGLMapViewDelegate mapViewDidFailLoadingMap:withError:] error is uninformative
The error passed into `-[MGLMapViewDelegate mapViewDidFailLoadingMap:withError:]` is an uninformative error. We synthesize this generic error for compatibility with MapKit because mbgl doesn’t actually tell the SDK what went wrong. Per https://github.com/mapbox/mapbox-gl-native/pull/8377#discussion_r105758312, `mbgl::MapObserver::onDidFailLoadingMap()` should accept the error or error message as a parameter. This would allow all the SDKs – not only the iOS and macOS SDKs – to provide more information when the map fails to load for some reason.

/cc @brunoabinader @fabian-guerra

### PR DESCRIPTION
**Pull request by brunoabinader**
Forwards the ~error type and message~ `std::exception_ptr` from style::Observer::onStyleError as well as non-style related errors.

As per @1ec5 comments in #8398:
> This would allow all the SDKs – not only the iOS and macOS SDKs – to provide more information when the map fails to load for some reason.

Fixes #8398.

### CODE REVIEW

**Comment by brunoabinader** [comment]
@1ec5 does the new entries in `MGLErrorCode` requires updating `CHANGELOG.md`?

**Comment by jfirebaugh** [comment]
What do you think about using `std::exception_ptr` as the error type rather than `ErrorType` + `std::string`? This would match our convention in other places, e.g. `style::Observer::on{Glyphs,Sprite,Source,Tile,Resource}Error`.

File: platform/ios/src/MGLMapView.mm [hunk 1]
```diff
@@ -5375,33 +5374,50 @@ void onCameraDidChange(mbgl::MapObserver::CameraChangeMode mode) override {
...
+        MGLErrorCode errorCode;
+        switch (type) {
+        case mbgl::MapObserver::ErrorType::ParseStyle:
+            errorCode = MGLErrorCodeParseStyleFailed;
+            break;
+        case mbgl::MapObserver::ErrorType::NotFound:
+            errorCode = MGLErrorCodeNotFound;
+            break;
+        case mbgl::MapObserver::ErrorType::LoadingStyle:
+            errorCode = MGLErrorCodeLoadStyleFailed;
```
Comment (1ec5) [inline platform/ios/src/MGLMapView.mm]: Would either `MGLErrorCodeBadServerResponse` or `MGLErrorCodeConnectionFailed` describe this failure, or is `MGLErrorCodeLoadStyleFailed` a distinct case?

File: platform/ios/src/MGLMapView.mm [hunk 2]
```diff
@@ -5375,33 +5374,50 @@ void onCameraDidChange(mbgl::MapObserver::CameraChangeMode mode) override {
...
+            break;
+        }
+        error = [NSError errorWithDomain:MGLErrorDomain code:errorCode userInfo:errorDescription ? @{
+            NSLocalizedDescriptionKey: errorDescription,
```
Comment (1ec5) [inline platform/ios/src/MGLMapView.mm]: Thank you so much for this! 👍 It turns out the [error user info dictionary](https://developer.apple.com/library/content/documentation/Cocoa/Conceptual/ErrorHandlingCocoa/ErrorObjectsDomains/ErrorObjectsDomains.html#//apple_ref/doc/uid/TP40001806-CH202-SW3) is called that because its contents are often displayed to the user with a localized description and sometimes a recovery suggestion. Here are some suggestions for improvements, taking advantage of the error type and assuming `message` comes directly from an `std::exception_ptr`, as suggested in https://github.com/mapbox/mapbox-gl-native/pull/8418#issuecomment-286820676:

* `ParseStyle`:
  * `NSLocalizedDescriptionKey`: “The map failed to load because the style is corrupted.”
  * `NSLocalizedFailureReasonErrorKey`: `@(message.c_str())`
* `NotFound`:
  * `NSLocalizedDescriptionKey`: “The map failed to load because the style can’t be found or is incompatible.”
  * `NSLocalizedFailureReasonErrorKey`: `@(message.c_str())`
* `LoadingStyle`:
  * `NSLocalizedDescriptionKey`: `@(message.c_str())`

For the localized descriptions, we can use the `NSLocalizedStringWithDefaultValue()` macro (as described [here](https://github.com/mapbox/mapbox-gl-native/blob/master/platform/ios/DEVELOPING.md#adding-user-facing-text)) to potentially localize the error message.

Let me know if you’d prefer that I make these changes myself.

**Comment by 1ec5** [comment]
This fixes #8086, which I previously missed before filing #8398 as a duplicate.

File: platform/ios/src/MGLMapView.mm (hunk 1 above)
Comment (brunoabinader) [inline platform/ios/src/MGLMapView.mm]: I'd prefer for map loading failure to have its own error type. However, we're no longer distinctively separating these in three different error types because `std::runtime_error` only provides a string.

File: platform/ios/src/MGLMapView.mm (hunk 2 above)
Comment (brunoabinader) [inline platform/ios/src/MGLMapView.mm]: > Would that means we’d have different subclasses of std::exception_ptr for each failure mode, or would everything be an std::runtime_error?

Good question - it seems we're using only plain `std::runtime_error` everywhere in GL native code, so I'd say let's keep the same pattern.

As explained above, we'll no longer be able to distinct between the three error types - however I don't think that would make much difference anyways - the error message is the most important debugging information we need.

Comment (1ec5) [inline platform/ios/src/MGLMapView.mm]: We do have a couple subclasses of `mbgl::util::Exception` meant to provide more distinguishable errors. Currently, the only subclasses appear to be `SpriteImageException` and `MisuseException`; could we add more subclasses for these error types?

Comment (brunoabinader) [inline platform/ios/src/MGLMapView.mm]: > could we add more subclasses for these error types?

I don't have a strong opinion on this, though for this approach to work we'd need to deduct the exception type via `catch` - see the exception juggling in https://github.com/mapbox/mapbox-gl-native/blob/master/include/mbgl/util/string.hpp#L44-L51 - for all platform-specific codes that needed to handle this.

Comment (1ec5) [inline platform/ios/src/MGLMapView.mm]: For the iOS and macOS implementations, the catch statements would replace the existing switch statement. For other implementations that don't need to distinguish individual failure reasons, catching a runtime_error would be sufficient.

**Comment by kkaefer** [comment]
related: https://github.com/mapbox/mapbox-gl-native/issues/7890
