### PR TITLE
[ios] Adds thread safe access to MGLNetworkConfiguration events dictionary

### LINKED ISSUE #14982: Crash in -[MGLNetworkConfiguration startDownloadEvent:type:]
**Maps SDK:** `ios-v5.1.0-alpha.2` (75659e26b8)
**Style:** `<Style: mapbox://styles/mapbox/satellite-streets-v11, accessToken: nil, name: Mapbox Satellite Streets, type: default, coordinate: nil, zoomLevel: nil>`

Studio Preview reportedly crashed at [MGLNetworkConfiguration.m:68](https://github.com/mapbox/mapbox-gl-native/blob/ios-v5.1.0-alpha.2/platform/darwin/src/MGLNetworkConfiguration.m#L68), from [http_file_source.mm:229](https://github.com/mapbox/mapbox-gl-native/blob/ios-v5.1.0-alpha.2/platform/darwin/src/http_file_source.mm#L229), which seems fairly innocuous. There’s no reported exception message, unfortunately.

@fabian-guerra I’m a little confused about these network telemetry events — I thought the idea was that they didn’t fire by default, since they’re expected to impact performance?

Introduced in https://github.com/mapbox/mapbox-gl-native/pull/13997 and `ios-v4.11.0`.

```
# Version: 2019.8 (103)
# Bundle Identifier: com.mapbox.StudioPreview
# Date: 2019-06-20T18:16:00Z
# OS Version: 12.3.1 (16F203)
# Device: iPad Pro (12.9 inch)
# RAM Free: 4.1%
# Disk Free: 15.3%
```

```
#3. Crashed: com.mapbox.mbgl.DefaultFileSource
0  libobjc.A.dylib                0x1aa8ea530 objc_msgSend + 16
1  CoreFoundation                 0x1ab5e3f90 -[__NSDictionaryM objectForKey:] + 216
2  Mapbox                         0x102d0b538 -[MGLNetworkConfiguration startDownloadEvent:type:] (MGLNetworkConfiguration.m:68)
3  Mapbox                         0x102f21238 mbgl::HTTPFileSource::request(mbgl::Resource const&, std::__1::function<void (mbgl::Response)>) (http_file_source.mm:229)
4  Mapbox                         0x102f3a82c mbgl::OnlineFileSource::Impl::activateRequest(mbgl::OnlineFileRequest*) (memory:2638)
5  CoreFoundation                 0x1ab68a650 __CFRUNLOOP_IS_CALLING_OUT_TO_A_TIMER_CALLBACK_FUNCTION__ + 28
6  CoreFoundation                 0x1ab68a380 __CFRunLoopDoTimer + 864
7  CoreFoundation                 0x1ab689bb4 __CFRunLoopDoTimers + 248
8  CoreFoundation                 0x1ab684b04 __CFRunLoopRun + 1844
9  CoreFoundation                 0x1ab6840b0 CFRunLoopRunSpecific + 436
10 CoreFoundation                 0x1ab684e0c CFRunLoopRun + 80
11 Mapbox                         0x102f2748c void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, mbgl::util::Thread<mbgl::DefaultFileSource::Impl>::Thread<std::__1::shared_ptr<mbgl::FileSource> const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, unsigned long long&>(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::shared_ptr<mbgl::FileSource> const&&&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&&&, unsigned long long&&&)::'lambda'()> >(void*) (thread.hpp:73)
12 libsystem_pthread.dylib        0x1ab3172c0 _pthread_body + 128
13 libsystem_pthread.dylib        0x1ab317220 _pthread_start + 44
14 libsystem_pthread.dylib        0x1ab31acdc thread_start + 4

--

#0. com.apple.main-thread
0  libsystem_kernel.dylib         0x1ab294ee4 __psynch_cvwait + 8
1  libsystem_pthread.dylib        0x1ab30fcf8 _pthread_cond_wait$VARIANT$mp + 636
2  AppleMetalGLRenderer           0x1cbdc6164 GLDShareGroupRec::waitUsage(int volatile*)
3  GLEngine                       0x1ccc33dbc glFinish_Exec
4  Mapbox                         0x102d85364 mbgl::gl::CommandEncoder::~CommandEncoder() (debug_group.hpp:19)
5  Mapbox                         0x102d85240 mbgl::gl::CommandEncoder::~CommandEncoder() (command_encoder.cpp:14)
6  Mapbox                         0x102e21fa8 mbgl::Renderer::Impl::render(mbgl::UpdateParameters const&) (renderer_impl.cpp:521)
7  Mapbox                         0x102ce2db0 -[MGLMapView renderSync] (memory:4517)
8  Mapbox                         0x102c94d3c -[MGLMapViewImplDelegate glkView:drawInRect:] (MGLMapView+Impl.mm:14)
9  GLKit                          0x1b865e8f4 -[GLKView _display:] + 216
10 Mapbox                         0x102ce3764 -[MGLMapView updateFromDisplayLink:] (MGLMapView.mm:1095)
11 QuartzCore                     0x1afa7ff90 CA::Display::DisplayLink::dispatch_items(unsigned long long, unsigned long long, unsigned long long) + 636
12 IOKit                          0x1ab9544b0 IODispatchCalloutFromCFMessage + 488
13 CoreFoundation                 0x1ab663a8c __CFMachPortPerform + 188
14 CoreFoundation                 0x1ab68a690 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE1_PERFORM_FUNCTION__ + 56
15 CoreFoundation                 0x1ab689ddc __CFRunLoopDoSource1 + 440
16 CoreFoundation                 0x1ab684c00 __CFRunLoopRun + 2096
17 CoreFoundation                 0x1ab6840b0 CFRunLoopRunSpecific + 436
18 GraphicsServices               0x1ad88479c GSEventRunModal + 104
19 UIKitCore                      0x1d79c3978 UIApplicationMain + 212
20 StudioPreview                  0x102828f20 main (OfflineStorage.swift:13)
21 libdyld.dylib                  0x1ab1498e0 start + 4
```

/cc @fabian-guerra

### PR DESCRIPTION
**Pull request by julianrex**
Fixes #14982, and replaces #15029 in @fabian-guerra's absence.

EDIT: #14982 is a crash in `-[MGLNetworkConfiguration startDownloadEvent:type:]` caused because `NSMutableDictionary` is not thread-safe and we have concurrent read/writes. This PR uses a concurrent dispatch queue (to allow concurrent reads) but with `dispatch_barrier_async` to ensure that writes/deletes are synchronous.

Using GCD is a common solution, though we will need to monitor performance.

/cc @chloekraw

### CODE REVIEW

**Comment by friedbunny** [comment]
@julianrex for posterity, could you please write up what the original issue was and how this fixes it?

File: platform/darwin/src/MGLNetworkConfiguration.m [hunk 1]
```diff
@@ -65,8 +67,9 @@ - (NSURLSessionConfiguration *)defaultSessionConfiguration {
 }
 
 - (void)startDownloadEvent:(NSString *)urlString type:(NSString *)resourceType {
-    if (urlString && ![self.events objectForKey:urlString]) {
-        [self.events setObject:@{ MGLStartTime: [NSDate date], MGLResourceType: resourceType } forKey:urlString];
+    NSDate *startDate = [NSDate date];
```
Comment (friedbunny) [inline platform/darwin/src/MGLNetworkConfiguration.m]: Nit: move this declaration into the following `if` statement.

File: platform/ios/test/MGLNetworkConfigurationTests.m [hunk 2]
```diff
@@ -0,0 +1,42 @@
+#import <Mapbox/Mapbox.h>
+#import <XCTest/XCTest.h>
+#import "MGLNetworkConfiguration_Private.h"
+
+@interface MGLNetworkConfigurationTests : XCTestCase
+@end
+
+@implementation MGLNetworkConfigurationTests
+
```
Comment (friedbunny) [inline platform/ios/test/MGLNetworkConfigurationTests.m]:
```suggestion

// Regression test for https://github.com/mapbox/mapbox-gl-native/issues/14982
```

File: platform/ios/CHANGELOG.md [hunk 3]
```diff
@@ -35,6 +35,8 @@ Mapbox welcomes participation and contributions from everyone. Please read [CONT
 * Deprecated variants of the above methods without completion handlers. ([#14959](https://github.com/mapbox/mapbox-gl-native/pull/14959))
 * Fixed an issue where the two-finger tilt gesture would continue after lifting one finger. ([#14969](https://github.com/mapbox/mapbox-gl-native/pull/14969))
 * Added `MGLMapView.compassView.visibility` and `MGLOrnamentVisibility` to allow configuration of compass visibility behavior. ([#15055](https://github.com/mapbox/mapbox-gl-native/pull/15055))
+* Fixed a crash during network access. ([#15113](https://github.com/mapbox/mapbox-gl-native/pull/15113))
+
```
Comment (friedbunny) [inline platform/ios/CHANGELOG.md]:
```suggestion
```

File: platform/darwin/src/MGLNetworkConfiguration.m (hunk 1 above)
Comment (julianrex) [reply platform/darwin/src/MGLNetworkConfiguration.m]: I had this outside to try and give a more accurate time, but the end-date isn't, so 🤷‍♂. I'm going to move this inside - though we should think about using `CACurrentMediaTime` - using `NSDate` here is a little overkill.

**Comment by julianrex** [comment]
@friedbunny mind taking a another quick look? The delegate method is now called on the main queue, which is wasn't before hand.
