### PR TITLE
[ios] Deactivate MGLMapView IBDesignable

### LINKED ISSUE #13424: Remove IB_DESIGNABLE from MGLMapView
*Ticketing out separately from #10072.*

Given our current issues with `MGLMapView` crashing the Interface Builder agent (#10573, #10072) let's remove the designable support. I would suggest that rather than removing wholesale, we should wrap with an `#ifdef` so that we can periodically check whether a crash occurs.

In addition, as @friedbunny [mentions](https://github.com/mapbox/mapbox-gl-native/issues/10072#issuecomment-332273649) the designable doesn't provide much value. 

Updating our documentation should be considered part of this issue.

**Mapbox SDK versions:** 4.7.0-alpha.1 (at time of writing)
**Xcode version:** 10.1 (at time of writing)

### PR DESCRIPTION
**Pull request by fabian-guerra**
Fixes #13424 

Only removes the IBDesignable support on iOS (we'll keep around macOS) to avoid crashing IB. IBInspectables will still be available and it won't require any documentation update.

### CODE REVIEW

**Comment by friedbunny** [comment]
Confirmed that our `IBInspectables` still work.

File: platform/ios/src/MGLSDKUpdateChecker.mm [hunk 1]
```diff
@@ -7,8 +7,7 @@ @implementation MGLSDKUpdateChecker
 + (void)checkForUpdates {
 #if TARGET_IPHONE_SIMULATOR
     // Abort if running in a playground.
-    if ([[NSBundle mainBundle].bundleIdentifier hasPrefix:@"com.apple.dt.playground."] ||
-        NSProcessInfo.processInfo.mgl_isInterfaceBuilderDesignablesAgent) {
+    if ([[NSBundle mainBundle].bundleIdentifier hasPrefix:@"com.apple.dt.playground."]) {
```
Comment (1ec5) [inline platform/ios/src/MGLSDKUpdateChecker.mm]: Do we need to check for a playground in any of the places where we were previously checking for IB?

Comment (friedbunny) [reply platform/ios/src/MGLSDKUpdateChecker.mm]: Technically it’s not even necessary to check for playgrounds here — it’s just to stop a bit of console spam.
