### PR TITLE
[ios, macos] NSPredicate expression filters.

### LINKED ISSUE #11567: Support expression operators in style layer predicates
#11251 implemented underlying support for converting an NSPredicate to an `mbgl::style::ExpressionFilter`, but that doesn’t appear to be hooked up to `-[NS*Predicate mgl_filter]` yet. As a result, the following code crashes:

```objc
lineLayer.predicate = [NSPredicate predicateWithFormat:@"maki == lowercase('THEATRE')"];
```

```
[General] Comparison predicate must compare an attribute (as a key path) to a constant or vice versa.
2018-03-30 04:06:54.994117-0700 Mapbox GL[41905:16769647] [General] (
	0   CoreFoundation                      0x00007fff459d6fcb __exceptionPreprocess + 171
	1   libobjc.A.dylib                     0x00007fff6c678c76 objc_exception_throw + 48
	2   CoreFoundation                      0x00007fff45a689ed +[NSException raise:format:] + 205
	3   Mapbox                              0x00000001005b1d44 -[NSComparisonPredicate(MGLAdditions) mgl_keyPath] + 436
	4   Mapbox                              0x00000001005ae032 -[NSComparisonPredicate(MGLAdditions) mgl_filter] + 498
	5   Mapbox                              0x00000001006119b1 -[MGLSymbolStyleLayer setPredicate:] + 289
```

The fix is to replace the switch statements in `-[NSPredicate mgl_filter]`, `-[NSComparisonPredicate mgl_filter]`, and `-[NSCompoundPredicate mgl_filter]` with calls to the respective `-mgl_jsonExpressionObject` methods. This will cause some tests to fail; #11013 covers implementing some NSPredicate-specific operators that are exercised by these tests.

/cc @fabian-guerra

### PR DESCRIPTION
**Pull request by fabian-guerra**
Fixes #11567 

- [x] Add support for predicate expression filters.
- [x] Add NSPredicate<->ExpressionFilter converter.
- [x] Update tests.
- [x] Update documentation.

### CODE REVIEW

File: platform/darwin/src/NSComparisonPredicate+MGLAdditions.mm [hunk 1]
```diff
@@ -1,218 +1,36 @@
...
+    switch (self.predicateOperatorType) {
+        case NSEqualToPredicateOperatorType:
+        case NSNotEqualToPredicateOperatorType:
+        case NSGreaterThanPredicateOperatorType:
+        case NSGreaterThanOrEqualToPredicateOperatorType:
+        case NSLessThanPredicateOperatorType:
+        case NSLessThanOrEqualToPredicateOperatorType:
+        case NSInPredicateOperatorType:
+        case NSContainsPredicateOperatorType:
         case NSBetweenPredicateOperatorType: {
```
Comment (1ec5) [inline platform/darwin/src/NSComparisonPredicate+MGLAdditions.mm]: We don’t really need a switch statement here anymore. `-mgl_jsonExpressionObject` can be responsible for raising an exception when the operator type is unsupported.

File: platform/darwin/src/NSExpression+MGLAdditions.mm [hunk 2]
```diff
@@ -538,6 +538,10 @@ + (instancetype)mgl_expressionWithJSONObject:(id)object {
                 return [NSExpression expressionForAggregate:MGLSubexpressionsWithJSONObjects(argumentObjects.firstObject)];
             }
             return [NSExpression mgl_expressionWithJSONObject:argumentObjects.firstObject];
+        } else if ([op isEqualToString:@"number"] ||
+                   [op isEqualToString:@"string"] ||
+                   [op isEqualToString:@"boolean"]) {
+            return [NSExpression mgl_expressionWithJSONObject:argumentObjects.firstObject];
```
Comment (1ec5) [inline platform/darwin/src/NSExpression+MGLAdditions.mm]: I’m not sure it’s a good idea to make the conversion from JSON to NSExpression lossy like this. If these calls to `number` etc. are failing the round-tripping tests, feel free to modify the tests to start out with these calls so that they pass without needing to remove the type assertions.

File: platform/darwin/test/MGLPredicateTests.mm [hunk 3]
```diff
@@ -576,6 +576,66 @@ - (void)testComparisonExpressionArray {
         NSArray *expected = @[@"==", @1, @2];
         XCTAssertEqualObjects([NSPredicate predicateWithFormat:@"1 = 2"].mgl_jsonExpressionObject, expected);
     }
+    {
+        NSPredicate *predicate = [NSPredicate predicateWithFormat:@"x == YES"];
+        NSArray *jsonExpression = @[@"==", @[@"get", @"x"], @YES];
+        XCTAssertEqualObjects(predicate.mgl_jsonExpressionObject, jsonExpression);
```
Comment (1ec5) [inline platform/darwin/test/MGLPredicateTests.mm]: Also test that reversing the order of the operands produces the same kind of expression.

File: platform/darwin/src/NSComparisonPredicate+MGLAdditions.mm [hunk 4]
```diff
@@ -330,9 +148,48 @@ - (id)mgl_jsonExpressionObject {
...
+            type = @"boolean";
+        } else {
+            type = @"number";
+        }
+    } else if (expression.expressionType == NSConstantValueExpressionType && [expression.constantValue isKindOfClass:NSString.class]) {
+        type = @"string";
+    }
+    
+    if (type) {
+        return @[type, expressionElement.mgl_jsonExpressionObject];
```
Comment (1ec5) [inline platform/darwin/src/NSComparisonPredicate+MGLAdditions.mm]: It shouldn’t be the job of the platform-specific code to insert type assertions based on the data type of the constant value.

Comment (1ec5) [reply platform/darwin/src/NSComparisonPredicate+MGLAdditions.mm]: Unfortunately, the code in this PR is only capable of inserting type assertions for the most basic expressions, but not for something more complex like `CAST(ele, 'NSNumber') * 0.3048 > 1000`. To handle the whole gamut of expressions that could require type assertions, we’d have to implement static type analysis in Objective-C.

Since it’s probably too late for mapbox/mapbox-gl-js#6459 to make it into the v4.0.0 release, we’ll have to settle for expecting the developer to include type assertions (or, more likely, `CAST()`) in their predicates. As long as the type checking in this PR isn’t incorrect, I suppose we can keep it, but it would complicate the developer’s mental model of when they’d need to add type assertions themselves.

File: platform/darwin/test/MGLPredicateTests.mm [hunk 5]
```diff
@@ -23,558 +23,404 @@ @interface MGLPredicateTests : XCTestCase
...
     {
-        auto actual = [NSPredicate predicateWithFormat:@"a == 'b' AND c == 'd'"].mgl_filter;
-        mbgl::style::AllFilter expected = {
-            .filters = {
-                mbgl::style::EqualsFilter { .key = "a", .value = std::string("b") },
-                mbgl::style::EqualsFilter { .key = "c", .value = std::string("d") },
-            },
-        };
-        MGLAssertEqualFilters(actual, expected);
+        NSPredicate *predicate = [NSPredicate predicateWithFormat:@"a != nil"];
```
Comment (1ec5) [inline platform/darwin/test/MGLPredicateTests.mm]: This used to be converted into a `NotHasFilter`. Ideally, we’d convert it to `["!", ["has", ["get", "a"]]]`. Are we sure that `["!-", ["get", "a"], null]` has the desired effect?

File: platform/darwin/test/MGLPredicateTests.mm [hunk 6]
```diff
@@ -23,558 +23,404 @@ @interface MGLPredicateTests : XCTestCase
...
     {
-        mbgl::style::NoneFilter filter = {
-            .filters = {
-                mbgl::style::EqualsFilter { .key = "a", .value = std::string("b") },
-                mbgl::style::EqualsFilter { .key = "c", .value = std::string("d") },
-            },
-        };
-        XCTAssertEqualObjects([NSPredicate mgl_predicateWithFilter:filter], [NSPredicate predicateWithFormat:@"NOT(a == 'b' OR c == 'd')"]);
+        NSPredicate *predicate = [NSPredicate predicateWithFormat:@"NOT %@ CONTAINS a", @[@"b", @"c"]];
+        NSArray *jsonExpression = @[@"!", @[@"has", @[@"literal", @[@"b", @"c"]], @[@"get", @"a"]]];
```
Comment (1ec5) [inline platform/darwin/test/MGLPredicateTests.mm]: #11632 will correct this to use a `match` expression.

File: platform/darwin/test/MGLPredicateTests.mm [hunk 7]
```diff
@@ -23,558 +23,404 @@ @interface MGLPredicateTests : XCTestCase
...
-
     {
-        mbgl::style::NoneFilter filter = {
-            .filters = {
-                mbgl::style::EqualsFilter { .key = "a", .value = std::string("b") },
-                mbgl::style::EqualsFilter { .key = "c", .value = std::string("d") },
-            },
-        };
-        XCTAssertEqualObjects([NSPredicate mgl_predicateWithFilter:filter], [NSPredicate predicateWithFormat:@"NOT(a == 'b' OR c == 'd')"]);
+        NSPredicate *predicate = [NSPredicate predicateWithFormat:@"NOT %@ CONTAINS a", @[@"b", @"c"]];
```
Comment (1ec5) [inline platform/darwin/test/MGLPredicateTests.mm]: #11632 will also test using an aggregate expression instead of a constant array value.

File: platform/darwin/src/NSComparisonPredicate+MGLAdditions.mm (hunk 4 above)
Comment (anandthakker) [reply platform/darwin/src/NSComparisonPredicate+MGLAdditions.mm]: https://github.com/mapbox/mapbox-gl-js/issues/6459 would not take very long to implement, once we have consensus on the design.  Is this something we should try to expedite to get into v4.0.0?

Comment (fabian-guerra) [reply platform/darwin/src/NSComparisonPredicate+MGLAdditions.mm]: @anandthakker if it's possible to get it done for 4.0.0 would be good. Otherwise I think we can live with this for now and in a patch release remove it.

/cc @1ec5

File: platform/darwin/src/NSPredicate+MGLAdditions.mm [hunk 8]
```diff
@@ -259,28 +271,33 @@ + (instancetype)mgl_predicateWithJSONObject:(id)object {
     NSString *op = objects.firstObject;
     
     if ([op isEqualToString:@"=="]) {
-        NSArray *subexpressions = MGLSubexpressionsWithJSONObjects([objects subarrayWithRange:NSMakeRange(1, objects.count - 1)]);
+        NSArray *sanitizedObjects = MGLSanitizeJSONObjects([objects subarrayWithRange:NSMakeRange(1, objects.count - 1)]);
```
[the remark this answers is not in the document]
Comment (fabian-guerra) [reply platform/darwin/src/NSPredicate+MGLAdditions.mm]: I removed the code you mentioned in https://github.com/mapbox/mapbox-gl-native/pull/11587#discussion_r180200037, but this code is required for comparison predicates to work as filters. `MGLSanitizeJSONObjects()` removes the data types before converting them.

File: platform/darwin/src/NSComparisonPredicate+MGLAdditions.mm [hunk 9]
```diff
@@ -1,231 +1,12 @@
 #import "NSComparisonPredicate+MGLAdditions.h"
 
+#import "MGLStyleValue_Private.h"
+
 #import "NSPredicate+MGLAdditions.h"
 #import "NSExpression+MGLPrivateAdditions.h"
 
 @implementation NSComparisonPredicate (MGLAdditions)
 
-- (mbgl::style::Filter)mgl_filter {
```
[the remark this answers is not in the document]
Comment (1ec5) [reply platform/darwin/src/NSComparisonPredicate+MGLAdditions.mm]: My mistake: we only need to keep `FilterEvaluator` around, since that’s responsible for converting `mbgl::Filter`s to NSPredicates as part of the `predicate` property’s getter. `-mgl_filter`, meanwhile, is part of the setter, which is already dead code, so we can remove it.

File: platform/darwin/src/NSPredicate+MGLAdditions.mm (hunk 8 above)
[the remark this answers is not in the document]
Comment (anandthakker) [reply platform/darwin/src/NSPredicate+MGLAdditions.mm]: Hmm.  I think a problem here is that this is unconditionally removing all `"number"`, `"string"`, `"boolean"` assertions.  Removing the ones that were automatically inferred is fine, because they can be inferred again if the expression is sent back into mbgl to be parsed.  But it's possible to have explicitly-added assertions that would _not_ be automatically inferred if they were stripped.  For example, `["==", ["number", ["id"]], ["get", "x"]]` is an expression that specifically asserts that a feature's `id` is a number and compares it to property with key `"x"`.  If the `"number"` wrapper were stripped here, the resulting expression would fail to parse. (And even if we relaxed the typing requirements so that it _did_ parse, its behavior would be different than that of the original.)

File: platform/darwin/test/MGLPredicateTests.mm (hunk 5 above)
Comment (anandthakker) [reply platform/darwin/test/MGLPredicateTests.mm]: `["==", ["get", "a"], null]` should be equivalent to `["!", ["has", "a"]]`, because `get` returns `null` for a missing key

Comment (anandthakker) [reply platform/darwin/test/MGLPredicateTests.mm]: That said, the latter is probably a more direct translation..

File: platform/darwin/src/NSPredicate+MGLAdditions.mm (hunk 8 above)
[the remark this answers is not in the document]
Comment (fabian-guerra) [reply platform/darwin/src/NSPredicate+MGLAdditions.mm]: This applies only to `>, >=, <, <=` this type of evaluation is not possible using `NSExpression` directly.

[the remark this answers is not in the document]
Comment (anandthakker) [reply platform/darwin/src/NSPredicate+MGLAdditions.mm]: Ah, okay.  Some expressions might still fail to roundtrip -- e.g., `[">", ["string", ["get", "x"]], ["string", ["get", "y"]]]` would result in `[">", ["get", "x"], ["get", "y"]]` -- but I suppose that's a known/acceptable issue?

File: platform/darwin/src/NSComparisonPredicate+MGLAdditions.mm [hunk 10]
```diff
@@ -330,9 +111,48 @@ - (id)mgl_jsonExpressionObject {
...
     if (op) {
-        return @[op, self.leftExpression.mgl_jsonExpressionObject, self.rightExpression.mgl_jsonExpressionObject];
+        id leftExpression = self.leftExpression.mgl_jsonExpressionObject;
+        id rightExpression = self.rightExpression.mgl_jsonExpressionObject;
+        
+        switch (self.predicateOperatorType) {
+            case NSLessThanPredicateOperatorType:
+            case NSLessThanOrEqualToPredicateOperatorType:
+            case NSGreaterThanPredicateOperatorType:
+            case NSGreaterThanOrEqualToPredicateOperatorType: {
```
[the remark this answers is not in the document]
Comment (fabian-guerra) [reply platform/darwin/src/NSComparisonPredicate+MGLAdditions.mm]: This condition applies only for this operators since are the only ones required to pass the comparator type.

File: platform/darwin/src/NSPredicate+MGLAdditions.mm (hunk 8 above)
[the remark this answers is not in the document]
Comment (fabian-guerra) [reply platform/darwin/src/NSPredicate+MGLAdditions.mm]: @anandthakker @1ec5 seems like the best solution is require that the developers add `CAST` to filter predicates. Something like:
`[NSPredicate predicateWithFormat:@"CAST(x, 'NSNumber') < 5"];`
This way we avoid all the problems mentioned above.

File: platform/darwin/src/NSComparisonPredicate+MGLAdditions.mm (hunk 4 above)
Comment (1ec5) [reply platform/darwin/src/NSComparisonPredicate+MGLAdditions.mm]: Either way, the SDK code should not elide type assertions during conversion.

File: platform/darwin/src/NSPredicate+MGLAdditions.mm (hunk 8 above)
[the remark this answers is not in the document]
Comment (1ec5) [reply platform/darwin/src/NSPredicate+MGLAdditions.mm]: The code here converts from JSON to NSPredicate. As long as an expression in JSON already has type assertions, those type assertions should be reflected in the NSPredicate. The fact that this prevents literal round-tripping of some predicates is unfortunate but not a big deal compared to potentially preventing an expression from working correctly.

File: platform/darwin/src/NSComparisonPredicate+MGLAdditions.mm [hunk 11]
```diff
@@ -361,9 +142,52 @@ - (id)mgl_jsonExpressionObject {
...
     }
     return nil;
 }
 
+/**
+ Infers the expressionObject type if it can not then tries to infer the type using fallbackExpression.
+ ExpressionFilters of type >, >=, <, <= requires that each compared value provides its type.
+ */
+- (id)mgl_typedJSONWithExpressionObject:(NSExpression *)expressionObject fallbackExpression:(NSExpression *)fallbackExpression {
+    NSExpression *expression = expressionObject.expressionType == NSConstantValueExpressionType ? expressionObject : fallbackExpression;
```
Comment (1ec5) [inline platform/darwin/src/NSComparisonPredicate+MGLAdditions.mm]: Replace `expressionObject` with `self` and `fallbackExpression` with `otherExpression`.

File: platform/darwin/src/NSComparisonPredicate+MGLAdditions.mm [hunk 12]
```diff
@@ -361,9 +142,52 @@ - (id)mgl_jsonExpressionObject {
...
+            type = @"boolean";
+        } else {
+            type = @"number";
+        }
+    } else if (expression.expressionType == NSConstantValueExpressionType && [expression.constantValue isKindOfClass:NSString.class]) {
+        type = @"string";
+    }
+    
+    if (type) {
+        return @[type, expressionObject.mgl_jsonExpressionObject];
```
Comment (1ec5) [inline platform/darwin/src/NSComparisonPredicate+MGLAdditions.mm]: If `self` isn’t already a function expression that casts or type-asserts, then wrap `self` in a new `MGL_FUNCTION` expression and return that expression.

File: platform/darwin/src/NSExpression+MGLAdditions.mm [hunk 13]
```diff
@@ -551,7 +551,7 @@ + (instancetype)expressionWithMGLJSONObject:(id)object {
                 return [NSExpression expressionForAggregate:MGLSubexpressionsWithJSONObjects(argumentObjects.firstObject)];
             }
             return [NSExpression expressionWithMGLJSONObject:argumentObjects.firstObject];
-        } else if ([op isEqualToString:@"to-boolean"]) {
+        } else if ([op isEqualToString:@"to-boolean"] || [op isEqualToString:@"boolean"]) {
```
Comment (1ec5) [inline platform/darwin/src/NSExpression+MGLAdditions.mm]: `boolValue` was only ever meant to coerce a value to a Boolean, not assert that it is a Boolean. Previously, `to-boolean` would be translated to `MGL_FUNCTION('to-boolean', …)`. Is there any potential for data loss this way?

File: platform/darwin/src/NSComparisonPredicate+MGLAdditions.mm [hunk 14]
```diff
@@ -361,9 +142,52 @@ - (id)mgl_jsonExpressionObject {
...
+        return @[op, leftJSONExpressionObject, rightJSONExpressionObject];
     }
     return nil;
 }
 
+/**
+ Infers the expressionObject type if it can not then tries to infer the type using fallbackExpression.
+ ExpressionFilters of type >, >=, <, <= requires that each compared value provides its type.
+ */
+- (id)mgl_typedJSONWithExpressionObject:(NSExpression *)expressionObject fallbackExpression:(NSExpression *)fallbackExpression {
```
[the remark this answers is not in the document]
Comment (fabian-guerra) [reply platform/darwin/src/NSComparisonPredicate+MGLAdditions.mm]: That method is generic. I was passing both sides of the comparison expression. So calling self didn't make sense.

I removed this code since it's purpose to aid the developers in the migration is not working as intended and is causing more problems per mi comment https://github.com/mapbox/mapbox-gl-native/pull/11587#discussion_r181504893.

File: platform/darwin/src/NSExpression+MGLAdditions.mm (hunk 13 above)
Comment (fabian-guerra) [reply platform/darwin/src/NSExpression+MGLAdditions.mm]: This was not meant to make it here. Removed

File: platform/darwin/test/MGLPredicateTests.mm [hunk 15]
```diff
@@ -23,558 +23,404 @@ @interface MGLPredicateTests : XCTestCase
 
 @implementation MGLPredicateTests
 
-- (void)testFilterization {
```
[the remark this answers is not in the document]
Comment (fabian-guerra) [reply platform/darwin/test/MGLPredicateTests.mm]: Filter test were not added per https://github.com/mapbox/mapbox-gl-native/pull/11587#discussion_r181454130.

File: platform/darwin/src/NSComparisonPredicate+MGLAdditions.mm (hunk 14 above)
[the remark this answers is not in the document]
Comment (1ec5) [reply platform/darwin/src/NSComparisonPredicate+MGLAdditions.mm]: For future reference, it would’ve been possible to call, e.g., `[leftExpression mgl_typeCheckedExpressionMatchingExpression:rightExpression]`, in which case `self` inside the method would’ve been equivalent to `leftExpression` at the call site.

File: platform/darwin/src/MGLVectorStyleLayer.h [hunk 16]
```diff
@@ -47,7 +47,7 @@ MGL_EXPORT
  ```swift
  let layer = MGLLineStyleLayer(identifier: "contour", source: terrain)
  layer.sourceLayerIdentifier = "contours"
- layer.predicate = NSPredicate(format: "(index == 5 || index == 10) && ele >= 1500.0")
+ layer.predicate = NSPredicate(format: "(index == 5 || index == 10) && CAST(ele, 'NSNumber') >= 1500.0")
```
Comment (1ec5) [inline platform/darwin/src/MGLVectorStyleLayer.h]: This illustrates the fact that many existing uses of predicates in v3._x_ will need to be modified slightly when migrating to v4.0.0. On balance, I think this is necessary until mapbox/mapbox-gl-js#6459, but it does mean we’ll need to be clear about this requirement in the documentation, particularly the function-to-expression migration guide and the “Predicates and Expressions” guide.

Comment (1ec5) [reply platform/darwin/src/MGLVectorStyleLayer.h]: Also, the iOS and macOS changelogs should have a blurb noting that:

* Predicate format strings can contain arithmetic and calls to built-in NSExpression functions.
* Key paths may need to be cast to NSString or NSNumber in some cases.

File: platform/darwin/docs/guides/Predicates and Expressions.md [hunk 17]
```diff
@@ -19,6 +19,17 @@ based on the feature’s attributes. Use the `MGLVectorStyleLayer.predicate`
 property to include only the features in the source layer that satisfy a
 condition that you define.
 
+When a predicate is used for filtering vector data the key should be cast
+explicitly into the key's type. A number based key will become: `CAST(key, 'NSNumber')`
```
Comment (1ec5) [inline platform/darwin/docs/guides/Predicates and Expressions.md]: Filtering vector data is the subject of this section, so it’s a bit redundant to say so.

File: platform/darwin/docs/guides/Predicates and Expressions.md [hunk 18]
```diff
@@ -19,6 +19,17 @@ based on the feature’s attributes. Use the `MGLVectorStyleLayer.predicate`
...
+
+`NSPredicateOperatorType`                     | Format string syntax
+----------------------------------------------|---------------------
+`NSGreaterThanOrEqualToPredicateOperatorType` | `CAST(key, 'valueType') >= value`<br />`CAST(key, 'valueType') => value`
+`NSLessThanOrEqualToPredicateOperatorType`    | `CAST(key, 'valueType') <= value`<br />`CAST(key, 'valueType') =< value`
+`NSGreaterThanPredicateOperatorType`          | `CAST(key, 'valueType') > value`
+`NSLessThanPredicateOperatorType`             | `CAST(key, 'valueType') < value`
```
Comment (1ec5) [inline platform/darwin/docs/guides/Predicates and Expressions.md]: This table is redundant to the table below it, which introduces these operators. Instead, add a paragraph below that table mentioning that `key` may need to be cast to a number or string using the `CAST()` operator and the type `NSNumber` or `NSString`. (Mention these types explicitly, because Swift developers may be inclined to use `Float` or `String` instead.)

File: platform/darwin/docs/guides/Predicates and Expressions.md [hunk 19]
```diff
@@ -19,6 +19,17 @@ based on the feature’s attributes. Use the `MGLVectorStyleLayer.predicate`
...
+
+
```
Comment (1ec5) [inline platform/darwin/docs/guides/Predicates and Expressions.md]: Also reword the paragraph below that starts with “ The predicate's left-hand expression must be…”, because feature attributes or these special attributes don’t need to be on the left side anymore.
