### PR TITLE
[core] Move should not call destructors

### LINKED ISSUE #14348: [core] Format expression parsing error for NSNumber and NSArray attributes.
When our iOS SDK is built with a `release configuration` and you set a format expressions that contain an NSArray or NSNumber as parameters to `MGLSymboStyleLayer.text` crashes with error:

`EXC_BAD_ACCESS (code=EXC_I386_GPFLT)`

**Platform:** iOS
**Mapbox SDK version:** release-liquid-beta.1/2

### Steps to trigger behavior

 1. Edit the iosapp schema and set build configuration to Release and turn on Zombie objects in the Diagnostics tab.
 2. Create a format expression with scale and font names.
 3. Set the expression to `MGLSymboStyleLayer.text`
 3. Crash.

The crash happens inside the method: `convert<MBGLValue>` in this line
https://github.com/mapbox/mapbox-gl-native/blob/fab134ba361900b11a7f51adc00621ece912b2df/platform/darwin/src/MGLStyleValue_Private.h#L92

This behavior is only seen when the attributes are either an NSArray or an NSNumber.
e.g.
```
NSArray *jsonExpression = @[ @"format", @"foo", @{ @"text-color": @[@"rgb", @255, @0, @0] } ];
```

But works for NSString.
e.g.
```
NSArray *jsonExpression = @[ @"format", @"foo", @{ @"text-color": @"blue" } ];
```

I made this test pr to reproduce the crash, tap on `Style Symbol Color` example.
https://github.com/mapbox/mapbox-gl-native/pull/14347

cc @alexshalamov @tmpsantos  @chloekraw @julianrex

### PR DESCRIPTION
**Pull request by alexshalamov**
Fixes #14348 
- Remove unnecessary temporary and move construct new object
- Remove explicit invocation of the destructor

### CODE REVIEW

File: include/mbgl/style/conversion_impl.hpp [hunk 1]
```diff
@@ -235,9 +235,7 @@ class Convertible {
         using Traits = ConversionTraits<T>;
         static VTable vtable = {
             [] (Storage&& src, Storage& dest) {
-                auto srcValue = reinterpret_cast<T&&>(src);
-                new (static_cast<void*>(&dest)) T(std::move(srcValue));
-                srcValue.~T();
+                new (static_cast<void*>(&dest)) T(reinterpret_cast<T&&>(src));
```
Comment (kkaefer) [inline include/mbgl/style/conversion_impl.hpp]: I think this removes too much: Before, we created a new value `srcValue`, and moved `src` to it. Then we explicitly called the destructor, and the compiler added an implicit second destructor call, resulting in two invocations.

This code avoids `srcValue`, and directly moves the casted `src` into the destination. This means that `Storage&&` (aka `std::aligned_storage_t<...>`) gets destructed, but we don't actually call the destructor for `T`.

Comment (kkaefer) [reply include/mbgl/style/conversion_impl.hpp]: Sorry, I made a reduction of this code in https://gist.github.com/kkaefer/97693761cf21d6f57348798c665ca8dd and found that this code is actually correct. I didn't consider that the vtable's `destroy` function will actually call the destructor after the move.

**Comment by kkaefer** [comment]
We also need this change:

```patch
diff --git a/include/mbgl/style/conversion_impl.hpp b/include/mbgl/style/conversion_impl.hpp
index 27b2ee191..d9a47bb97 100644
--- a/include/mbgl/style/conversion_impl.hpp
+++ b/include/mbgl/style/conversion_impl.hpp
@@ -110,6 +110,7 @@ public:
         vtable = v.vtable;
         if (vtable) {
             vtable->move(std::move(v.storage), this->storage);
+            vtable->destroy(v.storage);
         }
         v.vtable = nullptr;
         return *this;

```

Once the move operator moved the object outside of the source convertible in the move assignment operator, it's vtable will be set to `nullptr`. We treat the absence of a vtable as "this `aligned_storage_t` contains uninitialized memory, and never call the destructor on it.

**Comment by kkaefer** [comment]
Alternatively (and preferably), we can remove the `v.vtable = nullptr;` statement and remove all `if (vtable)` checks, since `Convertible` is now guaranteed to have a value:

```cpp
Convertible(Convertible&& v) : vtable(v.vtable) {
    vtable->move(std::move(v.storage), storage);
}

~Convertible() {
    vtable->destroy(storage);
}

Convertible& operator=(Convertible&& v) {
    vtable->destroy(storage);
    vtable = v.vtable;
    vtable->move(std::move(v.storage), storage);
    return *this;
}
```

File: include/mbgl/style/conversion_impl.hpp [hunk 2]
```diff
@@ -89,29 +89,18 @@ class Convertible {
...
     }
 
     ~Convertible() {
-        if (vtable) {
-            vtable->destroy(storage);
-        }
+        vtable->destroy(storage);
     }
 
     Convertible& operator=(Convertible&& v) {
```
Comment (pozdnyakov) [inline include/mbgl/style/conversion_impl.hpp]: check `if (this != &other)`  ? otherwise at `Convertible a; a = std::move(a)` storage will be destroyed

File: include/mbgl/style/conversion_impl.hpp (hunk 1 above)
Comment (pozdnyakov) [reply include/mbgl/style/conversion_impl.hpp]: nit: I'd still prefer `std::move(reinterpret_cast<T>(src))` as more evident.

File: include/mbgl/style/conversion_impl.hpp (hunk 2 above)
Comment (alexshalamov) [reply include/mbgl/style/conversion_impl.hpp]: :+1: done

**Comment by alexshalamov** [comment]
@kkaefer If there is something more to be done for this fix, I will do it in follow-up PR's.
