### PR TITLE
[core] Fix symbol rendering for multipoints

### LINKED ISSUE #7416: Fix symbol rendering for multipoints
Port https://github.com/mapbox/mapbox-gl-js/pull/3763

### PR DESCRIPTION
**Pull request by jfirebaugh**
Fixes #7416

### CODE REVIEW

File: src/mbgl/layout/symbol_layout.cpp [hunk 1]
```diff
@@ -258,55 +250,75 @@ void SymbolLayout::addFeature(const GeometryCollection &lines,
...
-
-            const bool addToBuffers = mode == MapMode::Still || withinPlus0;
-
-            symbolInstances.emplace_back(anchor, line, shapedText, shapedIcon, layout, addToBuffers, symbolInstances.size(),
-                    textBoxScale, textPadding, textPlacement,
-                    iconBoxScale, iconPadding, iconPlacement,
-                    face, indexedFeature);
+        }
+    } else if (feature.type == FeatureType::Polygon) {
+        // TODO: pole of inaccessibility
```
Comment (kkaefer) [inline src/mbgl/layout/symbol_layout.cpp]: should this be part of this PR?

Comment (jfirebaugh) [inline src/mbgl/layout/symbol_layout.cpp]: It's in #7465.
