### PR TITLE
[ios] Simplify -[MGLOfflineStorageTests testAddFileContent]

### LINKED ISSUE #14928: [ios] -[MGLOfflineStorageTests testAddFileContent] fails with multiple devices
When running `make ios-test MORE_SIMULATORS=1` with Xcode 10 at 823670ea35df7d35f68a9d3cb5a42dbc823b66ea (~`ios-v5.1.0-beta.1`), `-[MGLOfflineStorageTests testAddFileContent]` fails on all simulators:

```
Failing tests:
	test:
		-[MGLOfflineStorageTests testAddFileContent]
		-[MGLOfflineStorageTests testAddFileContent]
		-[MGLOfflineStorageTests testAddFileContent]
		-[MGLOfflineStorageTests testAddFileContent]
		-[MGLOfflineStorageTests testAddFileContent]
		-[MGLOfflineStorageTests testAddFileContent]
		-[MGLOfflineStorageTests testAddFileContent]
		-[MGLOfflineStorageTests testAddFileContent]
		-[MGLOfflineStorageTests testAddFileContent]
		-[MGLOfflineStorageTests testAddFileContent]
		-[MGLOfflineStorageTests testAddFileContent]
		-[MGLOfflineStorageTests testAddFileContent]
		-[MGLOfflineStorageTests testAddFileContent]
```

Seems like this test is taking a very long time:

```
Test case '-[MGLOfflineStorageTests testAddFileContent]' failed on 'iPhone Xs Max' (12.384 seconds)
Test case '-[MGLOfflineStorageTests testAddFileContent]' failed on 'iPhone Xʀ' (12.567 seconds)
Test case '-[MGLOfflineStorageTests testAddFileContent]' failed on 'iPad Pro (11-inch)' (11.952 seconds)
```

... so there’s something about this test that isn’t compatible with multiple concurrent simulators.

/cc @fabian-guerra

### PR DESCRIPTION
**Pull request by friedbunny**
Fixes #14928, where `-[MGLOfflineStorageTests testAddFileContent]` failed when run in parallel on multiple simulators.

That issue appears to have been caused by directly moving fixtures around from the build folder to inside the user’s simulator folders, which caused exceptions when multiple simulators expected a stable directory/file structure.

Since our fixtures are copied into the test bundle already, manually moving and setting permissions on them should be unnecessary. These tests have shown past instability (#12999, https://github.com/mapbox/mapbox-gl-native/pull/12911#issuecomment-422600110, #12913), but I’m hoping we can rely on a more conventional way of supplying test fixtures.

(These tests were originally added in #12791.)

## `XCTContext` and `XCTActivity`

I also wrapped subsections of `testAddFileContent` in `XCTContext`, which you can read more about in [Apple’s docs](https://developer.apple.com/documentation/xctest/activities_and_attachments/grouping_tests_into_substeps_with_activities?language=objc). This gives us a nicer breakdown in the test overview:

Screen Shot 2019-06-17 at 5 00 53 PM

/cc @fabian-guerra @julianrex

### CODE REVIEW

File: platform/darwin/test/MGLOfflineStorageTests.mm [hunk 1]
```diff
@@ -285,35 +285,16 @@ - (void)testResourceTransform {
...
-        [fileManager moveItemAtURL:resourceURL toURL:[NSURL fileURLWithPath:filePath] error:&error];
-        NSDictionary *atributes = @{ NSFilePosixPermissions: @0777 };
-        error = nil;
-        [fileManager setAttributes:atributes ofItemAtPath:filePath error:&error];
-        XCTAssertNil(error, @"Changing the file's permissions:%@ should not return an error.", filePath);
-        error = nil;
-        NSDictionary *fileAttributes = [fileManager attributesOfItemAtPath:filePath error:&error];
-        
+        NSDictionary *fileAttributes = [fileManager attributesOfItemAtPath:resourceURL.path error:&error];
+        XCTAssertNil(error, @"Getting the file's permissions:%@ should not return an error.", resourceURL.path);
```
Comment (friedbunny) [inline platform/darwin/test/MGLOfflineStorageTests.mm]: To-do: fix this message.

**Comment by friedbunny** [comment]
> Just one question: with parallel tests - is it possible to have simultaneous tests running on the same device/simulator?

Yes, but if you’re booting multiple copies of the same simulator, I believe they’re independent clones (APFS snapshots) of the original simulator. The issue for us here was that we were manually moving files out of our build directory, which meant they weren’t available after the first test run.

This PR and #14909 resolve the failures I’ve hit so far with parallel simulators, but I haven’t yet focused on the integration tests target.
