### PR TITLE
Custom layer fixes

### LINKED ISSUE #8448: [android] App crashes when swapping a custom layer
Crash when pressing FAB in `CustomLayerActivity` using Samsung Galaxy S6 edge+:

samsungsm-g928a

**Platform:** Android
**Mapbox SDK version:** master branch

### Steps to trigger behavior

 1. Open `CustomLayerActivity`
 2. Press FAB to swap custom layer
 3. Crash

### Expected behavior
App doesn't crash

### Actual behavior
App crashes

bugcustomlayer

### PR DESCRIPTION
**Pull request by ivovandongen**
Fixes #8448 

Fixes two issues reported in #8448:
- VAO usage blacklisted on mali-720 to fix https://github.com/mapbox/mapbox-gl-native/issues/8448#issuecomment-313668245 specifically
- Incorrect fragment shader code. Only breaks on older phones it seems

The issues where obscured by the fact that we don't have error checking in the custom layer functions (as it is external code). Any subsequent opengl operation would fail, hinting at unrelated points in the code. This pr adds some checks on calling into the custom layer code to render_custom_layer to makes sure these things are easier to catch. 

Also added error checking code to the example custom layer to make debugging easier in the future.

### CODE REVIEW

File: platform/android/src/example_custom_layer.cpp [hunk 1]
```diff
@@ -2,11 +2,114 @@
 #include <GLES2/gl2.h>
 
 #include <mbgl/util/logging.hpp>
-
+#include <mbgl/util/string.hpp>
```
Comment (jfirebaugh) [inline platform/android/src/example_custom_layer.cpp]: We should probably remove the `logging.hpp` and `string.hpp` dependencies. I don't think we should encourage custom layer implementations to depend on anything other than `custom_layer.hpp`.

File: src/mbgl/renderer/layers/render_custom_layer.cpp [hunk 2]
```diff
@@ -46,11 +47,11 @@ void RenderCustomLayer::render(PaintParameters& paintParameters, RenderSource*)
     if (context != impl().context || !initialized) {
         //If the context changed, deinitialize the previous one before initializing the new one.
         if (context && !contextDestroyed && impl().deinitializeFn) {
-            impl().deinitializeFn(context);
+            MBGL_CHECK_ERROR(impl().deinitializeFn(context));
```
Comment (jfirebaugh) [inline src/mbgl/renderer/layers/render_custom_layer.cpp]: Is this going to break on Qt due to the special use of `MBGL_CHECK_ERROR` there? (#11106)

cc @kkaefer @tmpsantos

Comment (tmpsantos) [reply src/mbgl/renderer/layers/render_custom_layer.cpp]: Not really, Qt is not using `MBGL_CHECK_ERROR` as described by https://github.com/mapbox/mapbox-gl-native/pull/11106

**Comment by ivovandongen** [comment]
@jfirebaugh Removed the dependencies on mbgl headers, expect for the custom layer specific.
