### PR TITLE
FileSource activation/deactivation tests

### LINKED ISSUE #10911: Add filesource activation/deactivation tests
We recently have seen a couple of bugs related to filesource activation/deactivation (https://github.com/mapbox/mapbox-gl-native/pull/10718, https://github.com/mapbox/mapbox-gl-native/pull/10904, https://github.com/mapbox/mapbox-gl-native/pull/10531). Let's cover these use-cases with instrumentation tests to guard against regressions.

### PR DESCRIPTION
**Pull request by tobrun**
Closes #10911

### CODE REVIEW

File: platform/android/MapboxGLAndroidSDKTestApp/src/androidTest/java/com/mapbox/mapboxsdk/testapp/action/RecyclerViewClickAction.java [hunk 1]
```diff
@@ -0,0 +1,33 @@
...
+
+import android.support.test.espresso.UiController;
+import android.support.test.espresso.ViewAction;
+import android.view.View;
+
+import org.hamcrest.Matcher;
+
+import static android.support.test.espresso.matcher.ViewMatchers.isDisplayed;
+
+public class RecyclerViewClickAction implements ViewAction {
```
Comment (LukasPaczos) [inline platform/android/MapboxGLAndroidSDKTestApp/src/androidTest/java/com/mapbox/mapboxsdk/testapp/action/RecyclerViewClickAction.java]: Do we need this class? As far as I can see it's not used anywhere.

File: platform/android/MapboxGLAndroidSDKTestApp/src/androidTest/java/com/mapbox/mapboxsdk/testapp/action/OrientationChangeAction.java [hunk 2]
```diff
@@ -17,7 +17,7 @@
 
   private final int orientation;
 
-  private OrientationChangeAction(int orientation) {
+  OrientationChangeAction(int orientation) {
```
Comment (LukasPaczos) [inline platform/android/MapboxGLAndroidSDKTestApp/src/androidTest/java/com/mapbox/mapboxsdk/testapp/action/OrientationChangeAction.java]: This one could stay private, right?

File: platform/android/MapboxGLAndroidSDKTestApp/src/androidTest/java/com/mapbox/mapboxsdk/testapp/activity/BaseActivityTest.java [hunk 3]
```diff
@@ -72,7 +73,7 @@ protected void waitLoop() {
   }
 
   protected void waitLoop(long waitTime) {
```
Comment (LukasPaczos) [inline platform/android/MapboxGLAndroidSDKTestApp/src/androidTest/java/com/mapbox/mapboxsdk/testapp/activity/BaseActivityTest.java]: Small nitpick, can we rename `#waitLoop()` to match with the new `WaitAction` class?

File: platform/android/src/file_source.cpp [hunk 4]
```diff
@@ -81,6 +81,13 @@ void FileSource::pause(jni::JNIEnv&) {
     }
 }
 
+jni::jboolean FileSource::isResumed(jni::JNIEnv&) {
+    if (activationCounter) {
+       return  (jboolean) (activationCounter != 0);
```
Comment (LukasPaczos) [inline platform/android/src/file_source.cpp]: The check here should be `(activationCounter > 0)` otherwise sequence
```
FileSource.activate();
FileSource.deactivate();
FileSource.deactivate();
```
will result in `FileSource.isResumed()` returning `true`.
