### PR TITLE
Query when renderer is being recreated

### LINKED ISSUE #14394: Crash when calling MapboxMap#query when activity is restarted
Follow up issue from downstream nav integration in https://github.com/mapbox/mapbox-navigation-android/issues/1865. When backgrounding the app, bringing back forward and having the following `Activity#onStart`:

```java
  @Override
  protected void onStart() {
    super.onStart();
    mapView.onStart();
    if (mapboxMap != null) {
      mapboxMap.queryRenderedFeatures(new PointF(0, 0));
    }
  }
```

This issue originates from destroying the renderer as part of backgrounding the app. When restarted the renderer hasn't been fully recreated yet. 

cc @Guardiola31337

### PR DESCRIPTION
**Pull request by tobrun**
Closes #14394, this PR hardens querying the map when the underlying surface is being recreated. With 7.3.0, we changed the lifespan of the renderer to match the surface (instead of the MapView). This change resulted in that the API found on our core renderer isn't usable directly after resuming an Activity. Checking if we have a surface solves that but this is something we need to revisit in the long run in a cleaner way.

This PR adds a regression test, additional javadoc explaining the issue and the actual fix. 

cc @Guardiola31337

### CODE REVIEW

File: platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/maplayout/SimpleMapActivity.java [hunk 1]
```diff
@@ -12,22 +14,30 @@
...
+    });
   }
 
   @Override
   protected void onStart() {
     super.onStart();
     mapView.onStart();
+    if (mapboxMap != null) {
+      // Regression test for #14394
+      mapboxMap.queryRenderedFeatures(new PointF(0,0));
```
Comment (LukasPaczos) [inline platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/maplayout/SimpleMapActivity.java]: How about moving the test to one of the query activities and leaving this one simple? :)

Comment (tobrun) [reply platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/maplayout/SimpleMapActivity.java]: atm, the query activities don't include a test for restarting them but that can be changed.

Comment (LukasPaczos) [reply platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/maplayout/SimpleMapActivity.java]: I was just thinking about a different tetstapp acttivity
