### PR TITLE
Avoid IndexOutOfBoundsException when destroying map object

### LINKED ISSUE #9785: AnnotationManager.addMarkers throws ArrayIndexOutOfBoundsException
```
Message: ArrayIndexOutOfBoundsException: length=0; index=0
com.mapbox.mapboxsdk.maps.AnnotationManager.addMarkers in SourceFile::195
com.mapbox.mapboxsdk.maps.MapboxMap.addMarkers in SourceFile::1167
com.company.map.ui.MapFragment.updateMarkers in SourceFile::261
com.company.map.ui.MapFragment.onMapReady in SourceFile::231
com.mapbox.mapboxsdk.maps.MapView$MapCallback.onMapReady in SourceFile::1037
com.mapbox.mapboxsdk.maps.MapView$MapCallback.access$1000 in SourceFile::1002
com.mapbox.mapboxsdk.maps.MapView$MapCallback$1.run in SourceFile::1020
android.os.Handler.handleCallback in Handler.java::739
android.os.Handler.dispatchMessage in Handler.java::95
android.os.Looper.loop in Looper.java::158
android.app.ActivityThread.main in ActivityThread.java::7224
java.lang.reflect.Method.invoke in Method.java::-2
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run in ZygoteInit.java::1230
com.android.internal.os.ZygoteInit.main in ZygoteInit.java::1120
```
**Platform:**
Android

**Mapbox SDK version:**
5.0.2@aar

### Cause
I believe the map has been disposed when the _onMapReady()_ is called after _onDestroy()_

I have not tested this on the current release but a quick code review of AnnotationManager suggests that the bug will happen still on 5.1.4.

### Anaylsis
In _AnnotationManager.addMarkers()_ there is a call to _nativeMapView.addMarkers(markers)_ which returns an array of ids.
Inside _NativeMapView.addMarkers()_ it checks to see if onDestroy has been called and returns a zero size array of longs.
_AnnotationManager.addMarkers()_ then fails to iterate correctly as it assumes that the size of the array is the size of the supplied list of markers, not zero.
A review of _AnnotationManager.addPolygons()_ and  _AnnotationManager.addPolylines()_ looks like they would suffer the same problem as the code appears cut and paste, could possibly factor out some common code.

### Suggested improvements
* Use the size of the returned array for the subsequent iterations
* Do not call _onMapReady()_ callback if the map has been destroyed

### PR DESCRIPTION
**Pull request by tobrun**
Closes #9785

### CODE REVIEW

File: platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MarkerContainer.java [hunk 1]
```diff
@@ -63,26 +63,13 @@ public Marker addBy(@NonNull BaseMarkerOptions markerOptions, @NonNull MapboxMap
       }
 
       if (markers.size() > 0) {
-        long[] ids = null;
-        if (nativeMapView != null) {
-          ids = nativeMapView.addMarkers(markers);
+        long[] ids = nativeMapView.addMarkers(markers);
```
Comment (zugaldia) [inline platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MarkerContainer.java]: Looks like the `if (nativeMapView != null)` check was lost during the refactor. Wouldn't we want to reintroduce it?

Comment (zugaldia) [inline platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MarkerContainer.java]: Same with the other two cases below.

Comment (tobrun) [inline platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MarkerContainer.java]: fixed with 7335566
