### PR TITLE
5427 marker view flat bug

### LINKED ISSUE #5427: Marker view flat bug
When an activity initiates the map with a tilt with a marker view flat set to true the icon isn't flattened until the user tilts the map manually. 

Purple marker in this gif shows what happens:
ezgif com-video-to-gif 3

cc: @tobrun @zugaldia

### PR DESCRIPTION
**Pull request by tobrun**
closes #5427

### CODE REVIEW

File: platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/annotation/MarkerViewActivity.java [hunk 1]
```diff
@@ -163,8 +163,6 @@ public boolean onMarkerClick(@NonNull Marker marker, @NonNull View view, @NonNul
                         .icon(IconFactory.getInstance(mMapView.getContext())
                                 .fromResource(R.drawable.ic_arsenal))
                 );
-
-                mMapboxMap.getUiSettings().setFocalPoint(new PointF(mMapView.getMeasuredWidth() / 2, mMapView.getMeasuredHeight() / 4));
```
Comment (zugaldia) [inline platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/annotation/MarkerViewActivity.java]: @tobrun Did you intend to remove this line?

File: platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/annotations/MarkerViewManager.java [hunk 2]
```diff
@@ -349,6 +349,9 @@ public void invalidateViewMarkersInBounds() {
                         if (adaptedView != null) {
 
                             // tilt
+                            if (marker.isFlat() && marker.getTilt() == 0) {
+                                marker.setTilt((float) mapboxMap.getCameraPosition().tilt);
+                            }
```
Comment (zugaldia) [inline platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/annotations/MarkerViewManager.java]: @tobrun How about this instead?

```
if (marker.isFlat() && marker.getTilt() != mapboxMap.getCameraPosition().tilt) {
	marker.setTilt((float) mapboxMap.getCameraPosition().tilt);
}
```

File: platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/annotation/MarkerViewActivity.java (hunk 1 above)
Comment (tobrun) [inline platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/annotation/MarkerViewActivity.java]: Yes, that was an artefact of implementing #4924.

File: platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/annotations/MarkerViewManager.java (hunk 2 above)
Comment (tobrun) [inline platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/annotations/MarkerViewManager.java]: that is mucho mejor!

Comment (tobrun) [inline platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/annotations/MarkerViewManager.java]: looking into this again, the `getCameraPosiition` will in most cases result in a JNI call, for high trafficking code as `MarkerViewManager.update()` this might not be ideal. The code inside the if check is currently only used to initialise the marker with the correct tilt value not to update it every time (this is done through a setter).

**Comment by tobrun** [comment]
@zugaldia I moved the initial tilt value setup to another place in the code (not longer a part of the high trafficking code in `MarkerVIewManager.update()` but as part of `MarkerView.setMapboxMap()`

**Comment by zugaldia** [comment]
@tobrun Sounds good, good catch on the JNI call. I'll merge it now.
