### PR TITLE
Qt QSQLite + HTTPRequest updates

### LINKED ISSUE #10413: [Qt] SQLite implementation issues with concurrent writes
We've seen concurrency issues related to the SQLite Qt-based implementation e.g. when two or more database connections attempt to write an entry into the `tiles` table, the entry's `data` column ends up empty, causing loss of data and rendering artifacts as seen below:

screenshot from 2017-11-08 13-33-01

In the image above, the same tile data for 0/0/0 is requested from two different render tiles, with one successfully obtaining the data, and the other not. The faulty render tile ends up writing the empty `data` column back in the offline database.

This bug has been haunting us for a while - though it doesn't show up as often due to a series of factors:

1. We don't necessarily generate the database file via Qt e.g. we could initialize it using the GLFW demo app (which uses the default database implementation) and further reuse it on Qt;
2. In some rare cases, the tiles shows just fine and the data is properly written into the database - suggesting this could be a race condition issue;
3. We only happen to request the same tile data from different render tiles when showing the _wrapped_ world, which is usually the case when approaching zoom levels 1 & 0.

So far my mitigation attempts have failed:
- Our Qt-based `Transaction` implementation doesn't follow `QSqlDatabase` transaction implementation, as it doesn't allow us to provide which transaction behavior to use. Instead, we use the same `exec()` calls as in the default SQLite implementation (I've also attempted using `QSqlDatabase`'s `transaction()`, `commit()` & `rollback()` calls with no effect).
- I've already attempted adding more transaction gates inside `OfflineDatabase::putTile` with no effect.

/cc @tmpsantos @kkaefer

### PR DESCRIPTION
**Pull request by brunoabinader**
- Cleanup & refactor `QSqlDatabase` usage in the Qt SQLite implementation.
- Fixes an issue in Qt's `HTTPRequest` implementation that causes data corruption when two or more HTTPRequest are pending on the same network reply - the first one gets the data while the following ones gets empty data because `QNetworkReply::readAll()` erases the contents of the data reply.

Fixes #10413.

### CODE REVIEW

File: platform/qt/src/sqlite3.cpp [hunk 1]
```diff
@@ -60,20 +60,23 @@ void checkDatabaseOpenError(const QSqlDatabase &db) {
     }
 }
 
+namespace {
+    thread_local uint64_t count = 0;
```
Comment (tmpsantos) [inline platform/qt/src/sqlite3.cpp]: We cannot use `thread_local` because it doesn't work on iOS. Use `mbgl::util::ThreadLocal` instead.

File: platform/qt/src/sqlite3.cpp [hunk 2]
```diff
@@ -60,20 +60,23 @@ void checkDatabaseOpenError(const QSqlDatabase &db) {
...
+}
+
 class DatabaseImpl {
 public:
-    DatabaseImpl(const char* filename, int flags) {
-        static uint64_t count = 0;
```
Comment (tmpsantos) [inline platform/qt/src/sqlite3.cpp]: Another way of implementing this without thread local would be using `QAtomicInt`. I'm fine with either way.

File: platform/qt/src/sqlite3.cpp [hunk 3]
```diff
@@ -169,9 +173,9 @@ void Database::exec(const std::string &sql) {
         if (!statement.endsWith(';')) {
             statement.append(';');
         }
-        QSqlQuery query(*impl->db);
-        query.setForwardOnly(true);
```
Comment (tmpsantos) [inline platform/qt/src/sqlite3.cpp]: Is this no longer useful? (was it ever useful anyway) :)

Comment (tmpsantos) [reply platform/qt/src/sqlite3.cpp]: Was reviewing all changes at once. On one commit you explain why you removed this. :+1:

File: platform/qt/src/sqlite3.cpp (hunk 1 above)
Comment (tmpsantos) [reply platform/qt/src/sqlite3.cpp]: https://github.com/mapbox/mapbox-gl-native/pull/9448

File: platform/qt/src/sqlite3.cpp [hunk 4]
```diff
@@ -60,20 +61,29 @@ void checkDatabaseOpenError(const QSqlDatabase &db) {
     }
 }
 
+namespace {
+    static QAtomicInt count = 0;
+
+    // Qt4 does not support operator++ in QAtomicInt.
+    QString incrementCount() {
+        count = count + 1;
```
Comment (tmpsantos) [inline platform/qt/src/sqlite3.cpp]: This is not exactly atomic, because you have in fact two operations.

I think you could do a `return QString::number(count.fetchAndAddAcquire(1));`

File: platform/qt/src/sqlite3.cpp [hunk 5]
```diff
@@ -60,20 +61,29 @@ void checkDatabaseOpenError(const QSqlDatabase &db) {
     }
 }
 
+namespace {
+    static QAtomicInt count = 0;
```
Comment (tmpsantos) [inline platform/qt/src/sqlite3.cpp]: I would also move this to inside `incrementCount` so it cannot be accessed outside the function scope.
