### PR TITLE
avoid adding duplicate points to bounds

### LINKED ISSUE #9953: LatLngBounds with one point
**Platform: Android **
**Mapbox SDK version: 5.1.3**

Create a LatLngBounds with one point trigger an exception (Cannot create a LatLngBounds with one position)

Create a LatLngBounds with two point with same coordinates works.

It should be considered to let user creates a bounds including only one point or improve the exception behavior. #

### PR DESCRIPTION
**Pull request by tobrun**
closes #9953, this PR validates if a point added to the LatLngBounds builder hasn't been added before. Atm a developer can create a bounds from one point by passing in the same point twice.

### CODE REVIEW

File: platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/geometry/LatLngBounds.java [hunk 1]
```diff
@@ -450,7 +450,9 @@ public LatLngBounds build() {
      */
     public Builder includes(List<LatLng> latLngs) {
       for (LatLng point : latLngs) {
-        latLngList.add(point);
+        if (!latLngList.contains(point)) {
```
Comment (Guardiola31337) [inline platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/geometry/LatLngBounds.java]: Could you extract this into a private method? The same exact piece of code is duplicated and could be simplified and used from both `includes` and `include` methods.
