### PR TITLE
Configure logging of HttpRequest, cleanup HttpRequest

### LINKED ISSUE #9638: Revisit log level for HTTP permanent errors
The Mapbox Android SDK currently includes verbose logs for all canceled HTTP requests. While this makes sense for unknown errors, it can cause an unexpectedly large amount of logging for apps that are designed to work in a mostly offline environment and should be revisited to determine if the amount of logs should be reduced.

cc @zugaldia

### PR DESCRIPTION
**Pull request by tobrun**
Closes #9638. 

To expose the configuration of enabling/disabling logging of HttpRequest. I had to expose a utility to workaround package private implementation of HttpRequest (this class is not part of our public API). Additionally on above change, a cleanup of the class was done (remove Hungarian notation, cleanup final/static keywords for fields, class naming conventions).

### CODE REVIEW

File: platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/http/HttpRequest.java [hunk 1]
```diff
@@ -0,0 +1,231 @@
...
+      } else {
+        resourceUrl = resourceUrl + "&";
+      }
+      resourceUrl = resourceUrl + "events=true";
+    }
+    return resourceUrl;
+  }
+
+  private Request buildRequest(String resourceUrl, String etag, String modified) {
+    String userAgentString = Util.toHumanReadableAscii(
```
Comment (zugaldia) [inline platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/http/HttpRequest.java]: Looks like we're now build the agent string with every request, could we change this so that it only happens once?

File: platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/http/HttpRequest.java [hunk 2]
```diff
@@ -0,0 +1,231 @@
...
+    this.nativePtr = nativePtr;
+
+    try {
+      // Don't try a request if we aren't connected
+      if (!Mapbox.isConnected()) {
+        throw new NoRouteToHostException("No Internet connection available.");
+      }
+
+      HttpUrl httpUrl = HttpUrl.parse(resourceUrl);
+      resourceUrl = adaptResourceUrl(httpUrl, resourceUrl);
```
Comment (zugaldia) [inline platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/http/HttpRequest.java]: Looks like `HttpUrl httpUrl` isn't used in this method and it could be moved into the new `adaptResourceUrl`

File: platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/http/HttpRequest.java [hunk 3]
```diff
@@ -0,0 +1,231 @@
...
+      onFailure(exception);
+    }
+  }
+
+  private String adaptResourceUrl(HttpUrl httpUrl, String resourceUrl) {
+    final String host = httpUrl.host().toLowerCase(MapboxConstants.MAPBOX_LOCALE);
+    if (host.equals("mapbox.com") || host.endsWith(".mapbox.com") || host.equals("mapbox.cn")
+      || host.endsWith(".mapbox.cn")) {
+      if (httpUrl.querySize() == 0) {
+        resourceUrl = resourceUrl + "?";
```
Comment (zugaldia) [inline platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/http/HttpRequest.java]: Would it be overkill to benefit from `HttpUrl.newBuilder()` here instead of doing it manually?

File: platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/http/HttpRequest.java (hunk 1 above)
Comment (tobrun) [inline platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/http/HttpRequest.java]: afaik, a new instance of HttpRequest.java is created every time for each request. The user agent isn't retained over instances.

Comment (zugaldia) [inline platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/http/HttpRequest.java]: @tobrun Thank you for the clarification. In that case let's leave it as is for this PR but let's ticket a follow up (if it doesn't exist yet) where we want to look into avoiding that behavior. If a new instance is created for each request we aren't benefitting from reusing the connection pool from OkHttp.

Comment (tobrun) [inline platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/http/HttpRequest.java]: We are actually benefiting from the connection pool because the client is contained in a static field. Every instance of HttpRequest will have the same OkHttpClient (while this works, I would like to manage this differently, don't feel this is very clean). I will work on creating a ticket to avoid creating HttpRequests object with every request.

File: platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/http/HttpRequest.java (hunk 3 above)
Comment (tobrun) [inline platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/http/HttpRequest.java]: This will be way cleaner:
```java

  private String adaptResourceUrl(String resourceUrl) {
    HttpUrl httpUrl = HttpUrl.parse(resourceUrl);
    if (httpUrl != null && isMapboxHost(httpUrl)) {
      HttpUrl.Builder builder = httpUrl.newBuilder();
      builder.addQueryParameter("events", "true");
      resourceUrl = builder.build().toString();
    }
    return resourceUrl;
  }
```

Comment (zugaldia) [inline platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/http/HttpRequest.java]: @tobrun awesome - let's do that unless profiling indicates worse performance.

File: platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/http/HttpRequest.java (hunk 1 above)
Comment (zugaldia) [inline platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/http/HttpRequest.java]: @tobrun You're right about the connection pool - I just included a simple `Timber.d("connectionPool: %s", mClient.connectionPool().hashCode());` on the constructor and I'm getting the same hash even for different activities. However, isn't still unnecessary to recreate the user agent for every request considering it doesn't change between requests?

Comment (tobrun) [inline platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/http/HttpRequest.java]: Yeah, we can make that field static for now this would result in not recreating the user agent. 
Follow up work for above in general in https://github.com/mapbox/mapbox-gl-native/issues/9772.

**Comment by tobrun** [comment]
@zugaldia  
c23e8e3 includes correct reusing `userAgen`t across HttpRequest instances. 
PR is ready for review.

**Comment by snkashis** [comment]
How exactly does one configure this in 5.2.1? Since moving to 5.2.0 & 5.2.1, our log volume for failed map requests on poor/intermittent connections has seemed to increase dramatically. We want to disable all logging of these failed requests to avoid Crashlytics picking them up and burning battery/network to send them.

**Comment by zugaldia** [comment]
> How exactly does one configure this in 5.2.1?

There's an example of how to do this in the `OfflineActivity.java` file included by this PR. Basically, you'd call `HttpRequestUtil.setLogEnabled(true)` to enable the extra logging, and `HttpRequestUtil.setLogEnabled(false)` to disable it.

**Comment by snkashis** [comment]
But I don't see that HttpRequestUtil file in the location mentioned in this PR anymore - https://github.com/mapbox/mapbox-gl-native/tree/master/platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/http

I cannot import it currently while running
implementation 'com.mapbox.mapboxsdk:mapbox-android-sdk:5.2.1@aar'
Do I need to import something else?

**Comment by tobrun** [comment]
This PR got reverted with https://github.com/mapbox/mapbox-gl-native/pull/9851, tracking to add this in https://github.com/mapbox/mapbox-gl-native/issues/10672.

**Comment by snkashis** [comment]
Okay great, I tried setting this up a week ago with the same instructions provided by @zugaldia , so thought I was missing something else.
