### PR TITLE
Fix CustomLayer context retain count

### LINKED ISSUE #10755: MGLOpenGLStyleLayer is released prior to calling MGLFinishCustomStyleLayer
Changes to core GL for asynchronous rendering changed when the `mbgl::style::CustomLayer`'s `CustomLayerDeinitializeFunction` callback method is invoked.

This callback is now invoked after the layer is removed from a style, and when it's corresponding `RenderCustomLayer` instance is destroyed. 

The `[MGLOpenGLStyleLayer setStyle:]` method is releasing itself as soon as the layer is removed from the style, which leaves the underlying `CustomLayer::Impl` instance holding on to a dangling pointer. 

This leads to `EXC_BAD_ACCESS` exceptions with call stack:
```
#1	0x00000001008745d8 in MGLFinishCustomStyleLayer(void*) 
#2	0x0000000100a5ca20 in mbgl::RenderCustomLayer::~RenderCustomLayer() 
#3	0x0000000100a5caa0 in mbgl::RenderCustomLayer::~RenderCustomLayer() 
#4	0x0000000100a5cad4 in mbgl::RenderCustomLayer::~RenderCustomLayer() 
#5	0x0000000100b637ec in std::__1::default_delete<mbgl::RenderLayer>::operator()(mbgl::RenderLayer*) const 
...
#20	0x0000000100b50b60 in mbgl::Renderer::Impl::render(mbgl::UpdateParameters const&)
#21	0x0000000100b484f0 in mbgl::Renderer::render(mbgl::UpdateParameters const&)
#22	0x000000010077ac7c in MGLRenderFrontend::render()
```

### PR DESCRIPTION
**Pull request by asheemmamoowala**
Fixes #10755 

In core, with style diffing a `RenderCustomLayer` instance is reused if the new style has a `CustomLayer` with the same identifier as the previous style. This was not handled correctly in `RenderCustomLayer`. When the `impl` or `context` for the layer is changed, it should invoke the `CustomLayerDeinitializeFunction` callback.

Changes to core GL for asynchronous rendering changed when the `mbgl::style::CustomLayer`'s `CustomLayerDeinitializeFunction` callback method is invoked. This resulted in the `MGLOpenGLStyleLayer` releasing itself early when removed from the owning style:

https://github.com/mapbox/mapbox-gl-native/blob/920057c9d6285fc30f4155a505e2bf15143e3842/platform/darwin/src/MGLOpenGLStyleLayer.mm#L114-L121

When `MGLFinishCustomStyleLayer` is called on a subsequent frame, it is left holding on to a dangling pointer to the layer.

To remedy this, the layer retention needs to match the lifecycle required by the async renderer. Using `__bridge_retain` implicitly retains the bridged pointer passed to core. This should be the correct behavior since we are not using a weak pointer. When `MGLFinishCustomStyleLayer` takes back ownership of the pointer from core and uses `__bridge_transfer`. 

Apple docs for [Toll-Free Bridged Types](https://developer.apple.com/library/content/documentation/CoreFoundation/Conceptual/CFDesignConcepts/Articles/tollFreeBridgedTypes.html) 

//cc @lilykaiser @jmkiley @jfirebaugh @1ec5

### CODE REVIEW

File: platform/darwin/src/MGLStyle.mm [hunk 1]
```diff
@@ -77,7 +77,6 @@ @interface MGLStyle()
 @property (nonatomic, readonly, weak) MGLMapView *mapView;
 @property (nonatomic, readonly) mbgl::style::Style *rawStyle;
 @property (readonly, copy, nullable) NSURL *URL;
-@property (nonatomic, readwrite, strong) NS_MUTABLE_DICTIONARY_OF(NSString *, MGLOpenGLStyleLayer *) *openGLLayers;
```
Comment (1ec5) [inline platform/darwin/src/MGLStyle.mm]: Looks like this dictionary wound up unused after #8626. The original purpose of this dictionary was to allow `-layerWithIdentifier:` to return a fully initialized MGLOpenGLStyleLayer object that still had its callback implementations intact. As long as that’s still working correctly, this change looks good.

**Comment by akitchen** [comment]
@1ec5 yep - darwin changes look good to me; @asheemmamoowala and I were also looking at this together yesterday. I'm currently testing with a local test case I have set up.

File: platform/darwin/src/MGLOpenGLStyleLayer.mm [hunk 2]
```diff
@@ -116,9 +116,7 @@ - (void)setStyle:(MGLStyle *)style {
         [NSException raise:@"MGLLayerReuseException"
                     format:@"%@ cannot be added to more than one MGLStyle at a time.", self];
     }
-    _style.openGLLayers[self.identifier] = nil;
     _style = style;
-    _style.openGLLayers[self.identifier] = self;
```
Comment (akitchen) [inline platform/darwin/src/MGLOpenGLStyleLayer.mm]: This is the only place where this dictionary was being used @1ec5 ; transferring the ownership is a better solution (and fixes the crash)

File: platform/darwin/src/MGLStyle.mm (hunk 1 above)
Comment (akitchen) [reply platform/darwin/src/MGLStyle.mm]: @1ec5 verified

Comment (asheemmamoowala) [reply platform/darwin/src/MGLStyle.mm]: @1ec5 `[MGLStlye layerFromMBGLLayer]` already takes care of this for all layer types.

**Comment by akitchen** [comment]
> I'm currently testing with a local test case I have set up.
Local test case / manual verification passed. I'm toying with some automated testing strategies for this but nothing that should block the merge.

File: platform/darwin/src/MGLOpenGLStyleLayer.mm [hunk 3]
```diff
@@ -101,7 +101,7 @@ - (instancetype)initWithIdentifier:(NSString *)identifier {
                                                             MGLPrepareCustomStyleLayer,
                                                             MGLDrawCustomStyleLayer,
                                                             MGLFinishCustomStyleLayer,
-                                                            (__bridge void *)self);
+                                                            (__bridge_retained void *)self);
```
Comment (jfirebaugh) [inline platform/darwin/src/MGLOpenGLStyleLayer.mm]: It's a corner case, but: this will leak a `MGLOpenGLStyleLayer` that's `init`'d but never added to a map.

Comment (asheemmamoowala) [reply platform/darwin/src/MGLOpenGLStyleLayer.mm]: 😞 I knew I was missing something! Moved to : https://github.com/mapbox/mapbox-gl-native/issues/10771
