### PR TITLE
Prevent stopless functions

### LINKED ISSUE #7249: MGLStyleFunction must have at least one stop
Raise an exception if MGLStyleFunction is initialized without any stops.

ref #7248

### PR DESCRIPTION
**Pull request by frederoni**
Fixes #7249 
Raises an exception if an `MGLStyleFunction` is initialized with no stops.

### CODE REVIEW

File: platform/darwin/src/MGLStyleValue.mm [hunk 1]
```diff
@@ -63,6 +63,7 @@ - (instancetype)init {
 
 - (instancetype)initWithBase:(CGFloat)base stops:(NSDictionary *)stops {
     if (self = [super init]) {
+        NSAssert(stops.allKeys.count, @"%@ need at least one stop.", [self class]);
```
Comment (1ec5) [inline platform/darwin/src/MGLStyleValue.mm]: `stops.count` would be more efficient.

Comment (1ec5) [inline platform/darwin/src/MGLStyleValue.mm]: `[self class]` resolves to `MGLConstantStyleValue` or `MGLStyleFunction`, but I think `self` would be more informative since it calls `-description`.

Comment (1ec5) [inline platform/darwin/src/MGLStyleValue.mm]: For internal errors, use `NSAssert()`. For developer errors, raise an NSException and give it a name like `NSInvalidArgumentException` that the developer can identify the exception by.

File: platform/darwin/test/MGLFunctionTests.m [hunk 2]
```diff
@@ -0,0 +1,13 @@
+#import <XCTest/XCTest.h>
+#import <Mapbox/Mapbox.h>
+
+@interface MGLFunctionTests : XCTestCase
+@end
+
+@implementation MGLFunctionTests
+
+- (void)testStoplessFunction {
+    XCTAssertThrows([MGLStyleValue<NSNumber *> valueWithStops:@{}], @"Stopless function should throw an exception");
```
Comment (1ec5) [inline platform/darwin/test/MGLFunctionTests.m]: If you give the exception a name, you can use `XCTAssertThrowsSpecificNamed()` here.

File: platform/darwin/test/MGLFunctionTests.m [hunk 3]
```diff
@@ -0,0 +1,13 @@
+#import <XCTest/XCTest.h>
+#import <Mapbox/Mapbox.h>
+
+@interface MGLFunctionTests : XCTestCase
```
Comment (1ec5) [inline platform/darwin/test/MGLFunctionTests.m]: Let’s call this MGLStyleValueTests for consistency with the file that contains the implementation.

Comment (frederoni) [inline platform/darwin/test/MGLFunctionTests.m]: MGLStyleValueTests is taken by a Swift class with the same name but I can't use that class to catch a specific exception name if the method itself doesn't throw the exception. Renamed it to MGLStyleValueObjCTests for now.

Comment (1ec5) [inline platform/darwin/test/MGLFunctionTests.m]: Ah, I see. Alternatively, maybe we can call this class MGLStyleValueTests and turn the Swift class into an extension on MGLStyleValueTests. Not sure if XCTest will be happy with that or not.

File: platform/darwin/src/MGLStyleValue.mm [hunk 4]
```diff
@@ -63,6 +63,10 @@ - (instancetype)init {
 
 - (instancetype)initWithBase:(CGFloat)base stops:(NSDictionary *)stops {
     if (self = [super init]) {
+        if (!stops.count)
+        {
+            [NSException raise:@"NSInvalidArgumentException" format:@"%@ requires at least one stop.", self];
```
Comment (1ec5) [inline platform/darwin/src/MGLStyleValue.mm]: Use the constant, `NSInvalidArgumentException`.

File: platform/darwin/test/MGLStyleValueObjCTests.m [hunk 5]
```diff
@@ -0,0 +1,13 @@
+#import <XCTest/XCTest.h>
+#import <Mapbox/Mapbox.h>
+
+@interface MGLStyleValueObjCTests : XCTestCase
+@end
+
+@implementation MGLStyleValueObjCTests
+
+- (void)testStoplessFunction {
+    XCTAssertThrowsSpecificNamed([MGLStyleValue<NSNumber *> valueWithStops:@{}], NSException, @"NSInvalidArgumentException", @"Stopless function should raise an exception");
```
Comment (1ec5) [inline platform/darwin/test/MGLStyleValueObjCTests.m]: The constant `NSInvalidArgumentException` works here too.
