### PR TITLE
[darwin] Fix direction wrapping

### LINKED ISSUE #14073: Clockwise map rotation gesture is broken after core camera refactor
### Steps to reproduce

 1. Pinch-rotate a map clockwise.

### Expected behavior

Map rotates and stays rotated (if the zoom level is sufficient to allow rotation).

### Actual behavior

Map rotates for the duration of the gesture, but erroneously snaps back to 0° when the gesture is released.

### Configuration

**Mapbox SDK versions:** `ios-v4.10.0-alpha.1`

This bisects to 73ac3c784fe755650dc631e2e722a47890981248 (#14017) by @brunoabinader and, so far, only exists in the `ios-v4.10.0-alpha.1` release. Have not confirmed if this affects other platforms.

/cc @julianrex @tobrun

### PR DESCRIPTION
**Pull request by friedbunny**
Fixes #14073 by re-adding the 0-to-360° wrapping for `MGLMapView.direction` that was removed in #14017. Without this wrapping, we’d get ±180° from core, which results in invalid `CLLocationDirection` for the negative half of the rotational spectrum.

This is a two line fix that adds a variety of tests to confirm that the iOS rotation gesture and compass rotation are correct.

/cc @brunoabinader @1ec5

### CODE REVIEW

File: include/mbgl/map/camera.hpp [hunk 1]
```diff
@@ -37,7 +37,7 @@ struct CameraOptions {
         levels. */
     optional<double> zoom;
 
-    /** Bearing, measured in degrees from true north. Wrapped to [0, 360). */
+    /** Bearing, measured in degrees from true north. Wrapped to [0, 360]. */
```
Comment (brunoabinader) [inline include/mbgl/map/camera.hpp]: This is still `[0, 360)`: check https://github.com/mapbox/mapbox-gl-native/blob/master/include/mbgl/math/wrap.hpp#L8-L16.

Comment (friedbunny) [reply include/mbgl/map/camera.hpp]: Ah, I wasn’t considering that this was [an intentional notation](https://en.wikipedia.org/wiki/Bracket#Mathematics) for a “half-open range”. 👍
