### PR TITLE
[ios] Improvement of the tilt gesture

### LINKED ISSUE #2192: Tilt gesture is slightly delayed
Compared to Apple, our tilt gesture lags — both in initial recognition and during the gesture. This may be two issues:
1. Our iOS gesture recognizer may be waiting too long to see if other gestures are failing
2. Setting pitch on the map view may have a lag before it takes effect

/cc @ansis @1ec5 @incanus

### PR DESCRIPTION
**Pull request by flashspys**
This implementation of the tilt gesture feels much better. It is inspired by Apple's implementation of the tilt gesture in the Maps application.

Fixes #2192.

### CODE REVIEW

**Comment by flashspys** [comment]
@friedbunny Edit from maintainers is allowed, glad that I could help!

File: platform/ios/src/MGLMapView.mm [hunk 1]
```diff
@@ -1968,20 +1968,21 @@ - (void)handleTwoFingerDragGesture:(UIPanGestureRecognizer *)twoFingerDrag
     [self cancelTransitions];
 
     self.cameraChangeReasonBitmask |= MGLCameraChangeReasonGestureTilt;
-
+    static CGFloat initialPitch;
```
Comment (julianrex) [inline platform/ios/src/MGLMapView.mm]: How does this affect the gesture when deallocating `MGLMapView` and then allocating a new one? (i.e. `initialPitch` will have the previous view's value)

Comment (flashspys) [reply platform/ios/src/MGLMapView.mm]: I don’t think so, as the initial pitch is always set in the beginning state of the gesture recognizer. So it would only be a problem, if the method gets called without being in the beginning state at the first call. I think due to the UIGestureRecognizer architecture this is not possible.

Comment (friedbunny) [reply platform/ios/src/MGLMapView.mm]: It shouldn’t be possible for a user to perform a tilt gesture on a new map view and get a stale value for `initialPitch` — `initialPitch` is set on `UIGestureRecognizerStateBegan`, which should always happen before we need this value to calculate the new pitch (to change the camera, and so on).

Comment (julianrex) [reply platform/ios/src/MGLMapView.mm]: Works for me - thanks @flashspys!
