### PR TITLE
Bind only active attributes in order to avoid exceeding attribute limits

### LINKED ISSUE #9331: glBindAttribLocation(id, location, name): Error GL_INVALID_VALUE
**Platform: Android 4.3 on Nexus 4**
**Mapbox SDK version: `master`**

### Steps to trigger behavior

 1. Open SimpleMapViewActivity
 2. Zoom in a bit

```
W/mbgl    ( 8747): {pboxsdk.testapp}[OpenGL]: Caching program in: /data/data/com.mapbox.mapboxsdk.testapp/cache/com.mapbox.gl.shader.fill.1e5a3a34.pbf
W/mbgl    ( 8747): {pboxsdk.testapp}[OpenGL]: Caching program in: /data/data/com.mapbox.mapboxsdk.testapp/cache/com.mapbox.gl.shader.fill_outline.1e5a3a34.pbf
...
D/AndroidRuntime( 8747): Shutting down VM
W/dalvikvm( 8747): threadid=1: thread exiting with uncaught exception (group=0x4173a700)
E/AndroidRuntime( 8747): FATAL EXCEPTION: main
E/AndroidRuntime( 8747): java.lang.Error: glBindAttribLocation(id, location, name): Error GL_INVALID_VALUE at /Users/ivo/git/mapbox-gl-native/src/mbgl/gl/attribute.cpp:9
E/AndroidRuntime( 8747): 	at com.mapbox.mapboxsdk.maps.NativeMapView.nativeRender(Native Method)
E/AndroidRuntime( 8747): 	at com.mapbox.mapboxsdk.maps.NativeMapView.render(NativeMapView.java:176)
E/AndroidRuntime( 8747): 	at com.mapbox.mapboxsdk.maps.MapView.onDraw(MapView.java:420)
E/AndroidRuntime( 8747): 	at android.view.View.draw(View.java:13944)
E/AndroidRuntime( 8747): 	at android.widget.FrameLayout.draw(FrameLayout.java:467)
E/AndroidRuntime( 8747): 	at android.view.View.getDisplayList(View.java:12838)
E/AndroidRuntime( 8747): 	at android.view.View.getDisplayList(View.java:12880)
E/AndroidRuntime( 8747): 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3057)
E/AndroidRuntime( 8747): 	at android.view.View.getDisplayList(View.java:12775)
E/AndroidRuntime( 8747): 	at android.view.View.getDisplayList(View.java:12880)
E/AndroidRuntime( 8747): 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3057)
E/AndroidRuntime( 8747): 	at android.view.View.getDisplayList(View.java:12775)
E/AndroidRuntime( 8747): 	at android.view.View.getDisplayList(View.java:12880)
E/AndroidRuntime( 8747): 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3057)
E/AndroidRuntime( 8747): 	at android.view.View.getDisplayList(View.java:12775)
E/AndroidRuntime( 8747): 	at android.view.View.getDisplayList(View.java:12880)
E/AndroidRuntime( 8747): 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3057)
E/AndroidRuntime( 8747): 	at android.view.View.getDisplayList(View.java:12775)
E/AndroidRuntime( 8747): 	at android.view.View.getDisplayList(View.java:12880)
E/AndroidRuntime( 8747): 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3057)
E/AndroidRuntime( 8747): 	at android.view.View.getDisplayList(View.java:12775)
E/AndroidRuntime( 8747): 	at android.view.View.getDisplayList(View.java:12880)
E/AndroidRuntime( 8747): 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3057)
E/AndroidRuntime( 8747): 	at android.view.View.getDisplayList(View.java:12775)
E/AndroidRuntime( 8747): 	at android.view.View.getDisplayList(View.java:12880)
E/AndroidRuntime( 8747): 	at android.view.HardwareRenderer$GlRenderer.buildDisplayList(HardwareRenderer.java:1411)
E/AndroidRuntime( 8747): 	at android.view.HardwareRenderer$GlRenderer.draw(HardwareRenderer.java:1359)
E/AndroidRuntime( 8747): 	at android.view.ViewRootImpl.draw(ViewRootImpl.java:2367)
E/AndroidRuntime( 8747): 	at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2239)
E/AndroidRuntime( 8747): 	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1872)
E/AndroidRuntime( 8747): 	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1004)
E/AndroidRuntime( 8747): 	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5481)
E/AndroidRuntime( 8747): 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:749)
E/AndroidRuntime( 8747): 	at android.view.Choreographer.doCallbacks(Choreographer.java:562)
E/AndroidRuntime( 8747): 	at android.view.Choreographer.doFrame(Choreographer.java:532)
E/AndroidRuntime( 8747): 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:735)
E/AndroidRuntime( 8747): 	at android.os.Handler.handleCallback(Handler.java:730)
E/AndroidRuntime( 8747): 	at android.os.Handler.dispatchMessage(Handler.java:92)
E/AndroidRuntime( 8747): 	at android.os.Looper.loop(Looper.java:137)
E/AndroidRuntime( 8747): 	at android.app.ActivityThread.main(ActivityThread.java:5103)
E/AndroidRuntime( 8747): 	at java.lang.reflect.Method.invokeNative(Native Method)
E/AndroidRuntime( 8747): 	at java.lang.reflect.Method.invoke(Method.java:525)
E/AndroidRuntime( 8747): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:737)
E/AndroidRuntime( 8747): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
E/AndroidRuntime( 8747): 	at dalvik.system.NativeStart.main(Native Method)
```

### PR DESCRIPTION
**Pull request by lbud**
I _think_ this fixes #9331, although I'm not sure how to go about testing on an older Android device.

This PR
* flips the order of `uniformsState` and `attributeLocations` in the `Program` constructor, so that the program is initially linked _before_ calling `attributeLocations`,
* changes `Attributes::bindLocations` to query active attributes, temporarily store a set of those attributes, and then manually bind only the active attributes, and 
* re-links the program once more after setting the attribute bindings.

### CODE REVIEW

File: src/mbgl/gl/attribute.hpp [hunk 1]
```diff
@@ -242,7 +247,18 @@ class Attributes {
...
+        int32_t attributeCount = getActiveAttributeCount(id);
+        int32_t maxAttributeLength = getMaxAttributeNameLength(id);
+
+        for (int32_t i = 0; i < attributeCount; i++) {
+            std::string attributeName = getAttributeName(id, maxAttributeLength, i);
+            activeAttributes.emplace(attributeName);
+        }
+
+        return Locations{ bindAttributeLocation(
+            id, locationToBindAttribute(activeAttributes, As::name()), As::name())... };
```
Comment (jfirebaugh) [inline src/mbgl/gl/attribute.hpp]: This is close, but we want to number them in the order defined by the `As` argument pack, rather than lexicographical order by name. The latter might put an attribute that's sometimes disabled at index 0, which as we know, causes issues. Try this:

```C++
AttributeLocation location = 0;
return Locations {
    (activeAttributes.count(As::name()) ? bindAttributeLocation(id, location++, As::name()) : -1)...
};
```

File: src/mbgl/gl/attribute.hpp [hunk 2]
```diff
@@ -242,7 +247,18 @@ class Attributes {
     static constexpr std::size_t Index = TypeIndex<A, As...>::value;
 
     static Locations bindLocations(const ProgramID& id) {
-        return Locations { bindAttributeLocation(id, Index<As>, As::name())... };
+        std::set<std::string> activeAttributes;
```
Comment (jfirebaugh) [inline src/mbgl/gl/attribute.hpp]: You can minimize the declarations and code here in the header by writing:

```C++
std::set<std::string> activeAttributes = getActiveAttributes(id);
```

Then `getActiveAttributes` is the only thing that needs to be declared; everything else can go in the .cpp.

File: src/mbgl/gl/attribute.cpp [hunk 3]
```diff
@@ -2,14 +2,47 @@
 #include <mbgl/gl/context.hpp>
 #include <mbgl/gl/gl.hpp>
 
+#include <cstring>
+
 namespace mbgl {
 namespace gl {
 
 AttributeLocation bindAttributeLocation(ProgramID id, AttributeLocation location, const char* name) {
-    MBGL_CHECK_ERROR(glBindAttribLocation(id, location, name));
```
Comment (jfirebaugh) [inline src/mbgl/gl/attribute.cpp]: Add `assert(location <= 8)` for good measure.

**Comment by ivovandongen** [comment]
@lbud Currently crashes on android devices:

```
********** Crash dump: **********
Build fingerprint: 'google/sailfish/sailfish:7.1.2/NJH47B/4021576:user/release-keys'
pid: 2543, tid: 2543, name: pboxsdk.testapp  >>> com.mapbox.mapboxsdk.testapp <<<
signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x0
Stack frame #00 pc 0010aa6c  /vendor/lib/egl/libGLESv2_adreno.so (_ZN10EsxProgram15GetActiveAttribEP10EsxContextjjPiS2_P22EsxProgramResourceTypePc+107)
Stack frame #01 pc 000ab6a7  /vendor/lib/egl/libGLESv2_adreno.so (_ZN10EsxContext17GlGetActiveAttribEjjiPiS0_PjPc+134)
Stack frame #02 pc 000a005f  /vendor/lib/egl/libGLESv2_adreno.so (glGetActiveAttrib+62)
Stack frame #03 pc 00399123  /data/app/com.mapbox.mapboxsdk.testapp-1/lib/arm/libmapbox-gl.so: Routine operator() at /Users/ivo/git/mapbox-gl-native/src/mbgl/gl/attribute.cpp:39
Stack frame #04 pc 00398fa9  /data/app/com.mapbox.mapboxsdk.testapp-1/lib/arm/libmapbox-gl.so: Routine mbgl::gl::getAttributeName(unsigned int, int, int) at /Users/ivo/git/mapbox-gl-native/src/mbgl/gl/attribute.cpp:39
Stack frame #05 pc 001d716b  /data/app/com.mapbox.mapboxsdk.testapp-1/lib/arm/libmapbox-gl.so: Routine mbgl::gl::Attributes<mbgl::attributes::a_pos>::bindLocations(unsigned int const&) at /Users/ivo/git/mapbox-gl-native/platform/android/MapboxGLAndroidSDK/.externalNativeBuild/cmake/debug/armeabi-v7a/../../../../../../../src/mbgl/gl/attribute.hpp:256
Stack frame #06 pc 001d5e0b  /data/app/com.mapbox.mapboxsdk.testapp-1/lib/arm/libmapbox-gl.so: Routine Program at /Users/ivo/git/mapbox-gl-native/platform/android/MapboxGLAndroidSDK/.externalNativeBuild/cmake/debug/armeabi-v7a/../../../../../../../src/mbgl/gl/program.hpp:37
Stack frame #07 pc 001d5961  /data/app/com.mapbox.mapboxsdk.testapp-1/lib/arm/libmapbox-gl.so: Routine mbgl::gl::Program<mbgl::gl::Triangle, mbgl::gl::Attributes<mbgl::attributes::a_pos>, mbgl::gl::Uniforms<mbgl::uniforms::u_matrix, mbgl::uniforms::u_world, mbgl::uniforms::u_image, mbgl::uniforms::u_opacity> >::createProgram(mbgl::gl::Context&, mbgl::ProgramParameters const&, char const*, char const*, char const*) at /Users/ivo/git/mapbox-gl-native/platform/android/MapboxGLAndroidSDK/.externalNativeBuild/cmake/debug/armeabi-v7a/../../../../../../../src/mbgl/gl/program.hpp:81
Stack frame #08 pc 001d5529  /data/app/com.mapbox.mapboxsdk.testapp-1/lib/arm/libmapbox-gl.so: Routine Program at /Users/ivo/git/mapbox-gl-native/platform/android/MapboxGLAndroidSDK/.externalNativeBuild/cmake/debug/armeabi-v7a/../../../../../../../src/mbgl/programs/program.hpp:40
Stack frame #09 pc 001d5349  /data/app/com.mapbox.mapboxsdk.testapp-1/lib/arm/libmapbox-gl.so: Routine Program at /Users/ivo/git/mapbox-gl-native/platform/android/MapboxGLAndroidSDK/.externalNativeBuild/cmake/debug/armeabi-v7a/../../../../../../../src/mbgl/programs/extrusion_texture_program.hpp:23
Stack frame #10 pc 001d4d8f  /data/app/com.mapbox.mapboxsdk.testapp-1/lib/arm/libmapbox-gl.so: Routine Programs at /Users/ivo/git/mapbox-gl-native/platform/android/MapboxGLAndroidSDK/.externalNativeBuild/cmake/debug/armeabi-v7a/../../../../../../../src/mbgl/programs/programs.hpp:20
Stack frame #11 pc 001cb569  /data/app/com.mapbox.mapboxsdk.testapp-1/lib/arm/libmapbox-gl.so: Routine std::__ndk1::__unique_if<mbgl::Programs>::__unique_single std::__ndk1::make_unique<mbgl::Programs, mbgl::gl::Context&, mbgl::ProgramParameters>(mbgl::gl::Context&, mbgl::ProgramParameters&&) at /Users/ivo/Library/Android/sdk/ndk-bundle/sources/cxx-stl/llvm-libc++/include/memory:3149
Stack frame #12 pc 001bbefb  /data/app/com.mapbox.mapboxsdk.testapp-1/lib/arm/libmapbox-gl.so: Routine std::__ndk1::__unique_if<mbgl::Painter>::__unique_single std::__ndk1::make_unique<mbgl::Painter, mbgl::gl::Context&, mbgl::TransformState const&, float const&, std::experimental::fundamentals_v1::optional<std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> > > const&>(mbgl::gl::Context&, mbgl::TransformState const&, float const&, std::experimental::fundamentals_v1::optional<std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> > > const&) at /Users/ivo/Library/Android/sdk/ndk-bundle/sources/cxx-stl/llvm-libc++/include/memory:3149
Stack frame #13 pc 001bc7e1  /data/app/com.mapbox.mapboxsdk.testapp-1/lib/arm/libmapbox-gl.so: Routine mbgl::Map::render(mbgl::View&) at /Users/ivo/git/mapbox-gl-native/src/mbgl/map/map.cpp:208
Stack frame #14 pc 000b8ab5  /data/app/com.mapbox.mapboxsdk.testapp-1/lib/arm/libmapbox-gl.so: Routine mbgl::android::NativeMapView::render(_JNIEnv&) at /Users/ivo/git/mapbox-gl-native/platform/android/src/native_map_view.cpp:300
Stack frame #15 pc 000ce603  /data/app/com.mapbox.mapboxsdk.testapp-1/lib/arm/libmapbox-gl.so: Routine operator() at /Users/ivo/git/mapbox-gl-native/platform/android/MapboxGLAndroidSDK/.externalNativeBuild/cmake/debug/armeabi-v7a/../../../../../../../mason_packages/headers/jni.hpp/3.0.0/include/jni/native_method.hpp:245
Stack frame #16 pc 000ce599  /data/app/com.mapbox.mapboxsdk.testapp-1/lib/arm/libmapbox-gl.so: Routine operator() at /Users/ivo/git/mapbox-gl-native/platform/android/MapboxGLAndroidSDK/.externalNativeBuild/cmake/debug/armeabi-v7a/../../../../../../../mason_packages/headers/jni.hpp/3.0.0/include/jni/native_method.hpp:112
Stack frame #17 pc 000ce561  /data/app/com.mapbox.mapboxsdk.testapp-1/lib/arm/libmapbox-gl.so: Routine __invoke at /Users/ivo/git/mapbox-gl-native/platform/android/MapboxGLAndroidSDK/.externalNativeBuild/cmake/debug/armeabi-v7a/../../../../../../../mason_packages/headers/jni.hpp/3.0.0/include/jni/native_method.hpp:110
Stack frame #18 pc 000ce68d  /data/app/com.mapbox.mapboxsdk.testapp-1/lib/arm/libmapbox-gl.so: Routine operator()<jni::jobject *> at /Users/ivo/git/mapbox-gl-native/platform/android/MapboxGLAndroidSDK/.externalNativeBuild/cmake/debug/armeabi-v7a/../../../../../../../mason_packages/headers/jni.hpp/3.0.0/include/jni/native_method.hpp:59
Stack frame #19 pc 000ce64d  /data/app/com.mapbox.mapboxsdk.testapp-1/lib/arm/libmapbox-gl.so: Routine __invoke<jni::jobject *> at /Users/ivo/git/mapbox-gl-native/platform/android/MapboxGLAndroidSDK/.externalNativeBuild/cmake/debug/armeabi-v7a/../../../../../../../mason_packages/headers/jni.hpp/3.0.0/include/jni/native_method.hpp:55
Stack frame #20 pc 00558a3f  /data/app/com.mapbox.mapboxsdk.testapp-1/oat/arm/base.odex (offset 0x52e000)
```

**Comment by lbud** [comment]
One small thing I wanted to flag is that is that I had to make `UniqueProgram program` in program.hpp public so that `LayoutAttributes::bindings` could access the ProgramID, needed to query `GL_ACTIVE_ATTRIBUTES` and only enable as many attributes as are active rather than the full set of possible attributes.

File: src/mbgl/gl/attribute.hpp [hunk 4]
```diff
@@ -255,8 +266,9 @@ class Attributes {
     }
 
     template <class DrawMode>
-    static Bindings bindings(const VertexBuffer<Vertex, DrawMode>& buffer) {
```
Comment (jfirebaugh) [inline src/mbgl/gl/attribute.hpp]: Does anything actually fail if you don't make this change? In theory, this function is called only for active attributes. If it's called for an attribute that isn't actually present, then there's a bug somewhere I think.

Comment (lbud) [inline src/mbgl/gl/attribute.hpp]: 🤔 @jfirebaugh good question — I added it after [this build](https://circleci.com/gh/mapbox/mapbox-gl-native/6870?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link), which was terminated during the render tests with
```
terminate called after throwing an instance of 'mbgl::gl::Error'
  what():  glEnableVertexAttribArray(location): Error GL_INVALID_VALUE at ../../../src/mbgl/gl/attribute.cpp:62
```
([glEnableVertexAttribArray documentation](https://www.khronos.org/registry/OpenGL-Refpages/es2.0/xhtml/glEnableVertexAttribArray.xml))
But I was able to reproduce that error locally at the time using a fill-color property function, which now works locally if I remove it… I'll remove it and see if any of the CI builds still have issues.

Comment (lbud) [inline src/mbgl/gl/attribute.hpp]: Actually, I spoke too soon — locally I get the same error:
```
libc++abi.dylib: terminating with uncaught exception of type mbgl::gl::Error: glEnableVertexAttribArray(location): Error GL_INVALID_VALUE at /Users/lbud/src/mapbox-gl-native/src/mbgl/gl/attribute.cpp:70
```
