### PR TITLE
[core][macOS] Compute camera center and zoom for geometry with fixed heading

### LINKED ISSUE #9809: Method for getting map camera settings from polyline, bearing, bounds and insets
This method should accept a polyline, a bearing, a bounding rectangle in pixels and an object defining padding in pixels on all sides. It should then return a center coordinate and a zoom level appropriate for showing the given polyline in the given bounds at the given bearing.

This is basically what's already happening in fitBounds. The only difference is that this returns the calculated values so that the developer can handle the fitting of the bounds using any transition they want.

```
getCamera(polyline: Array<LngLat>, bounds:Array<Point>, insets: Array<Float>, bearing: Float) {
  return {zoomLevel: Float, centerCoord: LngLat, bearing: Float}
}
```

cc @mapbox/gl @pveugen

### PR DESCRIPTION
**Pull request by asheemmamoowala**
Closes #9809 

Implement a `Map:: cameraForLatLngs` variant that allows specifying a heading and returns `CameraOptions` with `zoom`, `center`, and `angle`.

### CODE REVIEW

File: platform/macos/src/MGLMapView.h [hunk 1]
```diff
@@ -10,6 +10,7 @@ NS_ASSUME_NONNULL_BEGIN
 @class MGLAnnotationImage;
 @class MGLMapCamera;
 @class MGLStyle;
+@class MGLShape;
```
Comment (1ec5) [inline platform/macos/src/MGLMapView.h]: Can you make these changes to the iOS implementation of MGLMapView also? Thanks!

File: platform/macos/src/MGLMapView.h [hunk 2]
```diff
@@ -403,6 +404,19 @@ MGL_EXPORT IB_DESIGNABLE
...
+ and optionally some additional padding on each side.
+
+ @param shape The shape that the viewport will show in its entirety.
+ @param heading The heading of the viewport, measured in degrees clockwise from true north.
+ @param insets The minimum padding (in screen points) that will be visible
+    around the given coordinate bounds.
+ @param animated Specify `YES` to animate the change by smoothly scrolling and
+    zooming or `NO` to immediately display the given bounds.
+ */
+- (void)setVisibleShape:(MGLShape *)shape heading:(double)heading edgePadding:(NSEdgeInsets)insets animated:(BOOL)animated;
```
Comment (1ec5) [inline platform/macos/src/MGLMapView.h]: This method is reminiscent of `-showAnnotation:`, which also adds the passed-in annotation (which may be a shape) if it isn't already on the map. It might be nice to generalize that method with these additional parameters, but I'm not sure it's necessary to have one that only changes the camera, since the developer can readily compose `-cameraThatFitsShape:heading:edgePadding:` with `-setCamera:animated:`. The reason `-setVisibleCoordinateBounds:edgePadding:animated:` exists is that there's already a `visibleCoordinateBounds` property. But there isn't inherently a "visible shape" the way there's a visible coordinate bounds.

File: src/mbgl/map/map.cpp [hunk 3]
```diff
@@ -421,11 +421,24 @@ CameraOptions Map::cameraForLatLngs(const std::vector<LatLng>& latLngs, const Ed
...
+CameraOptions Map::cameraForLatLngs(const std::vector<LatLng>& latLngs, const EdgeInsets& padding) const {
+    return mbgl::cameraForLatLngs(latLngs, impl->transform, padding);
+}
+
+CameraOptions Map::cameraForLatLngs(const std::vector<LatLng>& latLngs, double heading, const EdgeInsets& padding) const {
+    double angle = -heading * util::DEG2RAD;
+    Transform transform(impl->transform.getState());
+    transform.setAngle(angle);
+    CameraOptions options = mbgl::cameraForLatLngs(latLngs, transform, padding);
+    options.angle = angle;
```
Comment (1ec5) [inline src/mbgl/map/map.cpp]: The return value inherits the current pitch, but the developer may want to animate to an arbitrary pitch for the same reason that they'd want to animate to an arbitrary angle.

File: src/mbgl/map/map.cpp [hunk 4]
```diff
@@ -421,11 +421,24 @@ CameraOptions Map::cameraForLatLngs(const std::vector<LatLng>& latLngs, const Ed
...
     options.zoom = zoom;
     return options;
 }
 
+CameraOptions Map::cameraForLatLngs(const std::vector<LatLng>& latLngs, const EdgeInsets& padding) const {
+    return mbgl::cameraForLatLngs(latLngs, impl->transform, padding);
+}
+
+CameraOptions Map::cameraForLatLngs(const std::vector<LatLng>& latLngs, double heading, const EdgeInsets& padding) const {
+    double angle = -heading * util::DEG2RAD;
```
Comment (1ec5) [inline src/mbgl/map/map.cpp]: The convention throughout mbgl seems to be to use the term "angle" for what might be called "heading" or "bearing" elsewhere.

File: platform/macos/src/MGLMapView.h [hunk 5]
```diff
@@ -457,6 +471,21 @@ MGL_EXPORT IB_DESIGNABLE
...
+ @param shape The shape to fit to the receiver’s viewport.
+ @param heading The heading of the viewport, measured in degrees clockwise from true north.
+ @param insets The minimum padding (in screen points) that would be visible
+    around the returned camera object if it were set as the receiver’s camera.
+ @return A camera object centered on the same location as the coordinate bounds
+    with zoom level as high (close to the ground) as possible while still
+    including the entire coordinate bounds. The camera object uses the current
+    direction and pitch.
+ */
+- (MGLMapCamera *)cameraThatFitsShape:(MGLShape *)shape heading:(double)heading edgePadding:(NSEdgeInsets)insets;
```
Comment (1ec5) [inline platform/macos/src/MGLMapView.h]: MGLMapView uses the term "direction" instead of "heading", because "heading" is part of a 3D camera system that's encapsulated in MGLMapCamera. If we allow the heading to be configured but not the pitch, we should use "direction" here for consistency with `-setDirection:`. On the other hand, if we make the pitch configurable, as suggested below, then this method might take a camera (as `matchingCamera:`) instead of separate `heading` and `pitch` parameters.

File: platform/macos/src/MGLMapView.h [hunk 6]
```diff
@@ -457,6 +471,21 @@ MGL_EXPORT IB_DESIGNABLE
...
+ optionally with some additional padding on each side.
+
+ @param shape The shape to fit to the receiver’s viewport.
+ @param heading The heading of the viewport, measured in degrees clockwise from true north.
+ @param insets The minimum padding (in screen points) that would be visible
+    around the returned camera object if it were set as the receiver’s camera.
+ @return A camera object centered on the same location as the coordinate bounds
+    with zoom level as high (close to the ground) as possible while still
+    including the entire coordinate bounds. The camera object uses the current
+    direction and pitch.
```
Comment (1ec5) [inline platform/macos/src/MGLMapView.h]: This method doesn't use the current direction, and it includes the entire shape, not an entire coordinate bounds.

File: platform/macos/src/MGLMapView.mm [hunk 7]
```diff
@@ -126,6 +127,46 @@
...
+        MGLMultiPolyline *shapeCollection = (MGLMultiPolyline *)shape;
+        for(MGLPolyline *s in shapeCollection.polylines) {
+            auto shapeLatLngs = coordinatesForShape(s);
+            latLngs.insert(latLngs.end(), shapeLatLngs.begin(), shapeLatLngs.end());
+        }
+    } else if ([shape isKindOfClass:[MGLShapeCollection class]]) {
+        MGLShapeCollection *shapeCollection = (MGLShapeCollection *)shape;
+        for(MGLShape *s in shapeCollection.shapes) {
+            auto shapeLatLngs = coordinatesForShape(s);
+            latLngs.insert(latLngs.end(), shapeLatLngs.begin(), shapeLatLngs.end());
```
Comment (1ec5) [inline platform/macos/src/MGLMapView.mm]: Consider having the mbgl::Map method take a Geometry; each MGLShape subclass already has an internal method for converting to a Geometry.

File: platform/macos/src/MGLMapView.h (hunk 2 above)
Comment (asheemmamoowala) [reply platform/macos/src/MGLMapView.h]: @1ec5 I added this method to help with testing in the macOS demo app. and didn't expect it to be added to the mobile SDKs. Maybe there is a case to add this functionality to `-showAnnotation` but I'd prefer to scope this PR down to just the `-cameraTheFitsShape` changes.
//cc @d-prukop

File: src/mbgl/map/map.cpp (hunk 3 above)
Comment (asheemmamoowala) [reply src/mbgl/map/map.cpp]: Opened this as a separate issue #10115. It depends on us first getting a fix for #2259.

File: platform/macos/src/MGLMapView.h (hunk 5 above)
Comment (asheemmamoowala) [reply platform/macos/src/MGLMapView.h]: Given #2259, I didn't want to add `pitch` just yet. 
:+1: on `direction`

File: platform/macos/src/MGLMapView.h (hunk 2 above)
Comment (1ec5) [reply platform/macos/src/MGLMapView.h]: We try to keep the iOS and macOS SDKs as close as possible. In fact, there’s an entire [project](https://github.com/mapbox/mapbox-gl-native/projects/10) tracking that work.

Ideally we would find a way to make `-cameraThatFitsShape:heading:edgePadding:` compatible with one of the `-setCamera:…` methods, perhaps `-setCamera:withDuration:animationTimingFunction:edgePadding:completionHandler:`, such that we could add the same method to both SDKs publicly.

File: platform/macos/src/MGLMapView.h [hunk 8]
```diff
@@ -403,6 +404,19 @@ MGL_EXPORT IB_DESIGNABLE
...
+ and optionally some additional padding on each side.
+
+ @param shape The shape that the viewport will show in its entirety.
+ @param direction The direction of the viewport, measured in degrees clockwise from true north.
+ @param insets The minimum padding (in screen points) that will be visible
+    around the given coordinate bounds.
+ @param animated Specify `YES` to animate the change by smoothly scrolling and
+    zooming or `NO` to immediately display the given bounds.
+ */
+- (void)setVisibleShape:(MGLShape *)shape direction:(double)direction edgePadding:(NSEdgeInsets)insets animated:(BOOL)animated;
```
Comment (1ec5) [inline platform/macos/src/MGLMapView.h]: I continue to think this would be a poor API to expose publicly, per https://github.com/mapbox/mapbox-gl-native/pull/10107#discussion_r142760198. For one thing, it isn’t possible to customize the duration or timing function or provide a completion handler, all options that come with `-setCamera:withDuration:animationTimingFunction:edgePadding:completionHandler:` on iOS.

If it’s really necessary to achieve a padding-less camera fitting a shape, can we remove this method, replace it with `-setCamera:withDuration:animationTimingFunction:edgePadding:completionHandler:` from iOS, and use the following code to achieve the same effect for the time being?

```objc
MGLMapCamera *camera = [mapView cameraThatFitsShape:shape direction:direction edgePadding:edgePadding];
NSEdgeInsets edgePadding = contentInsets;
edgePadding.left *= -1; edgePadding.right *= -1; edgePadding.top *= -1; edgePadding.bottom *= -1;
[mapView setCamera:camera withDuration:5 animationTimingFunction:nil edgePadding:edgePadding completionHandler:nil];
```

File: platform/ios/CHANGELOG.md [hunk 9]
```diff
@@ -29,6 +29,7 @@ Mapbox welcomes participation and contributions from everyone. Please read [CONT
 * Increased the default maximum zoom level from 20 to 22. ([#9835](https://github.com/mapbox/mapbox-gl-native/pull/9835))
 * Added an `overlays` property to `MGLMapView`. ([#8617](https://github.com/mapbox/mapbox-gl-native/pull/8617))
 * Selecting an annotation no longer sets the user tracking mode to `MGLUserTrackingModeNone`. ([#10094](https://github.com/mapbox/mapbox-gl-native/pull/10094))
+* Added `-[MGLMapView cameraThatFitsShape:direction:padding:]` to get a camera with zoom level and center coordinate computed to fit a shape. ([#10107](https://github.com/mapbox/mapbox-gl-native/pull/10107))
```
Comment (1ec5) [inline platform/ios/CHANGELOG.md]: This should say `edgePadding:`, not `padding:`.

**Comment by tobrun** [comment]
This is working great @asheemmamoowala :+1: 

ezgif com-video-to-gif 41

I might revisit the public api with overloaded methods (so bearing and padding are optional) 
Let's ship this and iterate on it further.
