### PR TITLE
[android] - add style loading callback 

### LINKED ISSUE #8262: setStyleUrl with callback
Style loading happens asynchronous and users are required to wait until the style has finished loading before altering any of the style properties. Capturing from https://github.com/mapbox/mapbox-gl-native/issues/8144 that this isn't always obvious. For example they can write code as:

```java
    mapView = (MapView) findViewById(R.id.mapView);
    mapView.onCreate(savedInstanceState);
    mapView.setStyleUrl(Style.SATELLITE);
    mapView.getMapAsync(new OnMapReadyCallback() {
      @Override
      public void onMapReady(@NonNull final MapboxMap map) {
        mapboxMap = map;
        mapboxMap.setStyleUrl(Style.MAPBOX_STREETS);
        try {
          mapboxMap.addSource(new GeoJsonSource("bus_stop",
            new URL("https://raw.githubusercontent.com/cheeaun/busrouter-sg/master/data/2/bus-stops.geojson")));
        } catch (MalformedURLException malformedUrlException) {
          Timber.e("That's not an url... ", malformedUrlException);
        }

        layer = new CircleLayer("stops_layer", "bus_stop");
        layer.setProperties(
          circleColor(Color.parseColor("#FF9800")),
          circleRadius(1.0f)
        );

        mapboxMap.addLayer(layer);
      }
 }
``` 
Executing this code would result in adding the GeoJsonSource and the CircleLayer to `Style.SATELLITE` instead of `Style.MAPBOX_STREETS`. Having `setStyleUrl(String, Callback)`would make it more obvious from API perspective + will remove the burden of writing boiler plate map change event code as:

```java
  mapView = (MapView) findViewById(R.id.mapView);
    mapView.onCreate(savedInstanceState);
    mapView.getMapAsync(new OnMapReadyCallback() {
      @Override
      public void onMapReady(@NonNull final MapboxMap map) {
        mapboxMap = map;
        mapView.addOnMapChangedListener(new MapView.OnMapChangedListener() {
          @Override
          public void onMapChanged(@MapView.MapChange int change) {
            if (change == MapView.DID_FINISH_LOADING_STYLE) {
              try {
                mapboxMap.addSource(new GeoJsonSource("bus_stop",
                  new URL("https://raw.githubusercontent.com/cheeaun/busrouter-sg/master/data/2/bus-stops.geojson")));
              } catch (MalformedURLException malformedUrlException) {
                Timber.e("That's not an url... ", malformedUrlException);
              }

              layer = new CircleLayer("stops_layer", "bus_stop");
              layer.setProperties(
                circleColor(Color.parseColor("#FF9800")),
                circleRadius(1.0f)
              );

              mapboxMap.addLayer(layer);
            }
          }
        });

        mapboxMap.setStyleUrl(Style.SATELLITE);
      }
    });

```
 
cc @mapbox/android

### PR DESCRIPTION
**Pull request by tobrun**
Closes #8262. 

This PR adds a style loading callback that is invoked when the style has finished loading.

### CODE REVIEW

File: platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapboxMap.java [hunk 1]
```diff
@@ -909,6 +909,52 @@ private void setApiBaseUrl(@NonNull MapboxMapOptions options) {
...
+        @Override
+        public void onMapChanged(@MapView.MapChange int change) {
+          if (change == MapView.DID_FINISH_LOADING_STYLE) {
+            callback.onStyleLoaded(url);
+            nativeMapView.removeOnMapChangedListener(this);
+          }
+        }
+      });
+    }
     nativeMapView.setStyleUrl(url);
```
Comment (incanus) [inline platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapboxMap.java]: Why not call this class's `setStyleUrl()` in order to gate the native call through fewer (i.e. a single) places?

File: platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapboxMap.java [hunk 2]
```diff
@@ -909,6 +909,52 @@ private void setApiBaseUrl(@NonNull MapboxMapOptions options) {
...
+   * style created in <a href="https://www.mapbox.com/studio">Mapbox Studio</a>.</li>
+   * <li>{@code http://...} or {@code https://...}:
+   * retrieves the style over the Internet from any web server.</li>
+   * <li>{@code asset://...}:
+   * reads the style from the APK {@code assets/} directory.
+   * This is used to load a style bundled with your app.</li>
+   * <li>{@code null}: loads the default {@link Style#MAPBOX_STREETS} style.</li>
+   * </ul>
+   * <p>
+   * This method is asynchronous and will return immediately before the style finishes loading.
```
Comment (incanus) [inline platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapboxMap.java]: This (and the similar comment(s) above) could be worded better—makes it sound like _immediately before_ instead of what actually happens, which is _immediately_ and _before the style finishes loading_.

File: platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapboxMap.java [hunk 3]
```diff
@@ -909,6 +909,52 @@ private void setApiBaseUrl(@NonNull MapboxMapOptions options) {
...
+   * If you wish to wait for the map to finish loading listen for the {@link MapView#DID_FINISH_LOADING_MAP} event.
```
Comment (incanus) [inline platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapboxMap.java]: Add a `,` after `loading`.

File: platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapboxMap.java [hunk 4]
```diff
@@ -909,6 +909,52 @@ private void setApiBaseUrl(@NonNull MapboxMapOptions options) {
...
+   *
+   * @param url      The URL of the map style
+   * @param callback Callback that is invoked when the style has loaded.
+   * @see Style
+   */
+  @UiThread
+  public void setStyleUrl(@NonNull final String url, @Nullable final OnStyleLoadedListener callback) {
+    if (callback != null) {
+      nativeMapView.addOnMapChangedListener(new MapView.OnMapChangedListener() {
+        @Override
```
Comment (incanus) [inline platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapboxMap.java]: This could be my Android newbness speaking, but do you need to call the superclass implementation if you are overriding here?

Comment (ivovandongen) [inline platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapboxMap.java]: @incanus It's an interface, not a class

File: platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapboxMap.java (hunk 1 above)
Comment (ivovandongen) [inline platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapboxMap.java]: @incanus That would be a circular reference and would cause a stack overflow

**Comment by incanus** [comment]
Just my minor comment docs changes above, but this is good to ship.
