### PR TITLE
[core] style loaded signal

### LINKED ISSUE #4527: [core] Several methods assume style object is created
We have several methods that are currently crashing because `map.setStyleURL` is async. For instance `addLayer`, `addClass`, `isLoaded` and several others. We should have a signal (`MapChangeDidFinishLoadingStyle`?) emitted right after `MapContext::loadStyleJSON`.

On Android for instance `MapChangeDidFinishLoadingMap` is used to indicate that the style was loaded as a whole but we need something to indicate that the style JSON arrived (and the style object was created). Otherwise we might ended up rendering a partial state and later add a custom layer or class.

This new signal would be better implemented after we get rid of the context thread (#2909) because we can safely call `view.notifyMapChange` from `MapContext::loadStyleJSON` after that.

Finally, we should maybe throw an runtime exception when calling the methods that depend on a style when the style json is not yet loaded.

/cc @brunoabinader @jfirebaugh

### PR DESCRIPTION
**Pull request by ivovandongen**
Fixes #4527

Needed to properly time callbacks in #6032

### CODE REVIEW

File: src/mbgl/map/map.cpp [hunk 1]
```diff
@@ -352,6 +352,8 @@ void Map::Impl::loadStyleJSON(const std::string& json) {
 
     // force style cascade, causing all pending transitions to complete.
     style->cascade(Clock::now(), mode);
+    
+    view.notifyMapChange(MapChangeDidFinishLoadingStyle);
```
Comment (tmpsantos) [inline src/mbgl/map/map.cpp]: We probably need a signal for style loading failures. In case of parsing error, the `MapChangeDidFinishLoadingStyle` will be emitted here.

Comment (ivovandongen) [inline src/mbgl/map/map.cpp]: In that case, does it make more sense to add the signals to the Style itself? 

In https://github.com/mapbox/mapbox-gl-native/blob/master/src/mbgl/style/style.cpp#L95 we can best check for parse errors.

Comment (tmpsantos) [inline src/mbgl/map/map.cpp]: Yes, I think so.

Comment (ivovandongen) [inline src/mbgl/map/map.cpp]: @tmpsantos to keep things clean, I've added a method to the observer on Style and kept the signal emitting in Map.

File: test/map/map.cpp [hunk 2]
```diff
@@ -202,6 +202,31 @@ TEST(Map, StyleEarlyMutation) {
...
+        if (change == mbgl::MapChangeDidFinishLoadingStyle) {
+            emitted = true;
+        }
+    });
+    map.setStyleJSON(util::read_file("test/fixtures/api/empty.json"));
+    EXPECT_TRUE(emitted);
+    
+    // But not when the style couldn't be parsed
+    emitted = false;
+    test.view.setMapChangeCallback([&](MapChange change) {
```
Comment (tmpsantos) [inline test/map/map.cpp]: No need to redefine this callback.

Comment (ivovandongen) [inline test/map/map.cpp]: Good point...

**Comment by ivovandongen** [comment]
@tmpsantos I've committed the changes you requested. Let me know if there's anything else or that it can be merged.

**Comment by tmpsantos** [comment]
:shipit:
