### PR TITLE
LatLng#distanceTo with TurfMeasurement#distance

### LINKED ISSUE #14216: LatLng distanceTo returns null for very close points
LatLng.distanceTo() returns NaN for very close points on Nexus One API 22 emulator (does not repro in two other emulators I tried)

Sample code:
`LatLng(40.00599, -105.29261).distanceTo(LatLng(40.005990000000025, -105.29260999999997)`

### Steps to reproduce

 1. Call LatLng.distanceTo for two very near points (see above) on a Nexus One API 22 emulator (Android Studio, OSX)

### Expected behavior
LatLng.distanceTo() returns 0.0 for any very close points

### Actual behavior
LatLng.distnaceTo() returns NaN for some specific very close points in specific environments

It would seem that a test for isNaN(tt) is a safer way to implement this.

### Configuration
OSX Android Studio emulator

**Android versions:** 
Android 22

**Device models:** 
Nexus One (emulated)

**Mapbox SDK versions:** 
7.2

### PR DESCRIPTION
**Pull request by tobrun**
Closes #14216, now that we use Turf as part of the Mapbox Maps SDK for Android in [#11447](https://github.com/mapbox/mapbox-gl-native/pull/11447/files#diff-4be1069e6893cf052bcebaa75621dd96R13). I feel we should use Turf whenever possible (vs writing the goespatial math ourselves). Validated that this PR produces non-NaN values for the use-case described in #14216 and added a test for it.

### CODE REVIEW

File: platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/geometry/LatLng.java [hunk 1]
```diff
@@ -318,24 +322,9 @@ public void writeToParcel(@NonNull Parcel out, int flags) {
...
-    final double cosa1 = Math.cos(a1);
-    final double cosb1 = Math.cos(b1);
-
-    final double t1 = cosa1 * Math.cos(a2) * cosb1 * Math.cos(b2);
-    final double t2 = cosa1 * Math.sin(a2) * cosb1 * Math.sin(b2);
-    final double t3 = Math.sin(a1) * Math.sin(b1);
-    final double tt = Math.acos(t1 + t2 + t3);
-
-    return GeometryConstants.RADIUS_EARTH_METERS * tt;
+    return TurfMeasurement.distance(
```
Comment (LukasPaczos) [inline platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/geometry/LatLng.java]: This returns a value in kilometers, while we are expecting a value in meters.

File: platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/geometry/LatLng.java [hunk 2]
```diff
@@ -318,24 +323,9 @@ public void writeToParcel(@NonNull Parcel out, int flags) {
...
+      Point.fromLngLat(longitude, latitude),
+      Point.fromLngLat(other.getLongitude(), other.getLatitude())
+    ) * 1000; // convert km to meter
```
Comment (LukasPaczos) [inline platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/geometry/LatLng.java]: `TurfMeasurment` exposes `TurfMeasurment#distance(Point, Point, String)` which may be a cleaner way to achieve the same thing :)

**Comment by Cloud9Clone** [comment]
Hello! Is the issue with the 0.0 distance for close objects solved?
