### PR TITLE
[core] Failed sprite requests do not block tiles rendering

### LINKED ISSUE #14582: Tile doesn't render after zoom
Not sure but think this is a follow up from https://github.com/mapbox/mapbox-gl-native/issues/14523. When testing v7.5.0-alpha.1 of the Android SDK containing https://github.com/mapbox/mapbox-gl-native/pull/14527.

### Before zoom:

> Target: LatLng [latitude=40.723102, longitude=-73.9979, altitude=0.0], Zoom:11.797530889511108, Bearing:14.754321455955505, Tilt:11.962963104248047

image

### After zoom:

> Target: LatLng [latitude=40.723102, longitude=-73.9979, altitude=0.0], Zoom:12.32962965965271, Bearing:24.598148703575134, Tilt:19.94444465637207

image

The tiles in the top aren't loading (the one in the bottom did and is showing more detail). 
fwiw zooming a bit more doesn't load the other tiles. 

cc @pozdnyakov @kkaefer @julianrex

### PR DESCRIPTION
**Pull request by pozdnyakov**
This patch unblocks tiles rendering if a sprite request has failed, it also enables `onStyleImageMissing` API call for the missing image.

Fixes #14582

### CODE REVIEW

**Comment by tmpsantos** [comment]
Worth mentioning that this aligns the behavior with GL JS and we could have a render test for this.

/cc @asheemmamoowala

File: src/mbgl/style/style_impl.cpp [hunk 1]
```diff
@@ -309,6 +309,9 @@ void Style::Impl::onSpriteError(std::exception_ptr error) {
     lastError = error;
     Log::Error(Event::Style, "Failed to load sprite: %s", util::toString(error).c_str());
     observer->onResourceError(error);
+    // Unblock rendering tiles (even though sprite request has failed).
+    spriteLoaded = true;
+    observer->onUpdate();
```
Comment (kkaefer) [inline src/mbgl/style/style_impl.cpp]: This will only unblock rendering in continuous mode. Still image mode will still fail because the `onResourceError` terminates the whole map render request.
