### PR TITLE
[ios, macos] Runtime styling cleanup and fixes.

### LINKED ISSUE #5943: Semantic issue — Moving a temporary object prevents copy elision
Following #5727 and #5935, I’m now seeing this compiler warning in the macOS workspace:

```
Semantic Issue Group
/path/to/mapbox-gl-native/platform/darwin/src/MGLStyle.mm:145:37: Moving a temporary object prevents copy elision
```

/cc @frederoni

### LINKED ISSUE #5956: Dead code
Per https://github.com/mapbox/mapbox-gl-native/pull/5727#discussion_r72363585, [this code path in `NSColor (MGLAdditions)`](https://github.com/mapbox/mapbox-gl-native/blob/a6ec5d1a5a25887669d31e1824e7a243de031a94/platform/macos/src/NSColor+MGLAdditions.mm#L7-10-L10) is dead code.

/cc @frederoni

### LINKED ISSUE #5958: MGLStyleAttribute methods don’t conform to Cocoa naming conventions
Per https://github.com/mapbox/mapbox-gl-native/pull/5727#discussion_r74301657, the [methods in MGLStyleAttribute](https://github.com/mapbox/mapbox-gl-native/blob/a6ec5d1a5a25887669d31e1824e7a243de031a94/platform/darwin/src/MGLStyleAttribute.hpp) shouldn’t end with “with”.

/cc @frederoni

### LINKED ISSUE #5961: MGLStyleFilter missing from macos.xcodeproj
Per https://github.com/mapbox/mapbox-gl-native/pull/5727#issuecomment-238963837, the macOS SDK is missing MGLStyleFilter. It looks like MGLStyleFilter is currently private, but the iOS and macOS projects should be as consistent as possible.

/cc @frederoni

### LINKED ISSUE #5969: MGLStyleAttributeFunction.functionType should be MGLStyleAttributeFunctionType
[`MGLStyleAttributeFunction.functionType`](https://github.com/mapbox/mapbox-gl-native/blob/0ae941d2a8a89276e1f0c2cf3870104d0e94fbc4/platform/darwin/src/MGLStyleAttributeFunction.h#L22) should be of type `MGLStyleAttributeFunctionType`, not NSNumber. The style specification [allows](https://www.mapbox.com/mapbox-gl-style-spec/#types-function) the `type` property to be omitted, but the value is actually `exponential` (`MGLStyleAttributeFunctionTypeExponential`) or `interval` (`MGLStyleAttributeFunctionTypeInterval`) by default, depending on the property, and it’s meaningless for a function to have no type. So there’s no need for a nullable object here.

/cc @frederoni

### LINKED ISSUE #5974: Move style class API to MGLStyle
Methods like `-[MGLMapView addClass:]` should be moved to MGLStyle alongside the layer and source APIs. We’ll need to deprecate the existing methods.

/cc @frederoni

### LINKED ISSUE #5975: Add source getter to MGLStyle
MGLStyle should have a `-sourceWithIdentifier:` method for random access to the style’s sources. It would call `mbgl::Map::getSource()` and convert the returned `mbgl::style::Source` into an MGLSource object. MGLSource may need `-hash` and `-isEqual:` implementations.

/cc @frederoni

### LINKED ISSUE #5989: NSColor+MGLAdditions.hpp is public
Building the macosapp target triggers the following compiler warning:

```
Lexical or Preprocessor Issue Group
/path/to/mapbox-gl-native/platform/macos/<module-includes>:1:1: Umbrella header for module 'Mapbox' does not include header '/path/to/mapbox-gl-native/platform/macos/src/NSColor+MGLAdditions.hpp'
```

This Objective-C++ header should not be public.

/cc @frederoni

### LINKED ISSUE #5992: Initializing UIApplication with an expression of incompatible type UIApplicationDelegate
MGLStyleLayerTests [erroneously assigns](https://github.com/mapbox/mapbox-gl-native/blob/112789a76111d4dd38e50c73ae1e81e5c53dd59c/platform/darwin/test/MGLStyleLayerTests.m#L8) the application delegate to a local variable of type UIApplication, resulting in this compiler warning and a potential uncaught exception at runtime:

```
/path/to/mapbox-gl-native/platform/darwin/test/MGLStyleLayerTests.m
/path/to/mapbox-gl-native/platform/darwin/test/MGLStyleLayerTests.m:8:20: Initializing 'UIApplication *__strong' with an expression of incompatible type 'id<UIApplicationDelegate> _Nullable'
```

/cc @frederoni

### PR DESCRIPTION
**Pull request by frederoni**
This PR will be used to clean up runtime styling. Issues that involves a bit more work and complexity will be handled in separate PRs.

Checklist:
 - [x] Remove unused function types (fixes #5969)
 - [x] Add source getter to MGLStyle (fixes #5975)
 - [x] Cocoa naming conventions (fixes #5958)
 - [x] Move style class API to MGLStyle (fixes #5974)
 - [x] Remove dead code (fixes #5956)
 - [x] MGLStyleFilter missing from macos.xcodeproj (fixes #5961) (omitted from iOS as well until it's implemented properly)
 - [x] NSColor+MGLAdditions.hpp is public (fixes #5989)
 - [x] Fix incorrect assignment in style layer tests (fixes #5992)
 - [x] Fix compiler warning about std::move (fixes #5943)

### CODE REVIEW

File: platform/ios/src/MGLMapView_Private.h [hunk 1]
```diff
@@ -15,6 +15,9 @@ extern const CGSize MGLAnnotationAccessibilityElementMinimumSize;
 
 - (mbgl::Map *)mbglMap;
 
+/** Converts NSTimeInterval to mbgl::Duration */
+mbgl::Duration MGLDurationInSeconds(NSTimeInterval duration);
+
```
Comment (frederoni) [inline platform/ios/src/MGLMapView_Private.h]: Do we have a better place to put these conversion methods?

File: platform/darwin/src/MGLStyle.mm [hunk 2]
```diff
@@ -104,6 +110,33 @@ + (NSURL *)emeraldStyleURL {
...
+    MGLSource *source = [[clazz alloc] init];
+    source.sourceIdentifier = identifier;
+    source.source = s;
+    
+    return source;
+}
+
+- (Class)classFromSource:(mbgl::style::Source *)source
+{
+    if (dynamic_cast<mbgl::style::VectorSource *>(source)) {
```
Comment (1ec5) [inline platform/darwin/src/MGLStyle.mm]: Use `source->is<mbgl::style::VectorSource>`, which relies on a generic interface, instead of `dynamic_cast`, which relies on RTTI.

File: platform/darwin/src/MGLStyle.mm [hunk 3]
```diff
@@ -142,12 +175,66 @@ - (void)insertLayer:(id <MGLStyleLayer, MGLStyleLayer_Private>)styleLayer
...
     self.mapView.mbglMap->removeSource(source.sourceIdentifier.UTF8String);
 }
 
+- (NS_ARRAY_OF(NSString *) *)styleClasses
+{
+    NSMutableArray *returnArray = [NSMutableArray array];
+    
+    const std::vector<std::string> &appliedClasses = self.mapView.mbglMap->getClasses();
+    
+    for (auto class_it = appliedClasses.begin(); class_it != appliedClasses.end(); class_it++)
```
Comment (1ec5) [inline platform/darwin/src/MGLStyle.mm]: Nit: `for (auto appliedClass : appliedClasses)`.

File: platform/darwin/src/MGLStyle.mm [hunk 4]
```diff
@@ -142,12 +175,66 @@ - (void)insertLayer:(id <MGLStyleLayer, MGLStyleLayer_Private>)styleLayer
...
 }
 
 - (void)removeSource:(MGLSource *)source
 {
     self.mapView.mbglMap->removeSource(source.sourceIdentifier.UTF8String);
 }
 
+- (NS_ARRAY_OF(NSString *) *)styleClasses
+{
+    NSMutableArray *returnArray = [NSMutableArray array];
```
Comment (1ec5) [inline platform/darwin/src/MGLStyle.mm]: Not critical, but you could initialize this array with a capacity of `appliedClasses.size()`.

File: platform/darwin/src/MGLStyle.mm [hunk 5]
```diff
@@ -142,12 +175,66 @@ - (void)insertLayer:(id <MGLStyleLayer, MGLStyleLayer_Private>)styleLayer
...
+    [self setStyleClasses:appliedClasses transitionDuration:0];
+}
+
+- (void)setStyleClasses:(NS_ARRAY_OF(NSString *) *)appliedClasses transitionDuration:(NSTimeInterval)transitionDuration
+{
+    std::vector<std::string> newAppliedClasses;
+    
+    for (NSString *appliedClass in appliedClasses)
+    {
+        newAppliedClasses.insert(newAppliedClasses.end(), [appliedClass UTF8String]);
```
Comment (1ec5) [inline platform/darwin/src/MGLStyle.mm]: Nit: `newAppliedClasses.push_back()`.

File: platform/ios/src/MGLMapView.h [hunk 6]
```diff
@@ -212,7 +212,7 @@ IB_DESIGNABLE
 /** 
  Currently active style classes, represented as an array of string identifiers.
  */
-@property (nonatomic) NS_ARRAY_OF(NSString *) *styleClasses;
+@property (nonatomic) NS_ARRAY_OF(NSString *) *styleClasses __attribute__((deprecated("Use -style.styleClasses:.")));
```
Comment (1ec5) [inline platform/ios/src/MGLMapView.h]: Nit: the `-` is for selector names, not key paths. How about: `Use -[MGLStyle styleClasses] via -[MGLMapView style].` Or: `Use style.styleClasses.`

File: platform/ios/src/MGLMapView.h [hunk 7]
```diff
@@ -212,7 +212,7 @@ IB_DESIGNABLE
 /** 
  Currently active style classes, represented as an array of string identifiers.
```
Comment (1ec5) [inline platform/ios/src/MGLMapView.h]: Also, because jazzy doesn’t currently display deprecation messages, we usually remove the documentation comment from deprecated symbols.

File: platform/ios/src/MGLMapView_Private.h (hunk 1 above)
Comment (1ec5) [inline platform/ios/src/MGLMapView_Private.h]: Not currently. We do need a good home for non-geometric utility functions. The macOS version of MGLMapView.mm also defines an `MGLDurationInSeconds()`. It’d be great if we could replace them with a single method somewhere in platform/darwin/src/. Considering that `NSTimeInterval` is defined in NSDate.h, how about adding a private NSDate+MGLAdditions.h that just contains this method for now but could in the future have a category on NSDate?

File: platform/darwin/src/MGLStyle.mm (hunk 2 above)
Comment (frederoni) [inline platform/darwin/src/MGLStyle.mm]: We have to land PR #6069 first.

File: platform/ios/src/MGLMapView.h [hunk 8]
```diff
@@ -209,32 +209,12 @@ IB_DESIGNABLE
...
+@property (nonatomic) NS_ARRAY_OF(NSString *) *styleClasses __attribute__((deprecated("Use style.styleClasses.")));
 
-/**
- Returns a Boolean value indicating whether the style class with the given
- identifier is currently active.
- 
- @param styleClass The style class to query for.
- @return Whether the style class is currently active.
- */
 - (BOOL)hasStyleClass:(NSString *)styleClass __attribute__((deprecated("Use -style.hasStyleClass:.")));
```
Comment (1ec5) [inline platform/ios/src/MGLMapView.h]: Nit: also drop the `-` here and on `-addStyleClass:` and `-removeStyleClass:`.

**Comment by 1ec5** [comment]
Reopened #5995 because it wasn’t included in this PR.
