### PR TITLE
[core] Fix symbol flickering during tile reload

### LINKED ISSUE #7615: Flickering symbol layers when tiles are refreshed
Tile layout is a two step process: first layout is performed for all non-symbol layers, then symbol layers are placed. Upon completion of the first step, [`GeometryTile` sets its buckets](https://github.com/mapbox/mapbox-gl-native/blob/b6894dd4fc24f93c77b1ad39f466997f1525f2bd/src/mbgl/tile/geometry_tile.cpp#L108) to the result of that step, which will not contain any symbol buckets. Upon completion of the second step, [it merges in symbol buckets](https://github.com/mapbox/mapbox-gl-native/blob/b6894dd4fc24f93c77b1ad39f466997f1525f2bd/src/mbgl/tile/geometry_tile.cpp#L118-L120).

When cached tiles are revalidated and new data is available, or when the tile layout needs to be refreshed due to runtime styling changes, the result of tile layout is intended to seamlessly replace the previously existing layout. However, due to the way that `GeometryTile` is currently implemented, any delay between the two steps can lead to flickering symbol layers, because previously existing symbol buckets are effectively discarded upon completion of the first step, and not replaced until the second step completes.

`GeometryTile` could avoid this effect if it kept symbol and non-symbol buckets segregated, discarding prior symbol buckets only when new symbol buckets became available.

### PR DESCRIPTION
**Pull request by jfirebaugh**
Discard prior symbol buckets only when new symbol buckets became available, in order to eliminate flickering when tiles are refreshed. Plus followup refactor.

Fixes #7615

### CODE REVIEW

File: src/mbgl/tile/geometry_tile.cpp [hunk 1]
```diff
@@ -115,9 +116,7 @@ void GeometryTile::onPlacement(PlacementResult result) {
     if (result.correlationID == correlationID) {
         availableData = DataAvailability::All;
     }
-    for (auto& bucket : result.buckets) {
-        buckets[bucket.first] = std::move(bucket.second);
-    }
+    symbolBuckets = std::move(result.symbolBuckets);
```
Comment (kkaefer) [inline src/mbgl/tile/geometry_tile.cpp]: This also fixes a potential issue that could occur when after a relayout, a layer doesn't have any data anymore. In this case, it wouldn't produce a new bucket, so the old bucket would not be overwritten.

**Comment by kkaefer** [comment]
Could you please use branch names that are unambiguous? Using a digit-only branch name makes it harder to check out the branch locally.

**Comment by kkaefer** [comment]
I tested this with a database that has prior cache data in my testing area (Berlin), and ran the following SQL command to simulate expired + non-304 responses from the server: `UPDATE tiles SET expires = 1483675317, etag = "xxx";`. When loading the map, I'm still seeing entire loaded, but expired tiles vanish and gradually reappear. It looks like this patch solves the particular case of relayouting, but doesn't solve the flicker for expired tiles replacing the previous tile.

Here's a frame sequence I recorded with this patch: http://bl.ocks.org/kkaefer/raw/a422cc89a78917aaf718fe022c61bfe8/

**Comment by kkaefer** [comment]
This pull request fixes a part of the issue; the other part of the issue was introduced just a few days ago in https://github.com/mapbox/mapbox-gl-native/pull/7586/commits/99c1a0ecbdadb54df32baddb1b0b88df71533c4b#diff-7c17b75ae445adc15c24e3f167193e4eR217:

When a tile in the cache is expired, we start a refresh request. In many cases, we're getting a 304 response (not modified) back, in which case we don't do anything. However, when the tile changed, we're calling `GeometryTile::setData()`, which triggers `GeometryTileWorker::setData()` on the worker thread. However, this is a reused worker, that has processed the previous (expired) tile already. Back when it processed the first tile, it eventually ran `GeometryTileWorker::redoLayout` and this line:

```cpp
std::vector<std::vector<std::unique_ptr<Layer>>> groups = groupByLayout(std::move(*layers));
```

This means that it *moved* the layer information objects out of itself, and through some hoops [into the `SymbolLayout` object](https://github.com/mapbox/mapbox-gl-native/blob/99c1a0ecbdadb54df32baddb1b0b88df71533c4b/src/mbgl/layout/symbol_layout.hpp#L59). When reparsing the tile with new data, `setLayers` isn't called (since nothing about them changed), but the `layers` vector optional is engaged, the the actual vector is empty, meaning that the layout process will not produce any buckets. This empty bucket list [now overwrites](https://github.com/mapbox/mapbox-gl-native/blob/99c1a0ecbdadb54df32baddb1b0b88df71533c4b/src/mbgl/tile/geometry_tile_worker.cpp#L260-L265) the previous (stale, but parsed) buckets. They reappear because immediately after invoking `GeometryTileWorker::setData()`, we're also calling [`redoLayout()`](https://github.com/mapbox/mapbox-gl-native/blob/59803d3025683a255737b5ae29bd7fc531a975a3/src/mbgl/tile/geometry_tile.cpp#L56), which gets a fresh set of cloned layer object over to the worker, and starts processing again.

I implemented a fix in https://github.com/mapbox/mapbox-gl-native/compare/7615...7615-reset-layers-after-redolayout, which works by disengaging the `optional` that holds the (now empty) layer objects.

**Comment by jfirebaugh** [comment]
Thanks for tracking down #7586 as a cause of flickering. Indeed, `GeometryTileWorker` shouldn't have been consuming the layers like that. The intent is that `GeometryTileWorker::set{Layers,Data,PlacementConfig}` can be invoked any number of times, in any order, and `GeometryTileWorker` will do the right thing. In particular `GeometryTileWorker` shouldn't assume that `GeometryTile` is going to call `redoLayout` directly after invoking `setData`. I want to replace `GeometryTile::redoLayout` with `GeometryTile::setLayers`, so that the public `GeometryTile` interface is oriented around _what data has changed_ rather than _what needs to happen in response to something changing_, which should be entirely the responsibility of the implementation.

File: src/mbgl/tile/geometry_tile.hpp [hunk 2]
```diff
@@ -59,7 +59,7 @@ class GeometryTile : public Tile {
 
     class PlacementResult {
     public:
-        std::unordered_map<std::string, std::shared_ptr<Bucket>> buckets;
+        std::unordered_map<std::string, std::shared_ptr<Bucket>> symbolBuckets;
```
Comment (jfirebaugh) [inline src/mbgl/tile/geometry_tile.hpp]: We could, however it would make `GeometryTile::getBucket` longer because it couldn't use `layer.is<SymbolLayer>() ? symbolBuckets : nonSymbolBuckets`. Not sure if it's worth it.

File: src/mbgl/layout/symbol_layout.cpp [hunk 3]
```diff
@@ -254,7 +254,7 @@ void SymbolLayout::addFeature(const SymbolFeature& feature,
                                                   ? SymbolPlacementType::Point
                                                   : layout.get<SymbolPlacement>();
     const float textRepeatDistance = symbolSpacing / 2;
-    IndexedSubfeature indexedFeature = {feature.index, sourceLayerName, layers.at(0)->getID(), symbolInstances.size()};
+    IndexedSubfeature indexedFeature = {feature.index, sourceLayerName, layerIDs.at(0), symbolInstances.size()};
```
Comment (kkaefer) [inline src/mbgl/layout/symbol_layout.cpp]: Is it guaranteed that `layerIDs` always has at least one element?

**Comment by kkaefer** [comment]
> what data has changed rather than what needs to happen in response to something changing

Yeah, agreed. There's a call to `redoLayout();` in `GeometryTile::setData(...)`. Instead of sending over the layers every time we call `setData()`, we should call `redoLayout()` when the object is constructed. With an expired tile, we right now call `redoLayout()` on the worker side 3×: once as part of the initial (expired) `setData`, once when calling `setData` with the fresh data, and then immediately after that again when calling `redoLayout` after the `setData` call.

File: src/mbgl/layout/symbol_layout.cpp (hunk 3 above)
Comment (jfirebaugh) [inline src/mbgl/layout/symbol_layout.cpp]: That invariant should hold: the layer IDs are constructed from the layer group, and if there's no group, no `SymbolLayout` will be created. However, just in case it doesn't, I used `at(0)` here rather than `[0]` to get an exception rather than invalid memory access.
