### PR TITLE
Compability for Samsung devices forcing 3-4 array vector length

### LINKED ISSUE #9745: [Android] IllegalArgumentException: R array length must be 3 or 4 with Samsung Device
Hello, i'm encountering an issue with Samsung Galaxy S4 (GT-I9505) and Android 4.3.

`Fatal Exception: java.lang.IllegalArgumentException: R array length must be 3 or 4
       at android.hardware.SensorManager.getRotationMatrixFromVector(SensorManager.java:1336)
       at com.mapbox.mapboxsdk.maps.widgets.MyLocationView$CompassListener.onSensorChanged(MyLocationView.java:821)
       at android.hardware.SystemSensorManager$SensorEventQueue.dispatchSensorEvent(SystemSensorManager.java:467)`

It seems a known issue on Samsung devices when they owns more 4 vector sensors.

**Platform:4.3
**Mapbox SDK version:5.1.0

### Steps to trigger behavior

 1. `map.getTrackingSettings().setMyBearingTrackingMode(MyBearingTracking.COMPASS)
 `

### Expected behavior
No crash :)
### Actual behavior
throw IllegalArgumentException on Samsung device

### PR DESCRIPTION
**Pull request by tobrun**
Closes #9745, as noted in issue and shown in [chromium](https://src.chromium.org/viewvc/chrome/trunk/src/content/public/android/java/src/org/chromium/content/browser/DeviceMotionAndOrientation.java?pathrev=246398) tracker. A couple of 4.3 Samsung devices throw an exception when the rotation vector size is larger as 4. This PR provides compatibility those devices.

Haven't been able to verify this issue myself, default implementation still works.

### CODE REVIEW

File: platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/widgets/MyLocationView.java [hunk 1]
```diff
@@ -865,6 +867,31 @@ public void onSensorChanged(SensorEvent event) {
...
+     */
+    @NonNull
+    float[] getRotationVectorFromSensorEvent(@NonNull SensorEvent event) {
+      if (event.values.length > 4) {
+        // On some Samsung devices SensorManager.getRotationMatrixFromVector
+        // appears to throw an exception if rotation vector has length > 4.
+        // For the purposes of this class the first 4 values of the
+        // rotation vector are sufficient (see crbug.com/335298 for details).
+        // Only affects Android 4.3
+        if (truncatedRotationVectorValue == null) {
```
Comment (Guardiola31337) [inline platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/widgets/MyLocationView.java]: It seems that this condition is always `false` because we're initializing it here https://github.com/mapbox/mapbox-gl-native/blob/76d1d87cc1c54fbe72549810610159306555b729/platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/widgets/MyLocationView.java#L814 so it could be removed. Am I missing something?

Comment (tobrun) [inline platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/widgets/MyLocationView.java]: correct, fixed in 3c4810e
