### PR TITLE
[core][ios][osx][android] fix icons with non-integer width/height

### LINKED ISSUE #2198: MGLAnnotationImage with scale greater than 1.0 causes crash.
Hello, I'm using MapboxGL 0.5 in my iOS map. When trying to annotate map with images of markers on retina displays, I got this error:
```
libc++abi.dylib: terminating with uncaught exception of type mbgl::util::SpriteImageException: Sprite image pixel count mismatch
```

Here's my setup:
```swift
class MyViewController: UIViewController, MGLMapViewDelegate {
    var mapView: MGLMapView!

    override func viewDidLoad() {
        super.viewDidLoad()
        
        // Create the map view.
        mapView = MGLMapView(frame: CGRect(x: 0, y: 0, width: 300, height: 300))
        mapView.delegate = self
        view.addSubview(mapView)

        // Add a single marker.
        let point = MGLPointAnnotation()
        point.coordinate = ...
        mapView.addAnnotation(point)
        mapView.setCenterCoordinate(...)
    }

    func mapView(mapView: MGLMapView, imageForAnnotation annotation: MGLAnnotation) -> MGLAnnotationImage? {
        // Memory Efficiency: If a marker is available from the reusable queue, make use of it.
        if let pin = mapView.dequeueReusableAnnotationImageWithIdentifier("customPin") {
            return pin
        }

        // Scale of the image below is automatically selected based on the display's pixel density.
        // Both @1x and @2x version is available. However, only @2x version causes the crash.
        let image = UIImage(named: "myCustomImage")!
        return MGLAnnotationImage(image: image, reuseIdentifier: "customPin")
    }
}
```

As I said in the comments, the crash occurs only when `image.scale > 1.0`. I've attempted to use the @1x version of the image only but that looks blurry and ugly on the retina display.

To confirm that the error isn't caused by a malformed image file, I've also tried several other @2x images. All of them crashed the app.

I have even managed to prove that this bug is caused explicitly by the scale of the image. The following code works because I've manually tuned down the scale of the @2x image from 2.0 to 1.0. The annotation displays on the map view correctly but has double the size of the original image. You can try and substitute any other scale in the `let scaledUpImage...` line to see my point. If you use scale greater than 1.0, you get a crash.

```swift
    func mapView(mapView: MGLMapView, imageForAnnotation annotation: MGLAnnotation) -> MGLAnnotationImage? {
        if let pin = mapView.dequeueReusableAnnotationImageWithIdentifier("customPin") {
            return pin
        }

        // This image will have scale 2.0 on retina displays.
        let image = UIImage(named: "myCustomImage")!

        // Use it to create a new image with scale 1.0 and double size.
        let scaledUpImage = UIImage(CGImage: image.CGImage, scale: 1.0, orientation: .Up)!
        return MGLAnnotationImage(image: scaledUpImage, reuseIdentifier: "customPin")
    }
```

Are there any workarounds?

### PR DESCRIPTION
**Pull request by ansis**
ref #3031
ref #2198

For example, an icon that has:
- a pixel width of 10
- a pixel ratio of 3
- a scaled with of 3.333

is now supported.

SpriteImage is now constructed with the pixel width of the image instead of the width.

this works in android with @tobrun's https://github.com/mapbox/mapbox-gl-native/tree/3031-test-branch-android
@1ec5 I think this should fix #2198 - what's the best way to test that?

### CODE REVIEW

**Comment by jfirebaugh** [comment]
Approach here looks sound. I would like to continue by changing the `SpriteImage` constructor signature to:

```
SpriteImage(PremultipliedImage&&, float pixelRatio, bool sdf = false)
```

And replacing these `SpriteImage` members:

```
    const uint16_t width;
    const uint16_t height;
    const uint16_t pixelWidth;
    const uint16_t pixelHeight;
    const std::string data;
```

With:

```
const PremultipliedImage image;
```

**Comment by 1ec5** [comment]
> I think this should fix #2198 - what's the best way to test that?

Change [this line](https://github.com/mapbox/mapbox-gl-native/blob/f62d41ae05adade69fb08cff3c071b960c25c857/ios/app/MBXViewController.mm#L520) to:

```objc
CGRect rect = CGRectMake(0, 0, 20, 15.5);
```

**Comment by 1ec5** [comment]
Can you add a line to the Android and iOS sections of the changelog, too? Lots of folks are eager to see this fixed. :clap:

**Comment by bleege** [comment]
Tagging myself here so that we can cherry pick this over to `release-android-3.1.0` branch when this lands.

**Comment by ansis** [comment]
@jfirebaugh SpriteImage and PremultipliedImage changes implemented in 9cef5a7

File: platform/android/src/jni.cpp [hunk 1]
```diff
@@ -1227,14 +1228,19 @@ void JNICALL nativeAddAnnotationIcon(JNIEnv *env, jobject obj, jlong nativeMapVi
 
     jbyte* pixelData = env->GetByteArrayElements(jpixels, nullptr);
     jsize size = env->GetArrayLength(jpixels);
-    std::string pixels(reinterpret_cast<char*>(pixelData), size);
     env->ReleaseByteArrayElements(jpixels, pixelData, JNI_ABORT);
```
Comment (jfirebaugh) [inline platform/android/src/jni.cpp]: This line needs to be moved to after the `std::copy`. (Actually I'm reading now that `GetByteArrayRegion` is a better API to use: http://developer.android.com/training/articles/perf-jni.html.)

File: platform/ios/src/MGLMapView.mm [hunk 2]
```diff
@@ -2304,11 +2304,11 @@ - (void)installAnnotationImage:(MGLAnnotationImage *)annotationImage
...
     size_t height = CGImageGetHeight(image);
     CGColorSpaceRef colorSpace = CGColorSpaceCreateDeviceRGB();
-    std::string pixels(width * height * 4, '\0');
+    mbgl::PremultipliedImage cPremultipliedImage(width, height);
     size_t bytesPerPixel = 4;
     size_t bytesPerRow = bytesPerPixel * width;
     size_t bitsPerComponent = 8;
-    char *pixelData = const_cast<char *>(pixels.data());
+    char *pixelData = reinterpret_cast<char *>(cPremultipliedImage.data.get());
     CGContextRef context = CGBitmapContextCreate(pixelData, width, height, bitsPerComponent, bytesPerRow, colorSpace, kCGImageAlphaPremultipliedLast);
```
Comment (jfirebaugh) [inline platform/ios/src/MGLMapView.mm]: Avoid the cast and pass `cPremultipliedImage.data.get()` directly to `CGBitmapContextCreate`.

File: src/mbgl/annotation/annotation_manager.cpp [hunk 3]
```diff
@@ -165,7 +165,7 @@ void AnnotationManager::removeIcon(const std::string& name) {
 
 double AnnotationManager::getTopOffsetPixelsForIcon(const std::string& name) {
     auto sprite = spriteStore.getSprite(name);
-    return sprite ? -sprite->height / 2 : 0;
+    return sprite ? -(std::ceil(sprite->image.height / sprite->pixelRatio)) / 2 : 0;
```
Comment (jfirebaugh) [inline src/mbgl/annotation/annotation_manager.cpp]: I'm not sure if this should use `std::ceil` or not.

File: test/sprite/sprite_store.cpp [hunk 4]
```diff
@@ -13,9 +13,10 @@ using namespace mbgl;
 TEST(SpriteStore, SpriteStore) {
     FixtureLog log;
 
-    const auto sprite1 = std::make_shared<SpriteImage>(8, 8, 2, std::string(16 * 16 * 4, '\0'));
-    const auto sprite2 = std::make_shared<SpriteImage>(8, 8, 2, std::string(16 * 16 * 4, '\0'));
-    const auto sprite3 = std::make_shared<SpriteImage>(8, 8, 2, std::string(16 * 16 * 4, '\0'));
+    PremultipliedImage image(16, 16);
+    const auto sprite1 = std::make_shared<SpriteImage>(std::move(image), 2);
```
Comment (jfirebaugh) [inline test/sprite/sprite_store.cpp]: `move`ing something twice isn't valid. Instead do `std::make_shared<SpriteImage>(PremultipliedImage(16, 16), 2)`.

**Comment by ansis** [comment]
@jfirebaugh thanks for finding all the bugs, they should be fixed now

**Comment by jfirebaugh** [comment]
:+1:

**Comment by bleege** [comment]
Should this be cherry picked into the `release-android-v3.1.0` branch?

**Comment by ansis** [comment]
@bleege I think so. at least the first commit (26faa6a5ade54c0a423aab84106876dc59be868f).

**Comment by tobrun** [comment]
I verified that this fixed the initial issue of having a rectangle image as marker icon

**Comment by bleege** [comment]
Cool!  @tobrun confirmed that he tested from `master` and both  26faa6a5ade54c0a423aab84106876dc59be868f and d34f8eb674b9753c47616f37ae88ff7a02f61ba0 made it in there.  I'll cherry pick both to `release-android-v3.1.0` for today's release at #3537 .

Thanks everyone!

**Comment by bleege** [comment]
FYI... I fudged the cherry pick process for the first commit 26faa6a5ade54c0a423aab84106876dc59be868f and ended up creating a new commit after resolving the changes instead of doing a `git cherry-pick --continue` hence 52fd9d7b505559972654a9f7af05d6be9c244f73.  I did it the proper way for the second commit however.  Discussed with @zugaldia this morning and we decided to leave this as is (and not deal with force pushes and other crazy git commands to be named later) and deal with the pain when the merge of `release-android-v3.1.0` into `master` after release.

**Comment by danswick** [comment]
Huge! Our mobile SDK users will be pumped when this lands. :clap:

**Comment by bleege** [comment]
@danswick FYI... we had to pull this from Android `3.1.0` today due to C++ Pain.  It's now scheduled for `4.0.0`.

**Comment by afathman** [comment]
When is the expected release of 4.0.0?

**Comment by bleege** [comment]
@afathman We're still planning the specifics around `4.0.0`, but in the interim the fix for this issues is available immediately for use via the nighlty `4.0.0-SNAPSHOT` builds.
