### PR TITLE
Fix deadlock in http request on hitting tile limit

### LINKED ISSUE #13669: Mapbox hangs after it reaches tile count limit after the first time
Mapbox still hangs after tile count limit is exceeded. I had the issue before with mapbox 6.5.0 and now still with 6.7.2 which should have had this issue fixed as per [this issue](https://github.com/mapbox/mapbox-gl-native/issues/12833)

### Steps to reproduce

 1. Compile this https://github.com/onaio/kujaku/ app implementing Mapbox MapView
 2. Checkout to branch `issue/220-update-mapbox-to-6.7.2` which has the mapbox SDK bump to `6.7.2` and run the `sample` module
 2. Open the app and enter a map name in the first field which is named **Offline Map Download** field
 3. Click on **START OFFLINE DOWNLOAD** which will start download a pretty huge offline region with the name you entered. A notification should appear showing the download progress. At around 2.34%, the download stops and a tile count limit exceeded error notification is shown. If you try to open the navigation menu and open an activity that uses the `MapView` such as **Low Level Add Point**, the application hangs and takes too long to open the activity.

I also tried setting the offline region to `OfflineRegion.STATE_INACTIVE` after the tile count limit was exceeded but this produces worse results because the sample application stops responding immediately and even the tile count limit error notification is not displayed.

### Expected behavior
I should be able to navigate to other maps either with the same error but smoothly. This should not make the whole application not respond.

### Configuration

**Android versions:** Android 7.0, 5.1.1
**Device models:** Samsung Galaxy Tab S2(SM-T713), Oppo A37fw
**Mapbox SDK versions:** 6.7.2

### PR DESCRIPTION
**Pull request by ivovandongen**
Fixes #13669

When hitting the tile limit for offline downloads the filesource thread deadlocks. The callback of the http requests triggers the clearing of all outstanding http request (including the one hitting the limit) and then a lock is requested for a second time in the cancel method called from the http request destructor.

In this case, cancel should not request a lock again, but just set the native pointer to 0.

### CODE REVIEW

File: platform/android/src/run_loop.cpp [hunk 1]
```diff
@@ -141,55 +141,45 @@ void RunLoop::Impl::wake() {
...
-    std::lock_guard<std::recursive_mutex> lock(mtx);
-
-    if (runnable->iter == runnables.end()) {
-        auto iter = runnables.insert(runnables.end(), runnable);
-        runnable->iter = std::move(iter);
-    }
+    std::lock_guard<std::mutex> lock(mutex);
+    runnables.push_back(runnable);
 
     wake();
```
Comment (pozdnyakov) [inline platform/android/src/run_loop.cpp]: nit: looks `wake()` does not need locked mutex
