### PR TITLE
[android] - move snapshot to NativeMapView

### LINKED ISSUE #7384: Reimplement Snapshot API Callback
With refactor in https://github.com/mapbox/mapbox-gl-native/pull/7189 we had to decouple MapView from MapboxMap, this resulted in a broken  callback for the snapshot API. The snapshot API allows you to get a bitmap of the shown Map. While moving this in a separate component we should look into investigating https://github.com/mapbox/mapbox-gl-native/issues/6238.

### PR DESCRIPTION
**Pull request by tobrun**
closes #7384.
Review @cammace

### CODE REVIEW

File: platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapView.java [hunk 1]
```diff
@@ -936,49 +925,6 @@ void setMapboxMap(MapboxMap mapboxMap) {
     // Snapshot API
```
Comment (cammace) [inline platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapView.java]: Comment can be removed

File: platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/NativeMapView.java [hunk 2]
```diff
@@ -50,6 +51,10 @@
     // Listeners for Map change events
     private CopyOnWriteArrayList<MapView.OnMapChangedListener> onMapChangedListeners;
 
+    // Listener for a bitmap of the map
+    private SnapshotRequest snapshotRequest;
+
+
```
Comment (cammace) [inline platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/NativeMapView.java]: nit

**Comment by tobrun** [comment]
@cammace fixed up your comments, can you rereview?
