### PR TITLE
Unify has surface state handling

### LINKED ISSUE #14422: (Android - MapBox 7.3.1) queryRenderedFeatures not working properly anymore
After updating from 7.3.0 to 7.3.1, it seems like the queryRenderedFeatures function is broken when resuming a fragment. The method is only returning 0 after stopping and resuming a fragment that holds the mapview. When using 7.3.0 everything worked fine. I assume that https://github.com/mapbox/mapbox-gl-native/pull/14395 broke the whole implementation for fragments.

### Configuration

**Android versions:** all
**Device models:** all
**Mapbox SDK versions:** 7.3.1

### PR DESCRIPTION
**Pull request by tobrun**
Closes #14422, Follow up from https://github.com/mapbox/mapbox-gl-native/pull/14395. This PR unifies state management around having a render surface created. Instead of maintaining it in 2 places NativeMapView + MapRenderer. This PR moves it fully to MapRenderer instead. This solves the issue from #14422.  Validated that both setups work correctly for quering with both TextureView as GLSurfaceView. Running tests on mutliple devices on firebase didn't show any issues. 

image

### CODE REVIEW

File: platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/renderer/MapRenderer.java [hunk 1]
```diff
@@ -30,7 +30,7 @@
 
   // Holds the pointer to the native peer after initialisation
   private long nativePtr = 0;
-
+  private boolean hasSurface = true;
```
Comment (LukasPaczos) [inline platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/renderer/MapRenderer.java]: Can this field be `protected` instead of having a setter? It's always set from the extending object anyway.

File: platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/renderer/glsurfaceview/GLSurfaceViewMapRenderer.java [hunk 2]
```diff
@@ -103,7 +102,7 @@ public void onDrawFrame(GL10 gl) {
    */
   @Override
   public void requestRender() {
-    if (!hasSurface) {
+    if (!hasSurface()) {
```
Comment (LukasPaczos) [inline platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/renderer/glsurfaceview/GLSurfaceViewMapRenderer.java]: This could also use a protected field instead.

File: platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/renderer/textureview/TextureViewMapRenderer.java [hunk 3]
```diff
@@ -43,6 +43,7 @@ public TextureViewMapRenderer(@NonNull Context context,
   @Override
   protected void onSurfaceCreated(GL10 gl, EGLConfig config) {
     super.onSurfaceCreated(gl, config);
+    hasSurface = true;
```
Comment (LukasPaczos) [inline platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/renderer/textureview/TextureViewMapRenderer.java]: Shouldn't this line be in the `MapRenderer#onSurfaceCreated`? Otherwise, I believe that `GLSurfaceViewMapRenderer` never sets the value to true.

File: platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/renderer/MapRenderer.java [hunk 4]
```diff
@@ -30,9 +30,9 @@
 
   // Holds the pointer to the native peer after initialisation
   private long nativePtr = 0;
-
   private double expectedRenderTime = 0;
   private MapboxMap.OnFpsChangedListener onFpsChangedListener;
+  protected boolean hasSurface;
```
Comment (LukasPaczos) [inline platform/android/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/renderer/MapRenderer.java]: This can be `private` now, or `GLSurfaceViewMapRenderer#requestRenderer` should use a field reference instead of a getter.

**Comment by tobrun** [comment]
Looked into this again and we can't unify setting the hasSurface flags for both renderers. They have a different lifespan. `SurfaceHolder.Callback#onSurfaceCreated` is called when an Activity is resumed but Renderer#onSurfaceCreated isn't. This would disable rendering when returning from the background.
