### PR TITLE
Preserve symlinks when zipping framework

### LINKED ISSUE #8636: Framework contains duplicate files instead of symlinks
As of macOS SDK v0.4.0, Mapbox.framework contains duplicate copies of files such as the Mapbox executable. Instead of symlinks to files and folders under Versions/A/, the root of the framework and the Versions/Current/ folder are polluted with copies of these files. As a result, the framework is bloated, fails to code-sign, and probably fails in other ways.

This is a regression of #5818, which was fixed in #5850 for v0.2.0.

/cc @kkaefer @frederoni

### PR DESCRIPTION
**Pull request by 1ec5**
When zipping the framework for deployment, preserve symlinks instead of resolving them. Prior to this change, the published framework bundle contained multiple copies of the Mapbox executable and of every resource file, because the standard layout for a framework on macOS requires symlinks from the root folder and Versions/Current/ to Versions/A/.

Fixes #8636.

/cc @kkaefer @frederoni

### CODE REVIEW

File: platform/ios/scripts/publish.sh [hunk 1]
```diff
@@ -27,7 +27,7 @@ cd build/ios/pkg
 ZIP=mapbox-ios-sdk-${PUBLISH_VERSION}${PUBLISH_STYLE}.zip
 step "Compressing ${ZIP}…"
 rm -f ../${ZIP}
-zip -r ../${ZIP} *
+zip -yr ../${ZIP} *
```
Comment (kkaefer) [inline platform/ios/scripts/publish.sh]: Why is there no changelog entry for iOS?

Comment (1ec5) [inline platform/ios/scripts/publish.sh]: There are no symlinks in the iOS SDK, so there’s no developer impact in practice. I made this change to the iOS SDK regardless in case we ever do need a symlink in there.
