### PR TITLE
Blacklist VAO usage on adreno 3xx

### LINKED ISSUE #9935: [android] Crash when swipping + zooming in building layer example
**Platform:** Android 5.0 - Moto X (2nd Generation) 
**Mapbox SDK version:** `master`

### Steps to trigger behavior

 1. Open Test app
 2. Open _Building layer_ example
 3. Swipe + zoom the map
 4. App crashes

### logcat

```
09-08 15:54:16.929 383-383/? I/DEBUG: *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
09-08 15:54:16.929 383-383/? I/DEBUG: Build fingerprint: 'motorola/victara_reteu/victara:5.0/LXE22.46-19/18:user/release-keys'
09-08 15:54:16.929 383-383/? I/DEBUG: Revision: 'p2bf'
09-08 15:54:16.929 383-383/? I/DEBUG: ABI: 'arm'
09-08 15:54:16.929 383-383/? I/DEBUG: pid: 7903, tid: 7903, name: pboxsdk.testapp  >>> com.mapbox.mapboxsdk.testapp <<<
09-08 15:54:16.929 383-383/? I/DEBUG: signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0xdeadbaad
09-08 15:54:16.959 383-383/? I/DEBUG: Abort message: 'invalid address or address of corrupt block 0xb93f6dc0 passed to dlfree'
09-08 15:54:16.959 383-383/? I/DEBUG:     r0 00000000  r1 bea33e28  r2 deadbaad  r3 00000000
09-08 15:54:16.959 383-383/? I/DEBUG:     r4 b93f6dc0  r5 b6f6e0f4  r6 9b434000  r7 b93f6dc8
09-08 15:54:16.959 383-383/? I/DEBUG:     r8 b8322270  r9 000030a0  sl b8035bb0  fp 00000438
09-08 15:54:16.960 383-383/? I/DEBUG:     ip b6f6869c  sp bea34218  lr b6f3d46b  pc b6f3d46c  cpsr 60000030
09-08 15:54:16.960 383-383/? I/DEBUG: backtrace:
09-08 15:54:16.960 383-383/? I/DEBUG:     #00 pc 0002b46c  /system/lib/libc.so (dlfree+1239)
09-08 15:54:16.960 383-383/? I/DEBUG:     #01 pc 00011fcf  /system/lib/libc.so (free+10)
09-08 15:54:16.960 383-383/? I/DEBUG:     #02 pc 0001e8fc  /system/vendor/lib/egl/libEGL_adreno.so (eglTimestampListFree+16)
09-08 15:54:16.960 383-383/? I/DEBUG:     #03 pc 00013ce4  /system/vendor/lib/egl/libEGL_adreno.so (qeglDrvAPI_eglSwapBuffers+1596)
09-08 15:54:16.961 383-383/? I/DEBUG:     #04 pc 0000791c  /system/vendor/lib/egl/libEGL_adreno.so (eglSwapBuffers+16)
09-08 15:54:16.961 383-383/? I/DEBUG:     #05 pc 00012267  /system/lib/libEGL.so (eglSwapBuffers+290)
09-08 15:54:16.961 383-383/? I/DEBUG:     #06 pc 000c57a7  /data/app/com.mapbox.mapboxsdk.testapp-1/lib/arm/libmapbox-gl.so
09-08 15:54:16.961 383-383/? I/DEBUG:     #07 pc 000dbb0f  /data/app/com.mapbox.mapboxsdk.testapp-1/lib/arm/libmapbox-gl.so
09-08 15:54:16.961 383-383/? I/DEBUG:     #08 pc 000dbaa5  /data/app/com.mapbox.mapboxsdk.testapp-1/lib/arm/libmapbox-gl.so
09-08 15:54:16.962 383-383/? I/DEBUG:     #09 pc 000dba6d  /data/app/com.mapbox.mapboxsdk.testapp-1/lib/arm/libmapbox-gl.so
09-08 15:54:16.962 383-383/? I/DEBUG:     #10 pc 000dbb99  /data/app/com.mapbox.mapboxsdk.testapp-1/lib/arm/libmapbox-gl.so
09-08 15:54:16.962 383-383/? I/DEBUG:     #11 pc 000dbb59  /data/app/com.mapbox.mapboxsdk.testapp-1/lib/arm/libmapbox-gl.so
09-08 15:54:16.962 383-383/? I/DEBUG:     #12 pc 0017835b  /data/dalvik-cache/arm/data@app@com.mapbox.mapboxsdk.testapp-1@base.apk@classes.dex
```

### Symbolicated Android crash

```
********** Crash dump: **********
Build fingerprint: 'motorola/victara_reteu/victara:5.0/LXE22.46-19/18:user/release-keys'
pid: 7903, tid: 7903, name: pboxsdk.testapp  >>> com.mapbox.mapboxsdk.testapp <<<
signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0xdeadbaad
Stack frame #00 pc 0002b46c  /system/lib/libc.so (dlfree+1239)
Stack frame #01 pc 00011fcf  /system/lib/libc.so (free+10)
Stack frame #02 pc 0001e8fc  /system/vendor/lib/egl/libEGL_adreno.so (eglTimestampListFree+16)
Stack frame #03 pc 00013ce4  /system/vendor/lib/egl/libEGL_adreno.so (qeglDrvAPI_eglSwapBuffers+1596)
Stack frame #04 pc 0000791c  /system/vendor/lib/egl/libEGL_adreno.so (eglSwapBuffers+16)
Stack frame #05 pc 00012267  /system/lib/libEGL.so (eglSwapBuffers+290)
Stack frame #06 pc 000c57a7  /data/app/com.mapbox.mapboxsdk.testapp-1/lib/arm/libmapbox-gl.so: Routine mbgl::android::NativeMapView::render(_JNIEnv&) at /Users/pguardiola/mapbox/mapbox-gl-native/platform/android/src/native_map_view.cpp:295
Stack frame #07 pc 000dbb0f  /data/app/com.mapbox.mapboxsdk.testapp-1/lib/arm/libmapbox-gl.so: Routine operator() at /Users/pguardiola/mapbox/mapbox-gl-native/platform/android/MapboxGLAndroidSDK/.externalNativeBuild/cmake/debug/armeabi-v7a/../../../../../../../mason_packages/headers/jni.hpp/3.0.0/include/jni/native_method.hpp:245
Stack frame #08 pc 000dbaa5  /data/app/com.mapbox.mapboxsdk.testapp-1/lib/arm/libmapbox-gl.so: Routine operator() at /Users/pguardiola/mapbox/mapbox-gl-native/platform/android/MapboxGLAndroidSDK/.externalNativeBuild/cmake/debug/armeabi-v7a/../../../../../../../mason_packages/headers/jni.hpp/3.0.0/include/jni/native_method.hpp:112
Stack frame #09 pc 000dba6d  /data/app/com.mapbox.mapboxsdk.testapp-1/lib/arm/libmapbox-gl.so: Routine __invoke at /Users/pguardiola/mapbox/mapbox-gl-native/platform/android/MapboxGLAndroidSDK/.externalNativeBuild/cmake/debug/armeabi-v7a/../../../../../../../mason_packages/headers/jni.hpp/3.0.0/include/jni/native_method.hpp:110
Stack frame #10 pc 000dbb99  /data/app/com.mapbox.mapboxsdk.testapp-1/lib/arm/libmapbox-gl.so: Routine operator()<jni::jobject *> at /Users/pguardiola/mapbox/mapbox-gl-native/platform/android/MapboxGLAndroidSDK/.externalNativeBuild/cmake/debug/armeabi-v7a/../../../../../../../mason_packages/headers/jni.hpp/3.0.0/include/jni/native_method.hpp:59
Stack frame #11 pc 000dbb59  /data/app/com.mapbox.mapboxsdk.testapp-1/lib/arm/libmapbox-gl.so: Routine __invoke<jni::jobject *> at /Users/pguardiola/mapbox/mapbox-gl-native/platform/android/MapboxGLAndroidSDK/.externalNativeBuild/cmake/debug/armeabi-v7a/../../../../../../../mason_packages/headers/jni.hpp/3.0.0/include/jni/native_method.hpp:55
Stack frame #12 pc 0017835b  /data/dalvik-cache/arm/data@app@com.mapbox.mapboxsdk.testapp-1@base.apk@classes.dex
```

👀 @ivovandongen

### LINKED ISSUE #10150: [android] Crash when testing user location drawable example
**Platform:** Android 5.0 Moto X (2nd gen)
**Mapbox SDK version:** `release-agua` branch

### Steps to trigger behavior

 1. User location drawable
 2. Scroll + zoom
 3. App crashes

### Logcat
```
--------- beginning of crash
10-06 20:09:36.170 16339-16741/com.mapbox.mapboxsdk.testapp A/libc: Fatal signal 11 (SIGSEGV), code 1, fault addr 0x1 in tid 16741 (GLThread 7752)
10-06 20:09:36.271 17936-17936/? I/DEBUG: *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
10-06 20:09:36.271 17936-17936/? I/DEBUG: Build fingerprint: 'motorola/victara_reteu/victara:5.0/LXE22.46-19/18:user/release-keys'
10-06 20:09:36.272 17936-17936/? I/DEBUG: Revision: 'p2bf'
10-06 20:09:36.272 17936-17936/? I/DEBUG: ABI: 'arm'
10-06 20:09:36.272 17936-17936/? I/DEBUG: pid: 16339, tid: 16741, name: GLThread 7752  >>> com.mapbox.mapboxsdk.testapp <<<
10-06 20:09:36.272 17936-17936/? I/DEBUG: signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x1
10-06 20:09:36.289 17936-17936/? I/DEBUG:     r0 00000001  r1 b9b68858  r2 28680232  r3 b9a96228
10-06 20:09:36.289 17936-17936/? I/DEBUG:     r4 a06e3d8c  r5 00000000  r6 a06e3da4  r7 a06e39e0
10-06 20:09:36.289 17936-17936/? I/DEBUG:     r8 a06e3da0  r9 6aa3c133  sl 0000c125  fp 11e1a300
10-06 20:09:36.289 17936-17936/? I/DEBUG:     ip b6f32de4  sp a06e3754  lr a5602d13  pc a4fa03fe  cpsr 200f0030
10-06 20:09:36.289 17936-17936/? I/DEBUG: backtrace:
10-06 20:09:36.289 17936-17936/? I/DEBUG:     #00 pc 000283fe  /data/app/com.mapbox.mapboxsdk.testapp-1/lib/arm/libmapbox-gl.so
10-06 20:09:36.289 17936-17936/? I/DEBUG:     #01 pc 0068ad0f  /data/app/com.mapbox.mapboxsdk.testapp-1/lib/arm/libmapbox-gl.so
10-06 20:09:36.289 17936-17936/? I/DEBUG:     #02 pc 005ab5b5  /data/app/com.mapbox.mapboxsdk.testapp-1/lib/arm/libmapbox-gl.so
10-06 20:09:36.289 17936-17936/? I/DEBUG:     #03 pc 005ab2e1  /data/app/com.mapbox.mapboxsdk.testapp-1/lib/arm/libmapbox-gl.so
10-06 20:09:36.289 17936-17936/? I/DEBUG:     #04 pc 0066720d  /data/app/com.mapbox.mapboxsdk.testapp-1/lib/arm/libmapbox-gl.so
10-06 20:09:36.289 17936-17936/? I/DEBUG:     #05 pc 00668871  /data/app/com.mapbox.mapboxsdk.testapp-1/lib/arm/libmapbox-gl.so
10-06 20:09:36.289 17936-17936/? I/DEBUG:     #06 pc 0058caf1  /data/app/com.mapbox.mapboxsdk.testapp-1/lib/arm/libmapbox-gl.so
10-06 20:09:36.289 17936-17936/? I/DEBUG:     #07 pc 00315533  /data/app/com.mapbox.mapboxsdk.testapp-1/lib/arm/libmapbox-gl.so
10-06 20:09:36.290 17936-17936/? I/DEBUG:     #08 pc 0030af51  /data/app/com.mapbox.mapboxsdk.testapp-1/lib/arm/libmapbox-gl.so
10-06 20:09:36.290 17936-17936/? I/DEBUG:     #09 pc 000f847b  /data/app/com.mapbox.mapboxsdk.testapp-1/lib/arm/libmapbox-gl.so
10-06 20:09:36.290 17936-17936/? I/DEBUG:     #10 pc 000fdd6f  /data/app/com.mapbox.mapboxsdk.testapp-1/lib/arm/libmapbox-gl.so
10-06 20:09:36.290 17936-17936/? I/DEBUG:     #11 pc 000fdd05  /data/app/com.mapbox.mapboxsdk.testapp-1/lib/arm/libmapbox-gl.so
10-06 20:09:36.290 17936-17936/? I/DEBUG:     #12 pc 000fdccd  /data/app/com.mapbox.mapboxsdk.testapp-1/lib/arm/libmapbox-gl.so
10-06 20:09:36.290 17936-17936/? I/DEBUG:     #13 pc 000fddf9  /data/app/com.mapbox.mapboxsdk.testapp-1/lib/arm/libmapbox-gl.so
10-06 20:09:36.290 17936-17936/? I/DEBUG:     #14 pc 000fddb9  /data/app/com.mapbox.mapboxsdk.testapp-1/lib/arm/libmapbox-gl.so
10-06 20:09:36.290 17936-17936/? I/DEBUG:     #15 pc 00181c03  /data/dalvik-cache/arm/data@app@com.mapbox.mapboxsdk.testapp-1@base.apk@classes.dex
```

### Symbolicated Android crash
```
Crash dump is completed

********** Crash dump: **********
Build fingerprint: 'motorola/victara_reteu/victara:5.0/LXE22.46-19/18:user/release-keys'
pid: 16339, tid: 16741, name: GLThread 7752  >>> com.mapbox.mapboxsdk.testapp <<<
signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x1
Stack frame #00 pc 000283fe  /data/app/com.mapbox.mapboxsdk.testapp-1/lib/arm/libmapbox-gl.so: Routine std::__ndk1::__tree_node_base<void*>* std::__ndk1::__tree_min<std::__ndk1::__tree_node_base<void*>*>(std::__ndk1::__tree_node_base<void*>*) at /Users/pguardiola/Library/Android/sdk/ndk-bundle/sources/cxx-stl/llvm-libc++/include/__tree:150
Stack frame #01 pc 0068ad0f  /data/app/com.mapbox.mapboxsdk.testapp-1/lib/arm/libmapbox-gl.so: Routine std::__ndk1::__tree_iterator<std::__ndk1::__value_type<std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> >, std::__ndk1::pair<mbgl::PaintPropertyBinders<mbgl::TypeList<mbgl::style::IconOpacity, mbgl::style::IconColor, mbgl::style::IconHaloColor, mbgl::style::IconHaloWidth, mbgl::style::IconHaloBlur> >, mbgl::PaintPropertyBinders<mbgl::TypeList<mbgl::style::TextOpacity, mbgl::style::TextColor, mbgl::style::TextHaloColor, mbgl::style::TextHaloWidth, mbgl::style::TextHaloBlur> > > >, std::__ndk1::__tree_node<std::__ndk1::__value_type<std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> >, std::__ndk1::pair<mbgl::PaintPropertyBinders<mbgl::TypeList<mbgl::style::IconOpacity, mbgl::style::IconColor, mbgl::style::IconHaloColor, mbgl::style::IconHaloWidth, mbgl::style::IconHaloBlur> >, mbgl::PaintPropertyBinders<mbgl::TypeList<mbgl::style::TextOpacity, mbgl::style::TextColor, mbgl::style::TextHaloColor, mbgl::style::TextHaloWidth, mbgl::style::TextHaloBlur> > > >, void*>*, int>::operator++() at /Users/pguardiola/Library/Android/sdk/ndk-bundle/sources/cxx-stl/llvm-libc++/include/__tree:796
Stack frame #02 pc 005ab5b5  /data/app/com.mapbox.mapboxsdk.testapp-1/lib/arm/libmapbox-gl.so: Routine operator() at /Users/pguardiola/mapbox/mapbox-gl-native/src/mbgl/tile/geometry_tile.cpp:195
Stack frame #03 pc 005ab2e1  /data/app/com.mapbox.mapboxsdk.testapp-1/lib/arm/libmapbox-gl.so: Routine mbgl::GeometryTile::upload(mbgl::gl::Context&) at /Users/pguardiola/mapbox/mapbox-gl-native/src/mbgl/tile/geometry_tile.cpp:204
Stack frame #04 pc 0066720d  /data/app/com.mapbox.mapboxsdk.testapp-1/lib/arm/libmapbox-gl.so: Routine mbgl::RenderTile::startRender(mbgl::PaintParameters&) at /Users/pguardiola/mapbox/mapbox-gl-native/src/mbgl/renderer/render_tile.cpp:60
Stack frame #05 pc 00668871  /data/app/com.mapbox.mapboxsdk.testapp-1/lib/arm/libmapbox-gl.so: Routine mbgl::TilePyramid::startRender(mbgl::PaintParameters&) at /Users/pguardiola/mapbox/mapbox-gl-native/src/mbgl/renderer/tile_pyramid.cpp:44
Stack frame #06 pc 0058caf1  /data/app/com.mapbox.mapboxsdk.testapp-1/lib/arm/libmapbox-gl.so: Routine mbgl::RenderGeoJSONSource::startRender(mbgl::PaintParameters&) at /Users/pguardiola/mapbox/mapbox-gl-native/src/mbgl/renderer/sources/render_geojson_source.cpp:72
Stack frame #07 pc 00315533  /data/app/com.mapbox.mapboxsdk.testapp-1/lib/arm/libmapbox-gl.so: Routine mbgl::Renderer::Impl::render(mbgl::UpdateParameters const&) at /Users/pguardiola/mapbox/mapbox-gl-native/src/mbgl/renderer/renderer_impl.cpp:395
Stack frame #08 pc 0030af51  /data/app/com.mapbox.mapboxsdk.testapp-1/lib/arm/libmapbox-gl.so: Routine mbgl::Renderer::render(mbgl::UpdateParameters const&) at /Users/pguardiola/mapbox/mapbox-gl-native/src/mbgl/renderer/renderer.cpp:32
Stack frame #09 pc 000f847b  /data/app/com.mapbox.mapboxsdk.testapp-1/lib/arm/libmapbox-gl.so: Routine mbgl::android::MapRenderer::render(_JNIEnv&) at /Users/pguardiola/mapbox/mapbox-gl-native/platform/android/src/map_renderer.cpp:130
Stack frame #10 pc 000fdd6f  /data/app/com.mapbox.mapboxsdk.testapp-1/lib/arm/libmapbox-gl.so: Routine operator() at /Users/pguardiola/mapbox/mapbox-gl-native/platform/android/MapboxGLAndroidSDK/.externalNativeBuild/cmake/debug/armeabi-v7a/../../../../../../../mason_packages/headers/jni.hpp/3.0.0/include/jni/native_method.hpp:245
Stack frame #11 pc 000fdd05  /data/app/com.mapbox.mapboxsdk.testapp-1/lib/arm/libmapbox-gl.so: Routine operator() at /Users/pguardiola/mapbox/mapbox-gl-native/platform/android/MapboxGLAndroidSDK/.externalNativeBuild/cmake/debug/armeabi-v7a/../../../../../../../mason_packages/headers/jni.hpp/3.0.0/include/jni/native_method.hpp:112
Stack frame #12 pc 000fdccd  /data/app/com.mapbox.mapboxsdk.testapp-1/lib/arm/libmapbox-gl.so: Routine __invoke at /Users/pguardiola/mapbox/mapbox-gl-native/platform/android/MapboxGLAndroidSDK/.externalNativeBuild/cmake/debug/armeabi-v7a/../../../../../../../mason_packages/headers/jni.hpp/3.0.0/include/jni/native_method.hpp:110
Stack frame #13 pc 000fddf9  /data/app/com.mapbox.mapboxsdk.testapp-1/lib/arm/libmapbox-gl.so: Routine operator()<jni::jobject *> at /Users/pguardiola/mapbox/mapbox-gl-native/platform/android/MapboxGLAndroidSDK/.externalNativeBuild/cmake/debug/armeabi-v7a/../../../../../../../mason_packages/headers/jni.hpp/3.0.0/include/jni/native_method.hpp:59
Stack frame #14 pc 000fddb9  /data/app/com.mapbox.mapboxsdk.testapp-1/lib/arm/libmapbox-gl.so: Routine __invoke<jni::jobject *> at /Users/pguardiola/mapbox/mapbox-gl-native/platform/android/MapboxGLAndroidSDK/.externalNativeBuild/cmake/debug/armeabi-v7a/../../../../../../../mason_packages/headers/jni.hpp/3.0.0/include/jni/native_method.hpp:55
Stack frame #15 pc 00181c03  /data/dalvik-cache/arm/data@app@com.mapbox.mapboxsdk.testapp-1@base.apk@classes.dex
```

👀 @tobrun @ivovandongen

### LINKED ISSUE #10151: [android] Crash when testing animation types example
**Platform:** Android 5.0 Moto X (2nd gen)
**Mapbox SDK version:** `release-agua` branch

### Steps to trigger behavior

 1. Animation types
 2. Click on `ANIMATE`
 3. App crashes

### Logcat
```
--------- beginning of crash
10-06 20:19:44.325 22234-22354/com.mapbox.mapboxsdk.testapp A/libc: invalid address or address of corrupt block 0xba728d88 passed to dlfree
10-06 20:19:44.325 22234-22354/com.mapbox.mapboxsdk.testapp A/libc: Fatal signal 11 (SIGSEGV), code 1, fault addr 0xdeadbaad in tid 22354 (GLThread 7798)
10-06 20:19:44.429 17936-17936/? I/DEBUG: *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
10-06 20:19:44.429 17936-17936/? I/DEBUG: Build fingerprint: 'motorola/victara_reteu/victara:5.0/LXE22.46-19/18:user/release-keys'
10-06 20:19:44.429 17936-17936/? I/DEBUG: Revision: 'p2bf'
10-06 20:19:44.430 17936-17936/? I/DEBUG: ABI: 'arm'
10-06 20:19:44.430 17936-17936/? I/DEBUG: pid: 22234, tid: 22354, name: GLThread 7798  >>> com.mapbox.mapboxsdk.testapp <<<
10-06 20:19:44.431 17936-17936/? I/DEBUG: signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0xdeadbaad
10-06 20:19:44.482 17936-17936/? I/DEBUG: Abort message: 'invalid address or address of corrupt block 0xba728d88 passed to dlfree'
10-06 20:19:44.482 17936-17936/? I/DEBUG:     r0 00000000  r1 a073a820  r2 deadbaad  r3 00000000
10-06 20:19:44.482 17936-17936/? I/DEBUG:     r4 ba728d88  r5 b6f340f4  r6 9b472000  r7 ba728d90
10-06 20:19:44.482 17936-17936/? I/DEBUG:     r8 70785910  r9 b929ee88  sl 00000000  fp 137af3d0
10-06 20:19:44.482 17936-17936/? I/DEBUG:     ip b6f2e69c  sp a073ac10  lr b6f0346b  pc b6f0346c  cpsr 600f0030
10-06 20:19:44.482 17936-17936/? I/DEBUG: backtrace:
10-06 20:19:44.482 17936-17936/? I/DEBUG:     #00 pc 0002b46c  /system/lib/libc.so (dlfree+1239)
10-06 20:19:44.483 17936-17936/? I/DEBUG:     #01 pc 00011fcf  /system/lib/libc.so (free+10)
10-06 20:19:44.483 17936-17936/? I/DEBUG:     #02 pc 00018e53  /data/app/com.mapbox.mapboxsdk.testapp-1/lib/arm/libmapbox-gl.so
10-06 20:19:44.483 17936-17936/? I/DEBUG:     #03 pc 005ac419  /data/app/com.mapbox.mapboxsdk.testapp-1/lib/arm/libmapbox-gl.so
10-06 20:19:44.483 17936-17936/? I/DEBUG:     #04 pc 005ac3f9  /data/app/com.mapbox.mapboxsdk.testapp-1/lib/arm/libmapbox-gl.so
10-06 20:19:44.483 17936-17936/? I/DEBUG:     #05 pc 005ac377  /data/app/com.mapbox.mapboxsdk.testapp-1/lib/arm/libmapbox-gl.so
10-06 20:19:44.483 17936-17936/? I/DEBUG:     #06 pc 005ac305  /data/app/com.mapbox.mapboxsdk.testapp-1/lib/arm/libmapbox-gl.so
10-06 20:19:44.483 17936-17936/? I/DEBUG:     #07 pc 005ac167  /data/app/com.mapbox.mapboxsdk.testapp-1/lib/arm/libmapbox-gl.so
10-06 20:19:44.483 17936-17936/? I/DEBUG:     #08 pc 005ac125  /data/app/com.mapbox.mapboxsdk.testapp-1/lib/arm/libmapbox-gl.so
10-06 20:19:44.483 17936-17936/? I/DEBUG:     #09 pc 005a96fd  /data/app/com.mapbox.mapboxsdk.testapp-1/lib/arm/libmapbox-gl.so
10-06 20:19:44.483 17936-17936/? I/DEBUG:     #10 pc 00608ca1  /data/app/com.mapbox.mapboxsdk.testapp-1/lib/arm/libmapbox-gl.so
10-06 20:19:44.483 17936-17936/? I/DEBUG:     #11 pc 00608cc1  /data/app/com.mapbox.mapboxsdk.testapp-1/lib/arm/libmapbox-gl.so
10-06 20:19:44.484 17936-17936/? I/DEBUG:     #12 pc 0058d441  /data/app/com.mapbox.mapboxsdk.testapp-1/lib/arm/libmapbox-gl.so
10-06 20:19:44.484 17936-17936/? I/DEBUG:     #13 pc 0058d3a9  /data/app/com.mapbox.mapboxsdk.testapp-1/lib/arm/libmapbox-gl.so
10-06 20:19:44.484 17936-17936/? I/DEBUG:     #14 pc 0058d35f  /data/app/com.mapbox.mapboxsdk.testapp-1/lib/arm/libmapbox-gl.so
10-06 20:19:44.484 17936-17936/? I/DEBUG:     #15 pc 0066c93f  /data/app/com.mapbox.mapboxsdk.testapp-1/lib/arm/libmapbox-gl.so
10-06 20:19:44.484 17936-17936/? I/DEBUG:     #16 pc 0066860d  /data/app/com.mapbox.mapboxsdk.testapp-1/lib/arm/libmapbox-gl.so
10-06 20:19:44.484 17936-17936/? I/DEBUG:     #17 pc 0066867d  /data/app/com.mapbox.mapboxsdk.testapp-1/lib/arm/libmapbox-gl.so
10-06 20:19:44.484 17936-17936/? I/DEBUG:     #18 pc 00668635  /data/app/com.mapbox.mapboxsdk.testapp-1/lib/arm/libmapbox-gl.so
10-06 20:19:44.484 17936-17936/? I/DEBUG:     #19 pc 005953bb  /data/app/com.mapbox.mapboxsdk.testapp-1/lib/arm/libmapbox-gl.so
10-06 20:19:44.484 17936-17936/? I/DEBUG:     #20 pc 005953e1  /data/app/com.mapbox.mapboxsdk.testapp-1/lib/arm/libmapbox-gl.so
10-06 20:19:44.484 17936-17936/? I/DEBUG:     #21 pc 0031b951  /data/app/com.mapbox.mapboxsdk.testapp-1/lib/arm/libmapbox-gl.so
10-06 20:19:44.484 17936-17936/? I/DEBUG:     #22 pc 0031b8b5  /data/app/com.mapbox.mapboxsdk.testapp-1/lib/arm/libmapbox-gl.so
10-06 20:19:44.485 17936-17936/? I/DEBUG:     #23 pc 0031b983  /data/app/com.mapbox.mapboxsdk.testapp-1/lib/arm/libmapbox-gl.so
10-06 20:19:44.485 17936-17936/? I/DEBUG:     #24 pc 0030e9c5  /data/app/com.mapbox.mapboxsdk.testapp-1/lib/arm/libmapbox-gl.so
10-06 20:19:44.485 17936-17936/? I/DEBUG:     #25 pc 0030edd1  /data/app/com.mapbox.mapboxsdk.testapp-1/lib/arm/libmapbox-gl.so
10-06 20:19:44.485 17936-17936/? I/DEBUG:     #26 pc 0030f083  /data/app/com.mapbox.mapboxsdk.testapp-1/lib/arm/libmapbox-gl.so
10-06 20:19:44.485 17936-17936/? I/DEBUG:     #27 pc 0030add1  /data/app/com.mapbox.mapboxsdk.testapp-1/lib/arm/libmapbox-gl.so
10-06 20:19:44.485 17936-17936/? I/DEBUG:     #28 pc 000f72c5  /data/app/com.mapbox.mapboxsdk.testapp-1/lib/arm/libmapbox-gl.so
10-06 20:19:44.485 17936-17936/? I/DEBUG:     #29 pc 000f9a47  /data/app/com.mapbox.mapboxsdk.testapp-1/lib/arm/libmapbox-gl.so
10-06 20:19:44.485 17936-17936/? I/DEBUG:     #30 pc 000f99f7  /data/app/com.mapbox.mapboxsdk.testapp-1/lib/arm/libmapbox-gl.so
10-06 20:19:44.485 17936-17936/? I/DEBUG:     #31 pc 002fb30d  /data/app/com.mapbox.mapboxsdk.testapp-1/lib/arm/libmapbox-gl.so
10-06 20:19:44.485 17936-17936/? I/DEBUG:     #32 pc 002fb4e7  /data/app/com.mapbox.mapboxsdk.testapp-1/lib/arm/libmapbox-gl.so
10-06 20:19:44.485 17936-17936/? I/DEBUG:     #33 pc 000fee91  /data/app/com.mapbox.mapboxsdk.testapp-1/lib/arm/libmapbox-gl.so
10-06 20:19:44.486 17936-17936/? I/DEBUG:     #34 pc 001004db  /data/app/com.mapbox.mapboxsdk.testapp-1/lib/arm/libmapbox-gl.so
10-06 20:19:44.486 17936-17936/? I/DEBUG:     #35 pc 00100471  /data/app/com.mapbox.mapboxsdk.testapp-1/lib/arm/libmapbox-gl.so
10-06 20:19:44.486 17936-17936/? I/DEBUG:     #36 pc 00100439  /data/app/com.mapbox.mapboxsdk.testapp-1/lib/arm/libmapbox-gl.so
10-06 20:19:44.486 17936-17936/? I/DEBUG:     #37 pc 00100565  /data/app/com.mapbox.mapboxsdk.testapp-1/lib/arm/libmapbox-gl.so
10-06 20:19:44.486 17936-17936/? I/DEBUG:     #38 pc 00100525  /data/app/com.mapbox.mapboxsdk.testapp-1/lib/arm/libmapbox-gl.so
10-06 20:19:44.486 17936-17936/? I/DEBUG:     #39 pc 00181c03  /data/dalvik-cache/arm/data@app@com.mapbox.mapboxsdk.testapp-1@base.apk@classes.dex
```

### Symbolicated Android crash
```
Crash dump is completed

********** Crash dump: **********
Build fingerprint: 'motorola/victara_reteu/victara:5.0/LXE22.46-19/18:user/release-keys'
pid: 22234, tid: 22354, name: GLThread 7798  >>> com.mapbox.mapboxsdk.testapp <<<
signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0xdeadbaad
Stack frame #00 pc 0002b46c  /system/lib/libc.so (dlfree+1239)
Stack frame #01 pc 00011fcf  /system/lib/libc.so (free+10)
Stack frame #02 pc 00018e53  /data/app/com.mapbox.mapboxsdk.testapp-1/lib/arm/libmapbox-gl.so: Routine std::__ndk1::__deallocate(void*) at /Users/pguardiola/Library/Android/sdk/ndk-bundle/sources/cxx-stl/llvm-libc++/include/new:176
Stack frame #03 pc 005ac419  /data/app/com.mapbox.mapboxsdk.testapp-1/lib/arm/libmapbox-gl.so: Routine ~IndexedSubfeature at /Users/pguardiola/mapbox/mapbox-gl-native/platform/android/MapboxGLAndroidSDK/.externalNativeBuild/cmake/debug/armeabi-v7a/../../../../../../../src/mbgl/geometry/feature_index.hpp:20
Stack frame #04 pc 005ac3f9  /data/app/com.mapbox.mapboxsdk.testapp-1/lib/arm/libmapbox-gl.so: Routine ~__tuple_leaf at /Users/pguardiola/Library/Android/sdk/ndk-bundle/sources/cxx-stl/llvm-libc++/include/tuple:183
Stack frame #05 pc 005ac377  /data/app/com.mapbox.mapboxsdk.testapp-1/lib/arm/libmapbox-gl.so: Routine std::__ndk1::allocator<std::__ndk1::pair<mbgl::IndexedSubfeature, mapbox::geometry::box<short> > >::destroy(std::__ndk1::pair<mbgl::IndexedSubfeature, mapbox::geometry::box<short> >*) at /Users/pguardiola/Library/Android/sdk/ndk-bundle/sources/cxx-stl/llvm-libc++/include/memory:1801
Stack frame #06 pc 005ac305  /data/app/com.mapbox.mapboxsdk.testapp-1/lib/arm/libmapbox-gl.so: Routine ~vector at /Users/pguardiola/Library/Android/sdk/ndk-bundle/sources/cxx-stl/llvm-libc++/include/iterator:1254
Stack frame #07 pc 005ac167  /data/app/com.mapbox.mapboxsdk.testapp-1/lib/arm/libmapbox-gl.so: Routine ~GridIndex at /Users/pguardiola/mapbox/mapbox-gl-native/platform/android/MapboxGLAndroidSDK/.externalNativeBuild/cmake/debug/armeabi-v7a/../../../../../../../src/mbgl/util/grid_index.hpp:13
Stack frame #08 pc 005ac125  /data/app/com.mapbox.mapboxsdk.testapp-1/lib/arm/libmapbox-gl.so: Routine ~FeatureIndex at /Users/pguardiola/mapbox/mapbox-gl-native/platform/android/MapboxGLAndroidSDK/.externalNativeBuild/cmake/debug/armeabi-v7a/../../../../../../../src/mbgl/geometry/feature_index.hpp:29
Stack frame #09 pc 005a96fd  /data/app/com.mapbox.mapboxsdk.testapp-1/lib/arm/libmapbox-gl.so: Routine std::__ndk1::default_delete<mbgl::FeatureIndex>::operator()(mbgl::FeatureIndex*) const at /Users/pguardiola/Library/Android/sdk/ndk-bundle/sources/cxx-stl/llvm-libc++/include/memory:2540
Stack frame #10 pc 00608ca1  /data/app/com.mapbox.mapboxsdk.testapp-1/lib/arm/libmapbox-gl.so: Routine ~VectorTile at /Users/pguardiola/mapbox/mapbox-gl-native/platform/android/MapboxGLAndroidSDK/.externalNativeBuild/cmake/debug/armeabi-v7a/../../../../../../../src/mbgl/tile/vector_tile.hpp:11
Stack frame #11 pc 00608cc1  /data/app/com.mapbox.mapboxsdk.testapp-1/lib/arm/libmapbox-gl.so: Routine ~VectorTile at /Users/pguardiola/mapbox/mapbox-gl-native/platform/android/MapboxGLAndroidSDK/.externalNativeBuild/cmake/debug/armeabi-v7a/../../../../../../../src/mbgl/tile/vector_tile.hpp:11
Stack frame #12 pc 0058d441  /data/app/com.mapbox.mapboxsdk.testapp-1/lib/arm/libmapbox-gl.so: Routine std::__ndk1::default_delete<mbgl::Tile>::operator()(mbgl::Tile*) const at /Users/pguardiola/Library/Android/sdk/ndk-bundle/sources/cxx-stl/llvm-libc++/include/memory:2540
Stack frame #13 pc 0058d3a9  /data/app/com.mapbox.mapboxsdk.testapp-1/lib/arm/libmapbox-gl.so: Routine void std::__ndk1::allocator_traits<std::__ndk1::allocator<std::__ndk1::__tree_node<std::__ndk1::__value_type<mbgl::OverscaledTileID, std::__ndk1::unique_ptr<mbgl::Tile, std::__ndk1::default_delete<mbgl::Tile> > >, void*> > >::__destroy<std::__ndk1::pair<mbgl::OverscaledTileID const, std::__ndk1::unique_ptr<mbgl::Tile, std::__ndk1::default_delete<mbgl::Tile> > > >(std::__ndk1::integral_constant<bool, false>, std::__ndk1::allocator<std::__ndk1::__tree_node<std::__ndk1::__value_type<mbgl::OverscaledTileID, std::__ndk1::unique_ptr<mbgl::Tile, std::__ndk1::default_delete<mbgl::Tile> > >, void*> >&, std::__ndk1::pair<mbgl::OverscaledTileID const, std::__ndk1::unique_ptr<mbgl::Tile, std::__ndk1::default_delete<mbgl::Tile> > >*) at /Users/pguardiola/Library/Android/sdk/ndk-bundle/sources/cxx-stl/llvm-libc++/include/memory:1674
Stack frame #14 pc 0058d35f  /data/app/com.mapbox.mapboxsdk.testapp-1/lib/arm/libmapbox-gl.so: Routine std::__ndk1::__tree<std::__ndk1::__value_type<mbgl::OverscaledTileID, std::__ndk1::unique_ptr<mbgl::Tile, std::__ndk1::default_delete<mbgl::Tile> > >, std::__ndk1::__map_value_compare<mbgl::OverscaledTileID, std::__ndk1::__value_type<mbgl::OverscaledTileID, std::__ndk1::unique_ptr<mbgl::Tile, std::__ndk1::default_delete<mbgl::Tile> > >, std::__ndk1::less<mbgl::OverscaledTileID>, true>, std::__ndk1::allocator<std::__ndk1::__value_type<mbgl::OverscaledTileID, std::__ndk1::unique_ptr<mbgl::Tile, std::__ndk1::default_delete<mbgl::Tile> > > > >::destroy(std::__ndk1::__tree_node<std::__ndk1::__value_type<mbgl::OverscaledTileID, std::__ndk1::unique_ptr<mbgl::Tile, std::__ndk1::default_delete<mbgl::Tile> > >, void*>*) at /Users/pguardiola/Library/Android/sdk/ndk-bundle/sources/cxx-stl/llvm-libc++/include/__tree:1726
Stack frame #15 pc 0066c93f  /data/app/com.mapbox.mapboxsdk.testapp-1/lib/arm/libmapbox-gl.so: Routine ~__tree at /Users/pguardiola/Library/Android/sdk/ndk-bundle/sources/cxx-stl/llvm-libc++/include/__tree:1716
Stack frame #16 pc 0066860d  /data/app/com.mapbox.mapboxsdk.testapp-1/lib/arm/libmapbox-gl.so: Routine ~map at /Users/pguardiola/Library/Android/sdk/ndk-bundle/sources/cxx-stl/llvm-libc++/include/map:807
Stack frame #17 pc 0066867d  /data/app/com.mapbox.mapboxsdk.testapp-1/lib/arm/libmapbox-gl.so: Routine ~TileCache at /Users/pguardiola/mapbox/mapbox-gl-native/platform/android/MapboxGLAndroidSDK/.externalNativeBuild/cmake/debug/armeabi-v7a/../../../../../../../src/mbgl/tile/tile_cache.hpp:13
Stack frame #18 pc 00668635  /data/app/com.mapbox.mapboxsdk.testapp-1/lib/arm/libmapbox-gl.so: Routine ~TilePyramid at /Users/pguardiola/mapbox/mapbox-gl-native/src/mbgl/renderer/tile_pyramid.cpp:30
Stack frame #19 pc 005953bb  /data/app/com.mapbox.mapboxsdk.testapp-1/lib/arm/libmapbox-gl.so: Routine ~RenderVectorSource at /Users/pguardiola/mapbox/mapbox-gl-native/platform/android/MapboxGLAndroidSDK/.externalNativeBuild/cmake/debug/armeabi-v7a/../../../../../../../src/mbgl/renderer/sources/render_vector_source.hpp:9
Stack frame #20 pc 005953e1  /data/app/com.mapbox.mapboxsdk.testapp-1/lib/arm/libmapbox-gl.so: Routine ~RenderVectorSource at /Users/pguardiola/mapbox/mapbox-gl-native/platform/android/MapboxGLAndroidSDK/.externalNativeBuild/cmake/debug/armeabi-v7a/../../../../../../../src/mbgl/renderer/sources/render_vector_source.hpp:9
Stack frame #21 pc 0031b951  /data/app/com.mapbox.mapboxsdk.testapp-1/lib/arm/libmapbox-gl.so: Routine std::__ndk1::default_delete<mbgl::RenderSource>::operator()(mbgl::RenderSource*) const at /Users/pguardiola/Library/Android/sdk/ndk-bundle/sources/cxx-stl/llvm-libc++/include/memory:2540
Stack frame #22 pc 0031b8b5  /data/app/com.mapbox.mapboxsdk.testapp-1/lib/arm/libmapbox-gl.so: Routine void std::__ndk1::allocator_traits<std::__ndk1::allocator<std::__ndk1::__hash_node<std::__ndk1::__hash_value_type<std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> >, std::__ndk1::unique_ptr<mbgl::RenderSource, std::__ndk1::default_delete<mbgl::RenderSource> > >, void*> > >::__destroy<std::__ndk1::pair<std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> > const, std::__ndk1::unique_ptr<mbgl::RenderSource, std::__ndk1::default_delete<mbgl::RenderSource> > > >(std::__ndk1::integral_constant<bool, false>, std::__ndk1::allocator<std::__ndk1::__hash_node<std::__ndk1::__hash_value_type<std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> >, std::__ndk1::unique_ptr<mbgl::RenderSource, std::__ndk1::default_delete<mbgl::RenderSource> > >, void*> >&, std::__ndk1::pair<std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> > const, std::__ndk1::unique_ptr<mbgl::RenderSource, std::__ndk1::default_delete<mbgl::RenderSource> > >*) at /Users/pguardiola/Library/Android/sdk/ndk-bundle/sources/cxx-stl/llvm-libc++/include/memory:1674
Stack frame #23 pc 0031b983  /data/app/com.mapbox.mapboxsdk.testapp-1/lib/arm/libmapbox-gl.so: Routine ~__hash_table at /Users/pguardiola/Library/Android/sdk/ndk-bundle/sources/cxx-stl/llvm-libc++/include/__hash_table:1480
Stack frame #24 pc 0030e9c5  /data/app/com.mapbox.mapboxsdk.testapp-1/lib/arm/libmapbox-gl.so: Routine ~unordered_map at /Users/pguardiola/Library/Android/sdk/ndk-bundle/sources/cxx-stl/llvm-libc++/include/__hash_table:1354
Stack frame #25 pc 0030edd1  /data/app/com.mapbox.mapboxsdk.testapp-1/lib/arm/libmapbox-gl.so: Routine ~Impl at /Users/pguardiola/mapbox/mapbox-gl-native/src/mbgl/renderer/renderer_impl.cpp:76
Stack frame #26 pc 0030f083  /data/app/com.mapbox.mapboxsdk.testapp-1/lib/arm/libmapbox-gl.so: Routine ~Impl at /Users/pguardiola/mapbox/mapbox-gl-native/src/mbgl/renderer/renderer_impl.cpp:63
Stack frame #27 pc 0030add1  /data/app/com.mapbox.mapboxsdk.testapp-1/lib/arm/libmapbox-gl.so: Routine std::__ndk1::default_delete<mbgl::Renderer::Impl>::operator()(mbgl::Renderer::Impl*) const at /Users/pguardiola/Library/Android/sdk/ndk-bundle/sources/cxx-stl/llvm-libc++/include/memory:2540
Stack frame #28 pc 000f72c5  /data/app/com.mapbox.mapboxsdk.testapp-1/lib/arm/libmapbox-gl.so: Routine std::__ndk1::default_delete<mbgl::Renderer>::operator()(mbgl::Renderer*) const at /Users/pguardiola/Library/Android/sdk/ndk-bundle/sources/cxx-stl/llvm-libc++/include/memory:2540
Stack frame #29 pc 000f9a47  /data/app/com.mapbox.mapboxsdk.testapp-1/lib/arm/libmapbox-gl.so: Routine void mbgl::AskMessageImpl<void, mbgl::android::MapRenderer, void (mbgl::android::MapRenderer::*)(), std::__ndk1::tuple<> >::ask<>(std::__ndk1::integer_sequence<unsigned int>) at /Users/pguardiola/mapbox/mapbox-gl-native/platform/android/MapboxGLAndroidSDK/.externalNativeBuild/cmake/debug/armeabi-v7a/../../../../../../../include/mbgl/actor/message.hpp:84
Stack frame #30 pc 000f99f7  /data/app/com.mapbox.mapboxsdk.testapp-1/lib/arm/libmapbox-gl.so: Routine mbgl::AskMessageImpl<void, mbgl::android::MapRenderer, void (mbgl::android::MapRenderer::*)(), std::__ndk1::tuple<> >::operator()() at /Users/pguardiola/mapbox/mapbox-gl-native/platform/android/MapboxGLAndroidSDK/.externalNativeBuild/cmake/debug/armeabi-v7a/../../../../../../../include/mbgl/actor/message.hpp:78
Stack frame #31 pc 002fb30d  /data/app/com.mapbox.mapboxsdk.testapp-1/lib/arm/libmapbox-gl.so: Routine mbgl::Mailbox::receive() at /Users/pguardiola/mapbox/mapbox-gl-native/src/mbgl/actor/mailbox.cpp:58
Stack frame #32 pc 002fb4e7  /data/app/com.mapbox.mapboxsdk.testapp-1/lib/arm/libmapbox-gl.so: Routine mbgl::Mailbox::maybeReceive(std::__ndk1::weak_ptr<mbgl::Mailbox>) at /Users/pguardiola/mapbox/mapbox-gl-native/src/mbgl/actor/mailbox.cpp:67
Stack frame #33 pc 000fee91  /data/app/com.mapbox.mapboxsdk.testapp-1/lib/arm/libmapbox-gl.so: Routine mbgl::android::MapRendererRunnable::run(_JNIEnv&) at /Users/pguardiola/mapbox/mapbox-gl-native/platform/android/src/map_renderer_runnable.cpp:21
Stack frame #34 pc 001004db  /data/app/com.mapbox.mapboxsdk.testapp-1/lib/arm/libmapbox-gl.so: Routine operator() at /Users/pguardiola/mapbox/mapbox-gl-native/platform/android/MapboxGLAndroidSDK/.externalNativeBuild/cmake/debug/armeabi-v7a/../../../../../../../mason_packages/headers/jni.hpp/3.0.0/include/jni/native_method.hpp:245
Stack frame #35 pc 00100471  /data/app/com.mapbox.mapboxsdk.testapp-1/lib/arm/libmapbox-gl.so: Routine operator() at /Users/pguardiola/mapbox/mapbox-gl-native/platform/android/MapboxGLAndroidSDK/.externalNativeBuild/cmake/debug/armeabi-v7a/../../../../../../../mason_packages/headers/jni.hpp/3.0.0/include/jni/native_method.hpp:112
Stack frame #36 pc 00100439  /data/app/com.mapbox.mapboxsdk.testapp-1/lib/arm/libmapbox-gl.so: Routine __invoke at /Users/pguardiola/mapbox/mapbox-gl-native/platform/android/MapboxGLAndroidSDK/.externalNativeBuild/cmake/debug/armeabi-v7a/../../../../../../../mason_packages/headers/jni.hpp/3.0.0/include/jni/native_method.hpp:110
Stack frame #37 pc 00100565  /data/app/com.mapbox.mapboxsdk.testapp-1/lib/arm/libmapbox-gl.so: Routine operator()<jni::jobject *> at /Users/pguardiola/mapbox/mapbox-gl-native/platform/android/MapboxGLAndroidSDK/.externalNativeBuild/cmake/debug/armeabi-v7a/../../../../../../../mason_packages/headers/jni.hpp/3.0.0/include/jni/native_method.hpp:59
Stack frame #38 pc 00100525  /data/app/com.mapbox.mapboxsdk.testapp-1/lib/arm/libmapbox-gl.so: Routine __invoke<jni::jobject *> at /Users/pguardiola/mapbox/mapbox-gl-native/platform/android/MapboxGLAndroidSDK/.externalNativeBuild/cmake/debug/armeabi-v7a/../../../../../../../mason_packages/headers/jni.hpp/3.0.0/include/jni/native_method.hpp:55
Stack frame #39 pc 00181c03  /data/dalvik-cache/arm/data@app@com.mapbox.mapboxsdk.testapp-1@base.apk@classes.dex
```

👀 @tobrun @ivovandongen

### LINKED ISSUE #10152: [android] Crash when testing custom layer example
**Platform:** Android 5.0 Moto X (2nd gen)
**Mapbox SDK version:** `release-agua` branch

### Steps to trigger behavior

 1. Custom Layer
 2. Update layer (invalidate) a couple of times
 3. App crashes

### Logcat
```
--------- beginning of crash
10-06 20:34:40.909 28668-28880/com.mapbox.mapboxsdk.testapp A/libc: Fatal signal 11 (SIGSEGV), code 1, fault addr 0x15 in tid 28880 (GLThread 7823)
10-06 20:34:40.992 28668-28954/com.mapbox.mapboxsdk.testapp V/HTTPRequest: [HTTP] Request was successful (code = 200).
10-06 20:34:41.011 17936-17936/? I/DEBUG: *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
10-06 20:34:41.011 17936-17936/? I/DEBUG: Build fingerprint: 'motorola/victara_reteu/victara:5.0/LXE22.46-19/18:user/release-keys'
10-06 20:34:41.011 17936-17936/? I/DEBUG: Revision: 'p2bf'
10-06 20:34:41.011 17936-17936/? I/DEBUG: ABI: 'arm'
10-06 20:34:41.011 17936-17936/? I/DEBUG: pid: 28668, tid: 28880, name: GLThread 7823  >>> com.mapbox.mapboxsdk.testapp <<<
10-06 20:34:41.011 17936-17936/? I/DEBUG: signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x15
10-06 20:34:41.028 17936-17936/? I/DEBUG:     r0 00000011  r1 b949d280  r2 b949d280  r3 00000011
10-06 20:34:41.028 17936-17936/? I/DEBUG:     r4 00000000  r5 00000207  r6 b949d280  r7 a07078b8
10-06 20:34:41.028 17936-17936/? I/DEBUG:     r8 a590e16c  r9 a590e174  sl bb49184c  fp bb491880
10-06 20:34:41.028 17936-17936/? I/DEBUG:     ip 00000015  sp a07076a8  lr a55eb85b  pc a53b7bbc  cpsr 000b0030
10-06 20:34:41.028 17936-17936/? I/DEBUG: backtrace:
10-06 20:34:41.028 17936-17936/? I/DEBUG:     #00 pc 00336bbc  /data/app/com.mapbox.mapboxsdk.testapp-1/lib/arm/libmapbox-gl.so
10-06 20:34:41.028 17936-17936/? I/DEBUG:     #01 pc 0056a857  /data/app/com.mapbox.mapboxsdk.testapp-1/lib/arm/libmapbox-gl.so
10-06 20:34:41.028 17936-17936/? I/DEBUG:     #02 pc 00569a5b  /data/app/com.mapbox.mapboxsdk.testapp-1/lib/arm/libmapbox-gl.so
10-06 20:34:41.028 17936-17936/? I/DEBUG:     #03 pc 00316a63  /data/app/com.mapbox.mapboxsdk.testapp-1/lib/arm/libmapbox-gl.so
10-06 20:34:41.028 17936-17936/? I/DEBUG:     #04 pc 0030af51  /data/app/com.mapbox.mapboxsdk.testapp-1/lib/arm/libmapbox-gl.so
10-06 20:34:41.029 17936-17936/? I/DEBUG:     #05 pc 000f847b  /data/app/com.mapbox.mapboxsdk.testapp-1/lib/arm/libmapbox-gl.so
10-06 20:34:41.029 17936-17936/? I/DEBUG:     #06 pc 000fdd6f  /data/app/com.mapbox.mapboxsdk.testapp-1/lib/arm/libmapbox-gl.so
10-06 20:34:41.029 17936-17936/? I/DEBUG:     #07 pc 000fdd05  /data/app/com.mapbox.mapboxsdk.testapp-1/lib/arm/libmapbox-gl.so
10-06 20:34:41.029 17936-17936/? I/DEBUG:     #08 pc 000fdccd  /data/app/com.mapbox.mapboxsdk.testapp-1/lib/arm/libmapbox-gl.so
10-06 20:34:41.029 17936-17936/? I/DEBUG:     #09 pc 000fddf9  /data/app/com.mapbox.mapboxsdk.testapp-1/lib/arm/libmapbox-gl.so
10-06 20:34:41.029 17936-17936/? I/DEBUG:     #10 pc 000fddb9  /data/app/com.mapbox.mapboxsdk.testapp-1/lib/arm/libmapbox-gl.so
10-06 20:34:41.029 17936-17936/? I/DEBUG:     #11 pc 00181c03  /data/dalvik-cache/arm/data@app@com.mapbox.mapboxsdk.testapp-1@base.apk@classes.dex
```

### Symbolicated Android crash
```
Crash dump is completed

********** Crash dump: **********
Build fingerprint: 'motorola/victara_reteu/victara:5.0/LXE22.46-19/18:user/release-keys'
pid: 28668, tid: 28880, name: GLThread 7823  >>> com.mapbox.mapboxsdk.testapp <<<
signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x15
Stack frame #00 pc 00336bbc  /data/app/com.mapbox.mapboxsdk.testapp-1/lib/arm/libmapbox-gl.so: Routine std::__ndk1::__tree<std::__ndk1::__value_type<std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> >, mbgl::gl::VertexArray>, std::__ndk1::__map_value_compare<std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> >, std::__ndk1::__value_type<std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> >, mbgl::gl::VertexArray>, std::__ndk1::less<std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> > >, true>, std::__ndk1::allocator<std::__ndk1::__value_type<std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> >, mbgl::gl::VertexArray> > >::__root() const at /Users/pguardiola/Library/Android/sdk/ndk-bundle/sources/cxx-stl/llvm-libc++/include/__tree:1009
Stack frame #01 pc 0056a857  /data/app/com.mapbox.mapboxsdk.testapp-1/lib/arm/libmapbox-gl.so: Routine std::__ndk1::map<std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> >, mbgl::gl::VertexArray, std::__ndk1::less<std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> > >, std::__ndk1::allocator<std::__ndk1::pair<std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> > const, mbgl::gl::VertexArray> > >::find(std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> > const&) at /Users/pguardiola/Library/Android/sdk/ndk-bundle/sources/cxx-stl/llvm-libc++/include/map:1220
Stack frame #02 pc 00569a5b  /data/app/com.mapbox.mapboxsdk.testapp-1/lib/arm/libmapbox-gl.so: Routine mbgl::RenderSymbolLayer::render(mbgl::PaintParameters&, mbgl::RenderSource*) at /Users/pguardiola/mapbox/mapbox-gl-native/src/mbgl/renderer/layers/render_symbol_layer.cpp:232
Stack frame #03 pc 00316a63  /data/app/com.mapbox.mapboxsdk.testapp-1/lib/arm/libmapbox-gl.so: Routine mbgl::Renderer::Impl::render(mbgl::UpdateParameters const&) at /Users/pguardiola/mapbox/mapbox-gl-native/src/mbgl/renderer/renderer_impl.cpp:538
Stack frame #04 pc 0030af51  /data/app/com.mapbox.mapboxsdk.testapp-1/lib/arm/libmapbox-gl.so: Routine mbgl::Renderer::render(mbgl::UpdateParameters const&) at /Users/pguardiola/mapbox/mapbox-gl-native/src/mbgl/renderer/renderer.cpp:32
Stack frame #05 pc 000f847b  /data/app/com.mapbox.mapboxsdk.testapp-1/lib/arm/libmapbox-gl.so: Routine mbgl::android::MapRenderer::render(_JNIEnv&) at /Users/pguardiola/mapbox/mapbox-gl-native/platform/android/src/map_renderer.cpp:130
Stack frame #06 pc 000fdd6f  /data/app/com.mapbox.mapboxsdk.testapp-1/lib/arm/libmapbox-gl.so: Routine operator() at /Users/pguardiola/mapbox/mapbox-gl-native/platform/android/MapboxGLAndroidSDK/.externalNativeBuild/cmake/debug/armeabi-v7a/../../../../../../../mason_packages/headers/jni.hpp/3.0.0/include/jni/native_method.hpp:245
Stack frame #07 pc 000fdd05  /data/app/com.mapbox.mapboxsdk.testapp-1/lib/arm/libmapbox-gl.so: Routine operator() at /Users/pguardiola/mapbox/mapbox-gl-native/platform/android/MapboxGLAndroidSDK/.externalNativeBuild/cmake/debug/armeabi-v7a/../../../../../../../mason_packages/headers/jni.hpp/3.0.0/include/jni/native_method.hpp:112
Stack frame #08 pc 000fdccd  /data/app/com.mapbox.mapboxsdk.testapp-1/lib/arm/libmapbox-gl.so: Routine __invoke at /Users/pguardiola/mapbox/mapbox-gl-native/platform/android/MapboxGLAndroidSDK/.externalNativeBuild/cmake/debug/armeabi-v7a/../../../../../../../mason_packages/headers/jni.hpp/3.0.0/include/jni/native_method.hpp:110
Stack frame #09 pc 000fddf9  /data/app/com.mapbox.mapboxsdk.testapp-1/lib/arm/libmapbox-gl.so: Routine operator()<jni::jobject *> at /Users/pguardiola/mapbox/mapbox-gl-native/platform/android/MapboxGLAndroidSDK/.externalNativeBuild/cmake/debug/armeabi-v7a/../../../../../../../mason_packages/headers/jni.hpp/3.0.0/include/jni/native_method.hpp:59
Stack frame #10 pc 000fddb9  /data/app/com.mapbox.mapboxsdk.testapp-1/lib/arm/libmapbox-gl.so: Routine __invoke<jni::jobject *> at /Users/pguardiola/mapbox/mapbox-gl-native/platform/android/MapboxGLAndroidSDK/.externalNativeBuild/cmake/debug/armeabi-v7a/../../../../../../../mason_packages/headers/jni.hpp/3.0.0/include/jni/native_method.hpp:55
Stack frame #11 pc 00181c03  /data/dalvik-cache/arm/data@app@com.mapbox.mapboxsdk.testapp-1@base.apk@classes.dex
```

👀 @tobrun @ivovandongen

### PR DESCRIPTION
**Pull request by ivovandongen**
Changes in the way we use vertex buffers introduced in #9009 causes crashes on usage of glBuffer(Sub)Data. This affects line placed text.

Relevant issues:
- Fixes #10152
- Fixes #10151
- Fixes #10150
- Fixes #9935

closes #10233

### CODE REVIEW

File: src/mbgl/gl/context.cpp [hunk 1]
```diff
@@ -248,10 +248,16 @@ UniqueTexture Context::createTexture() {
 }
 
 bool Context::supportsVertexArrays() const {
-    return vertexArray &&
-           vertexArray->genVertexArrays &&
-           vertexArray->bindVertexArray &&
-           vertexArray->deleteVertexArrays;
+    // Blacklist Adreno 3xx as it crashes on glBuffer(Sub)Data
+    const std::string renderer = reinterpret_cast<const char*>(glGetString(GL_RENDERER));
+    if (renderer.find("Adreno (TM) 3") != std::string::npos) {
```
Comment (asheemmamoowala) [inline src/mbgl/gl/context.cpp]: Can you make part of this check static? Its called on every every call to `Context::createVertexArray()`

**Comment by tobrun** [comment]
Tested with:

LG G Pad 8.3 | Adreno 320 :white_check_mark: 
LG Nexus 5 | Adreno 330  :white_check_mark: 
Nexus 6P | Adreno 430  :white_check_mark: 
Wiko U Feel Prime | Adreno 505  :white_check_mark: 
Pixel | Adreno 530  :white_check_mark: 
Kazam Trooper | Mali-400  :white_check_mark: 
Samsung J3 | Mali-400  :white_check_mark: 
Moto C Plus | Mali-T720  :white_check_mark:

**Comment by Guardiola31337** [comment]
Android 5.0 Moto X (2nd gen) | Adreno 330

#10151 

```
10-23 11:12:38.260 377-377/? I/DEBUG: *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
10-23 11:12:38.260 377-377/? I/DEBUG: Build fingerprint: 'motorola/victara_reteu/victara:5.0/LXE22.46-19/18:user/release-keys'
10-23 11:12:38.260 377-377/? I/DEBUG: Revision: 'p2bf'
10-23 11:12:38.260 377-377/? I/DEBUG: ABI: 'arm'
10-23 11:12:38.260 377-377/? I/DEBUG: pid: 22231, tid: 22344, name: Thread-3028  >>> com.mapbox.mapboxsdk.testapp <<<
10-23 11:12:38.260 377-377/? I/DEBUG: signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x5e936121
10-23 11:12:38.280 377-377/? I/DEBUG:     r0 b92f23d8  r1 b92f23d8  r2 a5643d49  r3 a5643d49
10-23 11:12:38.280 377-377/? I/DEBUG:     r4 b7916560  r5 b79165a0  r6 b7916560  r7 a0b6b8c0
10-23 11:12:38.280 377-377/? I/DEBUG:     r8 b7916568  r9 b7916568  sl b6ec9e4d  fp a0b6bdd0
10-23 11:12:38.280 377-377/? I/DEBUG:     ip 00000001  sp a0b6b7a0  lr a560a2b5  pc a560a2f0  cpsr 200f0030
10-23 11:12:38.281 377-377/? I/DEBUG: backtrace:
10-23 11:12:38.281 377-377/? I/DEBUG:     #00 pc 005ae2f0  /data/app/com.mapbox.mapboxsdk.testapp-1/lib/arm/libmapbox-gl.so
10-23 11:12:38.281 377-377/? I/DEBUG:     #01 pc 005ae2b1  /data/app/com.mapbox.mapboxsdk.testapp-1/lib/arm/libmapbox-gl.so
10-23 11:12:38.281 377-377/? I/DEBUG:     #02 pc 002fbc65  /data/app/com.mapbox.mapboxsdk.testapp-1/lib/arm/libmapbox-gl.so
10-23 11:12:38.281 377-377/? I/DEBUG:     #03 pc 002fbe3f  /data/app/com.mapbox.mapboxsdk.testapp-1/lib/arm/libmapbox-gl.so
10-23 11:12:38.281 377-377/? I/DEBUG:     #04 pc 0047c6c3  /data/app/com.mapbox.mapboxsdk.testapp-1/lib/arm/libmapbox-gl.so
10-23 11:12:38.281 377-377/? I/DEBUG:     #05 pc 0047c313  /data/app/com.mapbox.mapboxsdk.testapp-1/lib/arm/libmapbox-gl.so
10-23 11:12:38.281 377-377/? I/DEBUG:     #06 pc 00015e6b  /system/lib/libc.so (__pthread_start(void*)+30)
10-23 11:12:38.281 377-377/? I/DEBUG:     #07 pc 00013e3f  /system/lib/libc.so (__start_thread+6)
```
```
********** Crash dump: **********
Build fingerprint: 'motorola/victara_reteu/victara:5.0/LXE22.46-19/18:user/release-keys'
pid: 22231, tid: 22344, name: Thread-3028  >>> com.mapbox.mapboxsdk.testapp <<<
signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x5e936121
Stack frame #00 pc 005ae2f0  /data/app/com.mapbox.mapboxsdk.testapp-1/lib/arm/libmapbox-gl.so: Routine void mbgl::MessageImpl<mbgl::GeometryTileWorker, void (mbgl::GeometryTileWorker::*)(std::__ndk1::unique_ptr<mbgl::GeometryTileData const, std::__ndk1::default_delete<mbgl::GeometryTileData const> >, unsigned long long), std::__ndk1::tuple<std::__ndk1::unique_ptr<mbgl::GeometryTileData const, std::__ndk1::default_delete<mbgl::GeometryTileData const> >, unsigned long long> >::invoke<0u, 1u>(std::__ndk1::integer_sequence<unsigned int, 0u, 1u>) at /Users/pguardiola/mapbox/mapbox-gl-native/platform/android/MapboxGLAndroidSDK/.externalNativeBuild/cmake/debug/armeabi-v7a/../../../../../../../include/mbgl/actor/message.hpp:34
Stack frame #01 pc 005ae2b1  /data/app/com.mapbox.mapboxsdk.testapp-1/lib/arm/libmapbox-gl.so: Routine mbgl::MessageImpl<mbgl::GeometryTileWorker, void (mbgl::GeometryTileWorker::*)(std::__ndk1::unique_ptr<mbgl::GeometryTileData const, std::__ndk1::default_delete<mbgl::GeometryTileData const> >, unsigned long long), std::__ndk1::tuple<std::__ndk1::unique_ptr<mbgl::GeometryTileData const, std::__ndk1::default_delete<mbgl::GeometryTileData const> >, unsigned long long> >::operator()() at /Users/pguardiola/mapbox/mapbox-gl-native/platform/android/MapboxGLAndroidSDK/.externalNativeBuild/cmake/debug/armeabi-v7a/../../../../../../../include/mbgl/actor/message.hpp:29
Stack frame #02 pc 002fbc65  /data/app/com.mapbox.mapboxsdk.testapp-1/lib/arm/libmapbox-gl.so: Routine mbgl::Mailbox::receive() at /Users/pguardiola/mapbox/mapbox-gl-native/src/mbgl/actor/mailbox.cpp:58
Stack frame #03 pc 002fbe3f  /data/app/com.mapbox.mapboxsdk.testapp-1/lib/arm/libmapbox-gl.so: Routine mbgl::Mailbox::maybeReceive(std::__ndk1::weak_ptr<mbgl::Mailbox>) at /Users/pguardiola/mapbox/mapbox-gl-native/src/mbgl/actor/mailbox.cpp:67
Stack frame #04 pc 0047c6c3  /data/app/com.mapbox.mapboxsdk.testapp-1/lib/arm/libmapbox-gl.so: Routine operator() at /Users/pguardiola/mapbox/mapbox-gl-native/platform/default/mbgl/util/default_thread_pool.cpp:29
Stack frame #05 pc 0047c313  /data/app/com.mapbox.mapboxsdk.testapp-1/lib/arm/libmapbox-gl.so: Routine _ZNSt6__ndk18__invokeIZN4mbgl10ThreadPoolC1EjE3$_0JEEEDTclclsr3std6__ndk1E7forwardIT_Efp_Espclsr3std6__ndk1E7forwardIT0_Efp0_EEEOS4_DpOS5_ at /Users/pguardiola/Library/Android/sdk/ndk-bundle/sources/cxx-stl/llvm-libc++/include/type_traits:4287
Stack frame #06 pc 00015e6b  /system/lib/libc.so (__pthread_start(void*)+30)
Stack frame #07 pc 00013e3f  /system/lib/libc.so (__start_thread+6)
```

#10150 

```
10-23 11:16:09.206 377-377/? I/DEBUG: *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
10-23 11:16:09.206 377-377/? I/DEBUG: Build fingerprint: 'motorola/victara_reteu/victara:5.0/LXE22.46-19/18:user/release-keys'
10-23 11:16:09.206 377-377/? I/DEBUG: Revision: 'p2bf'
10-23 11:16:09.206 377-377/? I/DEBUG: ABI: 'arm'
10-23 11:16:09.207 377-377/? I/DEBUG: pid: 22710, tid: 25668, name: GLThread 5780  >>> com.mapbox.mapboxsdk.testapp <<<
10-23 11:16:09.207 377-377/? I/DEBUG: signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0xdeadbaad
10-23 11:16:09.250 377-377/? I/DEBUG: Abort message: 'invalid address or address of corrupt block 0xb81328a0 passed to dlfree'
10-23 11:16:09.250 377-377/? I/DEBUG:     r0 00000000  r1 a1a77b70  r2 deadbaad  r3 00000000
10-23 11:16:09.250 377-377/? I/DEBUG:     r4 b81328a0  r5 b6f100f4  r6 9a379000  r7 b81328a8
10-23 11:16:09.250 377-377/? I/DEBUG:     r8 70785910  r9 b7951288  sl 00000000  fp 12f66720
10-23 11:16:09.250 377-377/? I/DEBUG:     ip b6f0a69c  sp a1a77f60  lr b6edf46b  pc b6edf46c  cpsr 600f0030
10-23 11:16:09.251 377-377/? I/DEBUG: backtrace:
10-23 11:16:09.251 377-377/? I/DEBUG:     #00 pc 0002b46c  /system/lib/libc.so (dlfree+1239)
10-23 11:16:09.251 377-377/? I/DEBUG:     #01 pc 00011fcf  /system/lib/libc.so (free+10)
10-23 11:16:09.251 377-377/? I/DEBUG:     #02 pc 001edbd9  /data/app/com.mapbox.mapboxsdk.testapp-1/lib/arm/libmapbox-gl.so
10-23 11:16:09.251 377-377/? I/DEBUG:     #03 pc 001f02ab  /data/app/com.mapbox.mapboxsdk.testapp-1/lib/arm/libmapbox-gl.so
10-23 11:16:09.251 377-377/? I/DEBUG:     #04 pc 0068d0a9  /data/app/com.mapbox.mapboxsdk.testapp-1/lib/arm/libmapbox-gl.so
10-23 11:16:09.251 377-377/? I/DEBUG:     #05 pc 0068d06b  /data/app/com.mapbox.mapboxsdk.testapp-1/lib/arm/libmapbox-gl.so
10-23 11:16:09.251 377-377/? I/DEBUG:     #06 pc 0068d051  /data/app/com.mapbox.mapboxsdk.testapp-1/lib/arm/libmapbox-gl.so
10-23 11:16:09.252 377-377/? I/DEBUG:     #07 pc 0068d037  /data/app/com.mapbox.mapboxsdk.testapp-1/lib/arm/libmapbox-gl.so
10-23 11:16:09.252 377-377/? I/DEBUG:     #08 pc 0068d01d  /data/app/com.mapbox.mapboxsdk.testapp-1/lib/arm/libmapbox-gl.so
10-23 11:16:09.252 377-377/? I/DEBUG:     #09 pc 0068cff1  /data/app/com.mapbox.mapboxsdk.testapp-1/lib/arm/libmapbox-gl.so
10-23 11:16:09.252 377-377/? I/DEBUG:     #10 pc 0068cfad  /data/app/com.mapbox.mapboxsdk.testapp-1/lib/arm/libmapbox-gl.so
10-23 11:16:09.252 377-377/? I/DEBUG:     #11 pc 0068cf2b  /data/app/com.mapbox.mapboxsdk.testapp-1/lib/arm/libmapbox-gl.so
10-23 11:16:09.252 377-377/? I/DEBUG:     #12 pc 0068c157  /data/app/com.mapbox.mapboxsdk.testapp-1/lib/arm/libmapbox-gl.so
10-23 11:16:09.252 377-377/? I/DEBUG:     #13 pc 0068c9d3  /data/app/com.mapbox.mapboxsdk.testapp-1/lib/arm/libmapbox-gl.so
10-23 11:16:09.252 377-377/? I/DEBUG:     #14 pc 0068ca01  /data/app/com.mapbox.mapboxsdk.testapp-1/lib/arm/libmapbox-gl.so
10-23 11:16:09.252 377-377/? I/DEBUG:     #15 pc 001e6ab7  /data/app/com.mapbox.mapboxsdk.testapp-1/lib/arm/libmapbox-gl.so
10-23 11:16:09.252 377-377/? I/DEBUG:     #16 pc 006d3aff  /data/app/com.mapbox.mapboxsdk.testapp-1/lib/arm/libmapbox-gl.so
10-23 11:16:09.253 377-377/? I/DEBUG:     #17 pc 000bc0f7  /data/app/com.mapbox.mapboxsdk.testapp-1/lib/arm/libmapbox-gl.so
10-23 11:16:09.253 377-377/? I/DEBUG:     #18 pc 004b2e2d  /data/app/com.mapbox.mapboxsdk.testapp-1/lib/arm/libmapbox-gl.so
10-23 11:16:09.253 377-377/? I/DEBUG:     #19 pc 005ad9a1  /data/app/com.mapbox.mapboxsdk.testapp-1/lib/arm/libmapbox-gl.so
10-23 11:16:09.253 377-377/? I/DEBUG:     #20 pc 005af35d  /data/app/com.mapbox.mapboxsdk.testapp-1/lib/arm/libmapbox-gl.so
10-23 11:16:09.253 377-377/? I/DEBUG:     #21 pc 005af029  /data/app/com.mapbox.mapboxsdk.testapp-1/lib/arm/libmapbox-gl.so
10-23 11:16:09.253 377-377/? I/DEBUG:     #22 pc 005ac393  /data/app/com.mapbox.mapboxsdk.testapp-1/lib/arm/libmapbox-gl.so
10-23 11:16:09.253 377-377/? I/DEBUG:     #23 pc 00603c67  /data/app/com.mapbox.mapboxsdk.testapp-1/lib/arm/libmapbox-gl.so
10-23 11:16:09.253 377-377/? I/DEBUG:     #24 pc 00603bdd  /data/app/com.mapbox.mapboxsdk.testapp-1/lib/arm/libmapbox-gl.so
10-23 11:16:09.253 377-377/? I/DEBUG:     #25 pc 002fbc65  /data/app/com.mapbox.mapboxsdk.testapp-1/lib/arm/libmapbox-gl.so
10-23 11:16:09.253 377-377/? I/DEBUG:     #26 pc 002fbe3f  /data/app/com.mapbox.mapboxsdk.testapp-1/lib/arm/libmapbox-gl.so
10-23 11:16:09.253 377-377/? I/DEBUG:     #27 pc 000ffa45  /data/app/com.mapbox.mapboxsdk.testapp-1/lib/arm/libmapbox-gl.so
10-23 11:16:09.254 377-377/? I/DEBUG:     #28 pc 0010108f  /data/app/com.mapbox.mapboxsdk.testapp-1/lib/arm/libmapbox-gl.so
10-23 11:16:09.254 377-377/? I/DEBUG:     #29 pc 00101025  /data/app/com.mapbox.mapboxsdk.testapp-1/lib/arm/libmapbox-gl.so
10-23 11:16:09.254 377-377/? I/DEBUG:     #30 pc 00100fed  /data/app/com.mapbox.mapboxsdk.testapp-1/lib/arm/libmapbox-gl.so
10-23 11:16:09.254 377-377/? I/DEBUG:     #31 pc 00101119  /data/app/com.mapbox.mapboxsdk.testapp-1/lib/arm/libmapbox-gl.so
10-23 11:16:09.254 377-377/? I/DEBUG:     #32 pc 001010d9  /data/app/com.mapbox.mapboxsdk.testapp-1/lib/arm/libmapbox-gl.so
10-23 11:16:09.254 377-377/? I/DEBUG:     #33 pc 00181aeb  /data/dalvik-cache/arm/data@app@com.mapbox.mapboxsdk.testapp-1@base.apk@classes.dex
```
```
********** Crash dump: **********
Build fingerprint: 'motorola/victara_reteu/victara:5.0/LXE22.46-19/18:user/release-keys'
pid: 22710, tid: 25668, name: GLThread 5780  >>> com.mapbox.mapboxsdk.testapp <<<
signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0xdeadbaad
Stack frame #00 pc 0002b46c  /system/lib/libc.so (dlfree+1239)
Stack frame #01 pc 00011fcf  /system/lib/libc.so (free+10)
Stack frame #02 pc 001edbd9  /data/app/com.mapbox.mapboxsdk.testapp-1/lib/arm/libmapbox-gl.so: Routine ~MessageImpl at /Users/pguardiola/mapbox/mapbox-gl-native/platform/android/MapboxGLAndroidSDK/.externalNativeBuild/cmake/debug/armeabi-v7a/../../../../../../../include/mbgl/actor/message.hpp:20
Stack frame #03 pc 001f02ab  /data/app/com.mapbox.mapboxsdk.testapp-1/lib/arm/libmapbox-gl.so: Routine std::__ndk1::default_delete<mbgl::OfflineRegionObserver>::operator()(mbgl::OfflineRegionObserver*) const at /Users/pguardiola/Library/Android/sdk/ndk-bundle/sources/cxx-stl/llvm-libc++/include/memory:2540
Stack frame #04 pc 0068d0a9  /data/app/com.mapbox.mapboxsdk.testapp-1/lib/arm/libmapbox-gl.so: Routine ~__tuple_impl at /Users/pguardiola/Library/Android/sdk/ndk-bundle/sources/cxx-stl/llvm-libc++/include/tuple:403
Stack frame #05 pc 0068d06b  /data/app/com.mapbox.mapboxsdk.testapp-1/lib/arm/libmapbox-gl.so: Routine ~tuple at /Users/pguardiola/Library/Android/sdk/ndk-bundle/sources/cxx-stl/llvm-libc++/include/tuple:528
Stack frame #06 pc 0068d051  /data/app/com.mapbox.mapboxsdk.testapp-1/lib/arm/libmapbox-gl.so: Routine ~IndexedTuple at /Users/pguardiola/mapbox/mapbox-gl-native/platform/android/MapboxGLAndroidSDK/.externalNativeBuild/cmake/debug/armeabi-v7a/../../../../../../../include/mbgl/util/indexed_tuple.hpp:27
Stack frame #07 pc 0068d037  /data/app/com.mapbox.mapboxsdk.testapp-1/lib/arm/libmapbox-gl.so: Routine ~PaintPropertyBinders at /Users/pguardiola/mapbox/mapbox-gl-native/platform/android/MapboxGLAndroidSDK/.externalNativeBuild/cmake/debug/armeabi-v7a/../../../../../../../src/mbgl/renderer/paint_property_binder.hpp:280
Stack frame #08 pc 0068d01d  /data/app/com.mapbox.mapboxsdk.testapp-1/lib/arm/libmapbox-gl.so: Routine ~pair at /Users/pguardiola/Library/Android/sdk/ndk-bundle/sources/cxx-stl/llvm-libc++/include/utility:280
Stack frame #09 pc 0068cff1  /data/app/com.mapbox.mapboxsdk.testapp-1/lib/arm/libmapbox-gl.so: Routine ~pair at /Users/pguardiola/Library/Android/sdk/ndk-bundle/sources/cxx-stl/llvm-libc++/include/utility:280
Stack frame #10 pc 0068cfad  /data/app/com.mapbox.mapboxsdk.testapp-1/lib/arm/libmapbox-gl.so: Routine void std::__ndk1::allocator_traits<std::__ndk1::allocator<std::__ndk1::__tree_node<std::__ndk1::__value_type<std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> >, std::__ndk1::pair<mbgl::PaintPropertyBinders<mbgl::TypeList<mbgl::style::IconOpacity, mbgl::style::IconColor, mbgl::style::IconHaloColor, mbgl::style::IconHaloWidth, mbgl::style::IconHaloBlur> >, mbgl::PaintPropertyBinders<mbgl::TypeList<mbgl::style::TextOpacity, mbgl::style::TextColor, mbgl::style::TextHaloColor, mbgl::style::TextHaloWidth, mbgl::style::TextHaloBlur> > > >, void*> > >::__destroy<std::__ndk1::pair<std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> > const, std::__ndk1::pair<mbgl::PaintPropertyBinders<mbgl::TypeList<mbgl::style::IconOpacity, mbgl::style::IconColor, mbgl::style::IconHaloColor, mbgl::style::IconHaloWidth, mbgl::style::IconHaloBlur> >, mbgl::PaintPropertyBinders<mbgl::TypeList<mbgl::style::TextOpacity, mbgl::style::TextColor, mbgl::style::TextHaloColor, mbgl::style::TextHaloWidth, mbgl::style::TextHaloBlur> > > > >(std::__ndk1::integral_constant<bool, false>, std::__ndk1::allocator<std::__ndk1::__tree_node<std::__ndk1::__value_type<std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> >, std::__ndk1::pair<mbgl::PaintPropertyBinders<mbgl::TypeList<mbgl::style::IconOpacity, mbgl::style::IconColor, mbgl::style::IconHaloColor, mbgl::style::IconHaloWidth, mbgl::style::IconHaloBlur> >, mbgl::PaintPropertyBinders<mbgl::TypeList<mbgl::style::TextOpacity, mbgl::style::TextColor, mbgl::style::TextHaloColor, mbgl::style::TextHaloWidth, mbgl::style::TextHaloBlur> > > >, void*> >&, std::__ndk1::pair<std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> > const, std::__ndk1::pair<mbgl::PaintPropertyBinders<mbgl::TypeList<mbgl::style::IconOpacity, mbgl::style::IconColor, mbgl::style::IconHaloColor, mbgl::style::IconHaloWidth, mbgl::style::IconHaloBlur> >, mbgl::PaintPropertyBinders<mbgl::TypeList<mbgl::style::TextOpacity, mbgl::style::TextColor, mbgl::style::TextHaloColor, mbgl::style::TextHaloWidth, mbgl::style::TextHaloBlur> > > >*) at /Users/pguardiola/Library/Android/sdk/ndk-bundle/sources/cxx-stl/llvm-libc++/include/memory:1674
Stack frame #11 pc 0068cf2b  /data/app/com.mapbox.mapboxsdk.testapp-1/lib/arm/libmapbox-gl.so: Routine ~__tree at /Users/pguardiola/Library/Android/sdk/ndk-bundle/sources/cxx-stl/llvm-libc++/include/__tree:1716
Stack frame #12 pc 0068c157  /data/app/com.mapbox.mapboxsdk.testapp-1/lib/arm/libmapbox-gl.so: Routine ~map at /Users/pguardiola/Library/Android/sdk/ndk-bundle/sources/cxx-stl/llvm-libc++/include/__tree:1391
Stack frame #13 pc 0068c9d3  /data/app/com.mapbox.mapboxsdk.testapp-1/lib/arm/libmapbox-gl.so: Routine ~SymbolBucket at /Users/pguardiola/mapbox/mapbox-gl-native/platform/android/MapboxGLAndroidSDK/.externalNativeBuild/cmake/debug/armeabi-v7a/../../../../../../../src/mbgl/renderer/buckets/symbol_bucket.hpp:35
Stack frame #14 pc 0068ca01  /data/app/com.mapbox.mapboxsdk.testapp-1/lib/arm/libmapbox-gl.so: Routine ~SymbolBucket at /Users/pguardiola/mapbox/mapbox-gl-native/platform/android/MapboxGLAndroidSDK/.externalNativeBuild/cmake/debug/armeabi-v7a/../../../../../../../src/mbgl/renderer/buckets/symbol_bucket.hpp:35
Stack frame #15 pc 001e6ab7  /data/app/com.mapbox.mapboxsdk.testapp-1/lib/arm/libmapbox-gl.so: Routine std::__ndk1::default_delete<mbgl::FileSource>::operator()(mbgl::FileSource*) const at /Users/pguardiola/Library/Android/sdk/ndk-bundle/sources/cxx-stl/llvm-libc++/include/memory:2540
Stack frame #16 pc 006d3aff  /data/app/com.mapbox.mapboxsdk.testapp-1/lib/arm/libmapbox-gl.so: Routine std::__ndk1::__shared_count::__release_shared() at /Volumes/Android/buildbot/src/android/ndk-r15-release/external/libcxx/src/memory.cpp:67
Stack frame #17 pc 000bc0f7  /data/app/com.mapbox.mapboxsdk.testapp-1/lib/arm/libmapbox-gl.so: Routine ~shared_ptr at /Users/pguardiola/Library/Android/sdk/ndk-bundle/sources/cxx-stl/llvm-libc++/include/memory:4600
Stack frame #18 pc 004b2e2d  /data/app/com.mapbox.mapboxsdk.testapp-1/lib/arm/libmapbox-gl.so: Routine ~pair at /Users/pguardiola/Library/Android/sdk/ndk-bundle/sources/cxx-stl/llvm-libc++/include/utility:280
Stack frame #19 pc 005ad9a1  /data/app/com.mapbox.mapboxsdk.testapp-1/lib/arm/libmapbox-gl.so: Routine void std::__ndk1::allocator_traits<std::__ndk1::allocator<std::__ndk1::__hash_node<std::__ndk1::__hash_value_type<std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> >, std::__ndk1::shared_ptr<mbgl::Bucket> >, void*> > >::__destroy<std::__ndk1::pair<std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> > const, std::__ndk1::shared_ptr<mbgl::Bucket> > >(std::__ndk1::integral_constant<bool, false>, std::__ndk1::allocator<std::__ndk1::__hash_node<std::__ndk1::__hash_value_type<std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> >, std::__ndk1::shared_ptr<mbgl::Bucket> >, void*> >&, std::__ndk1::pair<std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> > const, std::__ndk1::shared_ptr<mbgl::Bucket> >*) at /Users/pguardiola/Library/Android/sdk/ndk-bundle/sources/cxx-stl/llvm-libc++/include/memory:1674
Stack frame #20 pc 005af35d  /data/app/com.mapbox.mapboxsdk.testapp-1/lib/arm/libmapbox-gl.so: Routine std::__ndk1::__hash_table<std::__ndk1::__hash_value_type<std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> >, std::__ndk1::shared_ptr<mbgl::Bucket> >, std::__ndk1::__unordered_map_hasher<std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> >, std::__ndk1::__hash_value_type<std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> >, std::__ndk1::shared_ptr<mbgl::Bucket> >, std::__ndk1::hash<std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> > >, true>, std::__ndk1::__unordered_map_equal<std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> >, std::__ndk1::__hash_value_type<std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> >, std::__ndk1::shared_ptr<mbgl::Bucket> >, std::__ndk1::equal_to<std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> > >, true>, std::__ndk1::allocator<std::__ndk1::__hash_value_type<std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> >, std::__ndk1::shared_ptr<mbgl::Bucket> > > >::clear() at /Users/pguardiola/Library/Android/sdk/ndk-bundle/sources/cxx-stl/llvm-libc++/include/__hash_table:1789
Stack frame #21 pc 005af029  /data/app/com.mapbox.mapboxsdk.testapp-1/lib/arm/libmapbox-gl.so: Routine std::__ndk1::__hash_table<std::__ndk1::__hash_value_type<std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> >, std::__ndk1::shared_ptr<mbgl::Bucket> >, std::__ndk1::__unordered_map_hasher<std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> >, std::__ndk1::__hash_value_type<std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> >, std::__ndk1::shared_ptr<mbgl::Bucket> >, std::__ndk1::hash<std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> > >, true>, std::__ndk1::__unordered_map_equal<std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> >, std::__ndk1::__hash_value_type<std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> >, std::__ndk1::shared_ptr<mbgl::Bucket> >, std::__ndk1::equal_to<std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> > >, true>, std::__ndk1::allocator<std::__ndk1::__hash_value_type<std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> >, std::__ndk1::shared_ptr<mbgl::Bucket> > > >::__move_assign(std::__ndk1::__hash_table<std::__ndk1::__hash_value_type<std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> >, std::__ndk1::shared_ptr<mbgl::Bucket> >, std::__ndk1::__unordered_map_hasher<std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> >, std::__ndk1::__hash_value_type<std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> >, std::__ndk1::shared_ptr<mbgl::Bucket> >, std::__ndk1::hash<std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> > >, true>, std::__ndk1::__unordered_map_equal<std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> >, std::__ndk1::__hash_value_type<std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> >, std::__ndk1::shared_ptr<mbgl::Bucket> >, std::__ndk1::equal_to<std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> > >, true>, std::__ndk1::allocator<std::__ndk1::__hash_value_type<std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> >, std::__ndk1::shared_ptr<mbgl::Bucket> > > >&, std::__ndk1::integral_constant<bool, true>) at /Users/pguardiola/Library/Android/sdk/ndk-bundle/sources/cxx-stl/llvm-libc++/include/__hash_table:1570
Stack frame #22 pc 005ac393  /data/app/com.mapbox.mapboxsdk.testapp-1/lib/arm/libmapbox-gl.so: Routine std::__ndk1::__hash_table<std::__ndk1::__hash_value_type<std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> >, std::__ndk1::shared_ptr<mbgl::Bucket> >, std::__ndk1::__unordered_map_hasher<std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> >, std::__ndk1::__hash_value_type<std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> >, std::__ndk1::shared_ptr<mbgl::Bucket> >, std::__ndk1::hash<std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> > >, true>, std::__ndk1::__unordered_map_equal<std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> >, std::__ndk1::__hash_value_type<std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> >, std::__ndk1::shared_ptr<mbgl::Bucket> >, std::__ndk1::equal_to<std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> > >, true>, std::__ndk1::allocator<std::__ndk1::__hash_value_type<std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> >, std::__ndk1::shared_ptr<mbgl::Bucket> > > >::operator=(std::__ndk1::__hash_table<std::__ndk1::__hash_value_type<std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> >, std::__ndk1::shared_ptr<mbgl::Bucket> >, std::__ndk1::__unordered_map_hasher<std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> >, std::__ndk1::__hash_value_type<std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> >, std::__ndk1::shared_ptr<mbgl::Bucket> >, std::__ndk1::hash<std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> > >, true>, std::__ndk1::__unordered_map_equal<std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> >, std::__ndk1::__hash_value_type<std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> >, std::__ndk1::shared_ptr<mbgl::Bucket> >, std::__ndk1::equal_to<std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> > >, true>, std::__ndk1::allocator<std::__ndk1::__hash_value_type<std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> >, std::__ndk1::shared_ptr<mbgl::Bucket> > > >&&) at /Users/pguardiola/Library/Android/sdk/ndk-bundle/sources/cxx-stl/llvm-libc++/include/__hash_table:1649
Stack frame #23 pc 00603c67  /data/app/com.mapbox.mapboxsdk.testapp-1/lib/arm/libmapbox-gl.so: Routine void mbgl::MessageImpl<mbgl::GeometryTile, void (mbgl::GeometryTile::*)(mbgl::GeometryTile::PlacementResult, unsigned long long), std::__ndk1::tuple<mbgl::GeometryTile::PlacementResult, unsigned long long> >::invoke<0u, 1u>(std::__ndk1::integer_sequence<unsigned int, 0u, 1u>) at /Users/pguardiola/mapbox/mapbox-gl-native/platform/android/MapboxGLAndroidSDK/.externalNativeBuild/cmake/debug/armeabi-v7a/../../../../../../../include/mbgl/actor/message.hpp:34
Stack frame #24 pc 00603bdd  /data/app/com.mapbox.mapboxsdk.testapp-1/lib/arm/libmapbox-gl.so: Routine mbgl::MessageImpl<mbgl::GeometryTile, void (mbgl::GeometryTile::*)(mbgl::GeometryTile::PlacementResult, unsigned long long), std::__ndk1::tuple<mbgl::GeometryTile::PlacementResult, unsigned long long> >::operator()() at /Users/pguardiola/mapbox/mapbox-gl-native/platform/android/MapboxGLAndroidSDK/.externalNativeBuild/cmake/debug/armeabi-v7a/../../../../../../../include/mbgl/actor/message.hpp:29
Stack frame #25 pc 002fbc65  /data/app/com.mapbox.mapboxsdk.testapp-1/lib/arm/libmapbox-gl.so: Routine mbgl::Mailbox::receive() at /Users/pguardiola/mapbox/mapbox-gl-native/src/mbgl/actor/mailbox.cpp:58
Stack frame #26 pc 002fbe3f  /data/app/com.mapbox.mapboxsdk.testapp-1/lib/arm/libmapbox-gl.so: Routine mbgl::Mailbox::maybeReceive(std::__ndk1::weak_ptr<mbgl::Mailbox>) at /Users/pguardiola/mapbox/mapbox-gl-native/src/mbgl/actor/mailbox.cpp:67
Stack frame #27 pc 000ffa45  /data/app/com.mapbox.mapboxsdk.testapp-1/lib/arm/libmapbox-gl.so: Routine mbgl::android::MapRendererRunnable::run(_JNIEnv&) at /Users/pguardiola/mapbox/mapbox-gl-native/platform/android/src/map_renderer_runnable.cpp:21
Stack frame #28 pc 0010108f  /data/app/com.mapbox.mapboxsdk.testapp-1/lib/arm/libmapbox-gl.so: Routine operator() at /Users/pguardiola/mapbox/mapbox-gl-native/platform/android/MapboxGLAndroidSDK/.externalNativeBuild/cmake/debug/armeabi-v7a/../../../../../../../mason_packages/headers/jni.hpp/3.0.0/include/jni/native_method.hpp:245
Stack frame #29 pc 00101025  /data/app/com.mapbox.mapboxsdk.testapp-1/lib/arm/libmapbox-gl.so: Routine operator() at /Users/pguardiola/mapbox/mapbox-gl-native/platform/android/MapboxGLAndroidSDK/.externalNativeBuild/cmake/debug/armeabi-v7a/../../../../../../../mason_packages/headers/jni.hpp/3.0.0/include/jni/native_method.hpp:112
Stack frame #30 pc 00100fed  /data/app/com.mapbox.mapboxsdk.testapp-1/lib/arm/libmapbox-gl.so: Routine __invoke at /Users/pguardiola/mapbox/mapbox-gl-native/platform/android/MapboxGLAndroidSDK/.externalNativeBuild/cmake/debug/armeabi-v7a/../../../../../../../mason_packages/headers/jni.hpp/3.0.0/include/jni/native_method.hpp:110
Stack frame #31 pc 00101119  /data/app/com.mapbox.mapboxsdk.testapp-1/lib/arm/libmapbox-gl.so: Routine operator()<jni::jobject *> at /Users/pguardiola/mapbox/mapbox-gl-native/platform/android/MapboxGLAndroidSDK/.externalNativeBuild/cmake/debug/armeabi-v7a/../../../../../../../mason_packages/headers/jni.hpp/3.0.0/include/jni/native_method.hpp:59
Stack frame #32 pc 001010d9  /data/app/com.mapbox.mapboxsdk.testapp-1/lib/arm/libmapbox-gl.so: Routine __invoke<jni::jobject *> at /Users/pguardiola/mapbox/mapbox-gl-native/platform/android/MapboxGLAndroidSDK/.externalNativeBuild/cmake/debug/armeabi-v7a/../../../../../../../mason_packages/headers/jni.hpp/3.0.0/include/jni/native_method.hpp:55
Stack frame #33 pc 00181aeb  /data/dalvik-cache/arm/data@app@com.mapbox.mapboxsdk.testapp-1@base.apk@classes.dex
```

#9935 

```
10-23 11:20:26.678 377-377/? I/DEBUG: *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
10-23 11:20:26.678 377-377/? I/DEBUG: Build fingerprint: 'motorola/victara_reteu/victara:5.0/LXE22.46-19/18:user/release-keys'
10-23 11:20:26.678 377-377/? I/DEBUG: Revision: 'p2bf'
10-23 11:20:26.678 377-377/? I/DEBUG: ABI: 'arm'
10-23 11:20:26.678 377-377/? I/DEBUG: pid: 27625, tid: 27895, name: GLThread 2667  >>> com.mapbox.mapboxsdk.testapp <<<
10-23 11:20:26.678 377-377/? I/DEBUG: signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x6c2d6c65
10-23 11:20:26.708 377-377/? I/DEBUG:     r0 00006376  r1 b7941b68  r2 42c65cd7  r3 b855a648
10-23 11:20:26.710 377-377/? I/DEBUG:     r4 0000636f  r5 6c2d6c65  r6 b7940d90  r7 00000000
10-23 11:20:26.710 377-377/? I/DEBUG:     r8 00000001  r9 00000dd8  sl 000000b8  fp 000003ff
10-23 11:20:26.710 377-377/? I/DEBUG:     ip ad7e6fdc  sp a0d0d648  lr ad74c93f  pc ad73f042  cpsr 200f0030
10-23 11:20:26.711 377-377/? I/DEBUG: backtrace:
10-23 11:20:26.711 377-377/? I/DEBUG:     #00 pc 0005f042  /system/vendor/lib/egl/libGLESv2_adreno.so (nobj_generate_names+69)
10-23 11:20:26.711 377-377/? I/DEBUG:     #01 pc 0006c93b  /system/vendor/lib/egl/libGLESv2_adreno.so (core_glGenBuffers+54)
10-23 11:20:26.711 377-377/? I/DEBUG:     #02 pc 00043d31  /system/vendor/lib/egl/libGLESv2_adreno.so (glGenBuffers+20)
10-23 11:20:26.711 377-377/? I/DEBUG:     #03 pc 004c675d  /data/app/com.mapbox.mapboxsdk.testapp-1/lib/arm/libmapbox-gl.so
10-23 11:20:26.711 377-377/? I/DEBUG:     #04 pc 004c6691  /data/app/com.mapbox.mapboxsdk.testapp-1/lib/arm/libmapbox-gl.so
10-23 11:20:26.711 377-377/? I/DEBUG:     #05 pc 004ee663  /data/app/com.mapbox.mapboxsdk.testapp-1/lib/arm/libmapbox-gl.so
10-23 11:20:26.711 377-377/? I/DEBUG:     #06 pc 0068c27f  /data/app/com.mapbox.mapboxsdk.testapp-1/lib/arm/libmapbox-gl.so
10-23 11:20:26.712 377-377/? I/DEBUG:     #07 pc 005acf61  /data/app/com.mapbox.mapboxsdk.testapp-1/lib/arm/libmapbox-gl.so
10-23 11:20:26.712 377-377/? I/DEBUG:     #08 pc 005acc8d  /data/app/com.mapbox.mapboxsdk.testapp-1/lib/arm/libmapbox-gl.so
10-23 11:20:26.712 377-377/? I/DEBUG:     #09 pc 00668c3d  /data/app/com.mapbox.mapboxsdk.testapp-1/lib/arm/libmapbox-gl.so
10-23 11:20:26.713 377-377/? I/DEBUG:     #10 pc 0066a2a1  /data/app/com.mapbox.mapboxsdk.testapp-1/lib/arm/libmapbox-gl.so
10-23 11:20:26.714 377-377/? I/DEBUG:     #11 pc 0058e471  /data/app/com.mapbox.mapboxsdk.testapp-1/lib/arm/libmapbox-gl.so
10-23 11:20:26.715 377-377/? I/DEBUG:     #12 pc 00316aa3  /data/app/com.mapbox.mapboxsdk.testapp-1/lib/arm/libmapbox-gl.so
10-23 11:20:26.715 377-377/? I/DEBUG:     #13 pc 0030c491  /data/app/com.mapbox.mapboxsdk.testapp-1/lib/arm/libmapbox-gl.so
10-23 11:20:26.715 377-377/? I/DEBUG:     #14 pc 000f902f  /data/app/com.mapbox.mapboxsdk.testapp-1/lib/arm/libmapbox-gl.so
10-23 11:20:26.715 377-377/? I/DEBUG:     #15 pc 000fe923  /data/app/com.mapbox.mapboxsdk.testapp-1/lib/arm/libmapbox-gl.so
10-23 11:20:26.715 377-377/? I/DEBUG:     #16 pc 000fe8b9  /data/app/com.mapbox.mapboxsdk.testapp-1/lib/arm/libmapbox-gl.so
10-23 11:20:26.715 377-377/? I/DEBUG:     #17 pc 000fe881  /data/app/com.mapbox.mapboxsdk.testapp-1/lib/arm/libmapbox-gl.so
10-23 11:20:26.715 377-377/? I/DEBUG:     #18 pc 000fe9ad  /data/app/com.mapbox.mapboxsdk.testapp-1/lib/arm/libmapbox-gl.so
10-23 11:20:26.715 377-377/? I/DEBUG:     #19 pc 000fe96d  /data/app/com.mapbox.mapboxsdk.testapp-1/lib/arm/libmapbox-gl.so
10-23 11:20:26.716 377-377/? I/DEBUG:     #20 pc 00181aeb  /data/dalvik-cache/arm/data@app@com.mapbox.mapboxsdk.testapp-1@base.apk@classes.dex
```
```
********** Crash dump: **********
Build fingerprint: 'motorola/victara_reteu/victara:5.0/LXE22.46-19/18:user/release-keys'
pid: 27625, tid: 27895, name: GLThread 2667  >>> com.mapbox.mapboxsdk.testapp <<<
signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x6c2d6c65
Stack frame #00 pc 0005f042  /system/vendor/lib/egl/libGLESv2_adreno.so (nobj_generate_names+69)
Stack frame #01 pc 0006c93b  /system/vendor/lib/egl/libGLESv2_adreno.so (core_glGenBuffers+54)
Stack frame #02 pc 00043d31  /system/vendor/lib/egl/libGLESv2_adreno.so (glGenBuffers+20)
Stack frame #03 pc 004c675d  /data/app/com.mapbox.mapboxsdk.testapp-1/lib/arm/libmapbox-gl.so: Routine operator() at /Users/pguardiola/mapbox/mapbox-gl-native/src/mbgl/gl/context.cpp:231
Stack frame #04 pc 004c6691  /data/app/com.mapbox.mapboxsdk.testapp-1/lib/arm/libmapbox-gl.so: Routine mbgl::gl::Context::createIndexBuffer(void const*, unsigned int) at /Users/pguardiola/mapbox/mapbox-gl-native/src/mbgl/gl/context.cpp:231
Stack frame #05 pc 004ee663  /data/app/com.mapbox.mapboxsdk.testapp-1/lib/arm/libmapbox-gl.so: Routine mbgl::gl::IndexBuffer<mbgl::gl::LineStrip> mbgl::gl::Context::createIndexBuffer<mbgl::gl::LineStrip>(mbgl::gl::IndexVector<mbgl::gl::LineStrip>&&) at /Users/pguardiola/mapbox/mapbox-gl-native/platform/android/MapboxGLAndroidSDK/.externalNativeBuild/cmake/debug/armeabi-v7a/../../../../../../../src/mbgl/gl/context.hpp:80
Stack frame #06 pc 0068c27f  /data/app/com.mapbox.mapboxsdk.testapp-1/lib/arm/libmapbox-gl.so: Routine mbgl::SymbolBucket::upload(mbgl::gl::Context&) at /Users/pguardiola/mapbox/mapbox-gl-native/src/mbgl/renderer/buckets/symbol_bucket.cpp:41
Stack frame #07 pc 005acf61  /data/app/com.mapbox.mapboxsdk.testapp-1/lib/arm/libmapbox-gl.so: Routine operator() at /Users/pguardiola/mapbox/mapbox-gl-native/src/mbgl/tile/geometry_tile.cpp:195
Stack frame #08 pc 005acc8d  /data/app/com.mapbox.mapboxsdk.testapp-1/lib/arm/libmapbox-gl.so: Routine mbgl::GeometryTile::upload(mbgl::gl::Context&) at /Users/pguardiola/mapbox/mapbox-gl-native/src/mbgl/tile/geometry_tile.cpp:204
Stack frame #09 pc 00668c3d  /data/app/com.mapbox.mapboxsdk.testapp-1/lib/arm/libmapbox-gl.so: Routine mbgl::RenderTile::startRender(mbgl::PaintParameters&) at /Users/pguardiola/mapbox/mapbox-gl-native/src/mbgl/renderer/render_tile.cpp:60
Stack frame #10 pc 0066a2a1  /data/app/com.mapbox.mapboxsdk.testapp-1/lib/arm/libmapbox-gl.so: Routine mbgl::TilePyramid::startRender(mbgl::PaintParameters&) at /Users/pguardiola/mapbox/mapbox-gl-native/src/mbgl/renderer/tile_pyramid.cpp:44
Stack frame #11 pc 0058e471  /data/app/com.mapbox.mapboxsdk.testapp-1/lib/arm/libmapbox-gl.so: Routine mbgl::RenderGeoJSONSource::startRender(mbgl::PaintParameters&) at /Users/pguardiola/mapbox/mapbox-gl-native/src/mbgl/renderer/sources/render_geojson_source.cpp:72
Stack frame #12 pc 00316aa3  /data/app/com.mapbox.mapboxsdk.testapp-1/lib/arm/libmapbox-gl.so: Routine mbgl::Renderer::Impl::render(mbgl::UpdateParameters const&) at /Users/pguardiola/mapbox/mapbox-gl-native/src/mbgl/renderer/renderer_impl.cpp:402
Stack frame #13 pc 0030c491  /data/app/com.mapbox.mapboxsdk.testapp-1/lib/arm/libmapbox-gl.so: Routine mbgl::Renderer::render(mbgl::UpdateParameters const&) at /Users/pguardiola/mapbox/mapbox-gl-native/src/mbgl/renderer/renderer.cpp:32
Stack frame #14 pc 000f902f  /data/app/com.mapbox.mapboxsdk.testapp-1/lib/arm/libmapbox-gl.so: Routine mbgl::android::MapRenderer::render(_JNIEnv&) at /Users/pguardiola/mapbox/mapbox-gl-native/platform/android/src/map_renderer.cpp:130
Stack frame #15 pc 000fe923  /data/app/com.mapbox.mapboxsdk.testapp-1/lib/arm/libmapbox-gl.so: Routine operator() at /Users/pguardiola/mapbox/mapbox-gl-native/platform/android/MapboxGLAndroidSDK/.externalNativeBuild/cmake/debug/armeabi-v7a/../../../../../../../mason_packages/headers/jni.hpp/3.0.0/include/jni/native_method.hpp:245
Stack frame #16 pc 000fe8b9  /data/app/com.mapbox.mapboxsdk.testapp-1/lib/arm/libmapbox-gl.so: Routine operator() at /Users/pguardiola/mapbox/mapbox-gl-native/platform/android/MapboxGLAndroidSDK/.externalNativeBuild/cmake/debug/armeabi-v7a/../../../../../../../mason_packages/headers/jni.hpp/3.0.0/include/jni/native_method.hpp:112
Stack frame #17 pc 000fe881  /data/app/com.mapbox.mapboxsdk.testapp-1/lib/arm/libmapbox-gl.so: Routine __invoke at /Users/pguardiola/mapbox/mapbox-gl-native/platform/android/MapboxGLAndroidSDK/.externalNativeBuild/cmake/debug/armeabi-v7a/../../../../../../../mason_packages/headers/jni.hpp/3.0.0/include/jni/native_method.hpp:110
Stack frame #18 pc 000fe9ad  /data/app/com.mapbox.mapboxsdk.testapp-1/lib/arm/libmapbox-gl.so: Routine operator()<jni::jobject *> at /Users/pguardiola/mapbox/mapbox-gl-native/platform/android/MapboxGLAndroidSDK/.externalNativeBuild/cmake/debug/armeabi-v7a/../../../../../../../mason_packages/headers/jni.hpp/3.0.0/include/jni/native_method.hpp:59
Stack frame #19 pc 000fe96d  /data/app/com.mapbox.mapboxsdk.testapp-1/lib/arm/libmapbox-gl.so: Routine __invoke<jni::jobject *> at /Users/pguardiola/mapbox/mapbox-gl-native/platform/android/MapboxGLAndroidSDK/.externalNativeBuild/cmake/debug/armeabi-v7a/../../../../../../../mason_packages/headers/jni.hpp/3.0.0/include/jni/native_method.hpp:55
Stack frame #20 pc 00181aeb  /data/dalvik-cache/arm/data@app@com.mapbox.mapboxsdk.testapp-1@base.apk@classes.dex
```

👀 @ivovandongen

**Comment by ivovandongen** [comment]
> Android 5.0 Moto X (2nd gen) | Adreno 330

@Guardiola31337 Are you sure you tested with this branch? I tested all of these on the same device without issues

**Comment by tobrun** [comment]
@Guardiola31337 did some follow up tests with an `Android 5.1 Moto X (2nd gen)` and I'm not hitting the crashes as shown above. Could I borrow your device for some tests? 

cc @ivovandongen
