### PR TITLE
Fixed NSLocale.languageCode crash in iOS 9.3

### LINKED ISSUE #12063: '-[__NSCFLocale languageCode]: unrecognized selector' error in iOS 9.x
**Platform:** iOS
**Mapbox SDK version:** 4.0.1

### Steps to trigger behavior

 1. In the [iOS examples app](https://github.com/mapbox/ios-sdk-examples), add the following code to the DDSCircleLayerExample.swift example in the mapView function:

```
let lang = Locale(identifier: "es")
style.localizeLabels(into: lang)
```

 2. Run the app using an iOS 9.x simulator

### Expected behavior

When selecting the DDS circle layer example, the map should load and display as expected.

### Actual behavior

When selecting the DDS circle layer example, the app crashes with the following logs:

```
2018-06-05 09:36:56.309 Examples[60815:3708325] [INFO] {}[General]: GPU Identifier: Apple Software Renderer
2018-06-05 09:36:56.385 Examples[60815:3714187] Mapbox Maps SDK for iOS version 4.0.2 is now available: https://github.com/mapbox/mapbox-gl-native/releases/tag/ios-v4.0.2
2018-06-05 09:36:56.405 Examples[60815:3708325] -[__NSCFLocale languageCode]: unrecognized selector sent to instance 0x7fc653c90a60
2018-06-05 09:36:56.419 Examples[60815:3708325] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[__NSCFLocale languageCode]: unrecognized selector sent to instance 0x7fc653c90a60'
*** First throw call stack:
(
	0   CoreFoundation                      0x0000000101576f45 __exceptionPreprocess + 165
	1   libobjc.A.dylib                     0x0000000100ff0deb objc_exception_throw + 48
	2   CoreFoundation                      0x000000010157f56d -[NSObject(NSObject) doesNotRecognizeSelector:] + 205
	3   CoreFoundation                      0x00000001014cceea ___forwarding___ + 970
	4   CoreFoundation                      0x00000001014cca98 _CF_forwarding_prep_0 + 120
	5   Mapbox                              0x00000001006c671a _Z31MGLGeoJSONOptionsFromDictionaryP12NSDictionaryIP8NSStringP11objc_objectE + 69274
	6   Foundation                          0x0000000100c20f11 -[NSBlockPredicate evaluateWithObject:substitutionVariables:] + 218
	7   Foundation                          0x0000000100be0d44 _filterObjectsUsingPredicate + 398
	8   Foundation                          0x0000000100be0b34 -[NSArray(NSPredicateSupport) filteredArrayUsingPredicate:] + 279
	9   Mapbox                              0x00000001006c63fc _Z31MGLGeoJSONOptionsFromDictionaryP12NSDictionaryIP8NSStringP11objc_objectE + 68476
	10  Mapbox                              0x000000010076d9a0 _Z24MGLMapPointForCoordinate22CLLocationCoordinate2Dd + 57615
	11  Mapbox                              0x000000010075de0d _Z45MBGLCustomGeometrySourceOptionsFromDictionaryP12NSDictionaryIP8NSStringP11objc_objectE + 236973
	12  Examples                            0x00000001004c0f32 _T08Examples27DDSCircleLayerExample_SwiftC7mapViewySo06MGLMapG0C_So8MGLStyleC16didFinishLoadingtFTf4dgd_n + 82
	13  Examples                            0x00000001004c0650 _T08Examples27DDSCircleLayerExample_SwiftC7mapViewySo06MGLMapG0C_So8MGLStyleC16didFinishLoadingtFTo + 48
	14  Mapbox                              0x0000000100748d15 _Z45MBGLCustomGeometrySourceOptionsFromDictionaryP12NSDictionaryIP8NSStringP11objc_objectE + 150709
	15  Mapbox                              0x000000010074d13f _Z45MBGLCustomGeometrySourceOptionsFromDictionaryP12NSDictionaryIP8NSStringP11objc_objectE + 168159
	16  Mapbox                              0x0000000100808601 utrie2_enumForLeadSurrogate_58 + 281354
	17  Mapbox                              0x000000010096eff0 utrie2_enumForLeadSurrogate_58 + 1750265
	18  Mapbox                              0x0000000100971286 utrie2_enumForLeadSurrogate_58 + 1759119
	19  Mapbox                              0x00000001009da43b utrie2_enumForLeadSurrogate_58 + 2189636
	20  Mapbox                              0x00000001007ccfdb utrie2_enumForLeadSurrogate_58 + 38116
	21  Mapbox                              0x00000001007cd120 utrie2_enumForLeadSurrogate_58 + 38441
	22  Mapbox                              0x00000001009ccd5f utrie2_enumForLeadSurrogate_58 + 2134632
	23  Mapbox                              0x00000001009cc305 utrie2_enumForLeadSurrogate_58 + 2131982
	24  CoreFoundation                      0x00000001014a3011 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 17
	25  CoreFoundation                      0x0000000101498f3c __CFRunLoopDoSources0 + 556
	26  CoreFoundation                      0x00000001014983f3 __CFRunLoopRun + 867
	27  CoreFoundation                      0x0000000101497e08 CFRunLoopRunSpecific + 488
	28  GraphicsServices                    0x0000000106006ad2 GSEventRunModal + 161
	29  UIKit                               0x0000000101e0530d UIApplicationMain + 171
	30  Examples                            0x00000001004a700f main + 111
	31  libdyld.dylib                       0x000000010528492d start + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException
(lldb)
```

Possibly related to https://github.com/mapbox/mapbox-gl-native/issues/7399?

cc @1ec5 @captainbarbosa

### PR DESCRIPTION
**Pull request by julianrex**
Fixes #12063 (same bug as #7399)

### CODE REVIEW

File: platform/darwin/src/MGLVectorTileSource.mm [hunk 1]
```diff
@@ -109,7 +109,9 @@ + (NSString *)preferredMapboxStreetsLanguage {
 + (NSString *)preferredMapboxStreetsLanguageForPreferences:(NSArray<NSString *> *)preferencesArray {
     BOOL acceptsEnglish = [preferencesArray filteredArrayUsingPredicate:
                            [NSPredicate predicateWithBlock:^BOOL(NSString * _Nullable language, NSDictionary<NSString *,id> * _Nullable bindings) {
-        return [[NSLocale localeWithLocaleIdentifier:language].languageCode isEqualToString:@"en"];
+
+        NSString *languageCode = [[NSLocale localeWithLocaleIdentifier:language] objectForKey:NSLocaleLanguageCode];
```
Comment (fabian-guerra) [inline platform/darwin/src/MGLVectorTileSource.mm]: Is it possible to wrap in a `if #available` statement so when we remove iOS 9 support we also remove this code and keep the latest API?

Comment (julianrex) [reply platform/darwin/src/MGLVectorTileSource.mm]: Yep we can do that - I'll modify the previous case of this too

File: platform/ios/CHANGELOG.md [hunk 2]
```diff
@@ -21,6 +21,7 @@ Mapbox welcomes participation and contributions from everyone. Please read [CONT
 * Added custom `-hitTest:withEvent:` to `MGLSMCalloutView` to avoid registering taps in transparent areas of the standard annotation callout. ([#11939](https://github.com/mapbox/mapbox-gl-native/pull/11939))
 * Improved performance and memory impact of `MGLScaleBar`. ([#11921](https://github.com/mapbox/mapbox-gl-native/pull/11921))
 * Fixed race conditions that could cause crashes when re-using `MGLMapSnapshotter` or using multiple snapshotters at the same time. ([#11831](https://github.com/mapbox/mapbox-gl-native/pull/11831))
+* Fixed crash on iOS 9.3 (`NSLocale.languageCode` introduced in iOS 10.0) ([#12123](https://github.com/mapbox/mapbox-gl-native/pull/12123))
```
Comment (friedbunny) [inline platform/ios/CHANGELOG.md]: We should be specific as to how the crash was triggered, so we’ll want to mention `-[MGLStyle localizeLabelsIntoLocale:]` instead of `NSLocale` directly.

Comment (fabian-guerra) [reply platform/ios/CHANGELOG.md]: @friedbunny to avoid waiting more I can fix this changelog in https://github.com/mapbox/mapbox-gl-native/pull/12086

File: platform/macos/CHANGELOG.md [hunk 3]
```diff
@@ -16,6 +16,8 @@
 * Adjusted when and how the camera transition update and finish callbacks are called, fixing recursion bugs. ([#11614](https://github.com/mapbox/mapbox-gl-native/pull/11614))
 * Fixed an issue preventing nested key path expressions get parsed accordingly to the spec. ([#11959](https://github.com/mapbox/mapbox-gl-native/pull/11959))
 * Fixed race conditions that could cause crashes when re-using `MGLMapSnapshotter` or using multiple snapshotters at the same time. ([#11831](https://github.com/mapbox/mapbox-gl-native/pull/11831))
+* Fixed crash in `-[MGLStyle localizeLabelsIntoLocale:]` on iOS 9.3 (attempting to access a property that was introduced in iOS 10.0 and used in Darwin code) ([#12123](https://github.com/mapbox/mapbox-gl-native/pull/12123))
```
Comment (1ec5) [inline platform/macos/CHANGELOG.md]: s/iOS 9.3/macOS 10.11/
s/iOS 10.0/macOS 10.12/
The way we use “Darwin” in this repository is a bit misleading – we don’t actually do any kernel programming – so we avoid mentioning that term in public-facing documentation.

Comment (julianrex) [reply platform/macos/CHANGELOG.md]: Good to know - how do we normally reference code that is shared between iOS and macOS? "shared platform code"?

Comment (julianrex) [reply platform/macos/CHANGELOG.md]: Updated in https://github.com/mapbox/mapbox-gl-native/pull/12146

Comment (friedbunny) [reply platform/macos/CHANGELOG.md]: > how do we normally reference code that is shared between iOS and macOS

We don’t tend to acknowledge the existence of other platforms on the iOS changelog.
